AWSTemplateFormatVersion: '2010-09-09'
Description: 'update routing table of iscale-mis'

Parameters:
  VPCID:
    Type: String
    Default: network
  RouteTable1: # default
    Type: String
    Default: rtb-04002ee670cac0914
  RouteTable2: # public
    Type: String
    Default: rtb-0e7ff75bb78c0c74c
  RouteTable3: # private a
    Type: String
    Default: rtb-0545a9e8bdb2dc267
  RouteTable4: # private b
    Type: String
    Default: rtb-093011f3e03e3c324
  VPCPeeringConnectionID1:
    Type: String
    Default: pcx-0b7eb44c41e581a0c
  VPCPeeringConnectionID2:
    Type: String
    Default: pcx-061ef849b7dab25be
  VPCPeeringConnectionID3:
    Type: String
    Default: pcx-051322a162025c974
  VPCPeeringConnectionID4:
    Type: String
    Default: pcx-0e4032816d03f6d73
  VPCPeeringConnectionID5:
    Type: String
    Default: pcx-06d250ba6b1832465
  VPCPeeringConnectionID6:
    Type: String
    Default: pcx-09cba94c838fd75fe

Resources:
  Table1Route1:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable1
      DestinationCidrBlock: "10.8.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID1
  
  Table1Route2:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable1
      DestinationCidrBlock: "10.6.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID2

  Table1Route3:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable1
      DestinationCidrBlock: "10.4.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID3

  Table1Route4:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable1
      DestinationCidrBlock: "10.11.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID4

  Table1Route5:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable1
      DestinationCidrBlock: "10.10.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID5

  Table1Route6:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable1
      DestinationCidrBlock: "10.12.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID6

###

  Table2Route1:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable2
      DestinationCidrBlock: "10.8.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID1
  
  Table2Route2:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable2
      DestinationCidrBlock: "10.6.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID2

  Table2Route3:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable2
      DestinationCidrBlock: "10.4.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID3

  Table2Route4:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable2
      DestinationCidrBlock: "10.11.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID4

  Table2Route5:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable2
      DestinationCidrBlock: "10.10.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID5

  Table2Route6:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable2
      DestinationCidrBlock: "10.12.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID6

##

  Table3Route1:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable3
      DestinationCidrBlock: "10.8.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID1
  
  Table3Route2:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable3
      DestinationCidrBlock: "10.6.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID2

  Table3Route3:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable3
      DestinationCidrBlock: "10.4.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID3

  Table3Route4:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable3
      DestinationCidrBlock: "10.11.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID4

  Table3Route5:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable3
      DestinationCidrBlock: "10.10.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID5

  Table3Route6:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable3
      DestinationCidrBlock: "10.12.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID6

###

  Table4Route1:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable4
      DestinationCidrBlock: "10.8.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID1
  
  Table4Route2:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable4
      DestinationCidrBlock: "10.6.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID2

  Table4Route3:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable4
      DestinationCidrBlock: "10.4.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID3

  Table4Route4:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable4
      DestinationCidrBlock: "10.11.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID4

  Table4Route5:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable4
      DestinationCidrBlock: "10.10.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID5

  Table4Route6:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable4
      DestinationCidrBlock: "10.12.0.0/24"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID6
