AWSTemplateFormatVersion: 2010-09-09
Description: MIS DB for glue testing (data from all PCHC UAT DB)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName


    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Topic Stack Name

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name)
    Type: String
    MinLength: 3
    MaxLength: 12
    Default: mis
  OrgName:
    Description: The name of the organization
    Type: String
    Default: pchc
    AllowedPattern: '^[a-z]+(-[a-z]+)*$'
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production # Test for uat
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  NetworkStackName:
    Description: The name of the network stack
    Type: String
    Default: pchc-dev-uw2-mis-network
    MinLength: 1
  SNSStackName:
    Description: The name of the SNS stack
    Type: String
    Default: iscale-dev-dev-uw2-sns
    MinLength: 1


Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:


##
# Database
##

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/database.yaml
      Parameters:
        Name: !Ref Name
        DatabaseName: !Join ['',[!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name], db]]
        AllocatedStorage: 20
        BackupRetentionPeriod: !If [IsProd, 30, 7]
        EnableEnhancedMonitoring: !If [IsProd, true, false]
        EnablePerformanceInsights: !If [IsProd, true, false]
        EnvName: !Ref EnvName
        Engine: mysql
        EngineVersion: 8.0.35
        Family: mysql8.0
        InstanceType: !If [IsProd, db.t4g.large, db.t4g.micro]
        MasterUser: root
        MultiAz: !If [IsProd, true, false]
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        SNSStackName: !Ref SNSStackName
        StorageEncrypted: true

  # AllowJumpHostIntoDB:
  #   Type: AWS::EC2::SecurityGroupIngress
  #   Properties:
  #     Description: Allow connection from jump host
  #     IpProtocol: TCP
  #     GroupId:
  #       Fn::GetAtt:
  #         - DBStack
  #         - Outputs.SecurityGroupId
  #     FromPort:
  #       Fn::GetAtt:
  #         - DBStack
  #         - Outputs.DBInstancePort
  #     ToPort:
  #       Fn::GetAtt:
  #         - DBStack
  #         - Outputs.DBInstancePort
  #     SourceSecurityGroupId:
  #       Fn::ImportValue:
  #         !Sub '${NetworkStackName}-JumpHostSecurityGroupId'
