AWSTemplateFormatVersion: 2010-09-09
Description: 'Template to update routing table of DB subnets and add secgroup rule 
  to allow iscale-mis resources to access RDS 
  (oregon UAT)'

Parameters:
  dsappRouteTable: # default
    Type: String
    Default: rtb-07e205e7e07b3d6e0
  pddtseodRouteTable: # public
    Type: String
    Default: rtb-05b24c85248a10c67
  paygateRouteTable: # private a
    Type: String
    Default: rtb-01cd028238bf18d0c

  VPCPeeringConnectionID1:
    Type: String
    Default: pcx-0e4032816d03f6d73
  VPCPeeringConnectionID2:
    Type: String
    Default: pcx-06d250ba6b1832465
  VPCPeeringConnectionID3:
    Type: String
    Default: pcx-09cba94c838fd75fe

Resources:
  Table1Route:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref dsappRouteTable
      DestinationCidrBlock: "10.16.0.0/23"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID1
  
  Table2Route:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref pddtseodRouteTable
      DestinationCidrBlock: "10.16.0.0/23"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID2

  Table3Route:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref paygateRouteTable
      DestinationCidrBlock: "10.16.0.0/23"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID3

# secg

  AllowIscaleMIStoDsappDB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow connection from iscale-mis-dev
      IpProtocol: TCP
      GroupId: sg-0d0631712b6ab2ec0
      FromPort: 3306
      ToPort: 3306
      CidrIp: 10.16.0.0/23

  AllowIscaleMIStoPddtseodDB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow connection from iscale-mis-dev
      IpProtocol: TCP
      GroupId: sg-0a818e4c23ffd7d31
      FromPort: 3306
      ToPort: 3306
      CidrIp: 10.16.0.0/23

  AllowIscaleMIStoPaygateDB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow connection from iscale-mis-dev
      IpProtocol: TCP
      GroupId: sg-0ae9fba22e42611ad
      FromPort: 3306
      ToPort: 3306
      CidrIp: 10.16.0.0/23
