AWSTemplateFormatVersion: 2010-09-09
Description: 'Template to update routing table of DB subnets and add secgroup rule 
  to allow iscale-mis resources to access RDS 
  (Singapore UAT)'

Parameters:
  pas6RouteTable:
    Type: String
    Default: rtb-0ab961b6bcb92c0d9
  pesonetRouteTable:
    Type: String
    Default: rtb-0c32e2345bf201681
  pddtsRouteTable:
    Type: String
    Default: rtb-05bb020bfcd0b00b1

  VPCPeeringConnectionID1:
    Type: String
    Default: pcx-0b7eb44c41e581a0c
  VPCPeeringConnectionID2:
    Type: String
    Default: pcx-061ef849b7dab25be
  VPCPeeringConnectionID3:
    Type: String
    Default: pcx-051322a162025c974

Resources:
  Table1Route:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref pas6RouteTable
      DestinationCidrBlock: "10.16.0.0/23"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID1
  
  Table2Route:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref pesonetRouteTable
      DestinationCidrBlock: "10.16.0.0/23"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID2

  Table3Route:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref pddtsRouteTable
      DestinationCidrBlock: "10.16.0.0/23"
      VpcPeeringConnectionId: !Ref VPCPeeringConnectionID3

# secg

  AllowIscaleMIStoPas6DB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow connection from iscale-mis-dev
      IpProtocol: TCP
      GroupId: sg-0dadae86b32e09654
      FromPort: 3306
      ToPort: 3306
      CidrIp: 10.16.0.0/23

  AllowIscaleMIStoPesonetDB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow connection from iscale-mis-dev
      IpProtocol: TCP
      GroupId: sg-01010bc194dff3925
      FromPort: 3306
      ToPort: 3306
      CidrIp: 10.16.0.0/23

  AllowIscaleMIStoPddtsDB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow connection from iscale-mis-dev
      IpProtocol: TCP
      GroupId: sg-0a4792b8b9ac9d703
      FromPort: 3306
      ToPort: 3306
      CidrIp: 10.16.0.0/23
