AWSTemplateFormatVersion: 2010-09-09
Description: FishingKaki Image Builder (For Marketplace and Classifieds)

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName
      - Label:
          default: Sharing Configuration
        Parameters:
          - ShareImage

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      NetworkStackName:
        default: Network Stack Name
      ShareImage:
        default: Share image with other account? If sharing, encryption will be disabled.
      SNSStackName:
        default: SNS Topic Stack Name

Parameters:
  Name:
    Description: Unique name/identifier (e.g. odoo-linux).
    Type: String
    Default: lazaki
    AllowedPattern: "^[a-z0-9]+(-[a-z0-9]+)*$"
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: fishingkaki
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: fishingkaki-stg-uw2-network
    MinLength: 1
  ShareImage:
    Description: Select true to not encrypt the image and share it with other accounts
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  SNSStackName:
    Description: the name of the SNS stack.
    Type: String
    Default: fishingkaki-stg-uw2-sns
    MinLength: 1

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml      
  IsImageShared: !Equals [!Ref ShareImage, true]

Resources:
  
  NginxComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: NginX
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2023
      Version: 1.0.0
      Description: Installs NginX
      ChangeDescription: Initial version
      Data: |
        name: NginX - InlineData
        description: Installation of NginX
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallNginx
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y nginx
                    - sudo mkdir /var/www
                    - sudo systemctl start nginx
                    - sudo systemctl enable nginx

  ApacheComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: Apache
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2023
      Version: 1.0.0
      Description: Installation of Apache
      ChangeDescription: Initial version
      Data: |
        name:  AmazonLinux2Apache - InlineData
        description: Installation of Apache
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallApache
                action: ExecuteBash
                inputs:
                  commands:
                    - |
                      sudo yum -y install httpd
                      sudo systemctl start httpd
                      sudo systemctl enable httpd

  MariaDBClientComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: MariaDB Client
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2023
      Version: 1.0.0
      Description: Installs MariaDB Client + dev libs
      ChangeDescription: Initial version
      Data: |
        name: MariaDB Client - InlineData
        description: Installation of MariaDB Client
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: YumInstallMariaDBCLient
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y mariadb105
              - name: YumInstallMariaDBDevel
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y mariadb105-devel

  PHP83ComponentAL2023:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: PHP83-Component-AL2023
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2023
      Version: 2.0.0
      Description: Installing php 8.3
      ChangeDescription: Initial version
      Data: |
        name: Php83 - InlineData
        description: Installing php 8.3
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallPHP
                action: ExecuteBash
                inputs:
                  commands:
                    - |
                      sudo yum install php8.3 -y
                      sudo yum install php php-{common,cgi,cli,fpm,mysqlnd,devel,gd,mbstring,curl,xml,pear,bcmath,json,opcache,gettext,intl,zip} -y

  ComposerComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: Composer-Component
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2023
      Version: 2.0.0
      Description: Installing composer
      ChangeDescription: Initial version
      Data: |
        name: Composer-Component - InlineData
        description: Installing composer
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallComposer
                action: ExecuteBash
                inputs:
                  commands:
                    - |
                      sudo curl -sS https://getcomposer.org/installer | sudo php
                      sudo mv composer.phar /usr/local/bin/composer
                      sudo ln -s /usr/local/bin/composer /usr/bin/composer

  SupervisorComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: Supervisor-Component
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2023
      Version: 1.0.0
      Description: Installing supervisord
      ChangeDescription: Initial version
      Data: |
        name: Supervisor-Component - InlineData
        description: Installing supervisor
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallSupervisor
                action: ExecuteBash
                inputs:
                  commands:
                    - |
                      sudo dnf install python3-pip -y
                      sudo pip3 install supervisor

  NodeJS22Component:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: NodeJS-22
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2023
      Version: 1.0.0
      Description: Installs NodeJS v22
      ChangeDescription: Initial version
      Data: |
        name: NodeJS - InlineData
        description: Installation of NodeJS v22
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallNodeJS20
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y gcc-c++ make
                    - curl -fsSL https://rpm.nodesource.com/setup_22.x | sudo bash -
                    - sudo yum install -y nodejs

##
# Image Builder
##

# FishingKaki Marketplace Image Recipe

  FishingKakiMarketPlaceImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Join [' ', [!Ref OrgName, 'fkmp-image']]
      Version: 2025.09.110
      ParentImage: !Join ['', ['arn:aws:imagebuilder:', !Ref AWS::Region, ':', !Ref AWS::AccountId, ':image/', !Ref OrgName, '-amazon-linux2023/2025.08.18']]
      WorkingDirectory: /tmp
      Description: !Join [' ', [!Ref OrgName, 'fishingkaki marketplace image']]
      Components: #Max 20
        - ComponentArn: !Ref ApacheComponent
        - ComponentArn: !Ref MariaDBClientComponent
        - ComponentArn: !Ref PHP83ComponentAL2023
        - ComponentArn: !Ref ComposerComponent
        - ComponentArn: !Ref SupervisorComponent
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            Encrypted: !If [IsImageShared, false, true]
            KmsKeyId: !If [IsImageShared, !Ref 'AWS::NoValue', !Join [':', ['arn:aws:kms', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'alias/aws/ebs']]]
            VolumeType: gp3
            VolumeSize: 8

# FishingKaki Classifieds Image Recipe

  # Frontend
  FishingKakiClassifiedsFEImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Join [' ', [!Ref OrgName, 'fkclassifieds-fe-image']]
      Version: 2025.09.17
      ParentImage: !Join ['', ['arn:aws:imagebuilder:', !Ref AWS::Region, ':', !Ref AWS::AccountId, ':image/', !Ref OrgName, '-amazon-linux2023/2025.08.18']]
      WorkingDirectory: /tmp
      Description: !Join [' ', [!Ref OrgName, 'fishingkaki classifieds frontend image']]
      Components: #Max 20
        - ComponentArn: !Ref NodeJS22Component
        - ComponentArn: !Ref NginxComponent
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            Encrypted: !If [IsImageShared, false, true]
            KmsKeyId: !If [IsImageShared, !Ref 'AWS::NoValue', !Join [':', ['arn:aws:kms', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'alias/aws/ebs']]]
            VolumeType: gp3
            VolumeSize: 8

  # Backend
  FishingKakiClassifiedsBEImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Join [' ', [!Ref OrgName, 'fkclassifieds-be-image']]
      Version: 2025.09.17
      ParentImage: !Join ['', ['arn:aws:imagebuilder:', !Ref AWS::Region, ':', !Ref AWS::AccountId, ':image/', !Ref OrgName, '-amazon-linux2023/2025.08.18']]
      WorkingDirectory: /tmp
      Description: !Join [' ', [!Ref OrgName, 'fishingkaki classifieds backend image']]
      Components: #Max 20
        - ComponentArn: !Ref ApacheComponent
        - ComponentArn: !Ref MariaDBClientComponent
        - ComponentArn: !Ref PHP83ComponentAL2023
        - ComponentArn: !Ref ComposerComponent
        - ComponentArn: !Ref SupervisorComponent
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            Encrypted: !If [IsImageShared, false, true]
            KmsKeyId: !If [IsImageShared, !Ref 'AWS::NoValue', !Join [':', ['arn:aws:kms', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'alias/aws/ebs']]]
            VolumeType: gp3
            VolumeSize: 8

# FishingKaki Marketplace Image Builder

  FishingKakiMarketPlaceImageBuilder:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/ec2-image-builder.yaml
      Parameters: 
        Name: fkmp
        EnvName: !Ref EnvName
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        ImageRecipeARN: !Ref FishingKakiMarketPlaceImageRecipe
        ShareImage: !Ref ShareImage
        SNSStackName: !Ref SNSStackName

# FishingKaki Classifieds Image Builder

  # Frontend
  FishingKakiClassifiedsFEImageBuilder:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/ec2-image-builder.yaml
      Parameters: 
        Name: fkclassifieds-fe
        EnvName: !Ref EnvName
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        ImageRecipeARN: !Ref FishingKakiClassifiedsFEImageRecipe
        ShareImage: !Ref ShareImage
        SNSStackName: !Ref SNSStackName

  # Backend
  FishingKakiClassifiedsBEImageBuilder:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/ec2-image-builder.yaml
      Parameters: 
        Name: fkclassifieds-be
        EnvName: !Ref EnvName
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        ImageRecipeARN: !Ref FishingKakiClassifiedsBEImageRecipe
        ShareImage: !Ref ShareImage
        SNSStackName: !Ref SNSStackName
