AWSTemplateFormatVersion: 2010-09-09
Description: CICS VPN Setup
Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Requester VPC
        Parameters:
          - RequesterNetworkStackName
      - Label:
          default: Target VPC
        Parameters:
          - TargetNetworkStackName
    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      RequesterNetworkStackName:
        default: Requester VPC network stack name
      TargetNetworkStackName:
        default: Target VPC network stack name

Parameters: 
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: cics-vpn
    MinLength: 3
    MaxLength: 20
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: pchc
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 12
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  RequesterNetworkStackName:
    Description: The name of the cloudformation Network stack
    Type: String
    Default: pchc-prd-ase1-cicsfe-network # edit for requester
  TargetNetworkStackName:
    Description: The name of the cloudformation Network stack
    Type: String
    Default: pchc-prd-ase1-cics-network # edit for accepter (terget)

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# VPC Peering
####


  VPCPeeringToCICSNetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/vpc-peering.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName

        # Requester VPC
        RequesterVpcId: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-VpcId'
        RequesterCidr: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-VpcCidrBlock'
        RequesterPublicRouteTable: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-PublicRouteTable'
        RequesterPrivateRouteTable1: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-PrivateRouteTable1'
        RequesterPrivateRouteTable2: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-PrivateRouteTable2'
        #RequesterPrivateRouteTable3: !ImportValue
        # 'Fn::Sub': '${RequesterNetworkStackName}-PrivateRouteTable3'

        # Target VPC
        TargetVpcId: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-VpcId'
        TargetCidr: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-VpcCidrBlock'
        TargetPublicRouteTable: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-PublicRouteTable'
        TargetPrivateRouteTable1: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-PrivateRouteTable1'
        TargetPrivateRouteTable2: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-PrivateRouteTable2'
        TargetPrivateRouteTable3: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-PrivateRouteTable3'

