AWSTemplateFormatVersion: 2010-09-09
Description: Build an SNS Topic and send notifications thru slack and email

Parameters: 
  name:
    Description: The name of the resource
    Type: String
    Default: snstopic
  environment:
    Description: The environment (production, staging, development, etc)
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
  envShort:
    Description: The environment (prd, stg, dev, etc)
    Type: String
    Default: prd
    AllowedValues:
      - prd
      - stg
      - dev
  organization:
    Description: The organization (iscale)
    Type: String
    Default: iscale
  regionShort:
    Description: Region where the the resource is hosted (eu1 - EU-Central-1, uw2 - US-West-2, uw1 - US-West-1)
    Type: String
    Default: uw2
  email:
    Description: The email address where to send the notifications
    Type: String
    Default: klarenz@iscale-solutions.com
  opsidianEndpoint:
    Description: The slack opsidian endpoint
    Type: String
    Default: https://api.opsidian.ai/sns/92435f38d03a73ac5a2eaa902c77ddf3

Resources:

  EventTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Id: Default
        Statement:
          - 
            Sid: __Default__1
            Effect: "Allow"
            Principal:
              Service: events.amazonaws.com
            Action: 
              - SNS:Publish
            Resource: !Ref snsTopic
          - 
            Sid: __Default__2
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action: 
              - SNS:Publish
            Resource: !Ref snsTopic
      Topics: [!Ref snsTopic]

  snsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join [ '-', [!Ref organization, !Ref envShort, !Ref regionShort,!Ref name] ]
      TopicName: !Join [ '-', [!Ref organization, !Ref envShort, !Ref regionShort,!Ref name] ]

  EmailSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: !Ref email
      Protocol: email
      TopicArn: !Ref snsTopic
  
  SlackSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: !Ref opsidianEndpoint
      Protocol: https
      TopicArn: !Ref snsTopic

Outputs:
  Arn: 
    Description: Arn of the SNS Topic
    Value: !Ref snsTopic
    Export:
      Name: !Sub "${AWS::StackName}-Arn"