  #This file is meant to contaain the common items in a typical AppServer setup. 
  #Do not nest this file, only include it.

  AppServerIamProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: AppServerIamRole


  DataS3Bucket:
    Type: AWS::S3::Bucket
    # This will become an issue if the stack is removed, then recreated. If retained, the bucket name will collide with the next instance of the stack
    # Recommend not specifying bucket name here for non-prod setups
    DeletionPolicy: Retain
    Properties:
      BucketName:
        Fn::If:
          - IsProd
          - Fn::Join: 
            - '-'
            - - Ref: OrgName
              - Fn::FindInMap: 
                - EnvShort
                - Ref: EnvName
                - Name
              - Fn::FindInMap:
                - RegionShort
                - Ref: 'AWS::Region'
                - Name 
              - Ref: Name
          - Ref: 'AWS::NoValue' #let the system choose a bucket name
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: 
            Fn::Join: 
              - '-'
              - - Ref: OrgName
                - Fn::FindInMap: 
                  - EnvShort
                  - Ref: EnvName
                  - Name
                - Fn::FindInMap:
                  - RegionShort
                  - Ref: 'AWS::Region'
                  - Name
                - Ref: Name
        - Key: Environment
          Value: 
            Ref: EnvName
        - Key: Organization
          Value: 
            Ref: OrgName
