  #This file is meant to contain the common items in a typical AppServer setup. 
  #Do not nest this file, only include it.

  AppServerIamProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: AppServerIamRole

  DataS3Bucket:
    Type: AWS::S3::Bucket
    # This will become an issue if the stack is removed, then recreated. If retained, the bucket name will collide with the next instance of the stack
    # Recommend not specifying bucket name here for non-prod setups
    DeletionPolicy: Retain
    Condition: UseInternalS3
    Properties:
      BucketName:
        Fn::If:
          - IsProd
          - Fn::Join: 
            - '-'
            - - Ref: OrgName
              - Fn::FindInMap: 
                - EnvShort
                - Ref: EnvName
                - Name
              - Fn::FindInMap:
                - RegionShort
                - Ref: 'AWS::Region'
                - Name 
              - Ref: Name
          - Ref: 'AWS::NoValue' #let the system choose a bucket name
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 3
          Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: 
            Fn::Join: 
              - '-'
              - - Ref: OrgName
                - Fn::FindInMap: 
                  - EnvShort
                  - Ref: EnvName
                  - Name
                - Fn::FindInMap:
                  - RegionShort
                  - Ref: 'AWS::Region'
                  - Name
                - Ref: Name
        - Key: Environment
          Value: 
            Ref: EnvName
        - Key: Organization
          Value: 
            Ref: OrgName

  AppServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        Fn::Join:
          - '-'
          - - Ref: OrgName
            - Fn::FindInMap: 
              - EnvShort
              - Ref: EnvName
              - Name
            - Fn::FindInMap:
              - RegionShort
              - Ref: 'AWS::Region'
              - Name
            - Ref: Name
            - appserver
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      Tags:
        - Key: Name
          Value: 
            Fn::Join: 
              - '-'
              - - Ref: OrgName
                - Fn::FindInMap: 
                  - EnvShort
                  - Ref: EnvName
                  - Name
                - Fn::FindInMap:
                  - RegionShort
                  - Ref: 'AWS::Region'
                  - Name
                - Ref: Name
                - appserver
        - Key: Environment
          Value: 
            Ref: EnvName
        - Key: Organization
          Value: 
            Ref: OrgName

  AppServerSecurityGroupHTTPIngress:
    Condition: HasLoadBalancerStackName
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId: 
        Fn::GetAtt: 
          - AppServerSecurityGroup
          - GroupId
      IpProtocol: TCP
      FromPort:
        Ref: InstancePort
      ToPort:
        Ref: InstancePort
      SourceSecurityGroupId:
        Fn::ImportValue:
          Fn::Sub: "${LoadBalancerStackName}-SecurityGroupId"
      Description: Allow connection from Load Balancer

  AppServerSecurityGroupSSHIngress: # Iannis - Make this conditionnal if can debug
    Type: AWS::EC2::SecurityGroupIngress
    Condition: IsNotProd
    Properties:
      GroupId:
        Fn::GetAtt:
          - AppServerSecurityGroup
          - GroupId
      IpProtocol: TCP
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0

  AppServerSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId:
        Fn::GetAtt:
          - AppServerSecurityGroup
          - GroupId
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      CidrIp: 0.0.0.0/0

  RDSSecurityGroupAllowAppServerIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: DatabaseSecurityGroupId
      IpProtocol: tcp
      FromPort:
        Ref: DatabasePort
      ToPort:
        Ref: DatabasePort
      SourceSecurityGroupId:
        Ref: AppServerSecurityGroup
      Description: Allow DB connection from App Servers

  AppServerIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 1
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: AccessCloudWatchMetrics
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                  - ec2:DescribeTags
                  - autoscaling:DescribeTags
                  - rds:DescribeDBClusters
                Resource: "*"
        - PolicyName: S3BucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject*
                  - s3:ListBucket
                  - s3:PutObject*
                  - s3:DeleteObject
                Resource: 
                  Fn::If:
                    - UseInternalS3
                    - - Fn::Join:
                        - '/'
                        - - Fn::GetAtt:
                            - DataS3Bucket
                            - Arn
                          - '*'
                      - Fn::GetAtt:
                        - DataS3Bucket
                        - Arn
                    - - Fn::Join:
                        - '/'
                        - - Ref: ExternalS3BucketArn
                          - '*'
                      - Ref: ExternalS3BucketArn
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLocation
                Resource: "arn:aws:s3:::*"
        - PolicyName: DeploymentResourcesAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObject*
                Resource: #Assume naming convention since deployment bucket follows this. Else we would have to read it from the deployment stack
                  Fn::Join:
                    - ''
                    - - "arn:aws:s3:::"
                      - Ref: OrgName
                      - '-'
                      - Fn::FindInMap:
                        - EnvShort
                        - Ref: EnvName
                        - Name
                      - '-'
                      - Fn::FindInMap:
                        - RegionShort
                        - Ref: 'AWS::Region'
                        - Name
                      - '-'
                      - Ref: Name
                      - "-code-deploy/*"
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStackResource
                Resource: '*'
        - PolicyName: WriteCloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: AccessSecrets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  Fn::Join:
                    - ':'
                    - - "arn:aws:secretsmanager"
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - secret
                      - Fn::If:
                        - HasSharedSecretId
                        - Fn::Join:
                          - '-'
                          - - Ref: SharedSecretId
                            - "*"
                        - Fn::Join:
                          - '-'
                          - - Ref: OrgName
                            - Fn::FindInMap:
                              - EnvShort
                              - Ref: EnvName
                              - Name
                            - Fn::FindInMap:
                              - RegionShort
                              - Ref: 'AWS::Region'
                              - Name
                            - Ref: Name
                            - "*"

  ####
  # EFS Section
  ####

  EFSSecurityGroup:
    Condition: UseInternalEFS
    Type: AWS::EC2::SecurityGroup
    Properties:
      #GroupDescription: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, efs]]
      GroupDescription:
        Fn::Join:
          - '-'
          - - Ref: OrgName
            - Fn::FindInMap:
              - EnvShort
              - Ref: EnvName
              - Name
            - Fn::FindInMap:
              - RegionShort
              - Ref: 'AWS::Region'
              - Name
            - Ref: Name
            - efs
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - Ref: OrgName
                - Fn::FindInMap:
                  - EnvShort
                  - Ref: EnvName
                  - Name
                - Fn::FindInMap:
                  - RegionShort
                  - Ref: 'AWS::Region'
                  - Name
                - Ref: Name
                - efs
        - Key: Environment
          Value:
            Ref: EnvName
        - Key: Organization
          Value:
            Ref: OrgName
  
  InternalEFSSecurityGroupIngress:
    Condition: UseInternalEFS
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::GetAtt:
          - EFSSecurityGroup
          - GroupId
      IpProtocol: TCP
      FromPort: 2049
      ToPort: 2049
      SourceSecurityGroupId:
        Fn::GetAtt:
          - AppServerSecurityGroup
          - GroupId
  
  ExternalEFSSecurityGroupIngress:
    Condition: UseExternalEFS
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Ref: ExternalEFSSecurityGroup
      IpProtocol: TCP
      FromPort: 2049
      ToPort: 2049
      SourceSecurityGroupId:
        Fn::GetAtt:
        - AppServerSecurityGroup
        - GroupId
  
  AppServerFileSystem:
    Condition: UseInternalEFS
    Type: AWS::EFS::FileSystem
    DeletionPolicy: Retain
    Properties:
      BackupPolicy:
        Status: 
          Fn::If:
            - IsProd
            - ENABLED
            - DISABLED
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
      FileSystemTags:
        - Key: Name
          Value:
            Fn::Join:
              - '-'
              - - Ref: OrgName
                - Fn::FindInMap:
                  - EnvShort
                  - Ref: EnvName
                  - Name
                - Fn::FindInMap:
                  - RegionShort
                  - Ref: 'AWS::Region'
                  - Name
                - Ref: Name
                - efs
        - Key: Environment
          Value:
            Ref: EnvName
        - Key: Organization
          Value:
            Ref: OrgName

  EFSMountTarget1:
    Condition: UseInternalEFS
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: AppServerFileSystem
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-InternalSubnetId1"
      SecurityGroups:
        - Ref: EFSSecurityGroup

  EFSMountTarget2:
    Condition: UseInternalEFS
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: AppServerFileSystem
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-InternalSubnetId2"
      SecurityGroups:
        - Ref: EFSSecurityGroup

  #####
  # Link the setup to the Load Balancer
  #####
  LoadBalancerDNSRecord:
    Condition: HasLoadBalancerStackName
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName:
        Fn::Join:
          - ''
          - - Ref: ClientDomainName
            - '.'
      RecordSets:
        - Name:
            Fn::If:
              - HasLoadBalancerHostName
              - Fn::Join:
                  - '.'
                  - - Ref: LoadBalancerHostName
                    - Ref: ClientDomainName
              - Fn::Join:
                  - '.'
                  - - Fn::Join:
                      - '-'
                      - - Ref: Name
                        - Fn::FindInMap:
                          - EnvShort
                          - Ref: EnvName
                          - Name
                    - Ref: ClientDomainName
          Type: A
          AliasTarget:
            HostedZoneId:
              Fn::ImportValue:
                Fn::Sub: "${LoadBalancerStackName}-CanonicalHostedZoneID"
            DNSName:
              Fn::ImportValue:
                Fn::Sub: "${LoadBalancerStackName}-DNSName"

  ELBSSLListenerRule:
    Condition: HasLoadBalancerStackName
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      Actions:
        - Type: forward
          TargetGroupArn: 
            Ref: AppServerTargetGroup
      Conditions: 
        - Field: host-header
          Values:
            - Fn::If:
              - HasLoadBalancerHostName
              - Fn::Join:
                  - '.'
                  - - Ref: LoadBalancerHostName
                    - Ref: ClientDomainName
              - Fn::Join:
                  - '.'
                  - - Fn::Join:
                      - '-'
                      - - Ref: Name
                        - Fn::FindInMap:
                          - EnvShort
                          - Ref: EnvName
                          - Name
                    - Ref: ClientDomainName
      ListenerArn:
        Fn::ImportValue:
          Fn::Sub: "${LoadBalancerStackName}-ApplicationListenerArn"
      Priority:
        Ref: LoadBalancerPriority