AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for empleyo.net

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: dns
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: empleyo
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
  DomainName:
    Description: The domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: empleyo.net

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref DomainName]]
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], hostedzone]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  HostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref HostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:489336767866:key/52683884-d204-4e05-875b-33625197293f
      Name: key_signing_key
      Status: ACTIVE

  HostedZoneDNSSEC:
    DependsOn: HostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref HostedZone

  GoogleWorkspaceMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: Google Workspace MX Records
      Name: !Ref DomainName
      Type: MX
      TTL: 43200
      ResourceRecords:
        - 1 SMTP.GOOGLE.COM
        - 15 ba4x3mg3ggi5ncc3pmbmpsx6x6gzvqu5mjflh4hsrgy5btthtdkq.mx-verification.google.com.

  DMARCRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: DMARC record
      Name: !Join ['.', [_dmarc, !Ref DomainName]]
      Type: TXT
      TTL: 14400
      ResourceRecords:
        - !Join ['', ["\"v=DMARC1;p=reject;pct=100;fo=1;rua=mailto:dmarc@", !Ref DomainName, "\""]]

  DomainTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      ResourceRecords:
        - '"klaviyo-site-verification=VpmJj2"'
      TTL: 14400
      Type: TXT
      Comment: Domain TXT Record

  GmailDKIMRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', [google._domainkey, !Ref DomainName]]
      ResourceRecords:
        - '"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCpBa8ejQAiN5Ol8ooUqZO84+ccziLnVIL5HYpi2JrrebXUygj72e5EUYpoh8IapFkMw+0MBJR2QSkUI+DXGhTWkhvFP79XpHj/KxyJe3hJysW86SLhrQo24zPB5V6eQqOYn8mYozwLkwWSYOY8aHxy5PX8hr8pYMEhGF+xeNVkQIDAQAB"'
      TTL: 14400
      Type: TXT
      Comment: Google Workspace Mail DKIM Record

### 
# Sendgrid
###

  SendgridSendRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[send, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - u161779.wl030.sendgrid.net

  SendgridDomainKeyRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[kl, _domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - kl.domainkey.u161779.wl030.sendgrid.net

  SendgridDomainKeyRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[kl2, _domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - kl2.domainkey.u161779.wl030.sendgrid.net

  OdooSSLValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_61a579c688385087cda61ae6726e08ae.odoo, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _e33dc5b5196c6c29df1b34522806f1ef.mhbtsbpdnt.acm-validations.aws.

  # SESDomainVerificationRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join ['.',[_amazonses, !Ref DomainName]]
  #     ResourceRecords:
  #       - '"SVaBAMnYLuRuHmq4QPvuug96412TPFH6M0W+mHst+DI="' #Employ us-west-2
  #       - '"545ISXQ14A0jt+72ZmXum25VhYCOWrm1yGI24ruvBrw="' #iScale Hosting us-west-2
  #     TTL: 14400
  #     Type: TXT
  #     Comment: SES Domain Verification

  SESDKIMRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[xz52upbf5j3zh76dmnbb3l6o4hlwywlt._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - xz52upbf5j3zh76dmnbb3l6o4hlwywlt.dkim.amazonses.com

  SESDKIMRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[to6vbshia7nz223i3rps5hckrhqsdmyp._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - to6vbshia7nz223i3rps5hckrhqsdmyp.dkim.amazonses.com

  SESDKIMRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[rb6r2jnufi3dry2ebtipccz4icm7pqoa._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - rb6r2jnufi3dry2ebtipccz4icm7pqoa.dkim.amazonses.com

  # SESHostingDKIMRecord1:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join ['.',[ceepikwuddabuijgvqvb377bkmvfpxco._domainkey, !Ref DomainName]]
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - ceepikwuddabuijgvqvb377bkmvfpxco.dkim.amazonses.com

  # SESHostingDKIMRecord2:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join ['.',[3l643zrnvijhxvxeyqkwz3qyajns3t7m._domainkey, !Ref DomainName]]
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - 3l643zrnvijhxvxeyqkwz3qyajns3t7m.dkim.amazonses.com

  # SESHostingDKIMRecord3:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join ['.',[su76sloo5yogcz6zpdtpwifeicd5ota5._domainkey, !Ref DomainName]]
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - su76sloo5yogcz6zpdtpwifeicd5ota5.dkim.amazonses.com

  ###
  # WWW records are pointing to the Wordpress.com account
  ###

  WWWRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', [www, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - !Ref DomainName

  WWWNoRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      TTL: 14400
      ResourceRecords:
        - 192.0.78.24
        - 192.0.78.25