AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for employ.global

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: dns
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: employ
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
  DomainName:
    Description: The domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: employ.global

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref DomainName]]
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], hostedzone]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  HostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref HostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:489336767866:key/52683884-d204-4e05-875b-33625197293f
      Name: key_signing_key
      Status: ACTIVE

  HostedZoneDNSSEC:
    DependsOn: HostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref HostedZone

  GoogleWorkspaceMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: Google Workspace MX Records
      Name: !Ref DomainName
      Type: MX
      TTL: 14400
      ResourceRecords:
        - 1 ASPMX.L.GOOGLE.COM
        - 5 ALT1.ASPMX.L.GOOGLE.COM.
        - 5 ALT2.ASPMX.L.GOOGLE.COM.
        - 10 ALT3.ASPMX.L.GOOGLE.COM.
        - 10 ALT4.ASPMX.L.GOOGLE.COM.

  DMARCRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: DMARC record
      Name: !Join ['.', [_dmarc, !Ref DomainName]]
      Type: TXT
      TTL: 14400
      ResourceRecords:
        - !Join ['', ["\"v=DMARC1;p=none;rua=mailto:dmarc@", !Ref DomainName, "\""]]

  DomainTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      ResourceRecords:
        - '"v=spf1 include:_spf.google.com include:emsd1.com include:amazonses.com ~all"'
      TTL: 14400
      Type: TXT
      Comment: Domain TXT Record

  GmailDKIMRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', [google._domainkey, !Ref DomainName]]
      ResourceRecords:
        - '"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCLxB09/ypwPmqX9NZBrLLMMTHZoi0Oe8EH7RPcN/Lee01CIs/b5wuZokhCeGbaGZmm9PmkakxRr8BSA3wEPOJUXeo6sYADWU5DuDtVjeFhgyp609S0WGompyz6ABOAXy56N7vmqYNJHjTRlyHf9Sc3cl+NEyW+kt8aTARWWQHm2QIDAQAB"'
      TTL: 14400
      Type: TXT
      Comment: Gmail DKIM Record

  ActiveHostedEmailCNAME:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[email, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - employ60416.activehosted.com.

  ActiveCampaignDKIM1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[acdkim1._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - dkim.acdkim1.acems1.com

  ActiveCampaignDKIM2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[acdkim2._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - dkim.acdkim2.acems1.com

  HostingSSLValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_17819dc11b9490c3915f1582f7f4f309, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _4bd0d39bdca26bb98ba7be8941ee15d9.zzxlnyslwt.acm-validations.aws.

  WildcardSSLValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_19e0d00e349028d0464c22859db05c1a, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _72bb2c46b68c326892f3c2a8e055e58b.hkmpvcwbzw.acm-validations.aws.

  SESDomainVerificationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_amazonses, !Ref DomainName]]
      ResourceRecords:
        - '"SVaBAMnYLuRuHmq4QPvuug96412TPFH6M0W+mHst+DI="' #Employ us-west-2
        - '"545ISXQ14A0jt+72ZmXum25VhYCOWrm1yGI24ruvBrw="' #iScale Hosting us-west-2
      TTL: 14400
      Type: TXT
      Comment: SES Domain Verification

  SESDKIMRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[zktbgbgq6azaqctl7yrizkzo6ufla272._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - zktbgbgq6azaqctl7yrizkzo6ufla272.dkim.amazonses.com

  SESDKIMRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[agy2gsr2fkj6r77vhibb6ld7gbzywzr5._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - agy2gsr2fkj6r77vhibb6ld7gbzywzr5.dkim.amazonses.com

  SESDKIMRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[pzuopz4zpbwakxnxezthcrf7kmw5glf5._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - pzuopz4zpbwakxnxezthcrf7kmw5glf5.dkim.amazonses.com

  SESHostingDKIMRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[ceepikwuddabuijgvqvb377bkmvfpxco._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - ceepikwuddabuijgvqvb377bkmvfpxco.dkim.amazonses.com

  SESHostingDKIMRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[3l643zrnvijhxvxeyqkwz3qyajns3t7m._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - 3l643zrnvijhxvxeyqkwz3qyajns3t7m.dkim.amazonses.com

  SESHostingDKIMRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[su76sloo5yogcz6zpdtpwifeicd5ota5._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - su76sloo5yogcz6zpdtpwifeicd5ota5.dkim.amazonses.com

  ###
  # WWW records are pointing to the Wordpress.com account
  ###

  WWWRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', [www, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - !Ref DomainName

  WWWNoRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      TTL: 14400
      ResourceRecords:
        - 192.0.78.139
        - 192.0.78.224