AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions a hosted domain

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: "Resource Configuration"
        Parameters:
          - Name
          - OrgName
          - EnvName
      -
        Label:
          default: "Domain Configuration"
        Parameters:
          - DomainName
          - HostedZoneType
      -
        Label:
          default: "Cloudformation Stack Configuration"
        Parameters:
          - NetworkStackName

    ParameterLabels:
      Name:
        default: "Name"
      OrgName:
        default: "Organization Name"
      EnvName:
        default: "Environment Name"
      DomainName:
        default: "The name of the domain"
      HostedZoneType:
        default: "Hosted Zone Type"
      NetworkStackName:
        default: "Network Stack Name"

Parameters: 
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: domain
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-hosting
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The name of the domain
    Type: String
    Default: iscale-hosting.com
  HostedZoneType:
    Description: AMI image used to instantiate the ASG instance
    Type: String
    Default: public
    AllowedValues:
      - public
      - private
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: iscale-hosting-prd-uw2-internal-network

Conditions: 
  IsPublic: !Equals [!Ref HostedZoneType, public]
  IsPrivate: !Equals [!Ref HostedZoneType, private]

Mappings: 
  EnvShort:
    Production:
      Name: prd
    Staging:
      Name: stg
    Development:
      Name: dev
    Test:
      Name: test
  RegionShort:
    us-east-2:
      Name: ue2
    us-east-1:
      Name: ue1
    us-west-1:
      Name: uw1
    us-west-2:
      Name: uw2
    ap-east-1:
      Name: ae1
    ap-south-1:
      Name: as1
    ap-northeast-1:
      Name: ane1
    ap-northeast-2:
      Name: ane2
    ap-northeast-3:
      Name: ane3
    ap-southeast-1:
      Name: ase1
    ap-southeast-2:
      Name: ase2
    ca-central-1:
      Name: cc1
    cn-north-1:
      Name: cn1
    cn-northwest-1:
      Name: cnw1
    eu-central-1:
      Name: ec1
    eu-west-1:
      Name: ew1
    eu-west-2:
      Name: ew2
    eu-west-3:
      Name: ew3
    eu-north-1:
      Name: en1
    me-south-1:
      Name: ms1
    sa-east-1:
      Name: se1
    us-gov-east-1:
      Name: uge1
    us-gov-west-1:
      Name: ugw1 

Resources:

####
# Route53 Section
####

  DefaultPrivateHostedZone:
    Type: "AWS::Route53::HostedZone"
    Condition: IsPrivate
    Properties: 
      HostedZoneConfig: 
        Comment: Hosted zone for iscale-hosting
      Name: !Ref DomainName
      VPCs: 
        - 
          VPCId:
            Fn::ImportValue:
              !Sub "${NetworkStackName}-VpcId"
          VPCRegion: !Ref 'AWS::Region'
      HostedZoneTags: 
        - 
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
        - 
          Key: Environment
          Value: !Ref EnvName
        - 
          Key: Organization
          Value: !Ref OrgName

  DefaultPublicHostedZone:
    Type: "AWS::Route53::HostedZone"
    Condition: IsPublic
    Properties: 
      HostedZoneConfig: 
        Comment: Hosted zone for iscale-hosting
      Name: !Ref DomainName
      HostedZoneTags: 
        - 
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
        - 
          Key: Environment
          Value: !Ref EnvName
        - 
          Key: Organization
          Value: !Ref OrgName

Outputs:

  # Outputs for private zone type
  HostedZoneId:
    Condition: IsPrivate
    Description: The private hosted zone ID
    Value: !Ref DefaultPrivateHostedZone
    Export:
      Name: !Sub "${AWS::StackName}-PrivateHostedZoneId"

  NameServers:
    Condition: IsPrivate
    Description: The private hosted Name Servers
    Value: !Join
      - ','
      - !GetAtt  DefaultPrivateHostedZone.NameServers
    Export:
      Name: !Sub "${AWS::StackName}-PrivateNameServers"

  # Outputs for public zone type
  HostedZoneId:
    Condition: IsPublic
    Description: The public hosted zone ID
    Value: !Ref DefaultPublicHostedZone
    Export:
      Name: !Sub "${AWS::StackName}-PublicHostedZoneId"

  NameServers:
    Condition: IsPublic
    Description: The public hosted Name Servers
    Value: !Join
      - ','
      - !GetAtt  DefaultPublicHostedZone.NameServers
    Export:
      Name: !Sub "${AWS::StackName}-PublicNameServers"