AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions an IAM Group

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName

    ParameterLabels:
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-hosting
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:
  
  AccessToVolendraSharedS3:
    Type:  AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: AccessToVolendraSharedS3
      Roles:
        - !Ref OdooAdminRole
        - !Ref OdooUserRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - arn:aws:s3:::volendra-s3-shared
              - arn:aws:s3:::volendra-s3-shared/*

  OdooAdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], odoo-admin-role]]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: 1
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: arn:aws:iam::338284463834:root
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess
      Policies:
        - PolicyName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], odoo-admin-policy]]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: SSMAccess
                Effect: Allow
                Action: 
                  - ssm:StartSession
                  - ec2:*
                  - elasticloadbalancing:*
                Resource: '*'
                Condition:
                  StringEquals:
                    ssm:resourceTag/Name:
                      - iscale-prd-uw2-zion13
                      - iscale-prd-uw2-zion14
                      - iscale-hosting-prd-uw2-odoo14e
                      - iscale-hosting-prd-uw2-hoa-odoo
              - Sid: TerminateSSM
                Effect: Allow
                Action:
                  - ssm:TerminateSession
                Resource:
                  - arn:aws:ssm:*:*:session/${aws:username}-*
              - Sid: ManageEC2Instance
                Effect: Allow
                Action: 
                  - ec2:*
                  - elasticloadbalancing:*
                Resource: '*'
                Condition:
                  StringEquals:
                    ec2:resourceTag/Name:
                      - iscale-prd-uw2-zion13
                      - iscale-prd-uw2-zion14
                      - iscale-hosting-prd-uw2-odoo14e
                      - iscale-hosting-prd-uw2-hoa-odoo
              - Sid: ManageAutoScalingGroups
                Effect: Allow
                Action: 
                  - autoscaling:*
                Resource: '*'
                Condition:
                  StringEquals:
                    autoscaling:resourceTag/Name: 
                      - iscale-prd-uw2-zion13
                      - iscale-prd-uw2-zion14
                      - iscale-hosting-prd-uw2-odoo14e
                      - iscale-hosting-prd-uw2-hoa-odoo
              - Sid: ManageRDS
                Effect: Allow
                Action: 
                  - rds:*
                Resource: !Join [':', ['arn:aws:rds', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'db:iscale-hosting-prd-uw2-payroll']]
              - Sid: InvokePayrollBlur
                Effect: Allow
                Action: 
                  - lambda:InvokeFunction
                Resource:
                  - !Join [':', ['arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function:iscale-prd-uw2-zion13-blur']]
                  - !Join [':', ['arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function:iscale-prd-uw2-zion14-blur']]
                  - !Join [':', ['arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function:iscale-hosting-prd-uw2-odoo14e-blur']]
              - Sid: AccessS3
                Effect: Allow
                Action:
                  - s3:Delete*
                  - s3:Get*
                  - s3:Put*
                  - s3:List*
                Resource:
                  - arn:aws:s3:::iscale-hosting-prd-uw2-odoo14e/volendra/*
                  - arn:aws:s3:::iscale-prd-uw2-zion13/volendra/*
                  - arn:aws:s3:::iscale-prd-uw2-zion14/volendra/*
              - Sid: ExplicityDeny
                Effect: Deny
                Action: 
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - autoscaling:CreateTags
                  - autoscaling:DeleteTags
                  - elasticloadbalancing:CreateTags
                  - elasticloadbalancing:DeleteTags
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], payroll-odoo-admin-role]]
        
  OdooUserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], odoo-user-role]]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: 1
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: arn:aws:iam::338284463834:root
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess
      Policies:
        - PolicyName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], payroll-odoo-user-policy]]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: InvokePayrollBlur
                Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Join [':', ['arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function:iscale-prd-uw2-zion13-blur']]
                  - !Join [':', ['arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function:iscale-prd-uw2-zion14-blur']]
                  - !Join [':', ['arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function:iscale-hosting-prd-uw2-odoo14e-blur']]
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], payroll-odoo-user-role]]