AWSTemplateFormatVersion: 2010-09-09
Description: PDDTS Resources pchc-prd-ase1-pddts

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName
      - Label:
          default: Load Balancer Configuration
        Parameters:
          - ClientDomainName
          - LoadBalancerCertificateArn
          - LoadBalancerHostName
      - Label:
          default: Instance Configuration
        Parameters:
          - InstanceKeyName
          - InstanceAMI
      - Label:
          default: Scheduler Configuration
        Parameters:
          - StartScheduleExpression
          - StopScheduleExpression

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      InstanceAMI:
        default: Instance AMI ID
      InstanceKeyName:
        default: Instance Key Name
      LoadBalancerCertificateArn:
        default: Load Balancer SSL Certificate ARN
      LoadBalancerHostName:
        default: Load Balancer Host Name
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Topic Stack Name
      ClientDomainName:
        default: Domain Name
      StartScheduleExpression:
        default: Start Schedule CRON Expression
      StopScheduleExpression:
        default: Stop Schedule CRON Expression

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name)
    Type: String
    MinLength: 3
    MaxLength: 9
    Default: pddts
  OrgName:
    Description: The name of the organization
    Type: String
    Default: pchc
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-software.com)
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: pchcdev.com
    MinLength: 1
  InstanceAMI:
    Description: Instance AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-00b8d9cb8a7161e41 #Default Amazon Linux 2 for Singapore
  InstanceKeyName:
    Description: Instance Key Name
    Type: String
    Default: ''
  LoadBalancerHostName:
    Description: (Optional) Custom Hostname for load balancer URL
    Type: String
    Default: ''
    MaxLength: 12
  LoadBalancerCertificateArn:
    Description: SSL Certificate for the ELB
    Type: String
    Default: arn:aws:acm:ap-southeast-1:470455329885:certificate/9f713d5d-cb7c-4e8e-acc2-46862d610ec8
  NetworkStackName:
    Description: The name of the network stack
    Type: String
    Default: pchc-dev-ase1-network
    MinLength: 1
  SNSStackName:
    Description: The name of the SNS stack
    Type: String
    Default: pchc-dev-ase1-sns
    MinLength: 1
  StartScheduleExpression:
    Description: Schedule expression when to start the objects
    Type: String
    Default: cron(0 0 ? * MON-FRI *)
  StopScheduleExpression:
    Description: Schedule expression when to stop the objects
    Type: String
    Default: cron(0 10 ? * MON-FRI *)

# Mappings:
#   Fn::Transform:
#     Name: AWS::Include
#     Parameters:
#       Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Mappings:
    #Short names for environment
  EnvShort:
    Production:
      Name: prd
    Staging:
      Name: stg
    Development:
      Name: dev
    Test:
      Name: test
  
  EnvLowerCase:
    Production:
      Name: production
    Staging:
      Name: staging
    Development:
      Name: development
    Test:
      Name: test

  #Short names for regions
  RegionShort:
    us-east-2:
      Name: ue2
    us-east-1:
      Name: ue1
    us-west-1:
      Name: uw1
    us-west-2:
      Name: uw2
    ap-east-1:
      Name: ae1
    ap-south-1:
      Name: as1
    ap-northeast-1:
      Name: ane1
    ap-northeast-2:
      Name: ane2
    ap-northeast-3:
      Name: ane3
    ap-southeast-1:
      Name: ase1
    ap-southeast-2:
      Name: ase2
    ca-central-1:
      Name: cc1
    cn-north-1:
      Name: cn1
    cn-northwest-1:
      Name: cnw1
    eu-central-1:
      Name: ec1
    eu-west-1:
      Name: ew1
    eu-west-2:
      Name: ew2
    eu-west-3:
      Name: ew3
    eu-north-1:
      Name: en1
    me-south-1:
      Name: ms1
    sa-east-1:
      Name: se1
    us-gov-east-1:
      Name: uge1
    us-gov-west-1:
      Name: ugw1 

  # Short Name for ELB
  ElbTypeShort:
    application:
      Name: alb
    network:
      Name: nlb

# Conditions:
#   Fn::Transform:
#     Name: AWS::Include
#     Parameters:
#       Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Conditions:
  IsDev:
    Fn::Equals:
      - Ref: EnvName
      - Development
  IsTest:
    Fn::Equals:
      - Ref: EnvName
      - Test
  IsStaging:
    Fn::Equals:
      - Ref: EnvName
      - Staging
  IsProd: 
    Fn::Equals:
      - Ref: EnvName
      - Production
  IsNotDev: 
    Fn::Not:
      - Condition: IsDev
  IsNotTest: 
    Fn::Not:
      - Condition: IsTest
  IsNotStaging: 
    Fn::Not:
      - Condition: IsStaging
  IsNotProd: 
    Fn::Not:
      - Condition: IsProd
  IsStagingOrProd: 
    Fn::Or:
      - Condition: IsStaging
      - Condition: IsProd
  IsDevOrStaging:
    Fn::Or:
      - Condition: IsDev
      - Condition: IsStaging

Resources:

  ###
  # Custom Network resources for BSP
  ###

  StrongSwanPublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: StrongSwan Public Security Group
        VpcId: 
          Fn::ImportValue:
            !Sub "${NetworkStackName}-VpcId"
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          - IpProtocol: icmp
            FromPort: -1
            ToPort: -1
            CidrIp: 0.0.0.0/0

  StrongSwanAZ1ENI:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: !Join
        - ' '
        - - BSP Access ENI
          - !Select
            - 0
            - Fn::GetAZs: !Ref 'AWS::Region'
      GroupSet:
        - !Ref StrongSwanPublicSecurityGroup
      PrivateIpAddress: 10.5.12.145
      SourceDestCheck: false
      SubnetId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-PublicSubnetId1"
      Tags:
        - Key: Name
          Value: StrongSwan public ENI

  StrongSwanAZ2ENI:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: !Join
        - ' '
        - - BSP Access ENI
          - !Select
            - 1
            - Fn::GetAZs: !Ref 'AWS::Region'
      GroupSet:
        - !Ref StrongSwanPublicSecurityGroup
      PrivateIpAddress: 10.5.13.100
      SourceDestCheck: false
      SubnetId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-PublicSubnetId2"
      
      Tags:
        - Key: Name
          Value: StrongSwan public ENI

  BSPVPNGatewayEIP1: # - Hardcoded for BSP
    DeletionPolicy: Retain #Make sure to retain always
    # Condition: IsProd
    Type: AWS::EC2::EIP

  BSPVPNGatewayEIP2: # - Hardcoded for BSP
    DeletionPolicy: Retain #Make sure to retain always
    # Condition: IsProd
    Type: AWS::EC2::EIP

  BSPRouteTableAZ1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VpcId"
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, bsp, route, table, a]]

  BSPRouteTableAZ2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VpcId"
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, bsp, route, table, b]]
  
  BSPRouteAssociationInternalSubnetAZ1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        Fn::ImportValue:
          !Sub "${NetworkStackName}-InternalSubnetId1"
      RouteTableId: !Ref BSPRouteTableAZ1

  BSPRouteAssociationInternalSubnetAZ2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        Fn::ImportValue:
          !Sub "${NetworkStackName}-InternalSubnetId2"
      RouteTableId: !Ref BSPRouteTableAZ2

  BSPRouteAssociationPublicSubnetAZ1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        Fn::ImportValue:
          !Sub "${NetworkStackName}-PublicSubnetId1"
      RouteTableId: !Ref BSPRouteTableAZ1

  BSPRouteAssociationPublicSubnetAZ2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        Fn::ImportValue:
          !Sub "${NetworkStackName}-PublicSubnetId2"

      RouteTableId: !Ref BSPRouteTableAZ2

  BSPRouteAssociationPrivateSubnetAZ1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        Fn::ImportValue:
          !Sub "${NetworkStackName}-PrivateSubnetId1"
      RouteTableId: !Ref BSPRouteTableAZ1

  BSPRouteAssociationPrivateSubnetAZ2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        Fn::ImportValue:
          !Sub "${NetworkStackName}-PrivateSubnetId2"
      RouteTableId: !Ref BSPRouteTableAZ2

  ##
  # BSP Target Resources
  ##

  BSP3rdPartyRouteAZ1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref BSPRouteTableAZ1
      DestinationCidrBlock: 192.168.4.100/32
      NetworkInterfaceId: !Ref StrongSwanAZ1ENI

  BSP3rdPartyRouteAZ2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref BSPRouteTableAZ2
      DestinationCidrBlock: 192.168.4.100/32
      NetworkInterfaceId: !Ref StrongSwanAZ2ENI

  BSPPhilPassPlusRouteAZ1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref BSPRouteTableAZ1
      DestinationCidrBlock: 192.168.80.200/32
      NetworkInterfaceId: !Ref StrongSwanAZ1ENI

  BSPPhilPassPlusRouteAZ2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref BSPRouteTableAZ2
      DestinationCidrBlock: 192.168.80.200/32
      NetworkInterfaceId: !Ref StrongSwanAZ2ENI

  ##
  # StrongSwan EC2 instances
  ##
  
  StrongSwanEC2SSMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      RoleName: StrongSwanEC2SSMRole

  StrongSwanInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref StrongSwanEC2SSMRole
      InstanceProfileName: StrongSwanInstanceProfile

  StrongSwanInstanceAZ1:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref StrongSwanInstanceProfile
      KeyName: !Ref InstanceKeyName
      ImageId: ami-02f26adf094f51167
      InstanceType: t3.micro
      NetworkInterfaces:
        - DeviceIndex: 0
          NetworkInterfaceId: !Ref StrongSwanAZ1ENI
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, BSP, gateway, a]]
  
  StrongSwanPublicEIPAttachAZ1:
    Type: AWS::EC2::EIPAssociation
    Properties:
      NetworkInterfaceId: !Ref StrongSwanAZ1ENI
      AllocationId: !GetAtt BSPVPNGatewayEIP1.AllocationId

  StrongSwanInstanceAZ2:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref StrongSwanInstanceProfile
      KeyName: !Ref InstanceKeyName
      ImageId: ami-02f26adf094f51167
      InstanceType: t3.micro
      NetworkInterfaces:
        - DeviceIndex: 0
          NetworkInterfaceId: !Ref StrongSwanAZ2ENI
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, BSP, gateway, b]]
  
  StrongSwanPublicEIPAttachAZ2:
    Type: AWS::EC2::EIPAssociation
    Properties:
      NetworkInterfaceId: !Ref StrongSwanAZ2ENI
      AllocationId: !GetAtt BSPVPNGatewayEIP2.AllocationId

  ##
  # PDDTS Application Resources
  ##

  ELBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/loadbalancer.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        CertificateArn: !Ref LoadBalancerCertificateArn
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/database.yaml
      Parameters:
        Name: !Ref Name
        DatabaseName: !Join ['',[!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name], db]]
        AllocatedStorage: 20
        BackupRetentionPeriod: !If [IsProd, 30, 7]
        EnableCPUCreditAlarm: !If [IsProd, true, false]
        EnableEnhancedMonitoring: !If [IsProd, true, false]
        EnablePerformanceInsights: !If [IsProd, true, false]
        EnvName: !Ref EnvName
        Engine: mysql
        EngineVersion: 8.0.20
        Family: mysql8.0
        InstanceType: !If [IsProd, db.t3.medium, db.t3.micro]
        MasterUser: root
        MultiAz: !If [IsProd, true, false]
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        SNSStackName: !Ref SNSStackName
        StorageEncrypted: true

  # DBSchedulerStack:
  #   DependsOn:
  #     - DBStack
  #   Condition: IsNotProd
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
  #     Parameters:
  #       Name: !Ref Name
  #       EnvName: !Ref EnvName
  #       OrgName: !Ref OrgName
  #       StartScheduleExpression: !Ref StartScheduleExpression
  #       StopScheduleExpression: !Ref StopScheduleExpression
  #       UseFriendlyNames: FALSE
  #       DatabaseInstanceName:
  #         Fn::GetAtt:
  #           - DBStack
  #           - Outputs.DBInstanceName

####
# PDDTS Application
####

  # DeployStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/deployment.yaml
  #     Parameters:
  #       Name: !Ref Name
  #       EnvName: !Ref EnvName
  #       OrgName: !Ref OrgName
  #       NetworkStackName: !Ref NetworkStackName
  #       SNSStackName: !Ref SNSStackName

  # CacheStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/elasticache.yaml
  #     Parameters:
  #       Name: !Ref Name
  #       EnvName: !Ref EnvName
  #       NetworkStackName: !Ref NetworkStackName
  #       AllowSecurityGroup: 
  #         Fn::GetAtt:
  #           - ServerStack
  #           - Outputs.AppServerSecurityGroup
  #       EncryptInTransit: TRUE
  #       NodeType: cache.t3.micro
  #       NumCacheClusters: 1
  #       OrgName: !Ref OrgName
  #       SnapshotRetentionLimit: !If [IsProd, 30, !Ref 'AWS::NoValue']
  #       SNSStackName: !Ref SNSStackName
  #       UseFriendlyNames: TRUE

  # ServerStack:
  #   DependsOn:
  #     - DBStack
  #     - DeployStack
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/appserver-basic.yaml
  #     Parameters:
  #       Name: !Ref Name
  #       EnvName: !Ref EnvName
  #       OrgName: !Ref OrgName
  #       ClientDomainName: !Ref ClientDomainName
  #       DatabaseEndpoint:
  #         Fn::GetAtt:
  #           - DBStack
  #           - Outputs.DBInstanceAddress
  #       DatabasePort:
  #         Fn::GetAtt:
  #           - DBStack
  #           - Outputs.DBInstancePort
  #       DatabaseSecurityGroupId:
  #         Fn::GetAtt:
  #           - DBStack
  #           - Outputs.SecurityGroupId
  #       InstanceAMI: !Ref InstanceAMI
  #       InstanceKeyName: !Ref InstanceKeyName
  #       InstancePort: 80
  #       InstanceSubnet: Private
  #       InstanceType: t3.micro
  #       LoadBalancerHostName: !If [IsProd, !Ref LoadBalancerHostName, !Ref 'AWS::NoValue']
  #       LoadBalancerPriority: 100
  #       LoadBalancerStackName: !Select [ 1, !Split [ '/', !Ref ELBStack]]
  #       NetworkStackName: !Ref NetworkStackName
  #       SharedSecretId:
  #         Fn::GetAtt:
  #           - DBStack
  #           - Outputs.DBSecretManagerKeyId
  #       SNSStackName: !Ref SNSStackName
  #       UseFriendlyNames: FALSE

  # SchedulerStack:
  #   DependsOn:
  #     - DBStack
  #     - ServerStack
  #   Condition: IsNotProd
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
  #     Parameters:
  #       Name: !Ref Name
  #       EnvName: !Ref EnvName
  #       OrgName: !Ref OrgName
  #       StartScheduleExpression: !Ref StartScheduleExpression
  #       StopScheduleExpression: !Ref StopScheduleExpression
  #       UseFriendlyNames: FALSE
  #       CodeDeployApplicationName:
  #         Fn::GetAtt:
  #           - DeployStack
  #           - Outputs.CodeDeployApplicationName
  #       CodeDeployDeploymentGroupName:
  #         Fn::GetAtt:
  #           - DeployStack
  #           - Outputs.CodeDeployDeploymentGroupName

  # BackupStack:
  #   DependsOn: 
  #     - DBStack
  #     - ServerStack
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/backup.yaml
  #     Parameters:
  #       Name: !Ref Name
  #       EnvName: !Ref EnvName
  #       OrgName: !Ref OrgName
  #       BackupARNList: !Join
  #         - ','
  #         - - Fn::GetAtt:
  #             - DBStack
  #             - Outputs.DBInstanceARN
  #           - Fn::GetAtt:
  #             - ServerStack
  #             - Outputs.AppServerEFSArn
  #       BackupTime: !If [IsProd, !Ref 'AWS::NoValue', 1] #Default backup time else 1AM UTC for dev

# Outputs:

#   DeploymentUserGroup:
#     Description: Add the BitBucket user into this group
#     Value:
#       Fn::GetAtt:
#         - DeployStack
#         - Outputs.DeploymentUserGroup