AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for waymaker-foundation.org

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: waymaker
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. iscale-solutions.us).
    Type: String
    Default: waymaker-foundation.org

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref ClientDomainName]]
      Name: !Ref ClientDomainName
      HostedZoneTags:
        -
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], iscale-solutions]]
        -
          Key: Environment
          Value: !Ref EnvName
        -
          Key: Organization
          Value: !Ref OrgName

  GoogleMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Ref ClientDomainName
      Comment: Google MX Records
      ResourceRecords:
        - 1 ASPMX.L.GOOGLE.COM
        - 5 ALT1.ASPMX.L.GOOGLE.COM
        - 5 ALT2.ASPMX.L.GOOGLE.COM
        - 10 ALT3.ASPMX.L.GOOGLE.COM
        - 10 ALT4.ASPMX.L.GOOGLE.COM
        - 15 pricuxi3kj4sjufqczyicin5hgctavoatwrdujj2xpwp5zk3n4kq.mx-verification.google.com.
      TTL: 3600
      Type: MX

  SESTxtRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: Google Verification TXT Record
      Name: !Join ['.', [_amazonses, !Ref ClientDomainName]]
      Type: TXT
      TTL: 3600
      ResourceRecords:
        - '"4UBt8cG6TwEKov8cj+vwDQM6vIYGjMAgnGjyX6CQuGI="'

  SESDKIMRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['uvt4vyhtxjle2joffafreuw3pykj2pnz._domainkey', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 3600
      Comment: !Join ['', ['DKIM Validation for *.', !Ref ClientDomainName, ' in ' , !Ref 'AWS::Region']]
      ResourceRecords:
        - uvt4vyhtxjle2joffafreuw3pykj2pnz.dkim.amazonses.com
  
  SESDKIMRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['5aiciwvhqcpw3bzo6f43awvtf4vfd3fk._domainkey', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 3600
      Comment: !Join ['', ['DKIM Validation for *.', !Ref ClientDomainName, ' in ' , !Ref 'AWS::Region']]
      ResourceRecords:
        - 5aiciwvhqcpw3bzo6f43awvtf4vfd3fk.dkim.amazonses.com

  SESDKIMRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['lm7gf7v4koonvxlgxgoca7cov5dwjfsq._domainkey', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 3600
      Comment: !Join ['', ['DKIM Validation for *.', !Ref ClientDomainName, ' in ' , !Ref 'AWS::Region']]
      ResourceRecords:
        - lm7gf7v4koonvxlgxgoca7cov5dwjfsq.dkim.amazonses.com

  WildcardCertificateValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['_1968a92d3ee61249e9db0cebca0f35b2', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 3600
      Comment: !Join ['', ['Validation for *.', !Ref ClientDomainName, ' in ' , !Ref 'AWS::Region']]
      ResourceRecords:
        - _e3a36d9794ed3e34ff4d71a0183b2069.rlltrpyzyf.acm-validations.aws.

  WWWCertificateValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join [".", ["_7d869b54c196a08db749af060213b8da", "www", !Ref ClientDomainName]]
      Type: CNAME
      TTL: 3600
      Comment: !Join ["", ["Validation for www.", !Ref ClientDomainName, "in us-east-1"]]
      ResourceRecords:
        - _355df2d64c42efd4fc543404339051fa.rlltrpyzyf.acm-validations.aws.
