AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for FPUA

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: fpua
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    Default: fpua.ph
  LoadBalancerStackName:
    Description: The name of the load balancer stack.
    Type: String
    Default: HostingProductionELB

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml


Resources:

####
# Route53 Section
####

  HostedZone: 
    Type: AWS::Route53::HostedZone
    Properties: 
      HostedZoneConfig: 
        Comment: !Join [' ',[Hosted Zone for, !Ref ClientDomainName]]
      Name: !Ref ClientDomainName
      HostedZoneTags: 
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], fpua]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  GoogleMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Ref ClientDomainName
      Comment: Google MX Records
      ResourceRecords:
        - 1 ASPMX.L.GOOGLE.COM
        - 5 ALT1.ASPMX.L.GOOGLE.COM
        - 5 ALT2.ASPMX.L.GOOGLE.COM
        - 10 ALT3.ASPMX.L.GOOGLE.COM
        - 10 ALT4.ASPMX.L.GOOGLE.COM
      TTL: 14400
      Type: MX
  
  DKIMRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[gxkw5vdjtkzkjqwb3sryg6c7rh5wsggg, _domainkey, !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14440
      ResourceRecords:
      - gxkw5vdjtkzkjqwb3sryg6c7rh5wsggg.dkim.amazonses.com

  DKIMRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[npci4kdvu3y5eoacoi232xyrlggg7u3l, _domainkey, !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14440
      ResourceRecords:
      - npci4kdvu3y5eoacoi232xyrlggg7u3l.dkim.amazonses.com
  
  DKIMRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[kcrp6lypxyyhjifvxk23gaewikyk5ph6, _domainkey, !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14440
      ResourceRecords:
      - kcrp6lypxyyhjifvxk23gaewikyk5ph6.dkim.amazonses.com

  SSLDomainCertificateRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_b5780500ae55b678a3705e9e510a00c4, !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14440
      ResourceRecords:
      - _2cff896b4f8cf47aa0501c8fe0d5ebf5.nfyddsqlcy.acm-validations.aws.

  DomainTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Ref ClientDomainName
      ResourceRecords: 
        - "\"v=spf1 include:amazonses.com ~all\""
        - "\"google-site-verification=28PnxCKBLEbpQkxe2zicJBB0s7_Pn27dKVlFYnwgcQY\""
      TTL: 14400
      Type: TXT
      Comment: TXT verifications

  DMARCTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Join ['.',[_dmarc, !Ref ClientDomainName]]
      ResourceRecords: 
        - "\"v=DMARC1;p=quarantine;pct=100;fo=1\""
      TTL: 14400
      Type: TXT
      Comment: DMARC TXT Record