AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for Bathala Resort

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: dns
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: bathala
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
  DomainName:
    Description: The domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: bathalaresort.com
  PanglaoDomainName:
    Description: The domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: bathalaresortpanglao.com

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

###
# bathalaresort.com
###

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref DomainName]]
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], hostedzone]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  HostedZoneDNSSEC:
    DependsOn: HostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref HostedZone

  GoogleWorkspaceMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: Google Workspace MX Records
      Name: !Ref DomainName
      Type: MX
      TTL: 14400
      ResourceRecords:
        - 1 ASPMX.L.GOOGLE.COM
        - 5 ALT1.ASPMX.L.GOOGLE.COM.
        - 5 ALT2.ASPMX.L.GOOGLE.COM.
        - 10 ALT3.ASPMX.L.GOOGLE.COM.
        - 10 ALT4.ASPMX.L.GOOGLE.COM.
        - 15 uzsa46ikehjpem5526gbqlnkgwvmwnyka4egxveuot6faosqg6mq.mx-verification.google.com.

  HostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref HostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

  BlueHostVerificationARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      TTL: 14400
      ResourceRecords:
        - 162.241.226.11
  
  GmailDKIMRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[google._domainkey, !Ref DomainName]]
      ResourceRecords:
        - '"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCCNDrbML8lv81fdsIuOxix7rdx6gcpaEnmby91IbYaqcPbX7zLR++JVWlxbU8g2pIP5zM3jXEGUXkme5mP+qquxwA6cH4QZTWyoFLB4lum+MpJ+FCjmj2T8lfL+WoOqt9VhQAxxtVCgeveX1zpQn1vazgqThcbsggHHosuLpUX+QIDAQAB"'
      TTL: 14400
      Type: TXT
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], gmail, dkim]]


  WWWARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', [www, !Ref DomainName]]
      Type: A
      TTL: 14400
      ResourceRecords:
        - 162.241.226.11

###
# bathalaresortpanglao.com
###

  PanglaoHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref PanglaoDomainName]]
      Name: !Ref PanglaoDomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], hostedzone]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  PanglaoHostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref PanglaoHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

  PanglaoHostedZoneDNSSEC:
    DependsOn: PanglaoHostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref PanglaoHostedZone

  PanglaoWWWARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref PanglaoHostedZone
      Name: !Join ['.', [www, !Ref PanglaoDomainName]]
      Type: A
      TTL: 14400
      ResourceRecords:
        - 162.241.226.11

  PanglaoBlueHostVerificationARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref PanglaoHostedZone
      Name: !Ref PanglaoDomainName
      Type: A
      TTL: 14400
      ResourceRecords:
        - 162.241.226.11