AWSTemplateFormatVersion: 2010-09-09
Description: DNS records powerbat.asia

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: asiadns
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: deltadore
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: powerbat.asia

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone: 
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref DomainName]]
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], hostedzone]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  WildcardSSLValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_83a3175e8672a13ecd4d360823f7928e, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _d241e96108cfbbdaf493c5684db77d2c.vtqfhvjlcp.acm-validations.aws.

  SESDomainVerificationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Join ['.',[_amazonses, !Ref DomainName]]
      ResourceRecords: 
        - "\"VxtzWT/Zk+FLYJKHx087OXyi3Ql1SFx4D4ukwUA60YA=\""
      TTL: 60
      Type: TXT
      Comment: SES Domain Verification

  SESDKIMRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[fxbnx2dhal2g7uwnccjdhzi2lkepa5eh._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - fxbnx2dhal2g7uwnccjdhzi2lkepa5eh.dkim.amazonses.com

  SESDKIMRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[y6mn5izezcokpyhsvge5oibnlqbmtmrn._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - y6mn5izezcokpyhsvge5oibnlqbmtmrn.dkim.amazonses.com

  SESDKIMRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[ecynhyvvcn67s73dj7az7skdab2vbwo4._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - ecynhyvvcn67s73dj7az7skdab2vbwo4.dkim.amazonses.com

  SESMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: SES Inbound MX Records
      Name: !Ref DomainName
      Type: MX
      TTL: 3600
      ResourceRecords:
        - 10 inbound-smtp.us-east-1.amazonaws.com