AWSTemplateFormatVersion: 2010-09-09
Description: powerbat Setup

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName
      - Label:
          default: Loan balancer configuration
        Parameters:
          - LoadBalancerCertificateArn
          - LoadBalancerHostName
      - Label:
          default: Instance Configuration
        Parameters:
          - InstanceKeyName
          - BackendAMI
          - FrontendAMI
          - ClientDomainName
      - Label:
          default: Scheduler Configuration
        Parameters:
          - StartScheduleExpression
          - StopScheduleExpression

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Topic Stack Name
      BackendAMI:
        default: Back end server AMI
      ClientDomainName:
        default: Domain Name
      FrontendAMI:
        default: Front end server AMI
      InstanceKeyName:
        default: Instance Key Name
      InstanceAMI:
        default: Instance AMI
      LoadBalancerCertificateArn:
        default: Load Balancer SSL certificate
      LoadBalancerHostName:
        default: Load Balancer Host Name
      StartScheduleExpression:
        default: Start Schedule CRON Expression
      StopScheduleExpression:
        default: Stop Schedule CRON Expression

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: powerbat
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: deltadore
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Staging
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-software.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: powerbat.ph
    MinLength: 1
  BackendAMI:
    Description: BackEnd AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-0cdb2ce311496b027
  FrontendAMI:
    Description: FrontEnd AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-0cdb2ce311496b027
  InstanceKeyName:
    Description: Instance Key Name
    Type: String
    Default: ''
  LoadBalancerHostName:
    Description: (Optional) Custom Hostname for load balancer URL
    Type: String
    Default: ''
  LoadBalancerCertificateArn:
    Description: The priority for ELB Listener
    Type: String
    Default: arn:aws:acm:ap-southeast-1:767970794407:certificate/ef3606b5-12e7-469f-a107-b695d912f4ec
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: deltadore-stg-ase1-network
    MinLength: 1
  SNSStackName:
    Description: the name of the SNS stack.
    Type: String
    Default: deltadore-prd-sns
    MinLength: 1
  StartScheduleExpression:
    Description: Schedule expression when to start the objects
    Type: String
    Default: cron(0 0 ? * MON-FRI *)
  StopScheduleExpression:
    Description: Schedule expression when to stop the objects
    Type: String
    Default: cron(0 10 ? * MON-FRI *)

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  HasLoadBalancerHostName: !Not [!Equals [!Ref LoadBalancerHostName, '']]
      
Resources:

  ELBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/loadbalancer.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        CertificateArn: !Ref LoadBalancerCertificateArn
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName

  PowerbatRDSParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
      Family: mysql5.7
      Parameters:
        character_set_client: utf8mb4
        character_set_connection: utf8mb4
        character_set_results: utf8mb4
        collation_connection: utf8mb4_general_ci
        log_bin_trust_function_creators: 1
        log_output: FILE
        long_query_time: 2
        slow_query_log: 1
        sql_mode: IGNORE_SPACE
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
  
  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/database.yaml
      Parameters:
        Name: !Ref Name
        DatabaseName: !Join ['',[!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name]]]
        EnableCPUCreditAlarm: false
        EnableEnhancedMonitoring: false
        EnvName: !Ref EnvName
        Engine: mysql
        EngineVersion: 5.7.41 #needs to be 5.7 per software requirements
        Family: mysql5.7
        MultiAz: !If [IsProd, true, false]
        InstanceType: db.t3.micro #Cannot go to t4g as it needs version 8 for this
        MasterUser: root
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        ParameterGroup: !Ref PowerbatRDSParameterGroup
        SNSStackName: !Ref SNSStackName
        StorageEncrypted: true

  FrontEndDeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/deployment.yaml
      Parameters:
        Name: !Join ['-', [!Ref Name, front]]
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName
        CreateDeployUser: true

  FrontEndStack:
    DependsOn:
      - DBStack
      - ELBStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/appserver-basic.yaml
      Parameters:
        Name: !Join ['-', [!Ref Name, front]]
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        LoadBalancerPriority: 100
        DatabaseEndpoint:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstanceAddress
        DatabasePort:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstancePort
        DatabaseSecurityGroupId:
          Fn::GetAtt:
            - DBStack
            - Outputs.SecurityGroupId
        HealthCheckPath: '/health'
        LoadBalancerStackName: !Select [ 1, !Split [ '/', !Ref ELBStack]]
        InstanceAMI: !Ref FrontendAMI #ami-012a1475cea8bb52c
        InstanceKeyName: !Ref InstanceKeyName
        InstanceSpotPrice: 0.5
        InstanceType: t3.micro
        LoadBalancerHostName: !If [HasLoadBalancerHostName, !Ref LoadBalancerHostName, 'AWS::NoValue']
        SNSStackName: !Ref SNSStackName
        SharedSecretId:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBSecretManagerKeyId
        NetworkStackName: !Ref NetworkStackName
        ClientDomainName: !Ref ClientDomainName
        UseFriendlyNames: FALSE

  CalculationStack:
    DependsOn:
      - DBStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/appserver-basic.yaml
      Parameters:
        Name: !Join ['-', [!Ref Name, 'calc']]
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        DatabaseEndpoint:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstanceAddress
        DatabasePort:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstancePort
        DatabaseSecurityGroupId:
          Fn::GetAtt:
            - DBStack
            - Outputs.SecurityGroupId
        ExternalEFSID:
          Fn::GetAtt:
            - FrontEndStack
            - Outputs.AppServerEFS
        ExternalEFSSecurityGroup:
          Fn::GetAtt:
            - FrontEndStack
            - Outputs.AppServerEFSSecurityGroup
        InstanceAMI: ami-03d33d4492bfdc8ce #!Ref BackendAMI
        InstanceKeyName: !Ref InstanceKeyName
        # InstanceSpotPrice: 0.5
        InstanceType: t3.micro
        SNSStackName: !Ref SNSStackName
        NetworkStackName: !Ref NetworkStackName
        ClientDomainName: !Ref ClientDomainName
        UseFriendlyNames: FALSE

  DataProcessorStack: 
    DependsOn:
      - DBStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/appserver-basic.yaml
      Parameters:
        Name: !Join ['-', [!Ref Name, 'proc']]
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        DatabaseEndpoint:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstanceAddress
        DatabasePort:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstancePort
        DatabaseSecurityGroupId:
          Fn::GetAtt:
            - DBStack
            - Outputs.SecurityGroupId
        ExternalEFSID:
          Fn::GetAtt:
            - FrontEndStack
            - Outputs.AppServerEFS
        ExternalEFSSecurityGroup:
          Fn::GetAtt:
            - FrontEndStack
            - Outputs.AppServerEFSSecurityGroup
        InstanceAMI: ami-0a12525e2e65d9e4d #!Ref BackendAMI
        InstanceKeyName: !Ref InstanceKeyName
        # InstanceSpotPrice: 0.5
        InstanceType: t3.micro
        SNSStackName: !Ref SNSStackName
        NetworkStackName: !Ref NetworkStackName
        ClientDomainName: !Ref ClientDomainName
        UseFriendlyNames: FALSE

  BackupStack:
    DependsOn: 
      - DBStack
      - FrontEndStack
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/backup.yaml
      Parameters: 
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        BackupARNList: !Join
          - ','
          - - Fn::GetAtt:
              - DBStack
              - Outputs.DBInstanceARN
            - Fn::GetAtt:
              - FrontEndStack
              - Outputs.AppServerEFSArn

  # SchedulerStack: 
  #   DependsOn: 
  #     - DBStack
  #     - AppServerStack
  #   Type: AWS::CloudFormation::Stack
  #   Properties: 
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
  #     Parameters: 
  #       Name: !Ref Name
  #       EnvName: !Ref EnvName
  #       OrgName: !Ref OrgName
  #       StartScheduleExpression: !Ref StartScheduleExpression
  #       StopScheduleExpression: !Ref StopScheduleExpression
  #       UseFriendlyNames: TRUE
  #       DatabaseClusterArn:
  #         Fn::GetAtt:
  #           - DBStack
  #           - Outputs.DBClusterARN
  #       CodeDeployApplicationName:
  #         Fn::GetAtt:
  #           - DeployStack
  #           - Outputs.CodeDeployApplicationName
  #       CodeDeployDeploymentGroupName:
  #         Fn::GetAtt:
  #           - DeployStack
  #           - Outputs.CodeDeployDeploymentGroupName
        
# Outputs:
#   DeploymentUserGroup:
#     Description: Add the BitBucket user into this group
#     Value: 
#       Fn::GetAtt:
#         - DeployStack
#         - Outputs.DeploymentUserGroup
