AWSTemplateFormatVersion: 2010-09-09
Description: Externisy IAM users

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: externisy
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  GithubUser:
    Type: AWS::IAM::User
    Properties:
      UserName: github_user
      Tags:
        - Key: Name
          Value: Github Access
        - Key: Email
          Value: github@externisy.fr

  GithubUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: GithubUser

Outputs:

  GithubUserAccessKeyId:
    Description: Access Key Id for the Github user
    Value: !Ref GithubUserAccessKey
  
  GithubUserAccessKeySecret:
    Description: Secret Key for the Github user
    Value: !GetAtt [GithubUserAccessKey, SecretAccessKey]