AWSTemplateFormatVersion: 2010-09-09
Description: PayGate Resources

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName
      - Label:
          default: Load Balancer Configuration
        Parameters:
          - ClientDomainName
          - LoadBalancerCertificateArn
          - LoadBalancerHostName
      - Label:
          default: Instance Configuration
        Parameters:
          - InstanceKeyName
          - InstanceAMI
      - Label:
          default: Scheduler Configuration
        Parameters:
          - StartScheduleExpression
          - StopScheduleExpression

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      InstanceAMI:
        default: Instance AMI ID
      InstanceKeyName:
        default: Instance Key Name
      LoadBalancerCertificateArn:
        default: Load Balancer SSL Certificate ARN
      LoadBalancerHostName:
        default: Load Balancer Host Name
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Topic Stack Name
      ClientDomainName:
        default: Domain Name
      StartScheduleExpression:
        default: Start Schedule CRON Expression
      StopScheduleExpression:
        default: Stop Schedule CRON Expression

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name)
    Type: String
    MinLength: 3
    MaxLength: 9
    Default: paygate
  OrgName:
    Description: The name of the organization
    Type: String
    Default: pchc
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Staging
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-software.com)
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: pchc.com.ph
    MinLength: 1
  InstanceAMI:
    Description: Instance AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-00b8d9cb8a7161e41 #Default Amazon Linux 2 for Singapore
  InstanceKeyName:
    Description: Instance Key Name
    Type: String
    Default: ''
  LoadBalancerHostName:
    Description: (Optional) Custom Hostname for load balancer URL
    Type: String
    Default: paygate
    MaxLength: 12
  LoadBalancerCertificateArn:
    Description: The priority for ELB Listener
    Type: String
    Default: arn:aws:acm:ap-southeast-1:050821737631:certificate/00ed4a3d-8f7d-45d5-a09f-354cd485c251
  NetworkStackName:
    Description: The name of the network stack
    Type: String
    Default: pchc-dev-ase1-network
    MinLength: 1
  SNSStackName:
    Description: The name of the SNS stack
    Type: String
    Default: pchc-dev-ase1-sns
    MinLength: 1
  StartScheduleExpression:
    Description: Schedule expression when to start the objects
    Type: String
    Default: cron(0 0 ? * MON-FRI *)
  StopScheduleExpression:
    Description: Schedule expression when to stop the objects
    Type: String
    Default: cron(0 10 ? * MON-FRI *)

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  ELBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/loadbalancer.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        CertificateArn: !Ref LoadBalancerCertificateArn
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/database.yaml
      Parameters:
        Name: !Ref Name
        DatabaseName: !Join ['',[!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name], db]]
        AllocatedStorage: 20
        BackupRetentionPeriod: !If [IsProd, 30, 7]
        EnableCPUCreditAlarm: !If [IsProd, true, false]
        EnableEnhancedMonitoring: !If [IsProd, true, false]
        EnablePerformanceInsights: !If [IsProd, true, false]
        EnvName: !Ref EnvName
        Engine: mysql
        EngineVersion: 8.0.20
        Family: mysql8.0
        InstanceType: !If [IsProd, db.t3.medium, db.t3.micro]
        MasterUser: root
        MultiAz: !If [IsProd, true, false]
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        SNSStackName: !Ref SNSStackName
        # SnapshotIdentifier: arn:aws:rds:ap-southeast-1:050821737631:snapshot:paygate-base-image-feb-08-2021
        StorageEncrypted: true

  DBSchedulerStack:
    DependsOn:
      - DBStack
    Condition: IsNotProd
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        StartScheduleExpression: !Ref StartScheduleExpression
        StopScheduleExpression: !Ref StopScheduleExpression
        UseFriendlyNames: FALSE
        DatabaseInstanceName:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstanceName

####
# PayGate Application
####

  PayGateDeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/deployment.yaml
      Parameters:
        Name: !Join ['-', ['pg', 'pg']]
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName

  PayGateAppServerStack:
    DependsOn:
      - DBStack
      - PayGateDeployStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/appserver-basic.yaml
      Parameters:
        Name: !Join ['-', ['pg', 'pg']]
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        ClientDomainName: !Ref ClientDomainName
        DatabaseEndpoint:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstanceAddress
        DatabasePort:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstancePort
        DatabaseSecurityGroupId:
          Fn::GetAtt:
            - DBStack
            - Outputs.SecurityGroupId
        InstanceAMI: !Ref InstanceAMI
        InstanceKeyName: !Ref InstanceKeyName
        InstancePort: 80
        InstanceType: t3.micro
        LoadBalancerHostName: !If [IsProd, !Ref LoadBalancerHostName, !Ref 'AWS::NoValue']
        LoadBalancerPriority: 100
        LoadBalancerStackName: !Select [ 1, !Split [ '/', !Ref ELBStack]]
        NetworkStackName: !Ref NetworkStackName
        SharedSecretId: 
          Fn::GetAtt:
            - DBStack
            - Outputs.DBSecretManagerKeyId
        SNSStackName: !Ref SNSStackName
        UseFriendlyNames: FALSE
  
  PaygateSchedulerStack:
    DependsOn:
      - DBStack
      - PayGateAppServerStack
    Condition: IsNotProd
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        StartScheduleExpression: !Ref StartScheduleExpression
        StopScheduleExpression: !Ref StopScheduleExpression
        UseFriendlyNames: FALSE
        CodeDeployApplicationName:
          Fn::GetAtt:
            - PayGateDeployStack
            - Outputs.CodeDeployApplicationName
        CodeDeployDeploymentGroupName:
          Fn::GetAtt:
            - PayGateDeployStack
            - Outputs.CodeDeployDeploymentGroupName

####
# PG-PCHC Application
####

  PGPCHCDeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/deployment.yaml
      Parameters:
        Name: !Join ['-', ['pg', 'pchc']]
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName

  PGPCHCAppServerStack:
    DependsOn:
      - DBStack
      - PGPCHCDeployStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/appserver-basic.yaml
      Parameters:
        Name: !Join ['-', ['pg', 'pchc']]
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        ClientDomainName: !Ref ClientDomainName
        DatabaseEndpoint:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstanceAddress
        DatabasePort:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstancePort
        DatabaseSecurityGroupId:
          Fn::GetAtt:
            - DBStack
            - Outputs.SecurityGroupId
        InstanceAMI: !Ref InstanceAMI
        InstanceKeyName: !Ref InstanceKeyName
        InstancePort: 80
        InstanceType: t3.micro
        LoadBalancerHostName: !If [IsProd, !Ref LoadBalancerHostName, !Ref 'AWS::NoValue']
        LoadBalancerPriority: 101
        LoadBalancerStackName: !Select [ 1, !Split [ '/', !Ref ELBStack]]
        NetworkStackName: !Ref NetworkStackName
        SharedSecretId:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBSecretManagerKeyId
        SNSStackName: !Ref SNSStackName
        UseFriendlyNames: FALSE

  PGPCHCSchedulerStack:
    DependsOn:
      - DBStack
      - PGPCHCAppServerStack
    Condition: IsNotProd
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        StartScheduleExpression: !Ref StartScheduleExpression
        StopScheduleExpression: !Ref StopScheduleExpression
        UseFriendlyNames: FALSE
        CodeDeployApplicationName:
          Fn::GetAtt:
            - PGPCHCDeployStack
            - Outputs.CodeDeployApplicationName
        CodeDeployDeploymentGroupName:
          Fn::GetAtt:
            - PGPCHCDeployStack
            - Outputs.CodeDeployDeploymentGroupName

####
# PG-Payment Application
####

  PGPaymentDeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/deployment.yaml
      Parameters:
        Name: !Join ['-', ['pg', 'pay']]
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName

  PGPaymentAppServerStack:
    DependsOn:
      - DBStack
      - PGPaymentDeployStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/appserver-basic.yaml
      Parameters:
        Name: !Join ['-', ['pg', 'pay']]
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        ClientDomainName: !Ref ClientDomainName
        DatabaseEndpoint:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstanceAddress
        DatabasePort:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstancePort
        DatabaseSecurityGroupId:
          Fn::GetAtt:
            - DBStack
            - Outputs.SecurityGroupId
        InstanceAMI: !Ref InstanceAMI
        InstanceKeyName: !Ref InstanceKeyName
        InstancePort: 80
        InstanceType: t3.micro
        LoadBalancerHostName: !If [IsProd, !Ref LoadBalancerHostName, !Ref 'AWS::NoValue']
        LoadBalancerPriority: 102
        LoadBalancerStackName: !Select [ 1, !Split [ '/', !Ref ELBStack]]
        NetworkStackName: !Ref NetworkStackName
        SharedSecretId:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBSecretManagerKeyId
        SNSStackName: !Ref SNSStackName
        UseFriendlyNames: FALSE

  PGPaymentSchedulerStack:
    DependsOn:
      - DBStack
      - PGPaymentAppServerStack
    Condition: IsNotProd
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        StartScheduleExpression: !Ref StartScheduleExpression
        StopScheduleExpression: !Ref StopScheduleExpression
        UseFriendlyNames: FALSE
        CodeDeployApplicationName:
          Fn::GetAtt:
            - PGPaymentDeployStack
            - Outputs.CodeDeployApplicationName
        CodeDeployDeploymentGroupName:
          Fn::GetAtt:
            - PGPaymentDeployStack
            - Outputs.CodeDeployDeploymentGroupName

###
# Backup Section
###

  BackupStack:
    DependsOn: 
      - DBStack
      - PGPCHCAppServerStack
      - PayGateAppServerStack
      - PGPaymentAppServerStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/backup.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        BackupARNList: !Join
          - ','
          - - Fn::GetAtt:
              - DBStack
              - Outputs.DBInstanceARN
            - Fn::GetAtt:
              - PGPCHCAppServerStack
              - Outputs.AppServerEFSArn
            - Fn::GetAtt:
              - PayGateAppServerStack
              - Outputs.AppServerEFSArn
            - Fn::GetAtt:
              - PGPaymentAppServerStack
              - Outputs.AppServerEFSArn

Outputs:

  PaygateDeploymentUserGroup:
    Description: Add the BitBucket user into this group
    Value:
      Fn::GetAtt:
        - PayGateDeployStack
        - Outputs.DeploymentUserGroup

  PGPCHCDeploymentUserGroup:
    Description: Add the BitBucket user into this group
    Value:
      Fn::GetAtt:
        - PGPCHCDeployStack
        - Outputs.DeploymentUserGroup

  PGPaymentDeploymentUserGroup:
    Description: Add the BitBucket user into this group
    Value:
      Fn::GetAtt:
        - PGPaymentDeployStack
        - Outputs.DeploymentUserGroup