AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for pchcdev.com

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: dns
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: pchcdev
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: pchcdev.com

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZoneStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/hostedzone.yaml
      Parameters: 
        Name: !Ref Name
        OrgName: !Ref OrgName
        EnvName: !Ref EnvName
        DomainName: !Ref DomainName

  APIPGPCHCRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[api-pg-pchc, !Ref DomainName]]
      ResourceRecords:
      - 3.16.134.28
      TTL: 3600
      Type: A

  BSPRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[bsp, !Ref DomainName]]
      ResourceRecords:
      - 13.229.103.34
      TTL: 3600
      Type: A

  DomainConnectRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[_domainconnect, !Ref DomainName]]
      Type: CNAME
      TTL: 3600
      ResourceRecords:
      - _domainconnect.gd.domaincontrol.com

  PaygateRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[paygate, !Ref DomainName]]
      ResourceRecords:
      - 3.16.134.28
      TTL: 3600
      Type: A

  PDDTsUATRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[pddtsuat, !Ref DomainName]]
      ResourceRecords:
      - 3.22.151.79
      TTL: 3600
      Type: A

  PGPaymentRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[pg-payment, !Ref DomainName]]
      ResourceRecords:
      - 3.16.134.28
      TTL: 3600
      Type: A

  PGPCHCRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[pg-pchc, !Ref DomainName]]
      ResourceRecords:
      - 3.16.134.28
      TTL: 3600
      Type: A

  PhilpassRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[philpass, !Ref DomainName]]
      ResourceRecords:
      - 52.76.38.68
      TTL: 3600
      Type: A

  NoWWWRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Ref DomainName
      ResourceRecords:
      - 3.16.134.28
      TTL: 3600
      Type: A

  DSPRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[dsp, !Ref DomainName]]
      Type: CNAME
      TTL: 3600
      ResourceRecords:
      - adjacent-turmeric-l87ezkssvc1sudn7s9zfs3tn.herokudns.com

  PgAcquireSIMRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[pg-acquirersim, !Ref DomainName]]
      Type: CNAME
      TTL: 3600
      ResourceRecords:
      - nameless-possum-7xl4jy0knulehg1mv5chg5kh.herokudns.com
  
  SFTPPDDTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[sftp-gw, pddtsuat, !Ref DomainName]]
      Type: CNAME
      TTL: 3600
      ResourceRecords:
      - s-1b5fc3dab70e44a5a.server.transfer.us-east-2.amazonaws.com
  
  WWWRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[www, !Ref DomainName]]
      ResourceRecords:
      - 3.16.134.28
      TTL: 3600
      Type: A

  WildCardCertValidation:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[_cedb5eaf34d3fc58b3168a2fe4946d16, !Ref DomainName]]
      Type: CNAME
      TTL: 3600
      ResourceRecords:
      - _26c2cb5fb12a440773568f1b58e5263b.vtqfhvjlcp.acm-validations.aws.