AWSTemplateFormatVersion: 2010-09-09
Description: PCHC Master - IAM Resources

Resources:

  LeyUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: ley123!
        PasswordResetRequired: true
      UserName: ljulian@pchc.com.ph
      Tags:
        - Key: Name
          Value: Ley Julian
        - Key: Email
          Value: ljulian@pchc.com.ph

  MabelUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: mabel123!
        PasswordResetRequired: true
      UserName: mabelkogaw@pchc.com.ph
      Tags:
        - Key: Name
          Value: Mabel Kogaw
        - Key: Email
          Value: mabelkogaw@pchc.com.ph

  MaxiUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Maxi@Hello123!
        PasswordResetRequired: true
      UserName: maxitorrecampo@pchc.com.ph
      Tags:
        - Key: Name
          Value: Maxi Torrecampo
        - Key: Email
          Value: maxitorrecampo@pchc.com.ph

  NicoUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: nico123!
        PasswordResetRequired: true
      UserName: nicopaulomendoza@pchc.com.ph
      Tags:
        - Key: Name
          Value: Nico Paulo Mendoza
        - Key: Email
          Value: nicopaulomendoza@pchc.com.ph

  AdminGroupUsers:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: Administrators #from basic account foundation
      Users:
        - !Ref LeyUser
        - !Ref MaxiUser
        - !Ref NicoUser

  BillingGroupUsers:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: Billing #from basic account foundation
      Users:
        - !Ref LeyUser
        - !Ref MabelUser
        - !Ref MaxiUser
        - !Ref NicoUser