AWSTemplateFormatVersion: 2010-09-09
Description: 'This is a modified Akamai Enterprise Application Access (EAA) cloudformation template.
  AWS CloudFormation Template Akamai Connector:  This template installs
  Akamai Connector **WARNING** This template creates an Amazon EC2 instance and an
  EBS volume. You will be billed for the AWS resources used if you create a stack
  from this template.'

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: "Resource Configuration"
        Parameters:
          - Name
          - OrgName
          - EnvName
      -
        Label:
          default: "EC2 Configuration"
        Parameters:
          - InstanceType
          - VpcId
          - VpcSubnet

    ParameterLabels:
      Name:
        default: "Resource Name"
      OrgName:
        default: "Organization Name"
      EnvName:
        default: "Environment Name"
      InstanceType:
        default: "Instance Type"
      VpcId:
        default: "VPC ID"
      VpcSubnet:
        default: "Subnet ID"

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: dsapp-akamai-eaa #change if needed
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: pchc
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  InstanceType:
    Description: Soha Connector instance type
    Type: String
    Default: c5.large
    AllowedValues:
    - c5.large
    - c5.xlarge
    - c5.2xlarge
    - c5.4xlarge
    - c5d.large
    - c5d.xlarge
    - c5d.2xlarge
    - c5d.4xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - m5d.large
    - m5d.2xlarge
    - m5d.4xlarge
    - r5.large
    - r5.xlarge
    - r5.2xlarge
    - r5.4xlarge
    - r5.8xlarge
    - r5d.large
    - r5d.xlarge
    - r5d.2xlarge
    - r5d.4xlarge
    - r5d.8xlarge
    - i3.large
    - i3.2xlarge
    - i3.4xlarge
    - i3.8xlarge
    - t3.xlarge
    - t3.2xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId of your existing Virtual Private Cloud (VPC).
    Default: 'vpc-0fed281d3b7026344' #change if needed
  VpcSubnet:
    Description: Enter the VPC subnet of you existing Virtual Private Cloud (VPC)
    Type: AWS::EC2::Subnet::Id
    Default: 'subnet-0a48f81980ff1167a' #change if needed, need public subnet

Mappings: 
  EnvShort:
    Production:
      Name: prd
    Staging:
      Name: stg
    Development:
      Name: dev
    Test:
      Name: test
  AWSInstanceType2Arch:
    c5.large:
      Arch: '64'
    c5.xlarge:
      Arch: '64'
    c5.2xlarge:
      Arch: '64'
    c5.4xlarge:
      Arch: '64'
    c5d.large:
      Arch: '64'
    c5d.xlarge:
      Arch: '64'
    c5d.2xlarge:
      Arch: '64'
    c5d.4xlarge:
      Arch: '64'
    m5.large:
      Arch: '64'
    m5.2xlarge:
      Arch: '64'
    m5.4xlarge:
      Arch: '64'
    m5d.large:
      Arch: '64'
    m5d.2xlarge:
      Arch: '64'
    m5d.4xlarge:
      Arch: '64'
    r5.large:
      Arch: '64'
    r5.xlarge:
      Arch: '64'
    r5.2xlarge:
      Arch: '64'
    r5.4xlarge:
      Arch: '64'
    r5.8xlarge:
      Arch: '64'
    r5d.large:
      Arch: '64'
    r5d.xlarge:
      Arch: '64'
    r5d.2xlarge:
      Arch: '64'
    r5d.4xlarge:
      Arch: '64'
    r5d.8xlarge:
      Arch: '64'
    i3.large:
      Arch: '64'
    i3.2xlarge:
      Arch: '64'
    i3.4xlarge:
      Arch: '64'
    i3.8xlarge:
      Arch: '64'
    t3.xlarge:
      Arch: '64'
    t3.2xlarge:
      Arch: '64'
  RegionMap: # change AMI ID if needed
    us-east-1:
      AMI: ami-04af29dfbe000e153
    us-west-1:
      AMI: ami-0a3467e704060a3d4
    us-west-2:
      AMI: ami-017bf5e389f0dac00
    eu-west-1:
      AMI: ami-0b4f5d35e1d1321c1
    ap-south-1:
      AMI: ami-0001437da27ed446e
    ap-southeast-1:
      AMI: ami-06342e1c0855d82dd
    ap-northeast-1:
      AMI: ami-019b9ef3127308ab7
    ap-northeast-2:
      AMI: ami-0281c97bcfeef6443
    ap-southeast-2:
      AMI: ami-09aed27d0d1948f83
    sa-east-1:
      AMI: ami-0e4667ea32c60ba21
    eu-central-1:
      AMI: ami-069b6673b0c06acdd
    us-gov-west-1:
      AMI: ami-00f912fc588d5a495
    us-east-2:
      AMI: ami-04b48070e5a4c3905
    eu-west-2:
      AMI: ami-02d96e2f4ed2a2089
    ca-central-1:
      AMI: ami-0734fef2df2ceb684
    ap-east-1:
      AMI: ami-05ed1e61cc387af47
    me-south-1:
      AMI: ami-00be3ed703ae0358a
    eu-west-3:
      AMI: ami-0fc762c35cd73a67e
    eu-north-1:
      AMI: ami-09b381565961cae79
    af-south-1:
      AMI: ami-060da77b7f1c31195
    eu-south-1:
      AMI: ami-0694c0d6ebb58f8f0
    ap-northeast-3:
      AMI: ami-01bb95237a92a8290
  AWSRegionArch2AMI:
    us-east-1:
      '32': NOT_YET_SUPPORTED
      '64': ami-04af29dfbe000e153
      64HVM: NOT_YET_SUPPORTED
    us-west-1:
      '32': NOT_YET_SUPPORTED
      '64': ami-0a3467e704060a3d4
      64HVM: NOT_YET_SUPPORTED
  RegionShort:
    us-east-2:
      Name: ue2
    us-east-1:
      Name: ue1
    us-west-1:
      Name: uw1
    us-west-2:
      Name: uw2
    ap-east-1:
      Name: ae1
    ap-south-1:
      Name: as1
    ap-northeast-1:
      Name: ane1
    ap-northeast-2:
      Name: ane2
    ap-northeast-3:
      Name: ane3
    ap-southeast-1:
      Name: ase1
    ap-southeast-2:
      Name: ase2
    ca-central-1:
      Name: cc1
    cn-north-1:
      Name: cn1
    cn-northwest-1:
      Name: cnw1
    eu-central-1:
      Name: ec1
    eu-west-1:
      Name: ew1
    eu-west-2:
      Name: ew2
    eu-west-3:
      Name: ew3
    eu-north-1:
      Name: en1
    me-south-1:
      Name: ms1
    sa-east-1:
      Name: se1
    us-gov-east-1:
      Name: uge1
    us-gov-west-1:
      Name: ugw1 

Resources:

####
# EC2 Section
####
  PCHCConnectorUAT1SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Opening everything outbound
      VpcId:
        Ref: VpcId
      SecurityGroupEgress:
      - IpProtocol: "-1"
        FromPort: "-1"
        ToPort: "-1"
        CidrIp: 0.0.0.0/0
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
      - Ref: PCHCConnectorUAT1SecurityGroup
      Tags:
        - 
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
        - 
          Key: Environment
          Value: !Ref EnvName
        - 
          Key: Organization
          Value: !Ref OrgName
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AMI
      SubnetId:
        Ref: VpcSubnet
      InstanceType:
        Ref: InstanceType
      UserData: # unique value in downloaded CF template from Akamai 
        Fn::Base64: H4sICGC5G2UC/2NvbmYudGFyAO06a7OiSJb1mV9B3NoPO2PVRQRUbkRHLAgiKiio+OieqUBIHspLHoL++s0EvfdWV3dPzcR2z+62J6pKKsk871dm8kw8E/81N6sRMG2QfvhdoN3Ar/222xT99ozGyXaH7HzAqw9/ABRZbqaQ/Ic/J3T6eJj7IfiB7LJdimR6NP3cpWiq3aOxDw/4fw9WHDm+++xH/u9HAwV1l65jnOwx5PvfGnq9zgeSZtrdHkUzNBwnqU679wFv/5HxbzmuaYd+9KuK+gfv/4/Cj4I45FbT5d8w0wVR7tt4Az/gFtPrOza9/wztYn+mqZ71me3s2c9Mm+2wvS5L9zqgWfQlA+kZpPWiOIqAlcfp51pZz+bRDE3/s2lZIMuerTi8rUjiNG/I0DSFWSCFQ2bu3UgTcZITpZkkBHqTEfWaZ/SMHcHlbeavToWzsCB2/ejG2pcUZDd6Xp4nLwQRxJYZeHGWv/T7bJtowqBIzdyPIyyCK6svzdg3ZOAoUU/ALPMdK7/IjWU2XKfA9rPFTUv1zFf6zbv5TR/1uy7VY7HANpN3K+BwH3LaSPUVJsQ/ZoN94f58mMScOC3N1P6SpHF1qYcFPzP3AbCxW3Z/ftT/R/3/pv73Yf2nHvX/TwCOH4A9MPPnSxj8e+o/2e1Q39R/hmIe9f+PgI+/CPjw5hb44H1hxMXKDJMA4B9/DTDsI770/AxHfoXDXzPCwW3RVzW2meD5rhfAv7kfuXgcBRc89wAewrIIZ4chLMUfcVhS4fzsGeIF+Ku7OkUQIJ9t8DhpHNZLMzMEuO2ndQ9yQSRz048gG0GA3kN0WZGg5gPYd8R46cMaHsYpqGnC9gHS2sYFbkHeiwxKkeMmxICnwAEpiCzwjH2EiO5THD+ya9qIpZ8J+boE9+DvC1yF2o8M9h9lWT6DwMxy34JtEeEWvg0IEBFIuIy4i0lA3KB69vIwgJr94dfhzWCw1GdJLX6G//BbgGGvyny35gVZUDQtD/9cm+8dvmdcQYa5qw3JvocaB1A9ea2At6l4AM4g+IRnMcR2eadL23dqjXzNJ2xT8LOZ+nGRfa3ADKoa50EQl7gJ7fMzIujXd3zrmzUY5D1KivxLfknAC+y1XAzD8Y/4HHZrGcQC+c28uAhsJICVmiVsiKCn2rgDcssD9jMuBfEe35sZHEctHsSJNw8vGGqvPuME5Bc2kW7T7YVumMPfW/v5xQp81IUiumj2x8+49fITZNxNzdA2c/Onm+UzYKaW9xOcl/3014ZFsbKCwgZ44EcA+iEHH5DOHehKbhGYKYymBDazWW2CPMZDE3L8jMs5bqdxktUqqtc2YkKt1WjraSjIzOjyC6jeAgiRQ8J+BA0jX2pkL/iPT38XeOnpbw2XcvSvcglfwOj7H+TTj37Op6jrT5/wp7+vOV29M3xXK3L5f4Lh16h6U26NoWa6Rozc8p9jGucvuA0cswjyT3gU3xAiPIhIAr3vvfrrt0isZ/f6H3dpZnUImgFu2rZ/e3R8ENhNlsxA8797iDopADC1Jr51hI0/QgAlhEvfL/cjGIRhk7XgW8TtPTCge96YRHEKn3KQQmkRooboS42zifkXvN6KNCMpOPugfMHJmm1YVhQotI8sdc8ijTxKcRu9MVyguEPEEOkQahGGVQbD3YwipOYQYUEV5eZ+dcHxs3vJQBjR4rF5NvFFblpHfJmacAOKw8HB5ykiBMsarDlFs92rV6DqAm0HzYbSBBQxajzTM2uH2N/MjJIDmnovasltbvOyKTSNX6O+oq5rdX35EREJ7+I/35a94H//6ceGvgCcepnvNGnuhhel1wIWgfRt5DVzRcA160KWQj+CjiU0XoVU4ZhBBp6/ptlMf2ne3RSPuH6fyaGkT6YD6TwhrE97ABUJnurIhVhru8Apds0rYvUm6itLMAmCqJ5j3hluHA6psoSq/E/I6V/uqsQb/IhUTbR+yKDVUSxlbygQbbjubVmdmKGnNiLVcuJqjITjajx+E6vgVPhnM0DlBnKUIHdEJQZl+hvlX5wI/0SgghJH+BSm5tzMvK81WfPx0vCM/XZhbqqzBCKQwij74Xug6aGgeVEvEzfukHk+1Gza6DEp9jCTeKDhPQJ5GadHHBWW2lDvgwiK4qZxkUCUtxYIz1MzykyrKeIZEnl/garOoKsGb4T8qJ5cgj18hGI6Zt33IJ5e7gzmppv9nEGUx24p2b4h8aFdy+iWkupgALC/gDjecfIqE8x+CC3KeK9nSV9QgUS5713mazJPo497g9H0A5fvym6osSxy2CNAoe5ZDGYsEJ1fUOS6KMF9h2FnNY7s+w1776ehahHr8W09ZAq1R6UHUMhHNsobSK3IqDCvBQFUBHL8pkGumzbslk5RFrqjCc3L3fSwC/r4+VcBF993ILf1+OffBOzjTWNfdS9N8ufSFJKGvoCOtGpxbtaDj3V41uPIqm8Hb2yn3f6mosEuKY+hwE2Qmhns7swCuoyVAhudT8LcVeO7z3vBn+qW+gkNQrnT2kPxpxuP9XBiZhkMERsOW54ZuSAET7+pHaSge+R/n26gdm7KCW7rXl6ryiumWgdw+FUXahyBF/TPN2pYLKbvGwWUp2LHaRLd9N66xDAlouNF1APDNNjU59FyOV/gtxNZ+Ld5WddauDjLgud3S74g3cYpDJOmySBg/0skR59AuNHpZQLCO2+Dt2U1Icgi3jS6tYWQcRpCv0AHar5WEi9KsooPRH0pD+UBtxQb1SmyLByEwYCLFi5XyjznyjqnTBc+1xsAMdWDMFo7KR0uSbEUtO14Eu9k72ypnCZOeY0rMfMgThXuKHHkSuQ9ZWAYSiVeOZ13VQNiUwZH1dtLQbinxoW5FivxwGnNOwtOVklsHzKMHQ6z3VJcKbxcIxq45VSLDH8bVoFNjT1rxFUjgTObhYoitsfkNhxnu419wbYbvtyQ4/Oe0h2tLUIhLFU5KJUicFdF2LZnS6699ty5cuBI5coxymFVqgeNUQTdVEZahU2XXHrHPJYUUr164U7QfTjeUTtargoKtb20GSWUmelyVc6WMqNet4wqWBfItYopXHZnW1x12Hi7FBcKzzU6KcvxijKKfRR0tusqUHSlFLWtYGiaLHCJAMcSbBeyl30YeIqWlYPmpSSWY2N1hZZZyD/XPA81L7iuOOeQ5bR4gMH/8Jw6HYI1nXlqZPn7lTHekYbOrUbblB2NtsmxXwq9Ae+tGELTZ0U/Sw6C3GmXusAyEiZepc4u2HGsSZTpqb+biinBkLlXULMcgGTdawejOc1ZI7q07WA4tTuOrJ6r+bm778+oSMWo5dgdkEeL48b7bKw71KToAPK0O+SODSTevIzzRe4rgdcllbHfFbQpqQ750WGd7sHE60RYnwrXh6rdKq5wM+8G+oDemRdaYKec4reWcbk8V8z4EA0jg87g2GBSjfgopCMmVlwgqxk2EcZO4RhDQbzO7JCKhsZxU1QpS0W2dJx6Mn22OjuqGpJedKkW68MCRsk6G/a8JNA1FqaHQ5brPhueORJWRsbpadK5RRilBS7igCtFjjMVT+H75QhZSG8HPL8th9xWnpRbaJHVCIMBJA0G0Be01ZAvFV7h2tJgcZIW8p4SoNkG5YrjaBhkmhAFHD1zgj4/6SzNZejqhBIusK3WXROtnS1QPHO2EnGxn4y2W65atBJ2ERLswTuNw0npKPrZaJ+TkcJR7XW4I2ljUgT7nYL1T21r1eX9uGOsi1Uwl1pFNPcNehEYLafLOFmLO61W1Eba78pLfzJNXdbv9Tt5NK+KmazlmJYn8nXcy6q89KncWnaNgzfZnTMDhunBZKP2Ghp4Pj5FgJhdGWJ+YcfzobwixltKZ3tdBRv5V3YcbIYW1zpz8rTbVq6tBWw6diOT8/UD3Te8gW6sj+FqOhgKmw7HnlW67S33IIjAjiuwGb3asfKFyoQFM6oYxZFdipllF3noaPa1fQijpSYd+qfk0C1MoC9OCZVAKba80J+P8niG1YlNVIVvk93TLZ02qfN9Vp2Ayz13HsHl65wpqgN9O1+KAj7XZQMiwyfi9jV7DqdLfsO7x5N39CW2bENPaJeLA5d8PVaWIw4G/EzoVwG1FybKgHNdDmaOEnrM3UPkMUqp0L3GW3knc+uVwHPigOcHdl/Ih1m1gGpnN8owsnalU/CyLGLt2WSjVVV3qguGF/RWk9m4p89WFVUSx/XsmrrqYqYwYEcO12KL2ZjJrGuIfjgzNCa5WNoMa5eT4DRcm0u153hbIwW9JCs44ki4Rt4/aYmjxnZgXJaT1ATza2d0bXWmkkweq7VHk8KVxWJrnQ86Z3u1PgCGoJXdkN62UpW2A2Lo0GFx1Sdqscwt90QdwqQVnDJeHuUiu2hBD53sTGwzuu64tiDxJGx1E/egijm/FIgNS7mba3V0ppYdsO0xZ2si0JxRPGv37P1wvF3sBmXZk+bYZO0R5QEcLp3o6mrudO8nyw5Lj3hx2ub9yerIady6S0YZUS26Gsyi6XJM01m3tfdUeU0DLBgOk/FAdmmDiC+KK48rc0HZG40i+MvuEnS3sjOypjMjsQLSDqEN2GCTXZaBYK5twJkORjs8kFRf01eiV5buSvYclhteZ7O1ye9G4/NlPHULRW1FllxOiiOjDkLSz9TJme9XUnwdY/wyjqUZlXUPu1ZGH6tBxz9T6yNF9rfH07Z/zrazYWteDFtL+tLWS0ntn8fTATNwfXJJ7Bc8dmjDnJ/1vck8Nk52AG2l0LJ0CieEBrux00jq7fjBpQcLE2Os2+OTQWVyCyaNi+iJ0dCzsXkOtwGio/ZWYcYyent0zKbhQi9GkuQV/cXVubT2U6mKhN5W41lFmhAMr7UcGJH7lVDYOyzvxVc1HBLWuEiOMohIj2EMSaEsOT2MmdY5pfsSqRm2zi/mo40TTLgCDOUtoVx6++ngxGIn4jTUqEmYOdxZiq4hb3ZzY9vhgJLvgKCYlK0ZxtLqLzerFb0dL66ANij1EI7snNxugYiN2padrSVTs4z2ONC7VZhXMNq0IluRqrGY67FStK6XK91dF8JRpRxdIZ0unbJ6IpoO2GOxl08iMd8FR0r3FKY976irSiSo60Lv6sfTQHE2ut+/LAbUUtCVUbyO2NBqtWAt0KbdxXCHBStnc5qZp90Zuklr1DKufjxjuqvKDDvuaThihd2krx0HO27dOpr7rDXzt50Ts5j2Ch/6g4lBNwa+5dCx6CwN6J/7qlgwFFUteNIfLLViadDdvDckR9VGYrzpZlFGsbu7SD51vAzgPhLbjkK/21lzvYk6XhZGzCt9UlkF2cJmojnbKhR2ZpkldRrz3eiiTQV2MN9NbTJOO91y42UltpbKthJMsxGhi93QrLbHozcH8wNvWdOT299QTACLlK2sZuzBOaQFBaRzKbq98zKZbfuXJdbbHwKN9J3FSIiM9W6SloVCmIf0MDBPPHNYjyWa282YeWfaDbQ8mM9UpWP110P7MuWIwSnCEj/1zxOH3a3ThD90kmhDJVWU8JuZSJfttekUM+nIVXawMEEwXK1GPjmv1i023Hqy3c0UzHK4RM/NwivTrdHr5ANVGm3L3eTS03VpVI7K7kAf6yCq/K1cliefVu3darNrORKww8sqhkqcjbXxMV1NTdgo6jP9AuRgRswOoTXyKssUL/OFVpG7EaVenWExHRzSeGUMe8uI29IxQWNStO2pA+YgZ52O6OT90ThSaOm6JAc0YAomVEVtROflaXrseRMxZHWhlzBRV5kOgyOzW1lYaxca+pmxp53UYbZHst3qSRlp7Fq8qLcmZW9wNLpTgx4TwxXdoRiX3HGRem3rbFaxQiecY8ZSLOSDU+5Zg5dOZS+cJks4UE2iGaNErTmj7JzFZHu1rctsTQ6XxGQkyWel3VvFC+ugLbCVVOiRJ/vmdbksFdJlonFLsqVK9gJlPFU312l7ciT61JjoK28l9zdq5dP3bOrhhg3t/79/U78AeVafVdZHoM0B4X3n9jqM9nDoHAJt3Lmz6QfoO4y31/UR8Avc5/poHxV8wkGaxuknvDRTdOj5qV776Xa6+jFoWHz+6swVIc6b5/sFzOvRCEAnCP4ZnQOD6E7Zfb12Qxu6LA7rK7AEbkjRJRg65Ynvs9HpUYMEXdigs4ofn/769Lfn+5VgfRAUw21g+m4aOgx6QocVT58gsqfbGQ86nEf7U98CT89vorwue2lQP+7m/wh4fP/z+P7n8f3vnxfePq38t33/26FJ8tvvf7uP73/+CHgcyz6OZR/Hso9j2T/9seyj/3/0/4/+/9H//yn7/yO4/I40/kH/TzGdb77/b9OP7///6P7/ccX4uGJ8XDE+rhgfV4yPK8bHFeO/fMX46Ckf8IAHPOABD3jAAx7wvxf+G5gFcBMAUAAA

Outputs:

  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: Ec2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - Ec2Instance
      - AvailabilityZone
