AWSTemplateFormatVersion: 2010-09-09
Description: VPC Peering Setup
Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Network Configuration
        Parameters:
          - NetworkStackName
          - RequesterVpcId
      - Label:
          default: CICS
        Parameters:
          - TargetNetworkStackNameCICS
          - TargetVpcIdCICS
          - TargetVpcInstanceIP1CICS
          - TargetVpcInstanceIP2CICS
      - Label:
          default: MAWS
        Parameters:
          - TargetNetworkStackNameMAWS
          - TargetVpcIdMAWS
          - TargetVpcInstanceIP1MAWS
      - Label:
          default: PAS6
        Parameters:
          - TargetNetworkStackNamePAS6
          - TargetVpcIdPAS6
          - TargetVpcInstanceIP1PAS6
      - Label:
          default: PDDTS
        Parameters:
          - TargetNetworkStackNamePDDTS
          - TargetVpcIdPDDTS
          - TargetVpcInstanceIP1PDDTS
      - Label:
          default: PESONET
        Parameters:
          - TargetNetworkStackNamePESONET
          - TargetVpcIdPESONET
          - TargetVpcInstanceIP1PESONET
      - Label:
          default: PHILPASS
        Parameters:
          - TargetNetworkStackNamePHILPASS
          - TargetVpcIdPHILPASS
          - TargetVpcInstanceIP1PHILPASS

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName: 
        default: Environment Name
# requester - fortigate vpc
      NetworkStackName:
        default: Requester Network Stack Name
      RequesterVpcId:
        default: Requester VPC ID
# target vpc 1 - cics
      TargetNetworkStackNameCICS:
        default: Target Network Stack Name
      TargetVpcIdCICS:
        default: Target VPC ID
      TargetVpcInstanceIP1CICS: 
        default: Jumpserver Private IP
      TargetVpcInstanceIP2CICS:
        default: Jumpserver Private IP
# target vpc 2 - maws
      TargetNetworkStackNameMAWS:
        default: Target Network Stack Name
      TargetVpcIdMAWS:
        default: Target VPC ID
      TargetVpcInstanceIP1MAWS:
        default: Jumpserver Private IP
# target vpc 3 - pas6
      TargetNetworkStackNamePAS6:
        default: Target Network Stack Name
      TargetVpcIdPAS6:
        default: Target VPC ID
      TargetVpcInstanceIP1PAS6:
        default: Jumpserver Private IP
# target vpc 4 - pddts
      TargetNetworkStackNamePDDTS:
        default: Target Network Stack Name
      TargetVpcIdPDDTS:
        default: Target VPC ID
      TargetVpcInstanceIP1PDDTS:
        default: Jumpserver Private IP
# target vpc 5 - pesonet
      TargetNetworkStackNamePESONET:
        default: Target Network Stack Name
      TargetVpcIdPESONET:
        default: Target VPC ID
      TargetVpcInstanceIP1PESONET:
        default: Jumpserver Private IP
# target vpc 6 - philpass
      TargetNetworkStackNamePHILPASS:
        default: Target Network Stack Name
      TargetVpcIdPHILPASS:
        default: Target VPC ID
      TargetVpcInstanceIP1PHILPASS:
        default: Jumpserver Private IP

Parameters: 
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: network
    MinLength: 3
    MaxLength: 20
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 12
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
# Requester - Fortigate network
  NetworkStackName:
    Description: The name of the requester cloudformation Network stack
    Type: String
    Default: pchc-prd-ase1-fortigate-network
  RequesterVpcId:
    Description: The name of the requester VPC
    #Type: AWS::EC2::VPC::Id
    Type: String
    Default: vpc-038b16318bb94efd2
# target vpc 1 - cics
  TargetNetworkStackNameCICS:
    Description: The name of the target cloudformation Network stack
    Type: String
    Default: pchc-prd-ase1-cics-network
  TargetVpcIdCICS:
    Description: The name of the target VPC
    Type: AWS::EC2::VPC::Id
    Default: vpc-0088aef7093f90bc5
  TargetVpcInstanceIP1CICS: # private ip of the target jump server
    Description: Target jumpserver private ip
    Type: String
    Default: 10.0.2.36/32
  TargetVpcInstanceIP2CICS: # private ip of the target jump server
    Description: Target jumpserver private ip
    Type: String
    Default: 10.0.2.59/32
# target vpc 2 - maws
  TargetNetworkStackNameMAWS:
    Description: The name of the target cloudformation Network stack
    Type: String
    Default: pchc-prd-ase1-maws-network
  TargetVpcIdMAWS:
    Description: The name of the target VPC
    Type: AWS::EC2::VPC::Id
    Default: vpc-0396b4741384ed183
  TargetVpcInstanceIP1MAWS: # private ip of the target jump server
    Description: Target jumpserver private ip
    Type: String
    Default: 10.5.22.20/32
# target vpc 3 - pas6
  TargetNetworkStackNamePAS6:
    Description: The name of the target cloudformation Network stack
    Type: String
    Default: pchc-prd-ase1-pas6-network
  TargetVpcIdPAS6:
    Description: The name of the target VPC
    Type: AWS::EC2::VPC::Id
    Default: vpc-0fed281d3b7026344
  TargetVpcInstanceIP1PAS6: # private ip of the target jump server
    Description: Target jumpserver private ip
    Type: String
    Default: 10.5.18.40/32
# target vpc 4 - pddts
  TargetNetworkStackNamePDDTS:
    Description: The name of the target cloudformation Network stack
    Type: String
    Default: pchc-prd-ase1-pddts-network
  TargetVpcIdPDDTS:
    Description: The name of the target VPC
    Type: AWS::EC2::VPC::Id
    Default: vpc-045c92570c51de046
  TargetVpcInstanceIP1PDDTS: # private ip of the target jump server
    Description: Target jumpserver private ip
    Type: String
    Default: 10.5.12.141/32
# target vpc 5 - pesonet
  TargetNetworkStackNamePESONET:
    Description: The name of the target cloudformation Network stack
    Type: String
    Default: pchc-prd-ase1-pesonet-network
  TargetVpcIdPESONET:
    Description: The name of the target VPC
    Type: AWS::EC2::VPC::Id
    Default: vpc-038dd712e7d2adb74
  TargetVpcInstanceIP1PESONET: # private ip of the target jump server
    Description: Target jumpserver private ip
    Type: String
    Default: 10.5.14.60/32
# target vpc 6 - philpass
  TargetNetworkStackNamePHILPASS:
    Description: The name of the target cloudformation Network stack
    Type: String
    Default: pchc-prd-ase1-philpass-network
  TargetVpcIdPHILPASS:
    Description: The name of the target VPC
    Type: AWS::EC2::VPC::Id
    Default: vpc-039c9b4fcdf7be924
  TargetVpcInstanceIP1PHILPASS: # private ip of the target jump server
    Description: Target jumpserver private ip
    Type: String
    Default: 10.0.0.42/32

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

###
# VPC Peering to Target VPC - CICS
###

  PeeringToTargetCICS:
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      PeerOwnerId: !Ref AWS::AccountId
      PeerRegion: !Ref AWS::Region
      PeerVpcId: !Ref TargetVpcIdCICS
      VpcId: !Ref RequesterVpcId
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, cics-peering]]

# Routes from requester to target

  RequesterPublicRouteCICS1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-PublicRouteTable'
      DestinationCidrBlock: !Ref TargetVpcInstanceIP1CICS # destination jumpserver IP
      VpcPeeringConnectionId: !Ref PeeringToTargetCICS # vpc peering id

  RequesterPublicRouteCICS2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-PublicRouteTable'
      DestinationCidrBlock: !Ref TargetVpcInstanceIP2CICS # destination jumpserver IP
      VpcPeeringConnectionId: !Ref PeeringToTargetCICS # vpc peering id
  
# Routes from target to requester

  TargetPublicRouteCICS:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${TargetNetworkStackNameCICS}-PublicRouteTable' # target subnet, might change
      DestinationCidrBlock: !ImportValue
        'Fn::Sub': '${NetworkStackName}-VpcCidrBlock'
      VpcPeeringConnectionId: !Ref PeeringToTargetCICS

# secgroup of target instance, add inbound rule
#
#  AllowTrafficToJumpServerCICS:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#      Description: Allow traffic from FortigateVPN VPC
#      IpProtocol: -1
#      GroupId: 
#        Fn::ImportValue:
#          !Sub '${TargetNetworkStackNameCICS}-JumpHostSecurityGroupId'
#      FromPort: -1
#      ToPort: -1
#      CidrIp: 10.0.5.0/25

###
# VPC Peering to Target VPC - MAWS
###

  PeeringToTargetMAWS:
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      PeerOwnerId: !Ref AWS::AccountId
      PeerRegion: !Ref AWS::Region
      PeerVpcId: !Ref TargetVpcIdMAWS
      VpcId: !Ref RequesterVpcId
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, cics-peering]]

# Routes from requester to target

  RequesterPublicRouteMAWS:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-PublicRouteTable'
      DestinationCidrBlock: !Ref TargetVpcInstanceIP1MAWS # destination jumpserver IP
      VpcPeeringConnectionId: !Ref PeeringToTargetMAWS # vpc peering id

# Routes from target to requester

  TargetPublicRouteMAWS:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${TargetNetworkStackNameMAWS}-PublicRouteTable' # target subnet, might change
      DestinationCidrBlock: !ImportValue
        'Fn::Sub': '${NetworkStackName}-VpcCidrBlock'
      VpcPeeringConnectionId: !Ref PeeringToTargetMAWS

###
# VPC Peering to Target VPC - PAS6
###

  PeeringToTargetPAS6:
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      PeerOwnerId: !Ref AWS::AccountId
      PeerRegion: !Ref AWS::Region
      PeerVpcId: !Ref TargetVpcIdPAS6
      VpcId: !Ref RequesterVpcId
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, pas6-peering]]

# Routes from requester to target

  RequesterPublicRoutePAS6:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-PublicRouteTable'
      DestinationCidrBlock: !Ref TargetVpcInstanceIP1PAS6 # destination jumpserver IP
      VpcPeeringConnectionId: !Ref PeeringToTargetPAS6 # vpc peering id

# Routes from target to requester

  TargetPublicRoutePAS6:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${TargetNetworkStackNamePAS6}-PublicRouteTable' # target subnet, might change
      DestinationCidrBlock: !ImportValue
        'Fn::Sub': '${NetworkStackName}-VpcCidrBlock'
      VpcPeeringConnectionId: !Ref PeeringToTargetPAS6

###
# VPC Peering to Target VPC - PDDTS
###

  PeeringToTargetPDDTS:
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      PeerOwnerId: !Ref AWS::AccountId
      PeerRegion: !Ref AWS::Region
      PeerVpcId: !Ref TargetVpcIdPDDTS
      VpcId: !Ref RequesterVpcId
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, pddts-peering]]

# Routes from requester to target

  RequesterPublicRoutePDDTS:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-PublicRouteTable'
      DestinationCidrBlock: !Ref TargetVpcInstanceIP1PDDTS # destination jumpserver IP
      VpcPeeringConnectionId: !Ref PeeringToTargetPDDTS # vpc peering id

# Routes from target to requester

  TargetPublicRoutePDDTS:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${TargetNetworkStackNamePDDTS}-PublicRouteTable' # target subnet, might change
      DestinationCidrBlock: !ImportValue
        'Fn::Sub': '${NetworkStackName}-VpcCidrBlock'
      VpcPeeringConnectionId: !Ref PeeringToTargetPDDTS

###
# VPC Peering to Target VPC - PESONET
###

  PeeringToTargetPESONET:
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      PeerOwnerId: !Ref AWS::AccountId
      PeerRegion: !Ref AWS::Region
      PeerVpcId: !Ref TargetVpcIdPESONET
      VpcId: !Ref RequesterVpcId
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, pesonet-peering]]

# Routes from requester to target

  RequesterPublicRoutePESONET:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-PublicRouteTable'
      DestinationCidrBlock: !Ref TargetVpcInstanceIP1PESONET # destination jumpserver IP
      VpcPeeringConnectionId: !Ref PeeringToTargetPESONET # vpc peering id

# Routes from target to requester

  TargetPublicRoutePESONET:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${TargetNetworkStackNamePESONET}-PublicRouteTable' # target subnet, might change
      DestinationCidrBlock: !ImportValue
        'Fn::Sub': '${NetworkStackName}-VpcCidrBlock'
      VpcPeeringConnectionId: !Ref PeeringToTargetPESONET

###
# VPC Peering to Target VPC - PHILPASS
###

  PeeringToTargetPHILPASS:
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      PeerOwnerId: !Ref AWS::AccountId
      PeerRegion: !Ref AWS::Region
      PeerVpcId: !Ref TargetVpcIdPHILPASS
      VpcId: !Ref RequesterVpcId
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, philpass-peering]]

# Routes from requester to target

  RequesterPublicRoutePHILPASS:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-PublicRouteTable'
      DestinationCidrBlock: !Ref TargetVpcInstanceIP1PHILPASS # destination jumpserver IP
      VpcPeeringConnectionId: !Ref PeeringToTargetPHILPASS # vpc peering id

# Routes from target to requester

  TargetPublicRoutePHILPASS:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !ImportValue
        'Fn::Sub': '${TargetNetworkStackNamePHILPASS}-PublicRouteTable' # target subnet, might change
      DestinationCidrBlock: !ImportValue
        'Fn::Sub': '${NetworkStackName}-VpcCidrBlock'
      VpcPeeringConnectionId: !Ref PeeringToTargetPHILPASS