AWSTemplateFormatVersion: 2010-09-09
Description: 'This is a modified Akamai Enterprise Application Access (EAA) cloudformation template.
  AWS CloudFormation Template Akamai Connector:  This template installs
  Akamai Connector **WARNING** This template creates an Amazon EC2 instance and an
  EBS volume. You will be billed for the AWS resources used if you create a stack
  from this template.'

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: "Resource Configuration"
        Parameters:
          - Name
          - OrgName
          - EnvName
      -
        Label:
          default: "EC2 Configuration"
        Parameters:
          - InstanceType
          - ImageId
          - NetworkStackName

    ParameterLabels:
      Name:
        default: "Resource Name"
      OrgName:
        default: "Organization Name"
      EnvName:
        default: "Environment Name"
      InstanceType:
        default: "Instance Type"
      ImageId:
        default: "Instance AMI"
      NetworkStackName:
        default: "Network Stack Name"

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: dsapp-akamai-eaa #change if needed
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: pchc
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  InstanceType:
    Description: Soha Connector instance type
    Type: String
    Default: c5.large
    AllowedValues:
    - c5.large
    - c5.xlarge
    - c5.2xlarge
    - c5.4xlarge
    - c5d.large
    - c5d.xlarge
    - c5d.2xlarge
    - c5d.4xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - m5d.large
    - m5d.2xlarge
    - m5d.4xlarge
    - r5.large
    - r5.xlarge
    - r5.2xlarge
    - r5.4xlarge
    - r5.8xlarge
    - r5d.large
    - r5d.xlarge
    - r5d.2xlarge
    - r5d.4xlarge
    - r5d.8xlarge
    - i3.large
    - i3.2xlarge
    - i3.4xlarge
    - i3.8xlarge
    - t3.xlarge
    - t3.2xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  ImageId:
    Description: Instance AMI, get the value from the downloaded Akamai CF template
    Type: String
    Default: ''
  NetworkStackName:
    Description: The name of the network stack
    Type: String
    Default: pchc-prd-ase1-pas6-network # change if needed
    MinLength: 1

Mappings: 
  EnvShort:
    Production:
      Name: prd
    Staging:
      Name: stg
    Development:
      Name: dev
    Test:
      Name: test
  RegionShort:
    us-east-2:
      Name: ue2
    us-east-1:
      Name: ue1
    us-west-1:
      Name: uw1
    us-west-2:
      Name: uw2
    ap-east-1:
      Name: ae1
    ap-south-1:
      Name: as1
    ap-northeast-1:
      Name: ane1
    ap-northeast-2:
      Name: ane2
    ap-northeast-3:
      Name: ane3
    ap-southeast-1:
      Name: ase1
    ap-southeast-2:
      Name: ase2
    ca-central-1:
      Name: cc1
    cn-north-1:
      Name: cn1
    cn-northwest-1:
      Name: cnw1
    eu-central-1:
      Name: ec1
    eu-west-1:
      Name: ew1
    eu-west-2:
      Name: ew2
    eu-west-3:
      Name: ew3
    eu-north-1:
      Name: en1
    me-south-1:
      Name: ms1
    sa-east-1:
      Name: se1
    us-gov-east-1:
      Name: uge1
    us-gov-west-1:
      Name: ugw1 

Resources:

####
# EC2 Section
####
  AkamaiConnectorSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Opening everything outbound
      VpcId:  
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VpcId"
      SecurityGroupEgress:
      - IpProtocol: "-1"
        FromPort: "-1"
        ToPort: "-1"
        CidrIp: 0.0.0.0/0

  AkamaiConnectorInstance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroupIds:
      - Ref: AkamaiConnectorSecurityGroup
      Tags:
        - 
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
        - 
          Key: Environment
          Value: !Ref EnvName
        - 
          Key: Organization
          Value: !Ref OrgName
      ImageId: !Ref ImageId
      SubnetId:  
        Fn::ImportValue:
          !Sub "${NetworkStackName}-PublicSubnetId1"
      InstanceType:
        Ref: InstanceType
      UserData: # unique value in downloaded CF template from Akamai 
        Fn::Base64: H4sICF5OTGYC/2NvbmYudGFyAO06aZObSJb9mV9BlPfD7sguQKCDiuiIBYEkkED32T3j4EgOcYpb+vWbCVJVud3d45nY9sxu64Vt4TzefWXCM/FM/Pdcq8ZAM0Hywx8CZAO/9UuSNP32jMYpsk1RP+DVD98B8jTTEkj+hz8ntHt4kLkB+JHqUd12r9unyWe2S7Mshf3wgP//YESh5drPbuj+cTRQUHcZBv1SvQ71/reGXq/9A8V02zTJ9Ci6B+OfbpOdH3Dye8a/YdmaGbjhbyrq78z/H4WfBHHIbabrv2KaDcLMNfEGfsQN3dI6JNX5pDNt5hPT7jLwyaI/mZ0eaLdN0O0Y7WbT5xQkBUjqTVEYAiOLkk+1sp41Tws095NmGCBNn40ouO2IoyRryDAMjRkggUNa5txIE1GcEaUWxwSaSYl6zzN6xjxweVv5m0vhKsyPbDe8sfY5AemNnpNl8QtB+JGh+U6UZi/9PksSTRjkiZa5UYiFcGf1uRn7igwcJeoFmKG9Y+VXuTG0husEmG66ummpXvlKv5mb3/RRz3XpHov5pha/2wGH+5DTRqovMCH+MRPouf3LYQqzoqTUEvNznETVpR4W3FTTfWBit/T+/G9R/5mv63/7Uf+/S/3v/1r977EsyT4agD8BWK4PdKBlz5fA/9fUf+h29Ff1vwOPBI/6/x3gw68CPry5BT54XxhxsdKC2Af4h98CDPuArx03xZFf4fBXC3Fw2/RFjW0WOK7t+PBv5oY2HoX+Bc8cgAewLMLVQQBL8QccllS4Pn2GeAH+6q5W7vvIZxs8VhIF9dZUCwBuukndg1wQyUxzQ8iG76N5iC7NY9R8APOOGC9dWMODKAE1Tdg+QFqHKMcNyHueQikyXIMY8ARYIAGhAZ6xDxDRfYnlhmZNG7H0CyFft+AO/H2Bu1D7kcL+oyzLZ+BraeYasC0i7Nw1AQFCAgmXEncxCYgbVM9OFvhQsz/+NrwZDJb6NK7FT/Effw8w7FWZ7/a8IAuKmuHgn2rzvcP3jCvIMHe1Idl1qHEA1ZPVCnhbivugAP5HPI0gtss7XZquVWvkSz5hm4IXWuJGefqlAlOoapwHflTiGrTPL4igX9dyja/2YJD3MM6zz9klBi+w17IxDMc/4HPYraUQC+Q3daLcN5EARqKVsCGCnmriFsgMB5jP+MiPdFzXUjiOWjyIE28eXjDUXn3CCcgvbCLtptsL7CCDv7f287Phu6gLRXTR6g+fcOPlZ8i4nWiBqWXazzfLp0BLDOdnuC79+S8Ni2Jl+LkJcN8NAfRDDj4gnVvQlezc1xIYTTFsZtPaBFmEBxrk+BmXMtxMojitVVTvbcSEWqvR1stQkGnh5VdQvQUQIoeE/QAaRj7XyF7wn57+JvCjp782XErhP8slnIDR97/Ipxv+kk9xuXz6iD/9bcct1TvDd7Uil/8HGH6Nqjfl1hhqpmvEyC3/MaZx/oKbwNJyP/uIh9ENIcKDiMTQ+96rv55FYj3b1/+4SzOrQ1Dzcc003duj5QLfbLJkCpr/3UPUSgCAqTV2DQ82/ggBlBBufb/dDWEQBk3WgrOI23tgQPe8MYniFD5lIIHSIkQN0ZcaZxPzL3h9FGlGElC4oHzBqZptWFYUKLSLLHXPIo08Sn4bvTGco7hDxBDpAGoRhlUKw10LQ6TmAGFBFeXmfnXBcdN7yUAY0WZZKzR8lWmGh68TDR5AcTg4+DRFhGBZgzUnb4579Q5UXaDtoNlQmoAiho1nOlrtEPrNzCg5oKX3ohbf1jaTTaFp/Br1FXVdq+vLT4hIcBf/+bbtBf/bzz819AVg1dtcq0lzN7woveawCCRvI6+ZKwS2VheyBPoRdCyh8SqkCkvzU/D8Jc1m+Uszd1M84vp9JoeSPmkWpPOEsD7pACoSPNWRC7HWdoFLzJpXxOpN1FeWYBIEYb1GuzPcOBxSZQlV+Z+Q0/+6qxJv8CNSNdH6IYVWR7GUvqFAtOG+t211Yoae2ohUy4mrERKOq/G4TayCc+4Wmo/KDeQoRu6ISgzK9DfKv7oQ/glBBSUO8SlMzZmWOl9qsubjpeEZ+/3C3FTnEQhBAqPsx2+BpoeC5kW9TNS4Q+q4ULNJo8c412EmcUDDewiyMko8HBWW2lDvgwiKYidRHkOUtxYIzxItTDWjKeIpElm/QFWn0FX9N0JuWC8ugQ4foZiWVvc9iKeXO4OZZqe/ZBDlsVtKNm9IXGjXMrylpDoYAOwvII53nLzKBLMfQosy3utd0mdUIFHue5f5mszT6OPeYDT9wOWbshtqLPMM9ghQqHsWgxkLhMULilwbJbhvMOysxpF+u2Hv/TRULWI9uu2HTKH2qHQACvnQRHkDqRUZFeY134eKQI7fNMh104bd0inKQnc0gXa5mx52QR8+/Sbg4vsO5LYf//S7gH24aeyL7qVJ/lySQNLQF9CVVi3OzXrwsQ7PehxZ9e3ijW2T5FcVDXZJWQQFboJUS2F3p+XQZYwEmOh+EuauGt993Qv+VLfUT2gQyp3UHoo/3Xish2MtTWGImHDYcLTQBgF4+l3tIAXdI//bdAO1c1OOf9v38lpVXjHVOoDDr7pQoxC8oH++UsNqNX3fKKA8FVlWk+im99YlgikRXS+iHhimwaY+j9fr+Qq/3cjCv81kXWvh5jT1n99t+Yx0GyUwTJomg4D9LxF7LoFwo9vLGAR33gZv22pCkEW8aXRrCyHjNIR+hQ7UfK0kXhxJKj4Ql2tpKA24tdioTpEk4SQMBly4srlS4jlbWnKKnvZOCr0VXTU/aDZjGpVSMaWwOMiT6Cg5haFyC3HKL7gS007iVOG8EUdtRN5RBtutUolXbsnb6hZiUwae6ugjP9BpOdd2YiWeuEUzZ8DFKoXpQadjBsP0uBY3Ci/ViAZ2OV2EW/cQVL5Jy44x5qqxwGnNRkURSZk6BHJ63JsX7LDnyz0lFzq9tBakCIUwVOW0KNW1VCmCcVWum3Ln2HPlxFGqwFHKGs7BUXXNa8p4UWHTNZfcMcsj1T0GIqUIIjXdSSRElKmC1FYHlKuODtfpbkGp7c1FCZa+etqelJOoYgqX3tkWN202OqzFlcJzjU7KUt7Q21wP/fZhV/nKUinFxUHYLhaSwMUCHIuxY8Be9MB3lEVaDprJkVjK280VWmYl/VLzPNS8YNvinEOWW0QDDP4Hca8k7X4mXcxqyQjhjEqyEx3NZvRZSMw1PJkT+mW8m3AHClo84bwwGe3pSNvIZQeTWL0P+O7UT6u9O5eK+TySL4u2MRics+5uxq7o9DqOBi1qS1X+qugZU/5wGRqwtk62fNDpYSxXEcvULGTR8QKZjzKLMydt5hAGl/VBJGSnTCXftXfnQVxwvVC4jItFQRyLTErHBytbYJo/a9Fdbr7PzR4t95djmSlmw6ljR4tjkMsBR1dQmDm5W8orPtoTdJ7TStG2N7RZ6QtfxWbuxBSGyjUaero2pjfTlRgrxHKp7brJbH+s5BnMQOtOax5MilZJLXqL2UyZCteI7srcNnaw9XIQg022WfN2tXVMU7noQ5OZyPwlHXClyHGa4ih8vxwjCy1Jn+cP5ZA7SJPyAC2yGWMwgEaDAfSFxWbIlwqvcORosDqPVpJOC9Bsg3LDcQwMsgXfIU6FsXPpZZdx/KszL/KBTWJzjRr5vT7bqdhVrpaZr5zsxbzsMt6MKvrxXA4rbzbI4ksm8ZpcXKeXqt/VWf54KGfTccvAElUEC2+VBubmMN73V3NeBgct3LeilpBaQ1BOqMykey1POC05Wdiqx7jXAzZtd+cGIUk9rEun2WLfCyeTCHhBFpimHXiuzx3LVTjruvyZFvgjEQg6f40u2rpcztsFM93suup81S89C+vb6lmYGGERnM5yFGhV4p4Nb91aX/y+HMfuAJBytz8bFxa5pmWYVFhx3PLFnnAw+2ZikBiTarpkGVd5TOaWFo+YA58ZcXumnKK10gqFjjIheqTCVetR3FbF6Zz0OGfu0atjYfb4DovViU1Uha+T3dMtnTap831WnYDLPXd64PJlzhTVwfIwX4sCPl9KW4gMn4iH1+w5nK75PW97Z8dzR2xJQk8gy9WJi78cK8sxt5BURcmlOJmPLuSAs20OZo4SeszdQyQZpVToXvJBOkrcbiPwnDjged5qn8x20WtlrdXiaEZTfkgZEi9JIkYOr/1qfWRPEUfY1nGxt6czOz+YrdXAZI7HStxp6ep8NdvTfMSIRqC7e2pYma1Ck9YpkDwsNdTNTJrNuF0/3XnUMlEn45Fo8mLK99jjcTKKXRCbPN0VHIHq+GXmtYthz1D6cjUtgr2LGavocHIUbZ2t9Ugwt6POxuWy6mrpwVBJzBlVetmU6GwLYdM7JhtKkT11mF2IVaviruWWxQoi970p6E7nMt/ZqCeGYOezpd8fK0BkhsmVO0oZK3mzltYZ+aHXd6rCEfyjcTAp218nBQZjgC73RuVN/HzVFWnTYTfJ4OAtw5lzciJn5e+W7LUUiCxRaWdZmdyqI/cYeRpFE7WvTrHzVhlHs1hKglZxLsnN2Zq2zUW1zGDWdnsqp13mZ6q36ZXeOJgvhNgymb2YtvmdeJZZ89TFpJHPRbuc1+YtPxkv8wnr9nY8bMgnVNtddKudbea7ksvVrXgx2FYMLbiRfTvPqWC2jSc05vtlvFI24kzNV/0oNVgmO0VVUDmGb7LFtHvsLLqTw8guja07TRYDIexvoyK7jnojsn9VRth2t5GIsvTjLpelncyRTklphEt1M1+PBxnQuHA3HKRMELZWq05nlUYtdsXJHNCCnTUv9h1sxY+rCipcO6SetiDWxGWa8+Zy1d3o8f6ab9otZjVf7Ve6znBdYmSu+vuusneGdncRHvrCCBvack/sRJet0hIuXX66Nvlpmc7owQbQEzemTXZibnL9IA8XTg4YsyPa53lGXeg+LXdNgcV6sZhRPtVXHda+XOaSGay347RiUpelO95l0mXGYkbrmmLMt+Kpe1YMxpZIUm2vB2FbIX2sncqgpQxn7G4qXoaEF5KnXcz6/ZOlBgYjGzopWv44Eq+Dads9zRZXOR3M5a2p62k456YUlgCLhc2cmfZVc1x0u4Fhb7gsmE4cdSguRyOCV8ZVWBA6dNa8lZ7b5IwN/SNrb50rsAkS2yV6vJ1vW+J0ObBYjxxnSeDKkh3uFLJtXxkqXiy5ABZri+vml61jLK6zbntyXDPnRbiJd5gwOZ/P+lncDkB62nILbx6fZGd1COGRhfFISgm3ljGnW04hiH60zKM5W2oeaJnVvLXU0j42HFxpOhqRcr+1uSbZzrbVDeuLOy7r6AXR565F2rsE5zI52vNhj2qp+saCMRKbxwJsg26BiaPQ3l24a6I7G0I/pJv1kFvLvC7sGVdlDULXyrXG7gsAG8RNmyKEznHCUIOewNoDF3QtbHO67Ej6QGbMqWKZSyXGbYuY2AOY3nJr7EwWlE5AQykTckNzc355YRdHfxGw271q08Sii3lGK59MXPXIJi2wHx3c/gL2h/J15BHWPO4RrVKojjvDPW43m0E4Kh2hJ9uCve1lviSQQoG1iqvFrPzLIlA450xIE45m+j7Ncux266WnxV5tU54lxsYp7+qeyxpalI1Ho2kKTZ7uLjqWxj1n0oc9nhr1HP5qVfSoL1vS6jzwKL2IyNCkJ+P9etRRietlrU/6yUVl9YyJK1LgBSHCvPI61xxwXHT2aT/RknmrGib2bC9nTjJ3gyU1VSR1aAKPDTdkGvC27uiyqRHW1N55srHBUmc6F+VJ0FmsneMCqp0lKbvwUGXJcnCenGesLJSnPaeT+djfHoUq2nnHYWpOR7bZ0UtsEK7cAUz+3GlUiKtLmnfaS7FNqAeGKbwZO4SFcwazYmSvu2FP6h6sueiFI0U5t43xtD3zMXq3d9m+VJHeiIn21ck/B90ZjKd2Zznzgt0g8SLa6jkaeVY6byX3d2rl07cc6uGBDZ3/v/1QvwJZWt9V1legzQXh/eT2OozOcOgeAh3cuUJzffQdxtt0fQX8As+5LjpH+R9xkCRR8hEvtQRden6s93683a5+8BsWn7+4c0WIs+b5/gLm9WoEoBsEt0D3wCC8U7ZfX7uhA10aBfUrsBgeSNFLMHTLE91Xo9ujBgl6YYPuKn56+svTX5/vrwTri6AIHgOTd8vQZdATuqx4+giRPd3ueNDlPDqfugZ4en4T5XXbS4P68W7+e8Dz4/vfx/e/j+9//7Tw9mnlv+z73zYDg/2r73+Zx/c/3wMe17KPa9nHtezjWvZPfy376P8f/f+j/3/0/3/K/t8Dlz+Qxt/p/+lO+6vv/0nm8f3/9+7/H68YH68YH68YH68YH68YH68YH68Y/+lXjI+e8gEPeMADHvCABzzgAf++8D8irPCmAFAAAA==

Outputs:

  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: AkamaiConnectorInstance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - AkamaiConnectorInstance
      - AvailabilityZone
