AWSTemplateFormatVersion: 2010-09-09
Description: 'This is a modified Akamai Enterprise Application Access (EAA) cloudformation template.
  AWS CloudFormation Template Akamai Connector:  This template installs
  Akamai Connector **WARNING** This template creates an Amazon EC2 instance and an
  EBS volume. You will be billed for the AWS resources used if you create a stack
  from this template.'

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: "Resource Configuration"
        Parameters:
          - Name
          - OrgName
          - EnvName
      -
        Label:
          default: "EC2 Configuration"
        Parameters:
          - InstanceType
          - ImageId
          - NetworkStackName

    ParameterLabels:
      Name:
        default: "Resource Name"
      OrgName:
        default: "Organization Name"
      EnvName:
        default: "Environment Name"
      InstanceType:
        default: "Instance Type"
      ImageId:
        default: "Instance AMI"
      NetworkStackName:
        default: "Network Stack Name"

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: dsapp-akamai-eaa #change if needed
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: pchc
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  InstanceType:
    Description: Soha Connector instance type
    Type: String
    Default: c5.large
    AllowedValues:
    - c5.large
    - c5.xlarge
    - c5.2xlarge
    - c5.4xlarge
    - c5d.large
    - c5d.xlarge
    - c5d.2xlarge
    - c5d.4xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - m5d.large
    - m5d.2xlarge
    - m5d.4xlarge
    - r5.large
    - r5.xlarge
    - r5.2xlarge
    - r5.4xlarge
    - r5.8xlarge
    - r5d.large
    - r5d.xlarge
    - r5d.2xlarge
    - r5d.4xlarge
    - r5d.8xlarge
    - i3.large
    - i3.2xlarge
    - i3.4xlarge
    - i3.8xlarge
    - t3.xlarge
    - t3.2xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  ImageId:
    Description: Instance AMI, get the value from the downloaded Akamai CF template
    Type: String
    Default: ''
  NetworkStackName:
    Description: The name of the network stack
    Type: String
    Default: pchc-prd-ase1-pas6-network # change if needed
    MinLength: 1

Mappings: 
  EnvShort:
    Production:
      Name: prd
    Staging:
      Name: stg
    Development:
      Name: dev
    Test:
      Name: test
  RegionShort:
    us-east-2:
      Name: ue2
    us-east-1:
      Name: ue1
    us-west-1:
      Name: uw1
    us-west-2:
      Name: uw2
    ap-east-1:
      Name: ae1
    ap-south-1:
      Name: as1
    ap-northeast-1:
      Name: ane1
    ap-northeast-2:
      Name: ane2
    ap-northeast-3:
      Name: ane3
    ap-southeast-1:
      Name: ase1
    ap-southeast-2:
      Name: ase2
    ca-central-1:
      Name: cc1
    cn-north-1:
      Name: cn1
    cn-northwest-1:
      Name: cnw1
    eu-central-1:
      Name: ec1
    eu-west-1:
      Name: ew1
    eu-west-2:
      Name: ew2
    eu-west-3:
      Name: ew3
    eu-north-1:
      Name: en1
    me-south-1:
      Name: ms1
    sa-east-1:
      Name: se1
    us-gov-east-1:
      Name: uge1
    us-gov-west-1:
      Name: ugw1 

Resources:

####
# EC2 Section
####

  AkamaiInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
      Roles:
        - !Ref AkamaiIamRole

  AkamaiIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Sid: "1"
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "ec2.amazonaws.com"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  AkamaiConnectorSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Opening everything outbound
      VpcId:  
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VpcId"
      SecurityGroupEgress:
      - IpProtocol: "-1"
        FromPort: "-1"
        ToPort: "-1"
        CidrIp: 0.0.0.0/0

  AkamaiConnectorInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref AkamaiInstanceProfile
      SecurityGroupIds:
      - Ref: AkamaiConnectorSecurityGroup
      Tags:
        - 
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
        - 
          Key: Environment
          Value: !Ref EnvName
        - 
          Key: Organization
          Value: !Ref OrgName
      ImageId: !Ref ImageId
      SubnetId:  
        Fn::ImportValue:
          !Sub "${NetworkStackName}-PublicSubnetId1"
      InstanceType:
        Ref: InstanceType
      UserData: # unique value in downloaded CF template from Akamai 
        Fn::Base64: H4sICCZ6TmYC/2NvbmYudGFyAO06aZOjRpb+zK8gqvfDzqi7xKGzIhyxIJCEJITQLfno4EgOiUskh+DXbyZIVdVu29MzsfbsrpXhauHMfGe+Kx88N5+b/7XQrmOgmSD+7g8ZVD1+65ei2NbbM56nKYZmviOv3/0JI4WJFiPy3/01B9Mj/cT1wfd0l+606D5NU8+dNsv0Wizx3WP8vx9GGFiu/ewG7h9HAzt1p1X5ON1t0+9/q9HtMt/RrQ7DtrptqtVF/s9W/k/9mf5vWLZm+m7wm4r6B+v/R8cPgjjkNrP1T4RmgyBxTbIe35NGr93X+kz3E2gB6lPL6rKfdEDRn9pMhwFtutU2rU4N9BmCOANxBRQGATCSMP5UKetZO2u+5n7SDANA+GyE/g0iCuOkJtNCgcYAMZrSEudGuhlGSTPXoqiJV2CzgnnGz8QZFG87f3Mr2kV4oe0GN9Y+xwDe6DlJEr00m15oaJ4TwuSl1+tTzdoN0lhL3DAgAgR5/VzPfUUGzTarDYShvWPlV7kxtJrrGJguXN20VO18pV+vLW76qNY6bLdPeKYWvYNA0z3EaS3VF5gw/4QJ9NT+5TRNWGGca7H5OYrDa1FNCy7UdA+YxC26Pz/y/yP/f5X/u4/8/xcZlusBHWjJc+F7/578T6PE/1X+b7eoR/7/M8aHXx3k8GYW5OB9YiTFq+ZHHiA//NYgiA/k2nEhie2KRL9aQIIb0Bc5tt7guLbjob/EDWwyDLyCTBxA+igtot2+j1LxBxKlVLQfPiO8gHw1Vyv1PGyzNR4rDv0KFGo+IE03rmqQApNMNDdAbHgeXkfoYBrh4gOYd8Rk7qIc7ocxqGii8gHROoQpaSDeU4ikSEgNYSBjYIEYBAZ4Jj4gRPctlhuYFW3M0i+EfAUhHfT7gqBw+QFR/ZHn+TPwNJi4BiqLmnbqmqAJgiYWDjbvYjYRbnB9dhLfQ5r9/rfH24GhVA+jSnxIfv97gyBelfkO5gWfoKgZDvmpOr53+J5JGR/MXW1Ydh1pHCD1JJUC3raSHsiA95GEIcJWvNOl6VqVRr7kE5UpZKbFbpjCLxUIkapJHnhhTmrofH5BBP+6lmt8BUMg3oMoTT4nRQReUK1lEwRJfiAXqFqDCAviFzph6plYACPWclQQIUs1SQskhgPMZ3LkhTqpaxDN4xIP4STrhxcCl1efyCbiFxWRdl3t+bafoN9b+fnZ8FxchWK6ePeHT6Tx8iNi3I4139QS7cfbyUOgxYbzI9oHf/x7zaJ4NbzUBKTnBgDZIYcesM4tZEp26mkx8qYIFbOwOoIkJH0NcfxMSglpxmEEKxVVsLWYSGsV2mobdjItKH4F1ZsDYXJY2A+gZuRzheyF/OHpZ4EfPf1UcykF/yqXaAF53/8gn27wSz7F5fLpI/n0845bzu8M39WKTf6fYPjVq96UW2GomK4QY7P855gm+YI0gaWlXvKRDMIbQowHE4mQ9b1Xf7WKxXq2y/+4S6NULqh5pGaa7u3RcoFn1lESgvr/7i5qxQCg0Bq5xhkV/hgBkhCBvgd3A+SEfh210Crm9u4YyDxvTGI/RU8JiJG0GFFN9KXCWfv8C1ldReqZGGQuyF9IumIbpRUZCe3ik7pHkVoeOb3N3hhOsd9hYpi0j7SI3Aoid9eCAKvZx1hwRrmZX5VwXHhPGRgjBp5omUauEs04k+tYQxdQEk0OPs0wIZTWUM5J6+teBYGzCzo7dGw4TCARg9oyHa0yCP12zDg44K33pBbd9taLdaKp7RrXFVVeq/LLD5iIfxf/+Qb2Qv784w81fQFYFZhr1WHuhheH1xQlgfht5jVyBcDWqkQWIztChiXUVoVVYWkeBM9f0qy3v9RrN8Vjrt9HciTpk2YhOk8Y65MOkCLBU+W5CGt1LmiLWfGKWb2J+soSCoIgqPZod4Zrg8OqzJEq/xNx+re7KskaPyZVEa0eIDp17EvwDQWmjeDewKrAjCy1FqmSk5yHWDiuwuPWvgouqZtpHk43iKMImyNOMTjS3yj/6kb0XwCuSOKAnKHQnGjQ+VKTFR8vNc/E7yfmOjuPQABi5GXff8uoayh0vLiWCWtzgI6LNBvXeoxSHUUSB9S8ByDJw/hM4sRSHdR7J0Ki2HGYRgjlrQQik1gLoGbUSRxikfUCqRoiU/XeCLlBtTkHOnpEYlpaVfdgnl7uDCaaDX/JII5jt5Bs3pC46Fzz4BaSKmcAqL5AON5x8ioTin4YLY54r72kzzhB4tj3LvLVkafWx73AqOuB4puiGy4s0wTVCEioexRDEQsE2Qv2XBsHuG84WKXCAb/9YO/1NFItZj28wSOmcHmUOwC7fGDiuIHVig8VxTXPQ4rAhl8XyFXRRtzCKY5CdzS+VtyPHlVBHz795iDF9xXIDZ789LuD+HDT2BfVSx38uThGpJEt4JZWJc7t9NBj5Z7VPD7Vt8Zbn6GorzIaqpKSEAlcO6kGUXWnpchkjBiYuD+JYleF777vhXyqSuonPInkjisLJZ9uPFbTkQYhchETTRuOFtjAB0+/qx2soLvnf5tukHZuyvFucC+vWeUVU6UDNP2qi3kYgBf8z1dqWK1m7wsFHKdCy6oD3exeuoQoJOL2Iq6BURis8/N4vV6syFtHFv3Vi1WuRcAQes/vQD5j3YYxcpO6yGii+rcZnd0mxo27lxHw77wN3sAqQohFsi50qxPCh1MT+hU6SPOVknhxJM3JgbhcS0NpwK3FWnWyJAluORhwgWJzucRztqQqK9fNhc5gqa/oWGbiJnQ4ueTmvH2+OGd31M8pnlPhkBP4CyGrMB+oB2GrqiMxn2w3pbiWETGO3ogDLp+qzBBqu2Nm+O3osBZXMs9Va3yeTzbsNiX0wGMOu6snL9VctCtEU4FLBuZu4uqjLWv4w9wQREPmwwqQy/O1Gmzdg3/1THbiEMaYtzZ+PzOHfUFdc/Ywp4q5wNHySSoQ27S85rUR1ytkYUOhv+t8LZX4Vx6GuSmICSEP4B3z+VDatLIT2/LJSI7rpScPKOp4MsrZbuLJaDMCZmR/g5Cq9HF0YGSVyolBfmd7udYZx5GXUi5y1dxY4Ly1uWunYH909NHmKpbckrfnW6RpeXCeoznPJ3R2kmo78ToouUm9eFhz3naNToeXTr/UvDjkOGXAqT0Orw/s6YBAkxw95ybhhs23Q9EZnQ/XVnk+nhHzm/0yCRacc973enS+ZcTtkRaVQ68hX6XE7Lh+CDqEUeRmuWW3GdVQykkxtha7spzZ155KifYpUyaUKy57jMhLVrnQ1KHB7r1+7LCNLLY3KmMRcYNxzszSPc6koy2kscArzqQz2Cr8tsOp29yON5zTZMRrNwbbJHV2YRxZQWtvnGYRvS1LImlSVxRz2jtzHVy7p86KtXbz6d7cbbeq123yfbgsxuOhzS3kiPV3HW4p7AUqheFBH8+N7pKwS4Nt9EYLfToC6bhUlBYsC3PTtIIdLLVE0iej6NASO+6wvRwFvb21iL0IduBKHKYNemkR/KR/SBVJN7uRKIYzZ3qAZ11KD0wuCZzK8WEh5uOSM/EJjVcbcXjiNrxtx7wtDnnVEAjOPkjT/MDz6mbM5WIuqIfJNDxKTmbM0QnNeJUTbFvkuUFMjSdXKYqDzuQyEDdH0ZD6+4KYxoNmPJFUwQ+mfmeabRvhGMjTZMVZx1OjIbCtaI+uvyIV6HHc2kqmLoYWtZ2p59E817si0aLHK2tyMIdg4ZmD8XLe74/W6oqf7C+NFeOtVHXS7QvTydCGp/ZotjNGygkGy0Pbt+bKwpEJj8rKdk4LS08cpabKB+YSbNirl3SGXHK+LHluNh5M9P1qp2+1zXhWCMpRVVdO4emMD2mKiHfDS2c89+eF3blcGZbyD+tzq89HcYPvFEIrawibsRf0RmV/s6WXy4256DSOYLy2z6aHEBEGe1AVea/OC2EXMbP5xuJ6zTxTToIldhsh5HjzbE740a4End2xHZ4vZ6vpB83EHPR6Wut7ogps4lz4Otg93cJpHTrfR9UpKO6x8wyKL2OmOB8sD4u1KJCLpbRFyMipeHiNnsPZmt+/908eRYTViYu+nMvzMadKyCYjFNkYi7cHnG1zhMzlo8HgMlpJOiuo0gRZSD5GVnOQjhK32wg8Jw54nqezQjF36cLgr26USZIFS/nIS5JIUEqfWp5WHsunCgpDm+LStujOzoNmd5YmGqtuGg7ldNYX2ptfTUFrLzIxQFGzUIJJtjFMopxolsWNueZyal0V6GsnUeYPF9GjuHmv4zPjcmZldGebKONd76p4uR+VM6o9bfsLwM4sjogo2GpZS+rsH4ueHgvLhJ23msU5VUK9oQ7npyCXJuODWwy38mkZT1g+MQRv3SyGWZyc9QaRnXMdUCORPR0jj8+0Y3YME5ZqHGfNhL5OgowO+gNtPp0Kbuyf8tZJoXe7lrybLigwP1MrAkrSmdbnRQQGwuKsTOcydCWJWUpDQVaNjZUs5DTeUf3DZXExhkudby6X1h5SC9mKmNaxTzTGqcRPM8Ea94+HfMRk0fzi7w6Dq6GyDd88zvh43BLCSxnT/SjRBxN3uNlfr80pf0l1yd4Q196q2Ts32UA8cydFnirZ6bC+SjFsZTkU0yJra95A5yxQduWFDJ3tEJxUVepKWcAmzLIgsrg9P/nZhIr9QNCHceb1BnmK6lVvyJdeJ6CV0yI6tlZqOFPlMGPlBgpZUnQyd9Gp41ATwuFjqXmCIionZsd40j9dLrPOkV+vm/7wPKT7lntEGbeTn7tuQ2lAc5AELmtHSmzs3e51XRLORRo2rX6nt4JzeMmmg8ycXnbxOBfpslClGW/13KG8XXYm3Y4AVrRt0U1rEWl9zdbCdE4Tg95a7q0nWqrwF2/ZUS7BfMLYfbEVHttaq4SgOB81/2g76nyaRc7ppBhu2N+2nPGe0oK+Q4THaVmA4yWA07LFXmR3Npv1JoIRjY584S67izydRTttu/BgHDYaOULYWFipFe8yxQbmnBjEsBTPKa11rVNBrRzvokzoWYvRZ8uQ4mEXsmOxaXcHjlleZ91ktQ0LI4OMdwmcNruLDwS3Wortoxo3tIXSPbXnxWiyHGpRVgrzw1ZqTW1VChvH5cYyGFbulhkb787hfKHNrIa2Pu03hN/oJrTqzPsLeNHX/bUfiJ2ZtS+LA81AuatwI2eaaezM7/KLYmAxaQsUlNPPaZm17FnBEKzq+PLK161yZF+MGeuZCl2uB8w5KNx4Lfr7BWWsTrR9kfaJkZ4v8bwrhJ4tWsfpGY6yLtFIFFbpM8llLtly5M3FSaDQM2ubOLvB3NDK/WEkL8U8Duh9t1Dh7LI2j01j7dDtaztWdjKRuslIPW8O0iJcGZbNR+2O1KemqmS6p+UiorzpmJLGorYJsx7vtte9Vgjba3O7sXfX8WkDCGQXzmjrJpbllbARnBW9MZFni+6pm5eTDuwuuktWPc6grLR8FD7D5mmu2OnMzi/ucBn3Q6IYQcE3+yLNqiKrxOtekOUOay3GHf7iFx3Dn2iDRGUWOUhmgaWC0WjtL7giOsaGrCeOQTiHMlyO7euheSjzNdQ2ppV12Ua/M0WVYpH2Z9yCWVnytGMwYa97cTvBhi5Z7pyPGYWeblYEJzbjQvB1SeyyXMGBsJHBTIwXXtjcjhpKMg+YyO8tJz0VJatWugfj3IZHUMoLfbLTJRo5U4ebntunS6ik+pze5AK8UMiGdY/Je3ZnxOn7URLMxNlov6LZi7VJJzstRxmdMWBri+4L6AhjwVVa1qCzNaVO3KVTVhzGjNPu+7Trt6c7V1mVo/0+Vhm1K+mjyaFRuPkG1ezFsn1miWGkgnGRBIneQ1XUQDdPBpds2l7eux4WXnDt6PRmkk5pylxZxmE5nUKH1VZF7hU9PleikFBWXEJlUbGLY/9yYfvt9q5pb0VtJ3NbeADFIroOqCEIhLHYeEu5v5Mrn77lUo8ubPj+/+2X+hVIYNWrrFqgdYPwfnN7ncZ3ONyHwBd3LtNcD3+H8bZctYBf0D3Xxfco7yMJ4jiMP5K5FuOm58cK9uOtu/rBq1l8/qLnihEn9fP9BcxrawTgDoKb4T4wCO6U7dfXbvhCB0O/egUWoQspfgmGuzzhfTfuHtVI8Asb3Kv44envTz89318JVo2gEF0D43fbcDPoCTcrnj4iZE+3Hg9uzuP7qWuAp+c3UV7BXmrUj3fzf8Z4fP/z+P7n8f3vX3e8fVr5b/v+l2nR9Nff/9KP73/+jPFoyz7aso+27KMt+5dvyz7q/0f9/6j/H/X/X7L+P4PiD6TxD+p/ts189f0/1X58//9n1/+PV4yPV4yPV4yPV4yPV4yPV4yPV4z/8ivGR035GI/xGI/xGI/xGI/xGP97x38D5aWbWwBQAAA=

Outputs:

  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: AkamaiConnectorInstance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - AkamaiConnectorInstance
      - AvailabilityZone
