AWSTemplateFormatVersion: 2010-09-09
Description: Provisions subscriptions to alerts

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName
          - Name
    ParameterLabels:
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      Name:
        default: Resource Name
      SNSStackName:
        default: SNS Topic Stack Name


Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name)
    Type: String
    MinLength: 3
    MaxLength: 9
    Default: snssubs
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: pchc
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  SNSStackName:
    Description: the name of the SNS stack.
    Type: String
    Default: pchc-prd-ase1-sns
    MinLength: 1

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Email Subcriptions
####

  NicoSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: nicopaulomendoza@pchc.com.ph
      Protocol: email
      TopicArn: 
        Fn::ImportValue:
          !Sub "${SNSStackName}-TopicArn"
  
  IannisSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: iannis@iscale-solutions.com
      Protocol: email
      TopicArn: 
        Fn::ImportValue:
          !Sub "${SNSStackName}-TopicArn"

  LeySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: leyjulian@pchc.com.ph
      Protocol: email
      TopicArn: 
        Fn::ImportValue:
          !Sub "${SNSStackName}-TopicArn"

  NoelSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: noelquitlong@pchc.com.ph
      Protocol: email
      TopicArn: 
        Fn::ImportValue:
          !Sub "${SNSStackName}-TopicArn"

  IannisSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: iannis@iscale-solutions.com
      Protocol: email
      TopicArn: 
        Fn::ImportValue:
          !Sub "${SNSStackName}-TopicArn"

  MaxiSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: maxitorrecampo@pchc.com.ph
      Protocol: email
      TopicArn: 
        Fn::ImportValue:
          !Sub "${SNSStackName}-TopicArn"

  JohnSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: johndaleregalado@pchc.com.ph
      Protocol: email
      TopicArn: 
        Fn::ImportValue:
          !Sub "${SNSStackName}-TopicArn"

  RenieSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: reniesugano@pchc.com.ph
      Protocol: email
      TopicArn: 
        Fn::ImportValue:
          !Sub "${SNSStackName}-TopicArn"