AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for iScale Solutions

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-hosting
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    Default: iscale-solutions.com
  LoadBalancerStackName:
    Description: The name of the load balancer stack.
    Type: String
    Default: HostingProductionELB

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml


Resources:

####
# Route53 Section
####

  HostedZone:
    DeletionPolicy: Retain
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref ClientDomainName]]
      Name: !Ref ClientDomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], iscale-solutions]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  GithubVerifiationTXTRecord:
    DeletionPolicy: Retain
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', [_github-challenge-iScale-Solutions, !Ref ClientDomainName]]
      ResourceRecords:
        - '3f5d14251b'
      TTL: 3600
      Comment: Github domain verification record
      Type: TXT
  
  # WWWRecord:
  #   Type: AWS::Route53::RecordSetGroup
  #   Properties:
  #     HostedZoneId : !Ref HostedZone
  #     Comment: WWW Record
  #     RecordSets:
  #       - Name: !Join ['.',[www, !Ref ClientDomainName]]
  #         Type: A
  #         AliasTarget:
  #           HostedZoneId:
  #             Fn::ImportValue:
  #               !Sub "${LoadBalancerStackName}-PublicELBCanonicalHostedZoneID" 
  #           DNSName:
  #             Fn::ImportValue:
  #               !Sub "${LoadBalancerStackName}-PublicELBDNS"
        

  # NoWWWRecord:
  #   Type: AWS::Route53::RecordSetGroup
  #   Properties:
  #     HostedZoneId : !Ref HostedZone
  #     Comment: No WWW Record
  #     RecordSets:
  #       - Name: !Ref ClientDomainName
  #         Type: A
  #         AliasTarget:
  #           HostedZoneId:
  #             Fn::ImportValue:
  #               !Sub "${LoadBalancerStackName}-PublicELBCanonicalHostedZoneID" 
  #           DNSName:
  #             Fn::ImportValue:
  #               !Sub "${LoadBalancerStackName}-PublicELBDNS"