AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for iScale Ventures

Parameters:
  OrgName:
    Description: The name of the organization
    Type: String
    Default: iscale-ventures
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
  ClientDomainName:
    Description: Client domain name (e.g iscale-ventures.com)
    Type: String
    Default: iscale-ventures.com

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone: 
    Type: AWS::Route53::HostedZone
    Properties: 
      HostedZoneConfig: 
        Comment: !Join [' ',[Hosted Zone for, !Ref ClientDomainName]]
      Name: !Ref ClientDomainName
      HostedZoneTags: 
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], iscale-solutions]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  WildcardSSLValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_22de51a656786d09160256b9e82951a1, !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _0eb71c23715404de498b564095fb454b.hkmpvcwbzw.acm-validations.aws.

  DKIMValidationRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[busdlhsn46wmhxhfyzhrda4n3tyqldhr, _domainkey, !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - busdlhsn46wmhxhfyzhrda4n3tyqldhr.dkim.amazonses.com

  DKIMValidationRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[vakrajk3dk4v3mm7jy73imk6q2ldfeco, _domainkey, !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - vakrajk3dk4v3mm7jy73imk6q2ldfeco.dkim.amazonses.com

  DKIMValidationRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[e5fkex6z7un5cq2wbsz3hwk2h6ooa46h, _domainkey, !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - e5fkex6z7un5cq2wbsz3hwk2h6ooa46h.dkim.amazonses.com

  VolendraZionCertValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_215c975a7fe84d9bf22e42ceec3263a9, zion, !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _7df0086e48576f65fa40501df31a649e.sxgfwvgjsz.acm-validations.aws.

  HostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref HostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

  HostedZoneDNSSEC:
    DependsOn: HostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref HostedZone