AWSTemplateFormatVersion: 2010-09-09
Description: Domain redirects to iscale-solutions.com This MUST be run in us-east-1 for SSL

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      DomainName:
        default: Domain Name

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 9
    Default: redirects
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The domain name to be redirected to
    Type: String
    Default: iscale-solutions.com

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
      
Resources:

  ## iscalesolutions.com ##
  iScaleSolutionsDotComHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: iscalesolutions.com
      HostedZoneConfig:
        Comment: !Join [' ', ['Redirects to', !Ref DomainName]]

  iScaleSolutionsDotComSSLCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: iscalesolutions.com
      SubjectAlternativeNames:
        - www.iscalesolutions.com
      ValidationMethod: DNS

  iScaleSolutionsDotComSSLValidationRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iScaleSolutionsDotComHostedZone
      Name: _9c0ce09ee688c0d752b0a0dcf9c44f69.iscalesolutions.com
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _e9f5e17c6596bf1bca68e7b6b3ba818d.xlfgrmvvlj.acm-validations.aws.

  iScaleSolutionsDotComSSLValidationRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iScaleSolutionsDotComHostedZone
      Name: _3ecdac889ae275471d0cea94317e7255.www.iscalesolutions.com
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _9b883af662437dda1a3c1353456dcb0a.xlfgrmvvlj.acm-validations.aws.

  iScaleSolutionsDotComHostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref iScaleSolutionsDotComHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:383761724374:key/cdcd5739-9c6f-41e1-b8f6-010e2ab3182d
      Name: key_signing_key
      Status: ACTIVE

  iScaleSolutionsDotComHostedZoneDNSSEC:
    DependsOn: iScaleSolutionsDotComHostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref iScaleSolutionsDotComHostedZone

  ISSSDC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/domain-redirect-s3.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        DomainSSLCert: !Ref iScaleSolutionsDotComSSLCert
        SourceDomainName: iscalesolutions.com
        RedirectDomainName: !Ref DomainName


  ## iscalesolution.com ##
  iScaleSolutionDotComHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: iscalesolution.com
      HostedZoneConfig:
        Comment: !Join [' ', ['Redirects to', !Ref DomainName]]

  iScaleSolutionDotComSSLCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: iscalesolution.com
      SubjectAlternativeNames:
        - www.iscalesolution.com
      ValidationMethod: DNS

  iScaleSolutionDotComSSLValidationRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iScaleSolutionDotComHostedZone
      Name: _72006c347e3c41ebe2f3313b69bcf361.iscalesolution.com
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _ca1d305f1a99f47f2a7edb6a4f785ad2.xlfgrmvvlj.acm-validations.aws.

  iScaleSolutionDotComSSLValidationRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iScaleSolutionDotComHostedZone
      Name: _a0b0c0c46dfdd682b1738320676bc4e5.www.iscalesolution.com
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _ee75a3467120863930bbdb7e2d017dd6.xlfgrmvvlj.acm-validations.aws.

  iScaleSolutionDotComHostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref iScaleSolutionDotComHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:383761724374:key/cdcd5739-9c6f-41e1-b8f6-010e2ab3182d
      Name: key_signing_key
      Status: ACTIVE

  iScaleSolutionDotComHostedZoneDNSSEC:
    DependsOn: iScaleSolutionDotComHostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref iScaleSolutionDotComHostedZone

  ISSDC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/domain-redirect-s3.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        DomainSSLCert: !Ref iScaleSolutionDotComSSLCert
        SourceDomainName: iscalesolution.com
        RedirectDomainName: !Ref DomainName

  ## iscale-solution.com ##
  iScaleDashSolutionDotComHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: iscale-solution.com
      HostedZoneConfig:
        Comment: !Join [' ', ['Redirects to', !Ref DomainName]]

  iScaleDashSolutionDotComSSLCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: iscale-solution.com
      SubjectAlternativeNames:
        - www.iscale-solution.com
      ValidationMethod: DNS

  iScaleDashSolutionDotComHostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref iScaleDashSolutionDotComHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:383761724374:key/cdcd5739-9c6f-41e1-b8f6-010e2ab3182d
      Name: key_signing_key
      Status: ACTIVE

  iScaleDashSolutionDotComHostedZoneDNSSEC:
    DependsOn: iScaleDashSolutionDotComHostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref iScaleDashSolutionDotComHostedZone

  iScaleDashSolutionDotComSSLValidationRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iScaleDashSolutionDotComHostedZone
      Name: _ef246dabbff13a84671a6cc524720029.iscale-solution.com
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _7e91760612e624e9d7cee8f655378597.xlfgrmvvlj.acm-validations.aws.

  iScaleDashSolutionDotComSSLValidationRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iScaleDashSolutionDotComHostedZone
      Name: _40852b7ac82ae525a3857973d5591f48.www.iscale-solution.com.
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _52dc653dfea487a2a793315f57ac10c5.xlfgrmvvlj.acm-validations.aws.

  ISDSDC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/domain-redirect-s3.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        DomainSSLCert: !Ref iScaleDashSolutionDotComSSLCert
        SourceDomainName: iscale-solution.com
        RedirectDomainName: !Ref DomainName

  ## i-scale-solution.com ##
  iDashScaleDashSolutionDotComHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: i-scale-solution.com
      HostedZoneConfig:
        Comment: !Join [' ', ['Redirects to', !Ref DomainName]]

  iDashScaleDashSolutionDotComHostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref iDashScaleDashSolutionDotComHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:383761724374:key/cdcd5739-9c6f-41e1-b8f6-010e2ab3182d
      Name: key_signing_key
      Status: ACTIVE

  iDashScaleDashSolutionDotComHostedZoneDNSSEC:
    DependsOn: iDashScaleDashSolutionDotComHostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref iDashScaleDashSolutionDotComHostedZone

  iDashScaleDashSolutionDotComSSLCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: i-scale-solution.com
      SubjectAlternativeNames:
        - www.i-scale-solution.com
      ValidationMethod: DNS

  iDashScaleDashSolutionDotComSSLValidationRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iDashScaleDashSolutionDotComHostedZone
      Name: _bcc9c5b93503a240d38b4c050cfd97f6.i-scale-solution.com
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _00c23bcae5546096ab6555ac6bfbda61.xlfgrmvvlj.acm-validations.aws.

  iDashScaleDashSolutionDotComSSLValidationRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iDashScaleDashSolutionDotComHostedZone
      Name: _8471b8fee922b8ca1e9f08f15c76280f.www.i-scale-solution.com.
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _7a3f96e9d2bf237dc7eb47c1f6870792.xlfgrmvvlj.acm-validations.aws.

  IDSDSDC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/domain-redirect-s3.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        DomainSSLCert: !Ref iDashScaleDashSolutionDotComSSLCert
        SourceDomainName: i-scale-solution.com
        RedirectDomainName: !Ref DomainName

## i-scale-solutions.com ##
  iDashScaleDashSolutionsDotComHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: i-scale-solutions.com
      HostedZoneConfig:
        Comment: !Join [' ', ['Redirects to', !Ref DomainName]]

  iDashScaleDashSolutionsDotComHostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref iDashScaleDashSolutionsDotComHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:383761724374:key/cdcd5739-9c6f-41e1-b8f6-010e2ab3182d
      Name: key_signing_key
      Status: ACTIVE

  iDashScaleDashSolutionsDotComHostedZoneDNSSEC:
    DependsOn: iDashScaleDashSolutionsDotComHostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref iDashScaleDashSolutionsDotComHostedZone

  iDashScaleDashSolutionsDotComSSLCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: i-scale-solutions.com
      SubjectAlternativeNames:
        - www.i-scale-solutions.com
      ValidationMethod: DNS

  iDashScaleDashSolutionsDotComSSLValidationRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iDashScaleDashSolutionsDotComHostedZone
      Name: _9dac77235c3f01e169a4114250b12ec1.i-scale-solutions.com
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _8ac5ed5a992c0ae38c875ee104c6f28b.xlfgrmvvlj.acm-validations.aws.

  iDashScaleDashSolutionsDotComSSLValidationRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iDashScaleDashSolutionsDotComHostedZone
      Name: _2f37426c5258830c0a45b6cb6f63597e.www.i-scale-solutions.com
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _db61cda67a54aace6a9dcac815b3aa09.xlfgrmvvlj.acm-validations.aws.

  IDSDSSDC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/domain-redirect-s3.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        DomainSSLCert: !Ref iDashScaleDashSolutionsDotComSSLCert
        SourceDomainName: i-scale-solutions.com
        RedirectDomainName: !Ref DomainName

## i-scalesolutions.com ##

  iDashScaleSolutionsDotComHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: i-scalesolutions.com
      HostedZoneConfig:
        Comment: !Join [' ', ['Redirects to', !Ref DomainName]]

  iDashScaleSolutionsDotComHostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref iDashScaleSolutionsDotComHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:383761724374:key/cdcd5739-9c6f-41e1-b8f6-010e2ab3182d
      Name: key_signing_key
      Status: ACTIVE

  iDashScaleSolutionsDotComHostedZoneDNSSEC:
    DependsOn: iDashScaleSolutionsDotComHostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref iDashScaleSolutionsDotComHostedZone

  iDashScaleSolutionsDotComSSLCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: i-scalesolutions.com
      SubjectAlternativeNames:
        - www.i-scalesolutions.com
      ValidationMethod: DNS

  iDashScaleSolutionsDotComSSLValidationRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iDashScaleSolutionsDotComHostedZone
      Name: _2c1f3000f29529802b819680f7e92b53.i-scalesolutions.com
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _389230c89432c0eb7b476aad516b6f98.xlfgrmvvlj.acm-validations.aws.

  iDashScaleSolutionsDotComSSLValidationRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iDashScaleSolutionsDotComHostedZone
      Name: _73c8156a502fea1e9f717587ee78db70.www.i-scalesolutions.com
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _1edcabd82accb61974907d0e8dec5a26.xlfgrmvvlj.acm-validations.aws.

  IDSSSDC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/domain-redirect-s3.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        DomainSSLCert: !Ref iDashScaleSolutionsDotComSSLCert
        SourceDomainName: i-scalesolutions.com
        RedirectDomainName: !Ref DomainName

## i-scalesolution.com ##

  iDashScaleSolutionDotComHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: i-scalesolution.com
      HostedZoneConfig:
        Comment: !Join [' ', ['Redirects to', !Ref DomainName]]

  iDashScaleSolutionDotComHostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref iDashScaleSolutionDotComHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:383761724374:key/cdcd5739-9c6f-41e1-b8f6-010e2ab3182d
      Name: key_signing_key
      Status: ACTIVE

  iDashScaleSolutionDotComHostedZoneDNSSEC:
    DependsOn: iDashScaleSolutionDotComHostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref iDashScaleSolutionDotComHostedZone

  iDashScaleSolutionDotComSSLCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: i-scalesolution.com
      SubjectAlternativeNames:
        - www.i-scalesolution.com
      ValidationMethod: DNS

  iDashScaleSolutionDotComSSLValidationRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iDashScaleSolutionDotComHostedZone
      Name: _f199a282347a2ed05f8aebb653a60f09.i-scalesolution.com.
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _2908eb348d391b47bb2e5861e4ef0a92.xlfgrmvvlj.acm-validations.aws.

  iDashScaleSolutionDotComSSLValidationRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref iDashScaleSolutionDotComHostedZone
      Name: _a9304f9f739546b6ee230edda3b22cdc.www.i-scalesolution.com.
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _76c27fb86856f9a66358c42b96b38e4f.xlfgrmvvlj.acm-validations.aws.

  IDSSDC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/domain-redirect-s3.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        DomainSSLCert: !Ref iDashScaleSolutionDotComSSLCert
        SourceDomainName: i-scalesolution.com
        RedirectDomainName: !Ref DomainName

## iscale-solutions.eu ##

  iScaleDashSolutionsDotEUSSLCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: iscale-solutions.eu
      SubjectAlternativeNames:
        - www.iscale-solutions.eu
      ValidationMethod: DNS

  iScaleDashSolutionsDotEUSSLValidationRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: iscale-solutions.eu.
      Name: _c39299dcdd37554746bd9c9ab4cce9aa.iscale-solutions.eu
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _ceb342f3830f9e8c818fd084f1ce5c79.xlfgrmvvlj.acm-validations.aws.

  iScaleDashSolutionsDotEUSSLValidationRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: iscale-solutions.eu.
      Name: _49e4f9f3073da03c370c9ffece7628f0.www.iscale-solutions.eu
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _21ab6a2b0770c67c93657bd794ebb5af.xlfgrmvvlj.acm-validations.aws.

  ISDSSEU:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/domain-redirect-s3.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        DomainSSLCert: !Ref iScaleDashSolutionsDotEUSSLCert
        SourceDomainName: iscale-solutions.eu
        RedirectDomainName: !Ref DomainName

## iscale-solutions.us ##

  iScaleDashSolutionsDotUSSSLCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: iscale-solutions.us
      SubjectAlternativeNames:
        - www.iscale-solutions.us
      ValidationMethod: DNS

  iScaleDashSolutionsDotUSSSLValidationRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: iscale-solutions.us.
      Name: _32cd9d12f6519b884658d181e229e113.iscale-solutions.us
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _7e847877b796df754dac396062754d40.xlfgrmvvlj.acm-validations.aws.

  iScaleDashSolutionsDotUSSSLValidationRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: iscale-solutions.us.
      Name: _e8f9236c61645e56197c7dd08bce143b.www.iscale-solutions.us
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _3a1900ebfa1c4862f0321139c05110ff.xlfgrmvvlj.acm-validations.aws.

  ISDSSUS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/domain-redirect-s3.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        DomainSSLCert: !Ref iScaleDashSolutionsDotUSSSLCert
        SourceDomainName: iscale-solutions.us
        RedirectDomainName: !Ref DomainName
