AWSTemplateFormatVersion: 2010-09-09
Description: Backup infrastructure for iScale

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Backup Resources
####

  BackupS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: iscale-solutions-backup
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteFiles
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 3
            Status: Enabled
          - Id: StorageClasses
            ExpirationInDays: 3650
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
              - StorageClass: GLACIER
                TransitionInDays: 90
              - StorageClass: DEEP_ARCHIVE
                TransitionInDays: 180
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags: 
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], data, backup]]
        - Key: Organization
          Value: !Ref OrgName
  
  DataBackupGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: DataBackup
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: ViewS3Bucket
                Effect: Allow
                Action: 
                  - s3:GetBucketLocation
                  - s3:ListAllMyBuckets
                Resource: !GetAtt BackupS3Bucket.Arn
              - Sid: SaveInS3BucketGSuiteFolder
                Effect: Allow
                Action:
                  - s3:GetObject*
                  - s3:ListBucket
                  - s3:PutObject*
                Resource:
                  - !GetAtt BackupS3Bucket.Arn
                  - !Join ['/', [!GetAtt BackupS3Bucket.Arn, 'Google_Workspace_Backup' , '*']]

  DataBackupUser:
    Type: AWS::IAM::User
    Properties:
      UserName: data_backup_user
      Groups:
      - !Ref DataBackupGroup
      Tags:
        - Key: Name
          Value: Data backup user
        - Key: Email
          Value: Databackup@externisy.fr

  DataBackupUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: DataBackupUser

Outputs:

  DataBackupUserAccessKeyId:
    Description: Access Key Id for the Data backup user
    Value: !Ref DataBackupUserAccessKey
  
  # DataBackupUserAccessKeySecret:
  #   Description: Secret Key for the Data backup user
  #   Value: !GetAtt [DataBackupUserAccessKey, SecretAccessKey]
