AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for iScale Solutions USA

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-solutions-us
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The client's domain name (e.g. iscale-solutions.us).
    Type: String
    Default: iscale-solutions.us
  DNSSECKey:
    Description: Enter the KMS key (from us-east-1) for DNSSSec (optional)
    Type: String
    Default: arn:aws:kms:us-east-1:383761724374:key/cdcd5739-9c6f-41e1-b8f6-010e2ab3182d

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  HasDNSSEC: !Not [!Equals [!Ref DNSSECKey, ""]]

Resources:

####
# Route53 Section
####

  HostedZone: 
    Type: AWS::Route53::HostedZone
    Properties: 
      HostedZoneConfig: 
        Comment: !Join [' ',[Hosted Zone for, !Ref DomainName]]
      Name: !Ref DomainName
      HostedZoneTags: 
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], iscale-solutions]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  DMARCRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: DMARC record
      Name: !Join ['.', [_dmarc, !Ref DomainName]]
      Type: TXT
      TTL: 14400
      ResourceRecords:
        - !Join ['', ["\"v=DMARC1;fo=1;p=reject;rua=mailto:dmarc@", !Ref DomainName, "\""]]

  GoogleTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Join ['.', ['@', !Ref DomainName]]
      Comment: Google TXT Record
      ResourceRecords:
        - "\"google-site-verification=lh4jj03NfRsou8gCuah3Jpt-WKLgBmxPK3X61SbUyug\""
      TTL: 60
      Type: TXT

  GmailDKIMRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[google._domainkey, !Ref DomainName]]
      ResourceRecords:
        - '"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCBuapwZM/cdP8kuSEl4WiG8noGWO7M3maEsiy9BYOoigz4E7OpEiTi/fITvE5EL12OeK/jaI+CukpKzDB9BVioF+lMSk1f9k1c8w+UeJ53SbL3Uu+DlusXQCNjAR+x20qnT347BNEPagHqiaVPFqBs4m8Yn7bBOPqvA4iNtBldaQIDAQAB"'
      TTL: 14400
      Type: TXT
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], gmail, dkim]]

  GoogleWorkspaceMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: Google Workspace MX Records
      Name: !Ref DomainName
      Type: MX
      TTL: 14400
      ResourceRecords:
        - 1 ASPMX.L.GOOGLE.COM
        - 5 ALT1.ASPMX.L.GOOGLE.COM.
        - 5 ALT2.ASPMX.L.GOOGLE.COM.
        - 10 ALT3.ASPMX.L.GOOGLE.COM.
        - 10 ALT4.ASPMX.L.GOOGLE.COM.
        - 15 MCFA4H4D5ZTEVZBY6DQPY5VYD7UWELLLPLTYCT2BL4ZVR2PJZESQ.MX-VERIFICATION.GOOGLE.COM

  ###
  # DNSSEC
  ###

  HostedZoneDNSSECSigningKey:
    Condition: HasDNSSEC
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref HostedZone
      KeyManagementServiceArn: !Ref DNSSECKey
      Name: key_signing_key
      Status: ACTIVE

  HostedZoneDNSSEC:
    Condition: HasDNSSEC
    DependsOn: HostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref HostedZone