AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for iScale Solutions

Parameters:
  OrgName:
    Description: The name of the organization
    Type: String
    Default: iscale
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The domain name (e.g. example.com).
    Type: String
    Default: iscale-solutions.com

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref DomainName]]
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], iscale-solutions]]
        - Key: Organization
          Value: !Ref OrgName

  ACMDomainValidation:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_e8fd6bf0a6e3de90baa0cb05b14d09e3, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _1752b437c96bbcafecc8e1377b6df57f.tljzshvwok.acm-validations.aws.

  ACMWWWValidation:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_d593c9ed7637aeb2cf52773f50057bc1.www, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _7375764e049b75c0feed4415deee8e20.tfmgdnztqk.acm-validations.aws

  BingValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[2fabea40f72d006741d28f19fd4a88de, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - verify.bing.com

  DMARCRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: DMARC record
      Name: !Join ['.', [_dmarc, !Ref DomainName]]
      Type: TXT
      TTL: 14400
      ResourceRecords:
        - !Join ['', ["\"v=DMARC1;p=none;rua=mailto:info@", !Ref DomainName, "\""]]

  DomainKeyValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', [1522905413783._domainkey, !Ref DomainName]]
      ResourceRecords:
        - '"k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCr6KMgdxxgg7oT3ulMwPJs9RXgXDrI9UWU118pHEMohl3UbL3Jwp4oxp/9N3thh/3WCJnYV134zbEVolZwqaT3JsFEq/mQ/RpW/JnOZ3rnxqJPurb2bcfJol4SDxiWVObzHX31xnANzFcXnq1/5dMK5QvW4Jh7n0fm4+4ywqiy2QIDAQAB"'
      TTL: 14400
      Comment: Domain Key validation record
      Type: TXT

  FreshDeskDomainKey1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[m1._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - acc687828.domainkey.freshdesk.com

  FreshDeskDomainKey2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[s1._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - s1acc687828.domainkey.freshdesk.com

  FreshDeskDomainKey3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[s2._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - s2acc687828.domainkey.freshdesk.com

  FreshDeskSPFRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[fddkim, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - spfmx.domainkey.freshdesk.com

  GithubVerificationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', [_github-challenge-iScale-Solutions, !Ref DomainName]]
      ResourceRecords:
        - '"3f5d14251b"'
      TTL: 14400
      Comment: Github domain verification record
      Type: TXT

  GoogleCalendarRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[calendar, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - ghs.googlehosted.com

  GoogleDriveRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[drive, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - ghs.googlehosted.com

  GoogleWebmailRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[webmail, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - ghs.googlehosted.com

  SESDKIMSGRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[33amredmcqwq5vwcvq26d6r5qd3j35hg._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - 33amredmcqwq5vwcvq26d6r5qd3j35hg.dkim.amazonses.com

  SESDKIMSGRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[c2wrtgzvr7c5mrhk7avxsg33ssipclhe._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - c2wrtgzvr7c5mrhk7avxsg33ssipclhe.dkim.amazonses.com

  SESDKIMSGRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[cmfktrkkceflopifvgd4syqlyppkzif7._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - cmfktrkkceflopifvgd4syqlyppkzif7.dkim.amazonses.com

  SESDKIMSGRecord4:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[iy4k5p72k3dzy476x6w4j7pg5xfamytf._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - iy4k5p72k3dzy476x6w4j7pg5xfamytf.dkim.amazonses.com

  SESDKIMSGRecord5:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[jopymnlwqjgn7xjqg2lrlxpqissgvtu4._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - jopymnlwqjgn7xjqg2lrlxpqissgvtu4.dkim.amazonses.com

  SESDKIMSGRecord6:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[q3uuckjdsu3r7sgsvwf62de2cvc6oyco._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - q3uuckjdsu3r7sgsvwf62de2cvc6oyco.dkim.amazonses.com

  SESValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', [_amazonses, !Ref DomainName]]
      ResourceRecords:
        - '"/Xi8Dvi1dK5SjyYdYYkRjhcMxA9MLFsBidtC9QWnRBA="'
        - '"Ov5SNoHVvgQPUyI3ryusA+jNqy3C1F8RG813oNJ2WKY="'
        - '"vhdlmXVMK77TgBSD4l2OMDgpJRuLh8qb/9lGaamd2MQ="'
      TTL: 14400
      Comment: Amazon SES validation record
      Type: TXT

  SupportRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: Support Record
      RecordSets:
        - Name: !Join ['.', [support, !Ref DomainName]]
          Type: A
          AliasTarget:
            HostedZoneId: Z3O0J2DXBE1FTB #hardcoded based on AWS static website setup
            DNSName: s3-website-ap-southeast-1.amazonaws.com.

  TXTDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      ResourceRecords:
        - '"MS=BB7A2F49A0BAD37655DF6C67793E9E9F7E752182"'
        - '"Security code=i4sc-gkkc-08f1"'
        - '"google-site-verification=HAPj8MVIPnC5bFAp-9NCSM4H192KTwL9TSZwK-GAhCk"'
        - '"v=spf1 include:transmail.net ~all"'
      TTL: 14400
      Comment: Domain TXT verification record
      Type: TXT
  
  ZohoHRRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[hr, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - people.cs.zohohost.com

  ZohoRecruitRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[recruit, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - customer-recruit.zoho.com