AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for ccifrance-philippines.org

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: cciph
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    Default: ccifrance-philippines.org

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone: 
    Type: AWS::Route53::HostedZone
    Properties: 
      HostedZoneConfig: 
        Comment: !Join [' ',[Hosted Zone for, !Ref ClientDomainName]]
      Name: !Ref ClientDomainName
      HostedZoneTags: 
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], cci-philippines]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName
  
  # HostedZoneDNSSECSigningKey:
  #   Type: AWS::Route53::KeySigningKey
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
  #     Name: key_signing_key
  #     Status: ACTIVE

  # HostedZoneDNSSEC:
  #   DependsOn: HostedZoneDNSSECSigningKey
  #   Type: AWS::Route53::DNSSEC
  #   Properties:
  #     HostedZoneId: !Ref HostedZone

  EventsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[events, !Ref ClientDomainName]]
      ResourceRecords:
       - 94.23.218.225
      Type: A
      TTL: 14400
      Comment: Events

  AgendaRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[agenda, !Ref ClientDomainName]]
      ResourceRecords: 
        - ghs.google.com
      TTL: 14400
      Type: CNAME
      Comment: Agenda

  BlogRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[blog, !Ref ClientDomainName]]
      ResourceRecords: 
        - ghs.google.com
      TTL: 14400
      Type: CNAME
      Comment: Google Blog

  GoogleDocsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[docs, !Ref ClientDomainName]]
      ResourceRecords: 
        - ghs.google.com
      TTL: 14400
      Type: CNAME
      Comment: Google Docs
  
  GlueUpDKIMRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[gumail10232,_domainkey, !Ref ClientDomainName]]
      ResourceRecords: 
        - gumail10232.ccifrance-philippines-aa9d4832258b48599.glueupmail.com
      TTL: 14400
      Type: CNAME
      Comment: GlueUp DKIM

  GlueUpDKIMRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[gumail1023,_domainkey, !Ref ClientDomainName]]
      ResourceRecords: 
        - gumail1023.ccifrance-philippines-aa9d4832258b48599.glueupmail.com
      TTL: 14400
      Type: CNAME
      Comment: GlueUp DKIM

  GlueUpDKIMRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[gumail1025, !Ref ClientDomainName]]
      ResourceRecords: 
        - ccifrance-philippines-aa9d4832258b48599.glueupmail.com
      TTL: 14400
      Type: CNAME
      Comment: GlueUp DKIM

  GoogleIMAPRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[imap, !Ref ClientDomainName]]
      ResourceRecords: 
        - ghs.google.com
      TTL: 14400
      Type: CNAME
      Comment: Google IMAP record

  GoogleMailRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[mail, !Ref ClientDomainName]]
      ResourceRecords: 
        - ghs.google.com
      TTL: 14400
      Type: CNAME
      Comment: Google Mail record

  GooglePopRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[pop, !Ref ClientDomainName]]
      ResourceRecords: 
        - ghs.google.com
      TTL: 14400
      Type: CNAME
      Comment: Google POP record

  GoogleSMTPRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[smtp, !Ref ClientDomainName]]
      ResourceRecords: 
        - ghs.google.com
      TTL: 14400
      Type: CNAME
      Comment: Google SMTP record

  WWWRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[www, !Ref ClientDomainName]]
      ResourceRecords:
      - 192.185.157.191
      TTL: 14400
      Type: A
      Comment: WWW record

  NoWWWRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref ClientDomainName
      ResourceRecords:
      - 192.185.157.191
      TTL: 14400
      Type: A
      Comment: Domain record

  FTPRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[ftp, !Ref ClientDomainName]]
      ResourceRecords: 
        - !Join ['.',[www, !Ref ClientDomainName]]
      TTL: 14400
      Type: CNAME
      Comment: FTP record

  CPanelRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[cpanel, !Ref ClientDomainName]]
      ResourceRecords: 
        - !Join ['.',[www, !Ref ClientDomainName]]
      TTL: 14400
      Type: CNAME
      Comment: FTP record

  GoogleMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref ClientDomainName
      ResourceRecords:
        - 1 ASPMX.L.GOOGLE.COM
        - 5 ALT1.ASPMX.L.GOOGLE.COM
        - 5 ALT2.ASPMX.L.GOOGLE.COM
        - 10 ALT3.ASPMX.L.GOOGLE.COM
        - 10 ALT4.ASPMX.L.GOOGLE.COM
      TTL: 14400
      Type: MX
      Comment: Google MX Records
  
  DomainTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref ClientDomainName
      ResourceRecords: 
        - '"v=spf1 include:_spf.google.com ~all"'
        - '"google-site-verification=iZtvkra8-737baq9Q_YyEfgo9DRHhQi7qbkSjY8kqRA"'
        - '"v=DMARC1; p=none; rua=jerome@ccifrance-philippines.org"'
      TTL: 14400
      Type: TXT
      Comment: Domain TXT Record

  GoogleDKIMRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[google, _domainkey, !Ref ClientDomainName]]
      ResourceRecords: 
        #- '"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApv67xCVY6oGY5Ok/5QquvBvwukXgd8uZOJBQX0JlqOOtKNQXUrzgIgO6+ 4kxmcIZZI7fAX23OwH6ctdVp5/QQW+8gV/+hPs7hyJd2LIscvRKRLtWE+Tj0KJ8H8UWecG2kGhNglJjOpc0KiTSeBE83VqDH75sGZpRw2uEBqvIji8jfIAN68o6YD+ 06hMIbPZ" "X9uJuax7i0ITVYx+56tKyEiW72aJGHqhXeUU9gpKN8FOj2U6xf0oMEfmYrZ8c33POLtp9Vc/oBKDbTaBK2ZG5VvTMyWnjIqFjPxhIwNe3giXPo4Cf9f1snYnu8DsAYM/N+7nOBdSq20y4pRXe9Yp61QIDAQAB"'
        #- '"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApv67xCVY6oGY5Ok/5QquvBvwukXgd8uZOJBQX0JlqOOtKNQXUrzgIgO6+4kxmcIZZI7fAX23OwH6ctdVp5/QQW+8gV/+hPs7hyJd2LIscvRKRLtWE+Tj0KJ8H8UWecG2kGhNglJjOpc0KiTSeBE83VqDH75sGZpRw2uEBqvIji8jfIAN68o6YD+06hMIbPZX9uJuax7i0ITVYx+56tKyEiW72aJGHqhXeUU9gpKN8FOj2U6xf0oMEfmYrZ8c33POLtp9Vc/oBKDbTaBK2ZG5VvTMyWnjIqFjPxhIwNe3giXPo4Cf9f1snYnu8DsAYM/N+7nOBdSq20y4pRXe9Yp61QIDAQAB"'
        - '"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCP+pr4WdpVG+SNyZAImiH2/gxK7EItvgfNPHGT6WsKnd2NU+VYPxvYJ40Ll+7/lkctgK3fkBsAkW4gPBq5d1pA+HjiWblQ7TChIEI5V4NWHsUSQq7RZCk0D3eadfx9Y4TeXkMNOeutiCmmYpWQ79ql3I9pfm6GPcqwP2JndkLf8QIDAQAB"'
      TTL: 14400
      Type: TXT
      Comment: Google DKIM record