AWSTemplateFormatVersion: 2010-09-09
Description: Odoo Image Builder

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName
      - Label:
          default: Sharing Configuration
        Parameters:
          - ShareImage

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      NetworkStackName:
        default: Network Stack Name
      ShareImage:
        default: Share image with other account? If sharing, encryption will be disabled.
      SNSStackName:
        default: SNS Topic Stack Name

Parameters:
  Name:
    Description: Unique name/identifier (e.g. odoo-linux).
    Type: String
    Default: odoo-linux
    AllowedPattern: "^[a-z0-9]+(-[a-z0-9]+)*$"
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: iscale-dev-dev-uw2-network
    MinLength: 1
  ShareImage:
    Description: Select true to not encrypt the image and share it with other accounts
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  SNSStackName:
    Description: the name of the SNS stack.
    Type: String
    Default: iscale-dev-dev-uw2-sns
    MinLength: 1

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml      
  IsImageShared: !Equals [!Ref ShareImage, true]

Resources:

  PIP3Component:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: PIP3
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2
      Version: 1.0.0
      Description: Installs PIP3
      ChangeDescription: Initial version
      Data: |
        name: PIP3 - InlineData
        description: Installation of PIP3
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallPIP3
                action: ExecuteBash
                inputs:
                  commands:
                    - python3 -m pip install -U pip
                    - ln -s /usr/local/bin/pip3 /usr/bin/
###
# Odoo14 Configurations
###

  Odoo14Component:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: Odoo 14
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2
      Version: 1.0.2
      Description: Installs Odoo 14
      ChangeDescription: Initial version
      Data: |
        name: Odoo 14 - InlineData
        description: Installation of Odoo 14
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallWkHTMLToPDF
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y --nogpgcheck https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox-0.12.5-1.centos7.x86_64.rpm
              - name: CreateDirs
                action: ExecuteBash
                inputs:
                  commands:
                    - mkdir -p /opt/odoo14
                    - mkdir -p /var/log/odoo14
              - name: DownloadOdoo14
                action: WebDownload
                maxAttempts: 3
                inputs:
                  - source: https://github.com/odoo/odoo/archive/14.0.zip
                    destination: /tmp/14.0.zip
              - name: UnzipOdoo14
                action: ExecuteBash
                inputs:
                  commands:
                    - unzip /tmp/14.0.zip -d /opt/odoo14
                    - mv -fv /opt/odoo14/odoo-14.0/* /opt/odoo14/
                    - rm -fr /opt/odoo14/odoo-14.0/
              - name: InstallOdoo14Requirements
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo pip3 install -r /opt/odoo14/requirements.txt
              - name: InstallOdoo14Cryptography
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo pip3 install setuptools-rust
                    - sudo pip3 install cryptography
              - name: CreateOdoo14config
                action: CreateFile
                inputs:
                  - path: /opt/odoo14/odoo14.conf
                    content: |
                      [options]
                      addons_path = /opt/odoo14/odoo/addons,/opt/odoo14/addons
                      admin_passwd = admin
                      csv_internal_sep = ,
                      data_dir = /home/ec2-user/.local/share/Odoo
                      db_host = False
                      db_maxconn = 64
                      db_name = False
                      db_password = False
                      db_port = False
                      db_sslmode = prefer
                      db_template = template0
                      db_user = False
                      dbfilter =
                      demo = {}
                      email_from = False
                      # geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
                      http_enable = True
                      http_interface =
                      http_port = 8069
                      import_partial =
                      limit_memory_hard = 2684354560
                      limit_memory_soft = 2147483648
                      limit_request = 8192
                      limit_time_cpu = 60
                      limit_time_real = 120
                      limit_time_real_cron = -1
                      list_db = True
                      log_db = False
                      log_db_level = warning
                      log_handler = :INFO
                      log_level = info
                      logfile =
                      longpolling_port = 8072
                      max_cron_threads = 2
                      osv_memory_age_limit = False
                      osv_memory_count_limit = False
                      pg_path =
                      pidfile =
                      proxy_mode = True
                      reportgz = False
                      screencasts =
                      screenshots = /tmp/odoo_tests
                      server_wide_modules = base,web
                      smtp_password = False
                      smtp_port = 25
                      smtp_server = localhost
                      smtp_ssl = False
                      smtp_user = False
                      syslog = False
                      test_enable = False
                      test_file =
                      test_tags = None
                      transient_age_limit = 1.0
                      translate_modules = ['all']
                      unaccent = False
                      upgrade_path =
                      without_demo = False
                      workers = 0
                    overwrite: true
              - name: SetOdoo14Permissions
                action: SetFolderOwner
                inputs:
                  - path: /opt/odoo14
                    owner: ec2-user
                    group: ec2-user
              - name: SetOdoo14LogPermissions
                action: SetFolderOwner
                inputs:
                  - path: /var/log/odoo14
                    owner: ec2-user
                    group: ec2-user
              - name: CreateOdoo14Service
                action: CreateFile
                inputs:
                  - path: /lib/systemd/system/odoo14.service
                    content: |
                      [Unit]
                      Description=Odoo14 Server
                          
                      [Service]
                      Type=simple
                      PermissionsStartOnly=true
                      SyslogIdentifier=odoo14-server
                      User=ec2-user
                      Group=ec2-user
                      ExecStart=/opt/odoo14/odoo-bin -c /opt/odoo14/odoo14.conf
                      WorkingDirectory=/opt/odoo14/
                          
                      [Install]
                      WantedBy=multi-user.target
                    overwrite: true

  OpenLDAPDevelComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: OpenLDAP Devel
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2
      Version: 1.0.0
      Description: Installs OpenLDAP Development packages
      ChangeDescription: Initial version
      Data: |
        name: InstallOpenLDAPDevel - InlineData
        description: This is the yum installation for OpenLDAP Devel
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: YumInstallOpenLDAPDevel
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y openldap-devel

  Odoo14ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Join [' ', [!Ref OrgName, 'odoo14']]
      Version: 1.0.11
      ParentImage: !Join ['', ['arn:aws:imagebuilder:', !Ref AWS::Region, ':', !Ref AWS::AccountId, ':image/', !Ref OrgName, '-amazon-linux/1.0.5/1']]
      WorkingDirectory: /tmp
      Description: !Join [' ', [!Ref OrgName, 'odoo14']]
      Components: #Max 20
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/python-3-linux/1.0.2/1']]
        - ComponentArn: !Ref PIP3Component
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'component/postgresql-12-client/1.0.0']]
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'component/python-3-devel/1.0.0']]
        - ComponentArn: !Ref OpenLDAPDevelComponent
        - ComponentArn: !Ref Odoo14Component
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'component/nginx/1.0.0']]
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/simple-boot-test-linux/1.0.0/1']]
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            Encrypted: !If [IsImageShared, false, true]
            KmsKeyId: !If [IsImageShared, !Ref 'AWS::NoValue', !Join [':', ['arn:aws:kms', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'alias/aws/ebs']]]
            VolumeType: gp2
            VolumeSize: 8

  Odoo14ImageBuilder: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/ec2-image-builder.yaml
      Parameters: 
        Name: odoo14
        EnvName: !Ref EnvName
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        ImageRecipeARN: !Ref Odoo14ImageRecipe
        ShareImage: !Ref ShareImage
        SNSStackName: !Ref SNSStackName

##
# Odoo13 Configurations
###

  Odoo13Component:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: Odoo 13
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2
      Version: 1.0.2
      Description: Installs Odoo 13
      ChangeDescription: Initial version
      Data: |
        name: Odoo 13 - InlineData
        description: Installation of Odoo 13
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallWkHTMLToPDF
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y --nogpgcheck https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox-0.12.5-1.centos7.x86_64.rpm
              - name: CreateDirs
                action: ExecuteBash
                inputs:
                  commands:
                    - mkdir -p /opt/odoo13
                    - mkdir -p /var/log/odoo13
              - name: DownloadOdoo13
                action: WebDownload
                maxAttempts: 3
                inputs:
                  - source: https://github.com/odoo/odoo/archive/13.0.zip
                    destination: /tmp/13.0.zip
              - name: UnzipOdoo13
                action: ExecuteBash
                inputs:
                  commands:
                    - unzip /tmp/13.0.zip -d /opt/odoo13
                    - mv -fv /opt/odoo13/odoo-13.0/* /opt/odoo13/
                    - rm -fr /opt/odoo13/odoo-13.0/
              - name: InstallOdoo13Requirements
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo pip3 install -r /opt/odoo13/requirements.txt
              - name: InstallOdoo13Cryptography
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo pip3 install setuptools-rust
                    - sudo pip3 install cryptography
              - name: CreateOdoo13config
                action: CreateFile
                inputs:
                  - path: /opt/odoo13/odoo13.conf
                    content: |
                      [options]
                      addons_path = /opt/odoo13/odoo/addons,/opt/odoo13/addons
                      admin_passwd = admin
                      csv_internal_sep = ,
                      data_dir = /home/ec2-user/.local/share/Odoo
                      db_host = False
                      db_maxconn = 64
                      db_name = False
                      db_password = False
                      db_port = False
                      db_sslmode = prefer
                      db_template = template0
                      db_user = False
                      dbfilter =
                      demo = {}
                      email_from = False
                      # geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
                      http_enable = True
                      http_interface =
                      http_port = 8069
                      import_partial =
                      limit_memory_hard = 2684354560
                      limit_memory_soft = 2147483648
                      limit_request = 8192
                      limit_time_cpu = 60
                      limit_time_real = 120
                      limit_time_real_cron = -1
                      list_db = True
                      log_db = False
                      log_db_level = warning
                      log_handler = :INFO
                      log_level = info
                      logfile =
                      longpolling_port = 8072
                      max_cron_threads = 2
                      osv_memory_age_limit = False
                      osv_memory_count_limit = False
                      pg_path =
                      pidfile =
                      proxy_mode = True
                      reportgz = False
                      screencasts =
                      screenshots = /tmp/odoo_tests
                      server_wide_modules = base,web
                      smtp_password = False
                      smtp_port = 25
                      smtp_server = localhost
                      smtp_ssl = False
                      smtp_user = False
                      syslog = False
                      test_enable = False
                      test_file =
                      test_tags = None
                      transient_age_limit = 1.0
                      translate_modules = ['all']
                      unaccent = False
                      upgrade_path =
                      without_demo = False
                      workers = 0
                    overwrite: true
              - name: SetOdoo13Permissions
                action: SetFolderOwner
                inputs:
                  - path: /opt/odoo13
                    owner: ec2-user
                    group: ec2-user
              - name: SetOdoo13LogPermissions
                action: SetFolderOwner
                inputs:
                  - path: /var/log/odoo13
                    owner: ec2-user
                    group: ec2-user
              - name: CreateOdoo13Service
                action: CreateFile
                inputs:
                  - path: /lib/systemd/system/odoo13.service
                    content: |
                      [Unit]
                      Description=Odoo13 Server
                          
                      [Service]
                      Type=simple
                      PermissionsStartOnly=true
                      SyslogIdentifier=odoo13-server
                      User=ec2-user
                      Group=ec2-user
                      ExecStart=/opt/odoo13/odoo-bin -c /opt/odoo13/odoo13.conf
                      WorkingDirectory=/opt/odoo13/
                          
                      [Install]
                      WantedBy=multi-user.target
                    overwrite: true

  Odoo13ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Join [' ', [!Ref OrgName, 'odoo13']]
      Version: 1.0.11
      ParentImage: !Join ['', ['arn:aws:imagebuilder:', !Ref AWS::Region, ':', !Ref AWS::AccountId, ':image/', !Ref OrgName, '-amazon-linux/1.0.5/1']]
      WorkingDirectory: /tmp
      Description: !Join [' ', [!Ref OrgName, 'odoo13']]
      Components: #Max 20
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/python-3-linux/1.0.2/1']]
        - ComponentArn: !Ref PIP3Component
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'component/postgresql-12-client/1.0.0']]
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'component/python-3-devel/1.0.0']]
        - ComponentArn: !Ref OpenLDAPDevelComponent
        - ComponentArn: !Ref Odoo13Component
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'component/nginx/1.0.0']]
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/simple-boot-test-linux/1.0.0/1']]
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            Encrypted: !If [IsImageShared, false, true]
            KmsKeyId: !If [IsImageShared, !Ref 'AWS::NoValue', !Join [':', ['arn:aws:kms', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'alias/aws/ebs']]]
            VolumeType: gp2
            VolumeSize: 8

  Odoo13ImageBuilder: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/ec2-image-builder.yaml
      Parameters: 
        Name: odoo13
        EnvName: !Ref EnvName
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        ImageRecipeARN: !Ref Odoo13ImageRecipe
        ShareImage: !Ref ShareImage
        SNSStackName: !Ref SNSStackName