AWSTemplateFormatVersion: 2010-09-09
Description: Base Image Builder for Amazon Linux

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      -
        Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Topic Stack Name

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: image-builder
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: iscale-dev-dev-uw2-network
    MinLength: 1
  SNSStackName:
    Description: the name of the SNS stack.
    Type: String
    Default: iscale-dev-dev-uw2-sns
    MinLength: 1

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml      

Resources:

###
# Common components
###

  CodeDeployComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: CodeDeploy
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2
      Version: 1.0.0
      Description: Installs the CodeDeploy Agent
      ChangeDescription: Initial version
      Data: |
        name: CodeDeploy - InlineData
        description: Installation of CodeDeploy Agent
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: YumInstallWgetRuby
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y wget
                    - sudo yum install -y ruby
              - name: CreateCodeDeployconfig
                action: CreateFile
                inputs:
                  - path: /opt/odoo14/odoo14.conf
                    content: |
                      [/var/log/aws/codedeploy-agent/codedeploy-agent.log]
                      datetime_format = %b %d %H:%M:%S
                      file = /var/log/aws/codedeploy-agent/codedeploy-agent.log
                      buffer_duration = 5000
                      log_stream_name = {instance_id}
                      initial_position = start_of_file
                      log_group_name = /var/log/aws/codedeploy-agent/codedeploy-agent.log
              - name: WGetInstall
                action: ExecuteBash
                inputs:
                  commands:
                    - wget -P /tmp https://aws-codedeploy-us-west-2.s3.us-west-2.amazonaws.com/latest/install
              - name: SetInstallPermissions
                action: SetFilePermissions
                inputs:
                  - path: /tmp/install
                    permissions: 700
              - name: ExecuteInstall
                action: ExecuteBash
                inputs:
                  commands:
                    - /tmp/install auto
              - name: CleanupInstall
                action: ExecuteBash
                inputs:
                  commands:
                    - rm -fr /tmp/install
              - name: LinkCFNInit
                action: CreateSymlink
                inputs:
                  - path: /usr/local/bin/cfn-init
                    target: /opt/aws/bin/cfn-init
                    force: true
              - name: LinkCFNHup
                action: CreateSymlink
                inputs:
                  - path: /usr/local/bin/cfn-hup
                    target: /opt/aws/bin/cfn-hup
                    force: true
              - name: LinkCFNSignal
                action: CreateSymlink
                inputs:
                  - path: /usr/local/bin/cfn-signal
                    target: /opt/aws/bin/cfn-signal
                    force: true

  AWSLinuxUtilitiesComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: AWS Linux Utilities
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2
      Version: 1.0.0
      Description: Installs EPEL repository, Git, JQuery, EFS, CFN, Telnet, wget
      ChangeDescription: Initial version
      Data: |
        name: AWWS Linux Utilities - InlineData
        description: Linux Utilities Installation
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: EPELInstall
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo amazon-linux-extras install -y epel
              - name: YumUpdate
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum -y update
              - name: InstallGit
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y git
              - name: InstallJQuery
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y jq
              - name: InstallEFS
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y amazon-efs-utils
              - name: InstallCloudFormation
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y aws-cfn-bootstrap
              - name: InstallTelnet
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y telnet
              - name: InstallWget
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y wget
  
  NginxComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: NginX
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2
      Version: 1.0.0
      Description: Installs NginX
      ChangeDescription: Initial version
      Data: |
        name: NginX - InlineData
        description: Installation of NginX
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: YumInstallNginx
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo amazon-linux-extras install -y nginx1
  
  OpenLDAPDevelComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: OpenLDAP Devel
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2
      Version: 1.0.0
      Description: Installs OpenLDAP Development packages
      ChangeDescription: Initial version
      Data: |
        name: InstallOpenLDAPDevel - InlineData
        description: This is the yum installation for OpenLDAP Devel
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: YumInstallOpenLDAPDevel
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y openldap-devel

  PostgreSQLClientComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: PostgreSQL 11 Client
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2
      Version: 1.0.0
      Description: Installs PostgreSQL 11 Client
      ChangeDescription: Initial version
      Data: |
        name: InstallPostgreSQL11 - InlineData
        description: This is the PostgreSQL 11 installation
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallPostgreSQL11
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo amazon-linux-extras install -y postgresql11
              - name: YumUpdate
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum -y update

  Python3DevelComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: Python 3 Devel
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2
      Version: 1.0.0
      Description: Installs Python 3 Development packages
      ChangeDescription: Initial version
      Data: |
        name: InstallPython3Devel - InlineData
        description: This is the yum installation for Python 3 Devel
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: YumInstallPythonDevel
                action: ExecuteBash
                inputs:
                  commands:
                    - sudo yum install -y gcc python3-devel.x86_64

  
###
# Amazon Linux Base Image
###

  AmazonLinuxImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Join [' ', [!Ref OrgName, 'amazon-linux']]
      Version: 1.0.0
      ParentImage: arn:aws:imagebuilder:us-west-2:aws:image/amazon-linux-2-x86/2019.11.21
      WorkingDirectory: /tmp
      Description: !Join [' ', ['Base image for', !Ref OrgName, 'amazon-linux']]
      Components: #Max 20
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/amazon-cloudwatch-agent-linux/1.0.0/1']]
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/aws-cli-version-2-linux/1.0.0/1']]
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/update-linux-kernel-mainline/1.0.0/1']]
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/update-linux/1.0.0/1']]
        - ComponentArn: !Ref AWSLinuxUtilitiesComponent
        - ComponentArn: !Ref CodeDeployComponent
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/stig-build-linux-high/2.8.0/1']]
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/reboot-linux/1.0.1/1']]
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/chrony-time-configuration-test/1.0.0/1']]
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/simple-boot-test-linux/1.0.0/1']]
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/validate-ssh-host-key-generation-linux/1.0.1/1']]
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            Encrypted: true
            KmsKeyId: !Join [':', ['arn:aws:kms', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'alias/aws/ebs']]
            VolumeType: gp2
            VolumeSize: 8

  AmazonLinuxBuilder: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/ec2-image-builder.yaml
      Parameters: 
        Name: 'amazon-linux'
        EnvName: !Ref EnvName
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        ImageRecipeARN: !Ref AmazonLinuxImageRecipe
        SNSStackName: !Ref SNSStackName