AWSTemplateFormatVersion: 2010-09-09
Description: Wordpress Image Builder

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName
      - Label:
          default: Sharing Configuration
        Parameters:
          - ShareImage

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      NetworkStackName:
        default: Network Stack Name
      ShareImage:
        default: Share image with other account? If sharing, encryption will be disabled.
      SNSStackName:
        default: SNS Topic Stack Name

Parameters:
  Name:
    Description: Unique name/identifier (e.g. wordpress).
    Type: String
    Default: wordpress
    AllowedPattern: "^[a-z0-9]+(-[a-z0-9]+)*$"
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-hosting
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: iscale-hosting-prd-uw2-network
    MinLength: 1
  ShareImage:
    Description: Select true to not encrypt the image and share it with other accounts
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  SNSStackName:
    Description: the name of the SNS stack.
    Type: String
    Default: iscale-hosting-prd-uw2-sns
    MinLength: 1

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml      
  IsImageShared: !Equals [!Ref ShareImage, true]

Resources:
  

###
# Wordpress Configurations
###

  WordpressPHPComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: Apache 7_4
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2
      Version: 1.0.0
      Description: Installs PHP7.4
      ChangeDescription: Initial version
      Data: |
        name: Apache PHP74 - InlineData
        description: Installation of Apache + PHP7.4
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: IntallPHPApache
                action: ExecuteBash
                inputs:
                  commands:
                    - |
                      sudo yum install -y amazon-linux-extras
                      sudo amazon-linux-extras enable php7.4
                      sudo yum clean metadata
                      sudo yum install -y php php-common php-pear
                      sudo yum install -y php-{cgi,curl,mbstring,gd,mysqlnd,gettext,json,xml,fpm,intl,zip}

  Wordpress56Component:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: Wordpress 5_6_0
      Platform: Linux
      SupportedOsVersions:
        - Amazon Linux 2
      Version: 1.0.2
      Description: Installs Wordpress 5.6.0
      ChangeDescription: Initial version
      Data: |
        name: Wordpress - InlineData
        description: Installation of Wordpress
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: CreateDirs
                action: ExecuteBash
                inputs:
                  commands:
                    - mkdir -p /var/www/html
              - name: DownloadWordpress
                action: WebDownload
                maxAttempts: 3
                inputs:
                  - source: https://wordpress.org/wordpress-5.6.tar.gz
                    destination: /tmp/wordpress-5.6.tar.gz
              - name: UnzipWordpress
                action: ExecuteBash
                inputs:
                  commands:
                    - tar xvfz /tmp/wordpress-5.6.tar.gz -C /var/www/html
                    - mv -fv /var/www/html/wordpress/* /var/www/html/
                    - mv -fv /var/www/html/wordpress/.* /var/www/html/
                    - rm -fr /var/www/html/wordpress/
                    - rm -f /tmp/wordpress-5.6.tar.gz
              - name: CreateHTAccess
                action: CreateFile
                inputs:
                  - path: /var/www/html/.htaccess
                    content: |
                      <IfModule mod_rewrite.c>
                        RewriteEngine On
                        RewriteBase /
                        RewriteRule ^index\.php$ - [L]
                        RewriteCond %{REQUEST_FILENAME} !-f
                        RewriteCond %{REQUEST_FILENAME} !-d
                        RewriteRule . /index.php [L]
                      </IfModule>
                    overwrite: false
              - name: AllowOverrideAllForWWWRoot
                action: ExecuteBash
                inputs:
                  commands:
                    - sed -i '0,/AllowOverride None/! {0,/AllowOverride None/ s/AllowOverride None/AllowOverride All/}' /etc/httpd/conf/httpd.conf
              - name: DefaultWPConfig
                action: ExecuteBash
                inputs:
                  commands:
                    - mv -fv /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
              - name: SetPermissions
                action: SetFolderOwner
                inputs:
                  - path: /var/www/html
                    owner: apache
                    group: apache

  Wordpress56ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Join [' ', [!Ref OrgName, 'wordpress 5_6_0']]
      Version: 1.0.3
      ParentImage: !Join ['', ['arn:aws:imagebuilder:', !Ref AWS::Region, ':', !Ref AWS::AccountId, ':image/', !Ref OrgName, '-amazon-linux/1.0.3/1']]
      WorkingDirectory: /tmp
      Description: !Join [' ', [!Ref OrgName, 'wordpress 5.6.0']]
      Components: #Max 20
        - ComponentArn: !Ref WordpressPHPComponent
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'component/mysql-client/1.0.0/1']]
        - ComponentArn: !Ref Wordpress56Component
        - ComponentArn: !Join [':', ['arn:aws:imagebuilder', !Ref 'AWS::Region', 'aws:component/simple-boot-test-linux/1.0.0/1']]
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            Encrypted: !If [IsImageShared, false, true]
            KmsKeyId: !If [IsImageShared, !Ref 'AWS::NoValue', !Join [':', ['arn:aws:kms', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'alias/aws/ebs']]]
            VolumeType: gp2
            VolumeSize: 8

  Wordpress560ImageBuilder: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/ec2-image-builder.yaml
      Parameters: 
        Name: wordpress-560
        EnvName: !Ref EnvName
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        ImageRecipeARN: !Ref Wordpress56ImageRecipe
        ShareImage: !Ref ShareImage
        SNSStackName: !Ref SNSStackName