AWSTemplateFormatVersion: 2010-09-09
Description: This CloudFormation stack will deploy the Chatbot AI Infrastructure

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName
          - DeletionProtection
          - ClientDomainName
      - Label:
          default: Instance Configuration
        Parameters:
          - InstanceKeyName
          - InstanceAMI
          - InstanceType
      - Label:
          default: Scheduler Configuration
        Parameters:
          - StartScheduleExpression
          - StopScheduleExpression

    ParameterLabels:
      Name:
        default: Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Stack Name
      DeletionProtection:
        default: Enable Deletion Protection
      InstanceKeyName:
        default: Key Pair Name
      InstanceAMI:
        default: AMI ID
      InstanceType:
        default: Instance Type
      StartScheduleExpression:
        default: Start Schedule Expression
      StopScheduleExpression:
        default: Stop Schedule Expression

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name)
    Type: String
    MinLength: 3
    MaxLength: 12
    Default: chatbotai
  OrgName:
    Description: The name of the organization
    Type: String
    Default: iscale-dev
    AllowedPattern: '^[a-z]+(-[a-z]+)*$'
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen
    MaxLength: 20
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production # Test for uat
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The domain name for the client
    Type: String
    Default: iscale-software.com
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    ConstraintDescription: Domain name must only contain lowercase letters, numbers and hyphen
    MaxLength: 30
  DeletionProtection:
    Description: Set to true to enable (valid only in Production mode)
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  InstanceAMI:
    Description: Instance AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-0edf4a7e3058418ad # AL2
  InstanceKeyName:
    Description: Instance Key Name
    Type: String
    Default: ''
  InstanceType:
    Description: Type of instance for app server
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
  ELBStackName:
    Description: The name of the ELB stack
    Type: String
    Default: iscale-dev-stg-uw2-alb
    MinLength: 1
  LoadBalancerHostName:
    Description: The host name of the load balancer
    Type: String
    Default: ''
  NetworkStackName:
    Description: The name of the network stack
    Type: String
    Default: iscale-dev-dev-uw2-network
    MinLength: 1
  SNSStackName:
    Description: The name of the SNS stack
    Type: String
    Default: iscale-dev-dev-uw2-sns
    MinLength: 1
  StartScheduleExpression:
    Description: Schedule expression when to start the objects
    Type: String
    Default: cron(0 0 ? * MON-FRI *)
  StopScheduleExpression:
    Description: Schedule expression when to stop the objects
    Type: String
    Default: cron(0 10 ? * MON-FRI *)
  EC2InstanceTag:
    Description: The tag to identify the EC2 instance
    Type: String
    Default: CHATBOTAI
  UseFriendlyNames:
    Description: Set to TRUE to have nice formatted scheduler event names
    Type: String
    AllowedValues:
      - TRUE
      - FALSE
    Default: TRUE

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
       Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  HasKeyName: !Not [!Equals [!Ref InstanceKeyName, '']]
  HasLoadBalancerHostName: !Not [!Equals [!Ref LoadBalancerHostName, '']]
  UseFriendlyNames: !Equals [!Ref UseFriendlyNames, TRUE]

Resources:

##
# K3s Cluster
##
  K3sMasterServerStack:
    DependsOn:
      - DBStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/appserver-basic2.yaml
      Parameters:
        Name: !Join ['-', [!Ref Name, master]]
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        ASGHealthCheckType: EC2
        ASGMaxSize: 1
        ASGDesiredSize: 0
        ClientDomainName: !Ref ClientDomainName
        DatabaseEndpoint:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstanceAddress
        DatabasePort:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstancePort
        DatabaseSecurityGroupId:
          Fn::GetAtt:
            - DBStack
            - Outputs.SecurityGroupId
        InstanceAMI: !Ref InstanceAMI
        InstanceKeyName: !If [HasKeyName, !Ref InstanceKeyName, !Ref 'AWS::NoValue']
        InstancePort: 8051
        InstanceSubnet: Private
        InstanceType: !Ref InstanceType
        LoadBalancerHostName: !If [HasLoadBalancerHostName, !Ref LoadBalancerHostName, !Ref 'AWS::NoValue']
        LoadBalancerPriority: 11
        LoadBalancerStackName: !Ref ELBStackName
        NetworkStackName: !Ref NetworkStackName
        SharedSecretId:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBSecretManagerKeyId
        SNSStackName: !Ref SNSStackName
        UseFriendlyNames: FALSE
        VolumeName: /dev/sda1
        LaunchTemplate: True
        VolumeSize: 20
        VolumeType: gp3
        
##
# K3s Master Scheduler
##       
  LambdaScheduleEC2InstanceRole:
    Condition: IsNotProd
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ScheduleEC2InstancePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:DescribeTags
                Resource: "*"
              - Effect: Allow
                Action:
                  - ec2:StartInstances
                  - ec2:StopInstances
                Resource: !Join [":", ["arn", "aws", "ec2", !Ref 'AWS::Region', !Ref 'AWS::AccountId', !Join ['/', ['instance', '*' ]]]]
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  StopEC2InstanceByTagFunction:
    Condition: IsNotProd
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda Function stopping an EC2 instance
      Handler: index.lambda_handler
      Role: !GetAtt LambdaScheduleEC2InstanceRole.Arn
      Runtime: python3.9
      Timeout: 60
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          SYSTEM_TAG: !Ref EC2InstanceTag
      Code:
        ZipFile: |
          import boto3
          import os
          
          ec2 = boto3.resource('ec2')

          def lambda_handler(event, context):
            # Use the filter() method of the instances collection to retrieve
            # all running EC2 instances.
            system_tag_value = os.environ.get('SYSTEM_TAG', 'DefaultValue')
            filters = [
                {
                    'Name' : 'tag:System', 
                    'Values': [system_tag_value]
                },
                {
                    'Name': 'instance-state-name', 
                    'Values': ['running']
                }]
            
            # Filter the and locate all running instances
            instances = ec2.instances.filter(Filters=filters)
            instance_ids_to_stop = [instance.id for instance in instances]
            
            # ensures instances are actually shutdown 
            if len(instance_ids_to_stop) > 0:
                try:    
                    # Perform the shutdown
                    shuttingDown = ec2.instances.filter(InstanceIds=instance_ids_to_stop).stop()
                    print(f"Stopped {len(instance_ids_to_stop)} instances")
                except Exception as e:
                    print(f"Error stopping instances: {e}")
            else:
                print ("Nothing to see here")

            return{
                'statusCode': 200,
                'statusMessage': 'OK'
            }
  StopEC2InstanceByTagFunctionPermission:
    Condition: IsNotProd
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref UserPermissionsGroup
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !GetAtt StopEC2InstanceByTagFunction.Arn
      PolicyName: AllowStopEC2InstanceByTag

  StopScheduledEC2InstanceEventRule:
    Type: AWS::Events::Rule
    Condition: IsNotProd
    Properties:
      Name: !If
        - UseFriendlyNames
        - !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, ec2, stop]]
        - !Ref 'AWS::NoValue'
      Description: !Join [' ',[ Stop, !Join ['-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]], at, !Ref StopScheduleExpression]]
      ScheduleExpression: !Ref StopScheduleExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt StopEC2InstanceByTagFunction.Arn
          Id: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, ec2, stop]]
  
  ScheduledEventPermissionToStopEC2Instance:
    Condition: IsNotProd
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StopEC2InstanceByTagFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt StopScheduledEC2InstanceEventRule.Arn
  
  UserPermissionsGroup:
    Type: AWS::IAM::Group

  # K3sMasterSchedulerStack:
  #   DependsOn:
  #     - DBStack
  #     - K3sMasterServerStack
  #   Condition: IsNotProd
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
  #     Parameters:
  #       Name: !Ref Name
  #       EnvName: !Ref EnvName
  #       OrgName: !Ref OrgName
  #       StartScheduleExpression: !Ref StartScheduleExpression
  #       StopScheduleExpression: !Ref StopScheduleExpression
  #       UseFriendlyNames: FALSE
  #       EC2InstanceTag: CHATBOTAI

  # K3sWorkerServerStack:
  #   DependsOn:
  #     - DBStack
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/appserver-basic2.yaml
  #     Parameters:
  #       Name: !Join ['-', [!Ref Name, k3s-worker]]
  #       EnvName: !Ref EnvName
  #       OrgName: !Ref OrgName
  #       ASGHealthCheckType: EC2
  #       ClientDomainName: !Ref ClientDomainName
  #       DatabaseEndpoint:
  #         Fn::GetAtt:
  #           - DBStack
  #           - Outputs.DBInstanceAddress
  #       DatabasePort:
  #         Fn::GetAtt:
  #           - DBStack
  #           - Outputs.DBInstancePort
  #       DatabaseSecurityGroupId:
  #         Fn::GetAtt:
  #           - DBStack
  #           - Outputs.SecurityGroupId
  #       InstanceAMI: !Ref InstanceAMI
  #       InstanceKeyName: !If [HasKeyName, !Ref InstanceKeyName, !Ref 'AWS::NoValue']
  #       InstancePort: 80
  #       InstanceSubnet: Private
  #       InstanceType: !Ref InstanceType
  #       # LoadBalancerHostName: !Ref LoadBalancerHostName
  #       LoadBalancerPriority: 100
  #       # LoadBalancerStackName: !Select [ 1, !Split [ '/', !Ref ELBStack]]
  #       NetworkStackName: !Ref NetworkStackName
  #       SharedSecretId:
  #         Fn::GetAtt:
  #           - DBStack
  #           - Outputs.DBSecretManagerKeyId
  #       SNSStackName: !Ref SNSStackName
  #       UseFriendlyNames: FALSE
  #       LaunchTemplate: True


##
# PostgreSQL Database
##
  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/database.yaml
      Parameters:
        Name: !Ref Name
        DatabaseName: !Join ['',[!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name], db]]
        AllocatedStorage: !If [IsProd, 50, 20]
        BackupRetentionPeriod: !If [IsProd, 30, 7]
        DeletionProtection: !If [IsProd, !Ref DeletionProtection, false]
        EnableEnhancedMonitoring: !If [IsProd, true, false]
        EnablePerformanceInsights: !If [IsProd, true, false]
        EnvName: !Ref EnvName
        Engine: postgres
        EngineVersion: 17.4
        Family: postgres17
        InstanceType: !If [IsProd, db.t4g.large, db.t4g.micro]
        MasterUser: root
        MultiAz: !If [IsProd, true, false]
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        Port: 5432
        SNSStackName: !Ref SNSStackName
        StorageEncrypted: true
        StorageType: gp3

  DBSchedulerStack:
    DependsOn:
      - DBStack
    Condition: IsNotProd
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        StartScheduleExpression: !Ref StartScheduleExpression
        StopScheduleExpression: !Ref StopScheduleExpression
        UseFriendlyNames: FALSE
        DatabaseInstanceName:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstanceName


###
# ECR - web-app
###

  ECRWebApp:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: false
      EncryptionConfiguration: 
        EncryptionType: AES256
      ImageScanningConfiguration: 
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      RepositoryName: chatbotai-webapp
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], webapp]]
        - Key: OrgName
          Value: !Ref OrgName

###
# ECR - backend
###

  ECRBackend:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: false
      EncryptionConfiguration: 
        EncryptionType: AES256
      ImageScanningConfiguration: 
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      RepositoryName: chatbotai-backend
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], ai-backend]]
        - Key: OrgName
          Value: !Ref OrgName

##
# IAM  Roles
##

  DeplomentUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join ['-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !Ref Name, ecr-deploy]]
      Policies:
        - PolicyName: ecrWriteAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'     
              - Effect: Allow
                Action:
                  - ecr:CompleteLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:InitiateLayerUpload
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                Resource: 
                  - !GetAtt ECRWebApp.Arn
                  - !GetAtt ECRBackend.Arn

  ExternalSecretsUser:    # for External Secrets (will change to IAM role once integrated with ArgoCD)
    Type: AWS::IAM::User
    Properties:
      UserName: !Join ['-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !Ref Name, external-secrets]]
      Policies:
        - PolicyName: ExternalSecretsPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:    
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource: 
                  - !GetAtt DBStack.Outputs.DBSecretManager

Outputs:
  ECRWebApp:
    Description: ECR Web App Repository
    Value: !GetAtt ECRWebApp.RepositoryUri
  
  ECRBackend:
    Description: ECR Backend Repository
    Value: !GetAtt ECRBackend.RepositoryUri
                


  
  
  