AWSTemplateFormatVersion: 2010-09-09
Description: Creates a temporary admin machine to be used as CLI with admin privileges

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
      - Label:
          default: Instance Configuration
        Parameters:
          - InstanceAMI

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      InstanceAMI:
        default: Instance AMI ID
      NetworkStackName:
        default: Network Stack Name

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name)
    Type: String
    MinLength: 3
    MaxLength: 9
    Default: admin
  OrgName:
    Description: The name of the organization
    Type: String
    Default: iscale
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  InstanceAMI:
    Description: Instance AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-00b8d9cb8a7161e41 #Default Amazon Linux 2 for Singapore
  NetworkStackName:
    Description: The name of the network stack
    Type: String
    Default: pchc-dev-ase1-network
    MinLength: 1

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  AdminSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Admin instance security group
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VpcId"

  AdminSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !GetAtt AdminSecurityGroup.GroupId
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      CidrIp: 0.0.0.0/0

  AdminIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: 1
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  AdminInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
      Roles:
        - !Ref AdminIamRole

  AdminInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref InstanceAMI
      InstanceType: t3.micro
      IamInstanceProfile: !Ref AdminInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet: [!GetAtt AdminSecurityGroup.GroupId]
          SubnetId: 
            Fn::ImportValue:
              !Sub "${NetworkStackName}-PublicSubnetId1"
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]