AWSTemplateFormatVersion: 2010-09-09
Description: |
  This cloudformation template provisions DNS records for iscale-software

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    Default: iscale-software.com

Mappings: 
  EnvShort:
    Production:
      Name: prd
    Staging:
      Name: stg
    Development:
      Name: dev
    Test:
      Name: test
  RegionShort:
    us-east-2:
      Name: ue2
    us-east-1:
      Name: ue1
    us-west-1:
      Name: uw1
    us-west-2:
      Name: uw2
    ap-east-1:
      Name: ae1
    ap-south-1:
      Name: as1
    ap-northeast-1:
      Name: ane1
    ap-northeast-2:
      Name: ane2
    ap-northeast-3:
      Name: ane3
    ap-southeast-1:
      Name: ase1
    ap-southeast-2:
      Name: ase2
    ca-central-1:
      Name: cc1
    cn-north-1:
      Name: cn1
    cn-northwest-1:
      Name: cnw1
    eu-central-1:
      Name: ec1
    eu-west-1:
      Name: ew1
    eu-west-2:
      Name: ew2
    eu-west-3:
      Name: ew3
    eu-north-1:
      Name: en1
    me-south-1:
      Name: ms1
    sa-east-1:
      Name: se1
    us-gov-east-1:
      Name: uge1
    us-gov-west-1:
      Name: ugw1 


Resources:

#############################################
#
# iscale-software domain
#
#############################################

####
# Route53 Section
####

  SPFDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : Z3IVOZ67OCE9RL
      Name: !Ref ClientDomainName
      ResourceRecords: 
        - "\"v=spf1 include:_spf.google.com ~all\""
      TTL: 60
      Type: TXT
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], spf]]

  AmazonSESDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : Z3IVOZ67OCE9RL
      Name: !Join ['.',[_amazonses, !Ref ClientDomainName]]
      ResourceRecords: 
        - "\"DNogfA2ANoIYSnMzkCpktt3qxBdJWa13Im9iipUmg+M=\""
      TTL: 60
      Type: TXT
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], amazon-ses]]

  DKIMDnsRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : Z3IVOZ67OCE9RL
      Name: !Join ['.',[dwfrkdx566uxcewp5a6exlhb2vpb6f5g._domainkey, !Ref ClientDomainName]]
      ResourceRecords: 
        - "dwfrkdx566uxcewp5a6exlhb2vpb6f5g.dkim.amazonses.com"
      TTL: 60
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], dkim1]]

  DKIMDnsRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : Z3IVOZ67OCE9RL
      Name: !Join ['.',[3hmxfh5w2p2dx7fjidw52vdskuaekj7k._domainkey, !Ref ClientDomainName]]
      ResourceRecords: 
        - "3hmxfh5w2p2dx7fjidw52vdskuaekj7k.dkim.amazonses.com"
      TTL: 60
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], dkim2]]

  DKIMDnsRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : Z3IVOZ67OCE9RL
      Name: !Join ['.',[alq5lof53ucgqt34hgw4ecaca45b7krz._domainkey, !Ref ClientDomainName]]
      ResourceRecords: 
        - "alq5lof53ucgqt34hgw4ecaca45b7krz.dkim.amazonses.com"
      TTL: 60
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], dkim3]]

  LetsEncryptWildcardDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : Z3IVOZ67OCE9RL
      Name: !Join ['.',[_acme-challenge, !Ref ClientDomainName]]
      ResourceRecords: 
        - "\"xSF7LCsjOdNTj_4FDcTU1J3xhd_PJdfYoB4kM6dh2Gg\""
      TTL: 60
      Type: TXT
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], letsencrypt-wildcard]]

  PayrollOdoo14DevRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : Z3IVOZ67OCE9RL
      Name: !Join ['.',[odoo14, !Ref ClientDomainName]]
      ResourceRecords:
        - "payroll.iscale-software.com"
      TTL: 3600
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], odoo14]]