AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions an IAM Group

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: "Resource Configuration"
        Parameters:
          - OrgName
          - EnvName

    ParameterLabels:
      OrgName:
        default: "Organization Name"
      EnvName:
        default: "Environment Name"

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Users
####

  AJ:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Albert123!
        PasswordResetRequired: true
      UserName: albert.john@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Albert John BORBE
        - Key: Email
          Value: albert.john@iscale-solutions.com
  
  Albert:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Albert123!
        PasswordResetRequired: true
      UserName: albert.manuel@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Albert MANUEL
        - Key: Email
          Value: albert.manuel@iscale-solutions.com

  Aira:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Aria123!
        PasswordResetRequired: true
      UserName: aira@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Aira GUEVERRA
        - Key: Email
          Value: aira@iscale-solutions.com

  Aris:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Aris123!
        PasswordResetRequired: true
      UserName: aris@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Aris DENCIO
        - Key: Email
          Value: aris@iscale-solutions.com          

  Bertrand:
    Type: AWS::IAM::User
    Properties:
      UserName: bnavarre
      Tags:
        - Key: Name
          Value: Bertrand NAVARRE
        - Key: Email
          Value: bertrand@iscale-solutions.com

  Dennis:
    Type: AWS::IAM::User
    Properties:
      UserName: dlagumbay
      Tags:
        - Key: Name
          Value: Dennis LAGUMBAY
        - Key: Email
          Value: dennis@iscale-solutions.com

  Franz:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Franz123!
        PasswordResetRequired: true
      UserName: franz.miguel@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Franz Miguel ORTEGA
        - Key: Email
          Value: franz.miguel@iscale-solutions.com

  Gerald:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Gerald123!
        PasswordResetRequired: true
      UserName: gerald@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Gerald VILLAFLORES
        - Key: Email
          Value: gerald@iscale-solutions.com

  Harold:
    Type: AWS::IAM::User
    Properties:
      UserName: harold@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Harold BATTALER
        - Key: Email
          Value: harold@iscale-solutions.com

  Honey:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Honey123!
        PasswordResetRequired: true
      UserName: honey.grace@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Honey Grace BATIAO
        - Key: Email
          Value: honey.grace@iscale-solutions.com

  JeanEmmanuel:
    Type: AWS::IAM::User
    Properties:
      UserName: jean.emmanuel@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Jean-Emmanuel LABIGNETTE
        - Key: Email
          Value: jean.emmanuel@iscale-solutions.com

  Jonalyn:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Jonah123!
        PasswordResetRequired: true
      UserName: jonalyn@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Jonalyn BENLIRO
        - Key: Email
          Value: jonalyn@iscale-solutions.com

  Lea:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Lea123!
        PasswordResetRequired: true
      UserName: lea@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Lea RENTILLO
        - Key: Email
          Value: lea@iscale-solutions.com

  Maricar:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Maricar123!
        PasswordResetRequired: true
      UserName: maricar@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Maricar VALENZUELA
        - Key: Email
          Value: maricar@iscale-solutions.com

  MartinLouie:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Maricar123!
        PasswordResetRequired: true
      UserName: martin.louie@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Martin Louie DE LA CERNA
        - Key: Email
          Value: martin.louie@iscale-solutions.com

  Patty:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Patty123!
        PasswordResetRequired: true
      UserName: patty@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Patricia Mae MARASIGAN
        - Key: Email
          Value: patty@iscale-solutions.com

  Randjae:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Randjae123!
        PasswordResetRequired: true
      UserName: randjae@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Randjae GALVAN
        - Key: Email
          Value: randjae@iscale-solutions.com

  Raphael:
    Type: AWS::IAM::User
    Properties:
      UserName: raphael@iscale-solutions.com
      Tags:
        - Key: Name
          Value: John Raphael ROSELLO
        - Key: Email
          Value: raphael@iscale-solutions.com

  Ronald:
    Type: AWS::IAM::User
    Properties:
      UserName: ronald@iscale-solutions.com
      Tags:
        - Key: Name
          Value: Ronald LEVIDA
        - Key: Email
          Value: ronald@iscale-solutions.com

####
# Groups
####

  #
  # Adding users to Group
  #

  # All users must be associated in MFA Group
  MFAUserGroupUsers:
    Type: AWS::IAM::UserToGroupAddition
    Properties: 
      GroupName: !Ref MFAUserGroup
      Users: 
        - !Ref Dennis
        - !Ref Bertrand

  # OdooAdministratorsGroupAddition:
  #   Type: AWS::IAM::UserToGroupAddition
  #   Properties: 
  #     GroupName: !Ref OdooAdministratorsGroup
  #     Users: 
  #       - !Ref OdooTestUser

  OdooUserGroupUsers:
    Type: AWS::IAM::UserToGroupAddition
    Properties: 
      GroupName: !Ref OdooUserGroup
      Users: 
        - !Ref Dennis
        - !Ref Bertrand

  AdministratorsGroupUsers:
    Type: AWS::IAM::UserToGroupAddition
    Properties: 
      GroupName: !Ref AdministratorsGroup
      Users: 
        - !Ref JeanEmmanuel

  ReadOnlyGroupUsers:
    Type: AWS::IAM::UserToGroupAddition
    Properties: 
      GroupName: !Ref ReadOnlyGroup
      Users: 
        - !Ref Aira
        - !Ref AJ
        - !Ref Albert
        - !Ref Aris
        - !Ref Bertrand
        - !Ref Dennis
        - !Ref Franz
        - !Ref Gerald
        - !Ref Harold
        - !Ref Honey
        - !Ref Jonalyn
        - !Ref Lea
        - !Ref Maricar
        - !Ref MartinLouie
        - !Ref Patty
        - !Ref Randjae
        - !Ref Raphael
        - !Ref Ronald

  #
  # Groups
  #

  # oDoo Admin Group
  OdooAdministratorsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: OdooAdmin
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess
      Policies:
        - 
          PolicyName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], odoo-admin-policy]]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - 
                Sid: AssumeRole
                Effect: Allow
                Action: 
                  - sts:AssumeRole
                Resource: "arn:aws:iam::178070162686:role/iscale-hosting-prd-uw2-odoo-admin-role"
              - 
                Sid: InvokeOdooFunctions
                Effect: Allow
                Action: 
                  - lambda:InvokeFunction
                Resource: 
                  - arn:aws:lambda:us-west-2:338284463834:function:iscale-dev-dev-uw2-odoo-scheduler

  # oDoo User Group
  OdooUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Odoo
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess
      Policies:
        - PolicyName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], odoo-admin-policy]]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AssumeRole
                Effect: Allow
                Action: 
                  - sts:AssumeRole
                Resource: "*" #user can switch to any role
              - Sid: InvokeOdooFunctions
                Effect: Allow
                Action: 
                  - lambda:InvokeFunction
                Resource: 
                  - arn:aws:lambda:us-west-2:338284463834:function:iscale-dev-dev-uw2-odoo-scheduler

  # Multi-Factor Authentication Group
  MFAUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: MFA
      Policies:
        - 
          PolicyName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], mfa-user-policy]]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - 
                Sid: AllowAllUsersToListAccounts
                Effect: Allow
                Action: 
                  - iam:ListAccountAliases
                  - iam:ListVirtualMFADevices
                  - iam:GetAccountPasswordPolicy
                Resource: "*"
              - 
                Sid: AllowIndividualUserToSeeAndManageOnlyTheirOwnAccountInformation
                Effect: Allow
                Action: 
                  - iam:ChangePassword
                  - iam:CreateAccessKey
                  - iam:CreateLoginProfile
                  - iam:DeleteAccessKey
                  - iam:DeleteLoginProfile
                  - iam:GetLoginProfile
                  - iam:ListAccessKeys
                  - iam:UpdateAccessKey
                  - iam:UpdateLoginProfile
                  - iam:ListServiceSpecificCredentials
                  - iam:ListSigningCertificates
                  - iam:DeleteSigningCertificate
                  - iam:UpdateSigningCertificate
                  - iam:UploadSigningCertificate
                  - iam:ListSSHPublicKeys
                  - iam:GetSSHPublicKey
                  - iam:DeleteSSHPublicKey
                  - iam:UpdateSSHPublicKey
                  - iam:UploadSSHPublicKey
                  - iam:GetUser
                Resource: 
                  - "arn:aws:iam::*:user/${aws:username}"
              - 
                Sid: AllowIndividualUserToViewAndManageTheirOwnMFA
                Effect: Allow
                Action: 
                  - iam:CreateVirtualMFADevice
                  - iam:DeleteVirtualMFADevice
                  - iam:EnableMFADevice
                  - iam:ListMFADevices
                  - iam:ResyncMFADevice
                Resource: 
                  - "arn:aws:iam::*:user/${aws:username}"
                  - "arn:aws:iam::*:mfa/${aws:username}"
              - 
                Sid: AllowIndividualUserToDeactivateOnlyTheirOwnMFAOnlyWhenUsingMFA
                Effect: Allow
                Action: 
                  - iam:DeactivateMFADevice
                Resource: 
                  - "arn:aws:iam::*:user/${aws:username}"
                  - "arn:aws:iam::*:mfa/${aws:username}"
                Condition:
                  Bool:
                    aws:MultiFactorAuthPresent: true
              - 
                Sid: BlockMostAccessUnlessSignedInWithMFA
                Effect: Deny
                NotAction: 
                  - iam:CreateVirtualMFADevice
                  - iam:DeleteVirtualMFADevice
                  - iam:ListVirtualMFADevices
                  - iam:EnableMFADevice
                  - iam:ResyncMFADevice
                  - iam:ListAccountAliases
                  - iam:ListSSHPublicKeys
                  - iam:ListAccessKeys
                  - iam:ListServiceSpecificCredentials
                  - iam:ListMFADevices
                  - iam:GetAccountSummary
                  - sts:GetSessionToken
                  - iam:GetUser
                  - lambda:Get*
                  - lambda:List*
                Resource: '*'
                Condition:
                  BoolIfExists:
                    aws:MultiFactorAuthPresent: false

  AdministratorsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Administrators
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  # Read-Only Group
  ReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: ReadOnly
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      Policies:
        - 
          PolicyName: AllowPasswordChange
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - 
                Sid: ViewPasswordPolicy
                Effect: Allow
                Action: iam:GetAccountPasswordPolicy
                Resource: '*'
              - 
                Sid: ChangePassword
                Effect: Allow
                Action: iam:ChangePassword
                Resource: !Join [ ':', [ 'arn:aws:iam:', !Ref 'AWS::AccountId', 'user/${aws:username}']]

####
# Roles
####

  # OdooAdminRole:
  #   DependsOn: OdooAdministratorsGroup
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - 
  #           Sid: "1"
  #           Effect: "Allow"
  #           Action: "sts:AssumeRole"
  #           Principal:
  #             AWS: !Join ['',['arn:aws:iam::',!Ref 'AWS::AccountId', ':group/', !Ref OdooAdministratorsGroup]]
  #     Tags:
  #       - 
  #         Key: Name
  #         Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], payroll-odoo-admin-policy]]
  #       - 
  #         Key: Environment
  #         Value: !Ref EnvName
  #       - 
  #         Key: Organization
  #         Value: !Ref OrgName
        
  # OdooUserRole:
  #   DependsOn: OdooUserGroup
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - 
  #           Sid: "1"
  #           Effect: "Allow"
  #           Action: "sts:AssumeRole"
  #           Principal:
  #             AWS: !Join ['',['arn:aws:iam::',!Ref 'AWS::AccountId', ':group/', !Ref OdooUserGroup]]
  #     Tags:
  #       - 
  #         Key: Name
  #         Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], payroll-odoo-user-policy]]
  #       - 
  #         Key: Environment
  #         Value: !Ref EnvName
  #       - 
  #         Key: Organization
  #         Value: !Ref OrgName