AWSTemplateFormatVersion: 2010-09-09
Description: DSAPP-CICS VPC Peering
Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Requester VPC
        Parameters:
          - RequesterNetworkStackName
      - Label:
          default: Target VPC
        Parameters:
          - TargetNetworkStackName
      - Label:
          default: Stacks
        Parameters:
          - DSAPPStackName
          - CICSStackName
    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      CICSStackName:
        default: CICS Stack Name
      DSAPPStackName:
        default: DSAPP Stack Name
      RequesterNetworkStackName:
        default: Requester VPC network stack name
      TargetNetworkStackName:
        default: Target VPC network stack name

Parameters: 
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: dsapp-cics
    MinLength: 3
    MaxLength: 20
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: pchc
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 12
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  RequesterNetworkStackName:
    Description: The name of the network stack for requester VPC
    Type: String
    Default: pchc-prd-ase1-dsapp-network
    MinLength: 1
  TargetNetworkStackName:
    Description: The name of the network stack for target VPC
    Type: String
    Default: pchc-prd-ase1-cics-network
    MinLength: 1
  DSAPPStackName:
    Description: The name of the DSAPP stack name
    Type: String
    Default: pchc-prd-ase1-dsapp
    MinLength: 1
  CICSStackName:
    Description: The name of the CICS  stack name
    Type: String
    Default: pchc-prd-ase1-cics
    MinLength: 1

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# VPC Peering
####

  VPCPeeringToCICSNetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/vpc-peering.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName

        # Requester VPC DSAPP
        RequesterVpcId: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-VpcId'
        RequesterCidr: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-VpcCidrBlock'
        RequesterPublicRouteTable: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-PublicRouteTable'
        RequesterPrivateRouteTable1: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-PrivateRouteTable1'
        RequesterPrivateRouteTable2: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-PrivateRouteTable2'

        # Target VPC CICS
        TargetVpcId: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-VpcId'
        TargetCidr: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-VpcCidrBlock'
        TargetPublicRouteTable: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-PublicRouteTable'
        TargetInternalRouteTable1: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-InternalRouteTable1'
        TargetInternalRouteTable2: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-InternalRouteTable2'
        TargetPrivateRouteTable1: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-PrivateRouteTable1'
        TargetPrivateRouteTable2: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-PrivateRouteTable2'
        TargetPrivateRouteTable3: !ImportValue
          'Fn::Sub': '${TargetNetworkStackName}-PrivateRouteTable3'

##
# DSAPP - CICS connection update secgroup
##

  CICSDBFromMAWSAppSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId: !ImportValue
        'Fn::Sub': '${CICSStackName}-DBSecurityGroup'
      IpProtocol: TCP
      FromPort: !ImportValue
        'Fn::Sub': '${CICSStackName}-DBPort'
      ToPort: !ImportValue
        'Fn::Sub': '${CICSStackName}-DBPort'
      SourceSecurityGroupId: !ImportValue
        'Fn::Sub': '${MAWSStackName}-AppServerSecurityGroup'
  
  # Allow MAWS App Servers to connect to CICS Fileshare
  CICSShareFromMAWSAppSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId: !ImportValue
        'Fn::Sub': '${CICSStackName}-CICSAPPSVRSecurityGroup'
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId: !ImportValue
        'Fn::Sub': '${MAWSStackName}-AppServerSecurityGroup'