AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for esportmasterclass.com

Parameters:
  Name:
    Description: Unique name/identifier
    Type: String
    Default: dns
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization
    Type: String
    Default: esport
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
  DomainName:
    Description: The domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: esportmasterclass.com

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref DomainName]]
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], hostedzone]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  DomainMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: MX Record
      Name: !Ref DomainName
      Type: MX
      TTL: 14400
      ResourceRecords:
        - 0 esportmasterclass-com.mail.protection.outlook.com.
  
  AutoDiscoverCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: Autodiscover CNAME record
      Name: !Join ['.', [autodiscover, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - autodiscover.outlook.com.
  
  SipCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: Sip CNAME record
      Name: !Join ['.', [sip, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - sipdir.online.lync.com.
  
  LyncDiscoverCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: LyncDiscover CNAME record
      Name: !Join ['.', [lyncdiscover, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - webdir.online.lync.com.
  
  EnterpriseRegistrationCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: EnterpriseRegistration CNAME record
      Name: !Join ['.', [enterpriseregistration, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - enterpriseregistration.windows.net.
  
  EnterpriseEnrollmentCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: EnterpriseEnrollment CNAME record
      Name: !Join ['.', [enterpriseenrollment, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - enterpriseenrollment.manage.windows.com.
  
  DomainTxtRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: Outlook verification TXT record
      Name: !Join ['.', ['@', !Ref DomainName]]
      Type: TXT
      TTL: 14400
      ResourceRecords:
        - '"v=spf1 include:spf.protection.outlook.com -all"'
  
  SESDKIMRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[a66ugoc6ri4ttjtjbrslphp6yp4brsqs._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - a66ugoc6ri4ttjtjbrslphp6yp4brsqs.dkim.amazonses.com

  SESDKIMRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[fozanlmp6owl7jfkcbt4arjp36r3dc3v._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - fozanlmp6owl7jfkcbt4arjp36r3dc3v.dkim.amazonses.com

  SESDKIMRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[nhmygd2bdrtntuj2b7dla5zkjx55s2kc._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - nhmygd2bdrtntuj2b7dla5zkjx55s2kc.dkim.amazonses.com

  SESTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: SES verification TXT record
      Name: !Join ['.', ['_amazonses', !Ref DomainName]]
      Type: TXT
      TTL: 14400
      ResourceRecords:
        - '"HVER+nf14SKSTI6qr048/oOXGqkQgeL8CUNDcjp0Z6M="'

  SipTlsSRVRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: HostedZone
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: _sip.tls SRV Record
      Name: !Join ['.', [_sip, tls, !Ref DomainName]]
      Type: SRV
      TTL: 14400
      ResourceRecords:
        - 100 1 443 sipdir.online.lync.com.
  
  SipFedSRVRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: HostedZone
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: _sipfederationtls._tcp SRV Record
      Name: !Join ['.', [_sipfederationtls, _tcp, !Ref DomainName]]
      Type: SRV
      TTL: 14400
      ResourceRecords:
        - 100 1 5061 sipfed.online.lync.com.

  WildcardSSLValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_b86f7bac633b55c327006a0bd8099c32, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - _ec684b53d51ba58db1737af678c16207.ltfvzjuylp.acm-validations.aws.

  ##
  # DNSSEC
  ##

  # HostedZoneDNSSECSigningKey:
  #   Type: AWS::Route53::KeySigningKey
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
  #     Name: key_signing_key
  #     Status: ACTIVE

  # HostedZoneDNSSEC:
  #   DependsOn: HostedZoneDNSSECSigningKey
  #   Type: AWS::Route53::DNSSEC
  #   Properties:
  #     HostedZoneId: !Ref HostedZone