AWSTemplateFormatVersion: 2010-09-09
Description: IAM Setting for Anchanto Dev

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 8
    Default: iam
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: anchanto
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  DeveloperGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Developer
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess
        - arn:aws:iam::aws:policy/AwsGlueDataBrewFullAccessPolicy

  PreetIAMUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: preet.kumar@anchanto.com
      Groups: 
        - !Ref DeveloperGroup

  RajreetIAMUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: rajreet.sarkar@anchanto.com
      Groups: 
        - !Ref DeveloperGroup

  SouravIAMUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: sourav.prasad@anchanto.com
      Groups: 
        - !Ref DeveloperGroup

  VarunIAMUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: varun.teja@anchanto.com
      Groups: 
        - !Ref DeveloperGroup
