AWSTemplateFormatVersion: 2010-09-09
Description: CloudCFO Resources

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      -
        Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName
          - LoadBalancerStackName
      -
        Label:
          default: Load Balancer Configuration
        Parameters:
          - ClientDomainName
          - LoadBalancerPriority
          - LoadBalancerHostName
      -
        Label:
          default: Instance Configuration
        Parameters:
          - InstanceKeyName
          - InstanceAMI
      -
        Label:
          default: Scheduler Configuration
        Parameters:
          - StartScheduleExpression
          - StopScheduleExpression

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      InstanceAMI:
        default: Instance AMI ID
      InstanceKeyName:
        default: Instance Key Name
      LoadBalancerHostName:
        default: Load Balancer Host Name
      LoadBalancerPriority:
        default: Load Balancer Rule Priority
      LoadBalancerStackName:
        default: Load Balancer Stack Name
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Topic Stack Name
      ClientDomainName:
        default: Domain Name
      StartScheduleExpression:
        default: Start Schedule CRON Expression
      StopScheduleExpression:
        default: Stop Schedule CRON Expression

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 9
    Default: app
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: cloudcfo
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Staging
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-software.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: cloudcfo.co
    MinLength: 1
  InstanceAMI:
    Description: Instance AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-02add6d4c1211485b
  InstanceKeyName:
    Description: Instance Key Name
    Type: String
    Default: ''
  LoadBalancerHostName:
    Description: (Optional) Custom Hostname for load balancer URL
    Type: String
    Default: app
    MaxLength: 12
  LoadBalancerPriority:
    Description: The priority for ELB Listener.
    Type: Number
    Default: 100
    MinValue: 1
    MaxValue: 50000
  LoadBalancerStackName:
    Description: The name of the load balancer stack.
    Type: String
    Default: cloudcfo-stg-uw2-alb
    MinLength: 1
  MaintenanceWebsiteCertificate:
    Description: Maintenance site certificate (For Prod Only)
    Type: String
    Default: arn:aws:acm:us-east-1:880804344419:certificate/61fe97b2-2645-4112-825d-51b69e5c8f58
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: cloudcfo-stg-uw2-network
    MinLength: 1
  SNSStackName:
    Description: The name of the SNS stack.
    Type: String
    Default: cloudcfo-prd-uw2-sns
    MinLength: 1
  StartScheduleExpression:
    Description: Schedule expression when to start the objects
    Type: String
    Default: cron(0 0 ? * MON-FRI *)
  StopScheduleExpression:
    Description: Schedule expression when to stop the objects
    Type: String
    Default: cron(0 10 ? * MON-FRI *)

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
      
Resources:

  DBStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/database.yaml
      Parameters: 
        Name: !Ref Name
        DatabaseName: !Join ['',[!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name], db]]
        AllocatedStorage: 20 #Gb
        BackupRetentionPeriod: !If [IsProd, 30, 7]
        EnableCPUCreditAlarm: !If [IsProd, true, false]
        EnableEnhancedMonitoring: !If [IsProd, true, false]
        EnablePerformanceInsights: !If [IsProd, true, false]
        EnvName: !Ref EnvName
        Engine: mysql
        EngineVersion: 8.0.20
        Family: mysql8.0
        InstanceType: !If [IsProd, db.t3.medium, db.t3.micro]
        MasterUser: root
        MultiAz: !If [IsProd, true, false]
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        SNSStackName: !Ref SNSStackName
        StorageEncrypted: true

  # DeployStack: 
  #   Type: AWS::CloudFormation::Stack
  #   Properties: 
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/deployment.yaml
  #     Parameters: 
  #       Name: !Ref Name
  #       EnvName: !Ref EnvName
  #       OrgName: !Ref OrgName
  #       NetworkStackName: !Ref NetworkStackName
  #       SNSStackName: !Ref SNSStackName
  
  AppServerStack: 
    DependsOn: 
      - DBStack
      # - DeployStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/appserver-basic.yaml
      Parameters: 
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        InstanceAMI: !Ref InstanceAMI
        InstanceKeyName: !Ref InstanceKeyName
        InstanceOS: Ubuntu
        InstancePort: 8080
        InstanceType: !If [IsProd, t3.medium, t3.small]
        LoadBalancerHostName: !If [IsProd, !Ref LoadBalancerHostName, !Ref 'AWS::NoValue']
        LoadBalancerPriority: !Ref LoadBalancerPriority
        DatabaseEndpoint: 
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstanceAddress
        DatabasePort: 
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstancePort
        DatabaseSecurityGroupId:
          Fn::GetAtt:
            - DBStack
            - Outputs.SecurityGroupId
        LoadBalancerStackName: !Ref LoadBalancerStackName
        SNSStackName: !Ref SNSStackName
        NetworkStackName: !Ref NetworkStackName
        ClientDomainName: !Ref ClientDomainName

  BackupStack:
    DependsOn: 
      - DBStack
      - AppServerStack
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/backup.yaml
      Parameters: 
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        BackupARNList: !Join
          - ','
          - - Fn::GetAtt:
              - DBStack
              - Outputs.DBInstanceARN
            - Fn::GetAtt:
              - AppServerStack
              - Outputs.AppServerEFSArn

  SchedulerStack: 
    DependsOn: 
      - DBStack
      - AppServerStack
    Condition: IsNotProd
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
      Parameters: 
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        StartScheduleExpression: !Ref StartScheduleExpression
        StopScheduleExpression: !Ref StopScheduleExpression
        UseFriendlyNames: TRUE
        DatabaseInstanceArn:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBInstanceARN
        # CodeDeployApplicationName:
        #   Fn::GetAtt:
        #     - DeployStack
        #     - Outputs.CodeDeployApplicationName
        # CodeDeployDeploymentGroupName:
        #   Fn::GetAtt:
        #     - DeployStack
        #     - Outputs.CodeDeployDeploymentGroupName

  ####
  #  Maintenance section
  ####
  MaintenanceBucket:
    Condition: IsProd
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], maintenance]]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
      Tags:
        -
          Key: Name
          Value: !Join [ '-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], maintenance]]
        -
          Key: Organization
          Value: !Ref OrgName

  MaintenanceBucketPolicy:
    Condition: IsProd
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref MaintenanceBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForMaintenance
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ["/",[!GetAtt MaintenanceBucket.Arn,"*"]]

####
# CloudFront Section
####

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Condition: IsProd
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "CloudFront Access to the S3 static origin"

  MaintenanceWebsiteCloudFront:
    Type: AWS::CloudFront::Distribution
    Condition: IsProd
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt [MaintenanceBucket, DomainName]
          Id: S3MaintenanceBucketOrigin
          S3OriginConfig:
            OriginAccessIdentity: !Join ["", ['origin-access-identity/cloudfront/', !Ref CloudFrontOriginAccessIdentity]]
        Enabled: 'true'
        Comment: !Join [" ", [ "Maintenance page for", !Ref ClientDomainName]]
        HttpVersion: http2
        DefaultRootObject: index.html
        Aliases:
        - !Join [".", ["maintenance", !Ref ClientDomainName]]
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: S3MaintenanceBucketOrigin
          ForwardedValues:
            QueryString: false
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 3600
          MaxTTL: 86400
        PriceClass: PriceClass_All
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: !Ref MaintenanceWebsiteCertificate

  MaintenanceCNAMERecord:
    Type: AWS::Route53::RecordSet
    Condition: IsProd
    Properties:
      HostedZoneName: !Join ['', [!Ref ClientDomainName, '.']]
      Name: !Join [".", ["maintenance", !Ref ClientDomainName]]
      Type: CNAME
      TTL: 300
      Comment: "Maintenance Site"
      ResourceRecords:
        - Fn::GetAtt:
          - MaintenanceWebsiteCloudFront
          - DomainName

# Outputs:
#   DeploymentUserGroup:
#     Description: Add the BitBucket user into this group
#     Value: 
#       Fn::GetAtt:
#         - DeployStack
#         - Outputs.DeploymentUserGroup
