AWSTemplateFormatVersion: 2010-09-09
Description: CloudCFO IAM related resources

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName
    ParameterLabels:
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: cloudcfo
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  DeveloperAccountAccessRole:
    DeletionPolicy: Retain
    Type: AWS::IAM::Role
    Properties:
      Description: Developer Access to the account
      RoleName: DeveloperAccountAccessRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/AutoScalingFullAccess
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AdministratorAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AmazonVPCFullAccess
        - arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AmazonOpenSearchServiceFullAccess
      Policies:
        - PolicyName: AllowAccessIntoUSEast1
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:*
                  - rds:*
                  - s3:*
                  - cloudformation:*
                Resource: '*'
                Condition:
                  StringEquals:
                    aws:RequestedRegion: us-east-1
        - PolicyName: Route53-SES-SNS-SQS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sns:*
                  - ses:*
                  - route53:*
                  - sqs:*
                Resource: '*'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - arn:aws:iam::338284463834:user/ceseng@iscale-solutions.com
                - arn:aws:iam::338284463834:user/ronald@iscale-solutions.com
            Action:
              - sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      Path: /

  VasIAMUser:
    DeletionPolicy: Retain
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: vas123! #will be reset right away
        PasswordResetRequired: true
      UserName: vas@cloudcfo.ph
      Groups:
        - Administrators