AWSTemplateFormatVersion: 2010-09-09
Description: Basic DNS records for cloufcfo.ph

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: cloudcfo
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: cloudcfo
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: cloudcfo.ph

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZoneStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/hostedzone.yaml
      Parameters: 
        Name: !Ref Name
        OrgName: !Ref OrgName
        EnvName: !Ref EnvName
        DomainName: !Ref DomainName

  AdminRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[admin, !Ref DomainName]]
      ResourceRecords:
      - 148.66.136.59
      TTL: 14400
      Type: A

  MailRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[mail, !Ref DomainName]]
      ResourceRecords:
      - 148.66.136.59
      TTL: 14400
      Type: A

  CPanelRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[cpanel, !Ref DomainName]]
      ResourceRecords:
      - 148.66.136.59
      TTL: 14400
      Type: A

  FTPRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[ftp, !Ref DomainName]]
      ResourceRecords:
      - 148.66.136.59
      TTL: 14400
      Type: A

  WebDiskRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[webdisk, !Ref DomainName]]
      ResourceRecords:
      - 148.66.136.59
      TTL: 14400
      Type: A

  WebDiskAdminRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[webdisk, admin, !Ref DomainName]]
      ResourceRecords:
      - 148.66.136.59
      TTL: 14400
      Type: A

  WHMRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[whm, !Ref DomainName]]
      ResourceRecords:
      - 148.66.136.59
      TTL: 14400
      Type: A

  WWWRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[www, !Ref DomainName]]
      ResourceRecords:
      - 148.66.136.59
      TTL: 14400
      Type: A

  NoWWWRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Ref DomainName
      ResourceRecords:
      - 148.66.136.59
      TTL: 14400
      Type: A

  WWWAdminRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[www, admin, !Ref DomainName]]
      ResourceRecords:
      - 148.66.136.59
      TTL: 14400
      Type: A

  EmailRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[email, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
      - email.secureserver.net

  AppCertificateRecordForMobbiz: #To be deleted after migration to CloudCFO account
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[_41e507b253a2253f0d4c2ef47607b023, app, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
      - _4873a58d534d22f770772940488a2db5.vhzmpjdqfx.acm-validations.aws

  AppCertificateRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[_d4028c3281930df9b47193b3f76d4d62, app, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
      - _1fb8032739448e3415a4a41fca6d82cf.bsgbmzkfwj.acm-validations.aws.

  WildcardCertificateRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[_91f93dc46f41713994bb6ed5f95aee23, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
      - _95c6df230bb8b83e2a4b3ec002447408.bsgbmzkfwj.acm-validations.aws.

  MaintenanceCertificateRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[_e7b22c22cbbef4b8dc45fe76a8f40d1b, maintenance, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
      - _b11307e6f8e5a0e2c038a0b5240a8e3c.bsgbmzkfwj.acm-validations.aws.

  GoogleDomainConnectRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[_domainconnect, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
      - _domainconnect.gd.domaincontrol.com

  GSuiteMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Comment: Google Suite MX Records
      Name: !Ref DomainName
      Type: MX
      TTL: 3600
      ResourceRecords:
        - 1 aspmx.l.google.com.
        - 10 aspmx2.googlemail.com.
        - 10 aspmx3.googlemail.com.
        - 5 alt1.aspmx.l.google.com.
        - 5 alt2.aspmx.l.google.com.

  CombinedTxtRecord: 
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Comment: Google Verification TXT Record
      Name: !Ref DomainName
      Type: TXT
      TTL: 14400
      ResourceRecords:
        - '"google-site-verification=ZSpkJgth-jXIYXY0DkqVnzPomaXjOceaG2pHJZ8O7cg"'
        - '"=spf1 include:_spf.google.com ~all"'

  AcmeChallengeTxtRecord: 
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Comment: TXT Verification Record
      Name: !Join ['.',[_acme-challenge, app, !Ref DomainName]]
      Type: TXT
      TTL: 14400
      ResourceRecords:
        - '"WqLg1IZFTwRU3Ljsrcu8uNgiaTtH_wE_bSGkcUueUS0"'

  AmazonSESRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[_amazonses, !Ref DomainName]]
      ResourceRecords: 
        - '"t9rhYnN75y9hA/rxRNdcff51s6xtiKtdj+c9HNO4UuA="'
      TTL: 14400
      Type: TXT
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], amazon-ses]]

  SESDKIMRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[e6ym6xdvz5v27hkjb3jdi5gbmikpt7k6._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - e6ym6xdvz5v27hkjb3jdi5gbmikpt7k6.dkim.amazonses.com
  
  SESDKIMRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[kv2dpnmn5rhuer5t5o552aad22h2ekn3._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - kv2dpnmn5rhuer5t5o552aad22h2ekn3.dkim.amazonses.com

  SESDKIMRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[vq5fbuc4xbd7dh4euwkklsffo5hs23wb._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - vq5fbuc4xbd7dh4euwkklsffo5hs23wb.dkim.amazonses.com
