AWSTemplateFormatVersion: 2010-09-09
Description: Basic DNS records for cloufcfo.co

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: cloudcfo
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: cloudcfo
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Staging
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: cloudcfo.co

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  HostedZoneStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/hostedzone.yaml
      Parameters: 
        Name: !Ref Name
        OrgName: !Ref OrgName
        EnvName: !Ref EnvName
        DomainName: !Ref DomainName

  AppCertificateRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[_9410043d978e638e4becabf224f66e3e, app-stg, !Ref DomainName]]
      Type: CNAME
      TTL: 300
      ResourceRecords:
      - _75b5c084cf80bab9696515564e97afe5.bsgbmzkfwj.acm-validations.aws