AWSTemplateFormatVersion: 2010-09-09
Description: Basic DNS records for cloufcfo.co

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: cloudcfo
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: cloudcfo
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Staging
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: cloudcfo.co

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  HostedZoneStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/hostedzone.yaml
      Parameters:
        Name: !Ref Name
        OrgName: !Ref OrgName
        EnvName: !Ref EnvName
        DomainName: !Ref DomainName

  AppCertificateRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[_9410043d978e638e4becabf224f66e3e, app-stg, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
      - _75b5c084cf80bab9696515564e97afe5.bsgbmzkfwj.acm-validations.aws

  AmazonSESRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[_amazonses, !Ref DomainName]]
      ResourceRecords: 
        - '"IP6t1xUS9VFYPWBDnPLwzqCE12VC/dHrNVqpsif3SCo="'
      TTL: 14400
      Type: TXT
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], amazon-ses]]

  SESDKIMRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[ov5rdowfsfgafjo3nuehvfttgnnndnka._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - ov5rdowfsfgafjo3nuehvfttgnnndnka.dkim.amazonses.com
  
  SESDKIMRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[zcvc2n7awaosm3qfpupdneprrhugaj6g._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - zcvc2n7awaosm3qfpupdneprrhugaj6g.dkim.amazonses.com

  SESDKIMRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[25l7tzelp2ifafhm45hfi5kpzhhu3wfi._domainkey, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
        - 25l7tzelp2ifafhm45hfi5kpzhhu3wfi.dkim.amazonses.com
  
  WildcardCertificateRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::GetAtt:
          - HostedZoneStack
          - Outputs.HostedZoneId
      Name: !Join ['.',[_06abbd458b4a5638280dbff0dcfb3d0f, !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      ResourceRecords:
      - _d69489b8bd84226bc4f09a3b73b22591.jddtvkljgg.acm-validations.aws.