AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions resources for Edia

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - DatabaseStackName
          - NetworkStackName
          - SNSStackName
          - LoadBalancerStackName
          - SharedSecretId
      - Label:
          default: Load Balancer Configuration
        Parameters:
          - ClientDomainName
          - LoadBalancerHostName
          - LoadBalancerPriority
      - Label:
          default: Instance Configuration
        Parameters:
          - InstanceKeyName
          - InstanceAMI
      - Label:
          default: Scheduler Configuration
        Parameters:
          - StartScheduleExpression
          - StopScheduleExpression
      - Label:
          default: Magento Repository Access
        Parameters:
          - MagentoPublicKey
          - MagentoPrivateKey

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      DatabaseStackName:
        default: Database Stack Name
      LoadBalancerPriority:
        default: Load Balancer Rule Priority
      LoadBalancerStackName:
        default: Load Balancer Stack Name
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Topic Stack Name
      ClientDomainName:
        default: Domain Name
      InstanceKeyName:
        default: Instance Key Name
      InstanceAMI:
        default: Instance AMI
      LoadBalancerHostName:
        default: Load Balancer Hostname
      MagentoPublicKey:
        default: Magento Public Key
      MagentoPrivateKey:
        default: Magento Private Key
      SharedSecretId:
        default: Shared secret id (only use for prod, else leave blank)
      StartScheduleExpression:
        default: Start Schedule CRON Expression
      StopScheduleExpression:
        default: Stop Schedule CRON Expression

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Staging
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-software.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: iscale-software.com
    MinLength: 1
  DatabaseStackName:
    Description: Database Stack Name (leave blank to create own DB Stack)
    Type: String
    Default: ''
  InstanceAMI:
    Description: Instance AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-0528a5175983e7f28 #Basic Amazon Linux AMI
  InstanceKeyName:
    Description: Instance Key Name
    Type: String
    Default: ''
  LoadBalancerHostName:
    Description: ELB Host Name (will be added to DNS)
    Type: String
    Default: ''
  LoadBalancerPriority:
    Description: The priority for ELB Listener.
    Type: Number
    Default: 100
    MinValue: 1
    MaxValue: 50000
  MagentoPublicKey:
    NoEcho: true
    Description: Magento Repository Public Key
    Type: String
    MinLength: 1
  MagentoPrivateKey:
    NoEcho: true
    Description: Magento Repository Private Key
    Type: String
    MinLength: 1
  LoadBalancerStackName:
    Description: THe name of the load balancer stack.
    Type: String
    Default: iscale-dev-stg-uw2-alb
    MinLength: 1
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: iscale-dev-dev-uw2-network
    MinLength: 1
  SharedSecretId:
    Description: Name of the secret Id to use. Can leave blank for default.
    Type: String
    Default: edia-prd-uw2-shop
  SNSStackName:
    Description: the name of the SNS stack.
    Type: String
    Default: iscale-dev-dev-uw2-sns
    MinLength: 1
  StartScheduleExpression:
    Description: Schedule expression when to start the objects
    Type: String
    Default: cron(0 0 ? * MON-FRI *)
  StopScheduleExpression:
    Description: Schedule expression when to stop the objects
    Type: String
    Default: cron(0 10 ? * MON-FRI *)

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  HasExternalDBStack: !Not [!Equals [!Ref DatabaseStackName, '']]
  HasOwnDBStack: !Not [!Condition HasExternalDBStack]

Resources:

  DBStack:
    Condition: HasOwnDBStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/database.yaml
      Parameters:
        Name: !Ref Name
        DatabaseName: !Join ['',[!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name]]]
        EnableCPUCreditAlarm: true
        EnableEnhancedMonitoring: true
        EnvName: !Ref EnvName
        Engine: aurora-mysql
        EngineVersion: 5.7.mysql_aurora.2.09.1
        Family: aurora-mysql5.7
        InstanceType: db.t3.small
        MasterUser: root
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        SNSStackName: !Ref SNSStackName
        StorageEncrypted: true

  DeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/deployment.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName
  
  AppServerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/appserver-magento.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        LoadBalancerPriority: !Ref LoadBalancerPriority
        DatabaseClusterARN: !If
          - HasExternalDBStack
          - Fn::ImportValue:
              !Sub "${DatabaseStackName}-ClusterArn"
          - Fn::GetAtt:
            - DBStack
            - Outputs.DBClusterARN
        DatabaseEndpoint: !If
          - HasExternalDBStack
          - Fn::ImportValue:
              !Sub "${DatabaseStackName}-ClusterEndpointAddress"
          - Fn::GetAtt:
            - DBStack
            - Outputs.ClusterEndpointAddress
        DatabasePort: !If
          - HasExternalDBStack
          - Fn::ImportValue:
              !Sub "${DatabaseStackName}-ClusterPort"
          - Fn::GetAtt:
            - DBStack
            - Outputs.ClusterPort
        DatabaseSecurityGroupId: !If
          - HasExternalDBStack
          - Fn::ImportValue:
              !Sub "${DatabaseStackName}-SecurityGroupId"
          - Fn::GetAtt:
            - DBStack
            - Outputs.SecurityGroupId
        LoadBalancerHostName: !Ref LoadBalancerHostName
        LoadBalancerStackName: !Ref LoadBalancerStackName
        InstanceAMI: !Ref InstanceAMI
        InstanceKeyName: !Ref InstanceKeyName
        InstanceSpotPrice: 0.5
        InstanceType: t3.medium
        SNSStackName: !Ref SNSStackName
        NetworkStackName: !Ref NetworkStackName
        ClientDomainName: !Ref ClientDomainName
        MagentoPublicKey: !Ref MagentoPublicKey
        MagentoPrivateKey: !Ref MagentoPrivateKey
        SharedSecretId: !If [IsProd, !Ref SharedSecretId, !Ref 'AWS::NoValue']
        UseFriendlyNames: FALSE

  BackupStack:
    Condition: HasOwnDBStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/backup.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        BackupARNList: !Join
          - ','
          - - Fn::GetAtt:
              - DBStack
              - Outputs.DBClusterARN
            - Fn::GetAtt:
              - AppServerStack
              - Outputs.AppServerEFSArn

  SchedulerStack:
    Condition: IsNotProd
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        StartScheduleExpression: !Ref StartScheduleExpression
        StopScheduleExpression: !Ref StopScheduleExpression
        UseFriendlyNames: TRUE
        DatabaseClusterArn:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBClusterARN
        CodeDeployApplicationName:
          Fn::GetAtt:
            - DeployStack
            - Outputs.CodeDeployApplicationName
        CodeDeployDeploymentGroupName:
          Fn::GetAtt:
            - DeployStack
            - Outputs.CodeDeployDeploymentGroupName

  HostedZone: 
    Condition: IsProd
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[INACTIVE Hosted Zone for, !Ref ClientDomainName]]
      Name: !Ref ClientDomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], hostedzone]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

Outputs:
  DeploymentUserGroup:
    Description: Add the BitBucket user into this group
    Value:
      Fn::GetAtt:
        - DeployStack
        - Outputs.DeploymentUserGroup