AWSTemplateFormatVersion: 2010-09-09
Description: IAM Resources for employ

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: iam
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: employ
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  OdooMaintenanceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      RoleName: OdooMaintenanceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - arn:aws:iam::924893643129:user/dennis@iscale-solutions.com
                - arn:aws:iam::338284463834:user/ceseng@iscale-solutions.com
            Action:
              - sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      Policies:
        - PolicyName: PipelineApproval
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - codepipeline:PutApprovalResult
                Resource: 
                  - !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:*employ*/Approval/Approval'
        - PolicyName: SSMAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: TerminateSSM
                Effect: Allow
                Action:
                  - ssm:ResumeSession
                  - ssm:TerminateSession
                Resource:
                  - arn:aws:ssm:*:*:session/${aws:username}-*
              - Effect: Allow
                Action:
                  - ssm:StartSession
                Resource: !Sub 'arn:aws:ec2:*:${AWS::AccountId}:instance/*'
                Condition:
                  StringEquals:
                    ssm:resourceTag/Name: employ-prd-uw2-odoo

  AccessToVolendraSharedS3:
    Type:  AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: AccessToVolendraSharedS3
      Roles:
        - !Ref OdooMaintenanceRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - arn:aws:s3:::volendra-s3-shared
              - arn:aws:s3:::volendra-s3-shared/*
