AWSTemplateFormatVersion: 2010-09-09
Description: This  template provisions basic details for a customer AWS account

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: Resource Configuration
        Parameters:
          - OrgName
      - 
        Label:
          default: User Roles
        Parameters:
          - AdminUsers
          - CreateReadOnlyUsers
          - ReadOnlyUsers
    
    ParameterLabels:
      AdminUsers:
        default: Administrators
      OrgName:
        default: Organization Name
      ReadOnlyUsers:
        default: Read-Only Users

Parameters:
  
  AdminUsers:
    Description: List of account Administrators
    Type: CommaDelimitedList
    Default: "arn:aws:iam::383761724374:user/iannis@iscale-solutions.com, arn:aws:iam::338284463834:user/jean.emmanuel@iscale-solutions.com"
  
  CreateReadOnlyUsers:
    Description: Set to true to specify read only users
    Default: false
    Type: String
    AllowedValues: [true, false]

  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  
  ReadOnlyUsers:
    Description: List of Read-Only Users
    Type: CommaDelimitedList
    Default: ''

Conditions:
  ShouldCreateReadOnlyUsers: !Equals [true, !Ref CreateReadOnlyUsers]

Resources:

  S3Bucket: 
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', [!Ref OrgName, 'cloudtrail']]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 3
          Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Join [ '-', [!Ref OrgName , cloudtrail]]
        - Key: Organization
          Value: !Ref OrgName
    
  S3BucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: 
        Ref: S3Bucket
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - 
            Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal: 
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: 
              !Sub |-
                arn:aws:s3:::${S3Bucket}
          - 
            Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal: 
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource:
              !Sub |-
                arn:aws:s3:::${S3Bucket}/AWSLogs/${AWS::AccountId}/*
            Condition: 
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
   
  CloudTrail:
    DeletionPolicy: Retain
    DependsOn:
      - S3BucketPolicy
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName:
        Ref: S3Bucket
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true
      TrailName: !Join ['-', [!Ref OrgName, 'trail']]

  AdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Administrators
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  BillingGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Billing
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/Billing

  ReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: ReadOnly
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess

  CloudFormationFullAccessRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role designed for CloudFormation to change anything
      RoleName: CloudFormationFullAccessRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  CloudFormationImportAccessRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role designed for CloudFormation import and guarantee that no existing resources are modified
      RoleName: CloudFormationImportAccessRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  EC2BasicSSMIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: 1
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  MasterAccountAccessRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Administrator access from trusted parties
      RoleName: MasterAccountAccessRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AdminUsers
            Action:
              - sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      Path: /

  OpsidianAccessRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Opsidian Access
      RoleName: OpsidianAccessRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::326365640391:root
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: iscale-solutions
      Path: /

  ReadOnlyAccountAccessRole:
    Condition: ShouldCreateReadOnlyUsers
    Type: AWS::IAM::Role
    Properties:
      Description: Read only access from trusted parties
      RoleName: ReadOnlyAccountAccessRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref ReadOnlyUsers
            Action:
              - sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: false
      Path: /

Outputs:
  
  CloudTrailBucket:
    Description: S3 Bucket holding the CloudTrail content
    Value: !Ref S3Bucket

  CloudTrail:
    Description: CloudTrail object
    Value: !Ref CloudTrail