AWSTemplateFormatVersion: 2010-09-09
Description: This  template provisions a basic EC2 instance with just simple env set

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName
      - Label:
          default: Cloudformation Stack Configuration
        Parameters:
          - LoadBalancerStackName
          - NetworkStackName
          - SNSStackName
          - UseFriendlyNames
      - Label:
          default: EFS Configuration
        Parameters:
          - ExternalEFSID
          - ExternalEFSSecurityGroup
      - Label:
          default: Load Balancer Configuration
        Parameters:
          - LoadBalancerPriority
          - LoadBalancerHostName
      - Label:
          default: Instance Configuration
        Parameters:
          - InstanceOS
          - InstanceAMI
          - InstancePort
          - InstanceSpotPrice
          - InstanceSubnet
          - InstanceType
      - Label:
          default: Domain Configuration
        Parameters:
          - ClientDomainName
      - Label:
          default: Database Settings
        Parameters:
          - DatabaseEndpoint
          - DatabasePort
          - DatabaseSecurityGroupId
      - Label:
          default: Shared Configuration
        Parameters:
          - SharedSecretId

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      DatabaseEndpoint:
        default: Database Endpoint
      DatabasePort:
        default: Database Port
      DatabaseSecurityGroupId:
        default: Database Security Group
      ExternalEFSID:
        default: External EFS ID
      ExternalEFSSecurityGroup:
        default: External EFS Security Group
      LoadBalancerStackName:
        default: Load Balancer Stack Name
      LoadBalancerHostName:
        default: Load Balancer Hostname
      LoadBalancerPriority:
        default: Load Balancer Priority
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Topic Stack Name
      ClientDomainName:
        default: Domain Name
      InstanceAMI:
        default: Instance AMI ID
      InstanceOS:
        default: Instance Operating System
      InstancePort:
        default: Instance Application Port
      InstanceSpotPrice:
        default: Spot price
      InstanceSubnet:
        default: Which subnet to use for the instance
      InstanceType:
        default: Instance Type
      SharedSecretId:
        default : Shared Secret Id
      UseFriendlyNames:
        default: Use Friendly Resource Names

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-software.com).
    Type: String
    Default: iscale-software.com
    MinLength: 1
  DatabaseEndpoint:
    Description: Database Endpoint
    Type: String
    MinLength: 1
  DatabasePort:
    Description: Database Port Number
    Type: Number
    MinValue: 1
    MaxValue: 65535
  DatabaseSecurityGroupId:
    Description: Database Security Group
    Type: String
    MinLength: 1
  ExternalEFSID:
    Description: EFS ID (leave blank to create appserver specific EFS)
    Type: String
    Default: ''
  ExternalEFSSecurityGroup:
    Description: EFS Security Group (Only utilized when ExternalEFSID is provided)
    Type: String
    Default: ''
  InstanceAMI:
    Description: Instance AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-0841edc20334f9287 #Basic Amazon Linux AMI
  InstanceKeyName:
    Description: Instance Key Name
    Type: String
    Default: ''
  InstanceOS:
    Description: Instance Operating System
    Type: String
    AllowedValues:
      - Amazon
      - Ubuntu
    Default: Amazon
  InstancePort:
    Description: Database Port Number
    Type: Number
    Default: 80 #Assume HTTP port as default on port 80
    MinValue: 1
    MaxValue: 65535
  InstanceSpotPrice:
    Description: Spot price to set (set to 0 to use on demand)
    Type: Number
    Default: 0
  InstanceSubnet:
    Description: Subnet to use for the instance
    Type: String
    AllowedValues:
      - Public
      - Private
    Default: Public
  InstanceType:
    Description: Instance Type
    Type: String
    Default: t3.small
  LoadBalancerHostName:
    Description: (Optional) Custom Hostname for load balancer URL
    Type: String
    Default: ''
    MaxLength: 12
  LoadBalancerPriority:
    Description: The priority for ELB Listener.
    Type: Number
    Default: 100
    MinValue: 1
    MaxValue: 50000
  LoadBalancerStackName:
    Description: (Optional) Name of the ELB Stack Name. ELB priority and HostName are ignored if this is left blank
    Type: String
    Default: ''
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 14
  NetworkStackName:
    Description: The name of the cloudformation Network stack
    Type: String
    Default: iscale-dev-dev-uw2-network
    MinLength: 1
  SNSStackName:
    Description: The name of the cloudformation SNS stack
    Type: String
    Default: iscale-dev-dev-uw2-sns
    MinLength: 1
  SharedSecretId:
    Description: Name of the secret Id to use. Can leave blank for default.
    Type: String
    Default: ''
  UseFriendlyNames:
    Description: Set to TRUE to have nice object names
    Type: String
    AllowedValues:
      - TRUE
      - FALSE
    Default: FALSE

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  HasInstanceKey: !Not [!Equals [!Ref InstanceKeyName, '']]
  HasLoadBalancerStackName: !Not [!Equals [!Ref LoadBalancerStackName, '']]
  HasLoadBalancerHostName: !Not [!Equals [!Ref LoadBalancerHostName, '']]
  HasProdLoadBalancerStackName: !And [!Condition IsProd, !Condition HasLoadBalancerStackName]
  HasSharedSecretId: !Not [!Equals [!Ref SharedSecretId, '']]
  HasSpotPrice: !Not [!Equals [!Ref InstanceSpotPrice, 0]]
  UseFriendlyNames: !Equals [!Ref UseFriendlyNames, TRUE]
  UsePrivateSubnet: !Equals [!Ref InstanceSubnet, Private]
  UseExternalEFS: !Not [!Equals [!Ref ExternalEFSID, '']]
  UseInternalEFS: !Not [!Condition UseExternalEFS]

Resources:
  
  #Include common resources for the app server (regardless of appserver type)
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/appserver.yaml
      
####
# AutoScaling Group 
####

  AppServerLaunchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata: 
      AWS::CloudFormation::Init: 
        configSets: 
          Basic: 
            - InstallCustomData
        InstallCustomData:
          files:
            /var/lib/cloud/instance/custom-data.sh: 
              content: !Sub
                - |
                  STACK_NAME=${AWS::StackName}
                  AWS_REGION=${AWS::Region}
                  DOMAIN=${DOMAIN}
                  ENVIRONMENT=${ENVIRONMENT}
                  CLIENT_NAME=${CLIENT_NAME}
                  EFS_ID=${EFS_ID}
                  APPLICATION_SITE=${APPLICATION_SITE}
                  INSTANCE_ROLE=${INSTANCE_ROLE}
                  SECRET_ID=${SECRET_ID}
                  BASE_URL=https://${DOMAIN}/
                  BUCKET_NAME=${BUCKET_NAME}
                  DB_HOST=${DB_HOST}
                  DB_PORT=${DB_PORT}
                - DOMAIN: !Join ['.', [!Join ['-',[!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name]]], !Ref ClientDomainName]]
                  ENVIRONMENT: !Ref EnvName
                  CLIENT_NAME: !Ref Name
                  APPLICATION_SITE: !Ref OrgName
                  INSTANCE_ROLE: !Ref AppServerIamRole
                  EFS_ID: !If
                    - UseInternalEFS
                    - !Ref AppServerFileSystem
                    - !Ref ExternalEFSID
                  SECRET_ID: !If
                    - HasSharedSecretId
                    - !Ref SharedSecretId
                    - !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
                  BUCKET_NAME: !Ref DataS3Bucket
                  DB_HOST: !Ref DatabaseEndpoint
                  DB_PORT: !Ref DatabasePort
              permissions: 0700
              owner: root
              group: root

    Properties:
      KeyName: !If [HasInstanceKey, !Ref InstanceKeyName, !Ref 'AWS::NoValue']
      ImageId: !Ref InstanceAMI
      SecurityGroups: [!GetAtt AppServerSecurityGroup.GroupId]
      InstanceType: !Ref InstanceType
      AssociatePublicIpAddress: !If [UsePrivateSubnet, false, true]
      IamInstanceProfile: !GetAtt AppServerIamProfile.Arn
      InstanceMonitoring: true
      SpotPrice: !If [HasSpotPrice, !Ref InstanceSpotPrice, !Ref 'AWS::NoValue']
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash -xe
            /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource AppServerLaunchConfig -c Basic --region ${AWS::Region} --role ${ROLE}
            # Start up the cfn-hup daemon to listen for changes to the EC2 metadata
             /usr/local/bin/cfn-hup || error_exit 'Failed to start cfn-hup'
            # Signal the status from cfn-init
             /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AppServerLaunchConfig  --region ${AWS::Region}
          - ROLE: !Ref AppServerIamRole

  AppServerAutoScalingGroup:
    # Iannis - make it conditional
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true
    Properties:
      AutoScalingGroupName: !If
        - UseFriendlyNames
        - !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, default, ASG]]
        - !Ref 'AWS::NoValue'
      Cooldown: 60
      MaxSize: 1
      MinSize: 0
      DesiredCapacity: 1
      VPCZoneIdentifier: !If
        - UsePrivateSubnet
        - - Fn::ImportValue:
              !Sub "${NetworkStackName}-PrivateSubnetId1"
          - Fn::ImportValue:
              !Sub "${NetworkStackName}-PrivateSubnetId2"
        - - Fn::ImportValue:
              !Sub "${NetworkStackName}-PublicSubnetId1"
          - Fn::ImportValue:
              !Sub "${NetworkStackName}-PublicSubnetId2"
      TargetGroupARNs: !If
        - HasLoadBalancerStackName
        - [!Ref AppServerTargetGroup]
        - !Ref 'AWS::NoValue'
      LaunchConfigurationName: !Ref AppServerLaunchConfig
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
          PropagateAtLaunch: True
        - Key: Environment
          Value: !Ref EnvName
          PropagateAtLaunch: True
        - Key: Organization
          Value: !Ref OrgName
          PropagateAtLaunch: True

  # Application Server ELB Target Group 
  AppServerTargetGroup:
    Condition: HasLoadBalancerStackName
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: / #Need to be a parameter
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200,301,302,303 #can make this a param if required
      Name: !Join [ '-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !Ref Name]]
      Port: !Ref InstancePort
      Protocol: HTTP
      VpcId:  
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VpcId"
      Tags:
        - Key: Name
          Value: !Join [ '-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !Ref Name]]

  ####
  # CloudWatch Section
  ####
  UnhealthyHostCountCloudWatchAlarm:
    Condition: HasProdLoadBalancerStackName
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Join [ '-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], 'alb', !Ref Name, 'unhealthy-host-count']]
      MetricName: UnHealthyHostCount
      Namespace: AWS/ApplicationELB
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 60
      Statistic: Maximum
      Threshold: 1
      AlarmActions:
        - Fn::ImportValue:
            !Sub "${SNSStackName}-TopicArn"
      OKActions:
        - Fn::ImportValue:
            !Sub "${SNSStackName}-TopicArn"
      Dimensions:
        - Name: LoadBalancer
          Value:
            Fn::ImportValue:
              !Sub "${LoadBalancerStackName}-LoadBalancerFullName"
        - Name: TargetGroup
          Value: !Ref AppServerTargetGroup

  SlowTargetResponseTimeCloudWatchAlarm:
    Condition: HasProdLoadBalancerStackName
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Join [ '-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], 'alb', !Ref Name, 'slow-response-time']]
      MetricName: TargetResponseTime
      Namespace: AWS/ApplicationELB
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 60
      Statistic: Maximum
      Threshold: 5 #if greater than 5 seconds
      AlarmActions:
        - Fn::ImportValue:
            !Sub "${SNSStackName}-TopicArn"
      OKActions:
        - Fn::ImportValue:
            !Sub "${SNSStackName}-TopicArn"
      Dimensions:
        - Name: LoadBalancer
          Value:
            Fn::ImportValue:
              !Sub "${LoadBalancerStackName}-LoadBalancerFullName"
        - Name: TargetGroup
          Value: !Ref AppServerTargetGroup

Outputs:

  AppServerEFSArn:
    Description: ARN of the AppServer EFS
    Value: !If
      - UseInternalEFS
      - !Join ['', ['arn:aws:elasticfilesystem:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':file-system/', !Ref AppServerFileSystem]]
      - !Join ['', ['arn:aws:elasticfilesystem:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':file-system/', !Ref ExternalEFSID]]

  AppServerEFS:
    Description: ID of the AppServer EFS
    Value: !If
      - UseInternalEFS
      - !Ref AppServerFileSystem
      - !Ref ExternalEFSID

  AppServerEFSSecurityGroup:
    Description: EFS Security Group
    Value: !If
      - UseInternalEFS
      - !Ref EFSSecurityGroup
      - !Ref ExternalEFSSecurityGroup

  AppServerSecurityGroup:
    Description: AppServer Security Group
    Value: !Ref AppServerSecurityGroup

  AppServerTargetGroup:
    Condition: HasProdLoadBalancerStackName
    Description: Target Group for the AppServer
    Value: !Ref AppServerTargetGroup