AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions an EC2 instance with all surrounding objects

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: "Resource Configuration"
        Parameters:
          - OrgName
          - EnvName
      -
        Label:
          default: "Cloudformation Stack Configuration"
        Parameters:
          - NetworkStackName
          - SNSStackName

    ParameterLabels:
      OrgName:
        default: "Organization Name"
      EnvName:
        default: "Environment Name"

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: iscaleclient
  NetworkStackName:
    Description: The name of the cloudformation Network stack
    Type: String
    Default: iscale-dev-dev-uw2-network
  SNSStackName:
    Description: The name of the cloudformation SNS stack
    Type: String
    Default: iscale-dev-dev-uw2-sns

Mappings: 
  'Fn::Transform':
    Name: 'AWS::Include'
    Parameters:
      Location: "s3://iscale-dev-cloudformation/include/mappings.yaml"

Resources:
  
  AppServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join [ '-', [!Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]], appserver] ]
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VpcId"
      Tags:
        - 
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, appserver]]
        - 
          Key: Environment
          Value: !Ref EnvName
        - 
          Key: Organization
          Value: !Ref OrgName



# Outputs:
