AWSTemplateFormatVersion: 2010-09-09
Description: This  template provisions a basic EC2 instance with just simple env set

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName
      -
        Label:
          default: Cloudformation Stack Configuration
        Parameters:
          - LoadBalancerStackName
          - NetworkStackName
          - SNSStackName
      -
        Label:
          default: Load Balancer Configuration
        Parameters:
          - LoadBalancerPriority
      -
        Label:
          default: Instance Configuration
        Parameters:
          - InstanceOS
          - InstanceAMI
      -
        Label:
          default: Domain Configuration
        Parameters:
          - ClientDomainName
      -
        Label:
          default: Database Configuration
        Parameters:
          - DatabaseEndpoint
          - DatabasePort
          - DatabaseSecurityGroupId

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      DatabaseEndpoint:
        default: Database Endpoint
      DatabasePort:
        default: Database Port
      DatabaseSecurityGroupId:
        default: Database Security Group
      LoadBalancerStackName:
        default: Load Balancer Stack Name
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Topic Stack Name
      ClientDomainName:
        default: Domain Name
      InstanceAMI:
        default: Instance AMI ID
      InstanceOS:
        default: Instance Operating System
      

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-software.com).
    Type: String
    Default: iscale-software.com
    MinLength: 1
  DatabaseEndpoint:
    Description: Database Endpoint
    Type: String
    MinLength: 1
  DatabasePort:
    Description: Database Port Number
    Type: Number
    MinValue: 1
    MaxValue: 65535
  DatabaseSecurityGroupId:
    Description: Database Security Group
    Type: String
    MinLength: 1
  InstanceAMI:
    Description: Instance AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-0841edc20334f9287 #Basic Amazon Linux AMI
  InstanceKeyName:
    Description: Instance Key Name
    Type: String
    Default: ''
  InstanceOS:
    Description: Instance Operating System
    Type: String
    AllowedValues:
      - Amazon
      - Ubuntu
  LoadBalancerPriority:
    Description: The priority for ELB Listener.
    Type: Number
    Default: 100
    MinValue: 1
    MaxValue: 50000
  LoadBalancerStackName:
    Description: Name of the ELB Stack Name
    Type: String
    MinLength: 1
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 9
  NetworkStackName:
    Description: The name of the cloudformation Network stack
    Type: String
    Default: iscale-dev-dev-uw2-network
    MinLength: 1
  SNSStackName:
    Description: The name of the cloudformation SNS stack
    Type: String
    Default: iscale-dev-dev-uw2-sns
    MinLength: 1

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  HasInstanceKey: !Not [!Equals [!Ref InstanceKeyName, '']]

Resources:
  
  #Include common resources for the app server (regardless of appserver type)
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/appserver.yaml
      
####
# AutoScaling Group 
####

  AppServerLaunchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata: 
      AWS::CloudFormation::Init: 
        configSets: 
          Basic: 
            - InstallCustomData
        InstallCustomData:
          files:
            /var/lib/cloud/instance/custom-data.sh: 
              content: !Sub
                - |
                  STACK_NAME=${AWS::StackName}
                  AWS_REGION=${AWS::Region}
                  DOMAIN=${DOMAIN}
                  ENVIRONMENT=${ENVIRONMENT}
                  CLIENT_NAME=${CLIENT_NAME}
                  APPLICATION_SITE=${APPLICATION_SITE}
                  INSTANCE_ROLE=${INSTANCE_ROLE}
                  SECRET_ID=${SECRET_ID}
                  BASE_URL=https://${DOMAIN}/
                  BUCKET_NAME=${BUCKET_NAME}
                  DB_HOST=${DB_HOST}
                  DB_PORT=${DB_PORT}
                  AWS_SES_USER=${AWS_SES_USER}
                  AWS_SES_PASSWORD=${AWS_SES_PASSWORD}
                - DOMAIN: !Join ['.', [!Join ['-',[!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name]]], !Ref ClientDomainName]]
                  ENVIRONMENT: !Ref EnvName
                  CLIENT_NAME: !Ref Name
                  APPLICATION_SITE: !Ref OrgName
                  INSTANCE_ROLE: !Ref AppServerIamRole
                  SECRET_ID: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
                  BUCKET_NAME: !Ref DataS3Bucket
                  DB_HOST: !Ref DatabaseEndpoint
                  DB_PORT: !Ref DatabasePort
                  AWS_SES_USER: !Ref SESUserAccessKey
                  AWS_SES_PASSWORD: !GetAtt SESUserAccessKey.SecretAccessKey
              permissions: 0700
              owner: root
              group: root

    Properties:
      KeyName: !If [HasInstanceKey, !Ref InstanceKeyName, !Ref 'AWS::NoValue']
      ImageId: !Ref InstanceAMI
      SecurityGroups: [!GetAtt AppServerSecurityGroup.GroupId]
      InstanceType: t3.small #Iannis - make param
      AssociatePublicIpAddress: true
      IamInstanceProfile: !GetAtt AppServerIamProfile.Arn
      InstanceMonitoring: true
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash -xe
            # yum update -y
            # Install the files and packages from the metadata
            # yum install -y aws-cfn-bootstrap
            /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource AppServerLaunchConfig -c Basic --region ${AWS::Region} --role ${ROLE}
            # Start up the cfn-hup daemon to listen for changes to the EC2 metadata
             /usr/local/bin/cfn-hup || error_exit 'Failed to start cfn-hup'
            # Signal the status from cfn-init
             /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AppServerLaunchConfig  --region ${AWS::Region}
          - ROLE: !Ref AppServerIamRole

  AppServerAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true
    Properties:
      Cooldown: 60
      MaxSize: 1
      MinSize: 0
      DesiredCapacity: 1
      VPCZoneIdentifier:
        -
          Fn::ImportValue:
            !Sub "${NetworkStackName}-PublicSubnetId1"
        -
          Fn::ImportValue:
            !Sub "${NetworkStackName}-PublicSubnetId2"
      TargetGroupARNs: [!Ref AppServerTargetGroup]
      LaunchConfigurationName: !Ref AppServerLaunchConfig
      Tags:
        - 
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
          PropagateAtLaunch: True
        - 
          Key: Environment
          Value: !Ref EnvName
          PropagateAtLaunch: True
        - 
          Key: Organization
          Value: !Ref OrgName
          PropagateAtLaunch: True

  # Application Server ELB Target Group 
  AppServerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: / #Need to be a parameter
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher: 
        HttpCode: 200,302
      Name: !Join [ '-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !Ref Name]]
      Port: 80
      Protocol: HTTP
      VpcId:  
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VpcId"
      Tags:
        - 
          Key: Name
          Value: !Join [ '-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !Ref Name]]

Outputs:

  AppServerEFSArn:
    Description: ARN of the AppServer EFS
    Value: !GetAtt AppServerFileSystem.Arn

  AppServerTargetGroup:
    Description: Target Group for the AppServer
    Value: !Ref AppServerTargetGroup

  SESAccessKeyId:
    Description: SES User Access Key ID
    Value: !Ref SESUserAccessKey
    
  SESSecretAccessKey:
    Description: SES Secret Access Key
    Value: !GetAtt SESUserAccessKey.SecretAccessKey