AWSTemplateFormatVersion: 2010-09-09
Description: Magento EC2 instance using Amazon Linux with all surrounding objects

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName
      -
        Label:
          default: Cloudformation Stack Configuration
        Parameters:
          - LoadBalancerStackName
          - NetworkStackName
          - SNSStackName
      -
        Label:
          default: Instance Configuration
        Parameters:
          - InstanceKeyName
          - InstanceAMI
          - InstancePort
      -
        Label:
          default: Load Balancer Configuration
        Parameters:
          - LoadBalancerPriority
          - LoadBalancerHostName
      -
        Label:
          default: Domain Configuration
        Parameters:
          - ClientDomainName
      -
        Label:
          default: Database Configuration
        Parameters:
          - DatabaseEndpoint
          - DatabasePort
          - DatabaseSecurityGroupId

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      DatabaseEndpoint:
        default: Database Endpoint
      DatabasePort:
        default: Database Port
      DatabaseSecurityGroupId:
        default: Database Security Group
      InstanceAMI:
        default: Instance AMI ID
      InstancePort:
        default: Instance Application Port
      InstanceKeyName:
        default: Instance Key Name
      LoadBalancerStackName:
        default: Load Balancer Stack Name
      LoadBalancerHostName:
        default: Load Balancer Hostname
      LoadBalancerPriority:
        default: Load Balancer Priority
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Topic Stack Name
      ClientDomainName:
        default: Domain Name

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-software.com).
    Type: String
    Default: iscale-software.com
    MinLength: 1
  DatabaseEndpoint:
    Description: Database Endpoint
    Type: String
    MinLength: 1
  DatabasePort:
    Description: Database Port Number
    Type: Number
    MinValue: 1
    MaxValue: 65535
  DatabaseSecurityGroupId:
    Description: Database Security Group
    Type: String
    MinLength: 1
  InstanceAMI:
    Description: Instance AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-0841edc20334f9287 #Basic Amazon Linux AMI
  InstanceKeyName:
    Description: Instance Key Name
    Type: String
    Default: ''
  InstancePort:
    Description: Database Port Number
    Type: Number
    Default: 80 #Assume HTTP port as default on port 80
    MinValue: 1
    MaxValue: 65535
  InstanceType:
    Description: The type of EC2 instance
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large
  LoadBalancerHostName:
    Description: (Optional) Custom Hostname for load balancer URL
    Type: String
    Default: ''
    MaxLength: 12
  LoadBalancerPriority:
    Description: The priority for ELB Listener.
    Type: Number
    Default: 100
    MinValue: 1
    MaxValue: 50000
  LoadBalancerStackName:
    Description: Name of the ELB Stack Name
    Type: String
    MinLength: 1
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 8
  NetworkStackName:
    Description: The name of the cloudformation Network stack
    Type: String
    Default: iscale-dev-dev-uw2-network
    MinLength: 1
  SNSStackName:
    Description: The name of the cloudformation SNS stack
    Type: String
    Default: iscale-dev-dev-uw2-sns
    MinLength: 1
  UseFriendlyNames:
    Description: Set to TRUE to have nice object names
    Type: String
    AllowedValues:
      - TRUE
      - FALSE
    Default: TRUE


Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  UseFriendlyNames: !Equals [!Ref UseFriendlyNames, TRUE]
  HasInstanceKey: !Not [!Equals [!Ref InstanceKeyName, '']]
  HasLoadBalancerHostName: !Not [!Equals [!Ref LoadBalancerHostName, '']]

Resources:
  
  #Include common resources for the app server (regardless of appserver type)
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/appserver.yaml
  
####
# AutoScaling Group 
####

  AppServerLaunchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata: 
      AWS::CloudFormation::Init: 
        configSets: 
          NodeJS: 
            - InstallLogAgent
            - InstallCustomData
            - InstallEFS
            # - InstallNodeJS
            - InstallMySQLClient
            - InstallCodeDeployAgent
            # - InstallHardening
        InstallLogAgent:
          Fn::Transform:
            Name: AWS::Include
            Parameters:
              Location: s3://iscale-dev-cloudformation/include/installLogAgent.yaml
        InstallCustomData:
          Fn::Transform:
            Name: AWS::Include
            Parameters:
              Location: s3://iscale-dev-cloudformation/include/installCustomData.yaml
        InstallCodeDeployAgent:
          Fn::Transform:
            Name: AWS::Include
            Parameters:
              Location: s3://iscale-dev-cloudformation/include/installCodeDeploy.yaml
        InstallEFS:
          Fn::Transform:
            Name: AWS::Include
            Parameters:
              Location: s3://iscale-dev-cloudformation/include/installEFS.yaml
        InstallMySQLClient:
          Fn::Transform:
            Name: AWS::Include
            Parameters:
              Location: s3://iscale-dev-cloudformation/include/installMySQLClient.yaml
        InstallNodeJS:
          Fn::Transform:
            Name: AWS::Include
            Parameters:
              Location: s3://iscale-dev-cloudformation/include/installNodeJS.yaml
        InstallHardening:
          Fn::Transform:
            Name: AWS::Include
            Parameters:
              Location: s3://iscale-dev-cloudformation/include/installHardening.yaml
        

    Properties:
      KeyName: !If [HasInstanceKey, !Ref InstanceKeyName, !Ref 'AWS::NoValue']
      ImageId: !Ref InstanceAMI
      SecurityGroups: [!GetAtt AppServerSecurityGroup.GroupId]
      InstanceType: !Ref InstanceType
      AssociatePublicIpAddress: true
      IamInstanceProfile: !GetAtt AppServerIamProfile.Arn
      InstanceMonitoring: true
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash -xe
            # yum update -y
            # Install the files and packages from the metadata
            yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource AppServerLaunchConfig -c NodeJS --region ${AWS::Region} --role ${ROLE}
            # Start up the cfn-hup daemon to listen for changes to the EC2 metadata
            /opt/aws/bin/cfn-hup || error_exit 'Failed to start cfn-hup'
            # Signal the status from cfn-init
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AppServerLaunchConfig  --region ${AWS::Region}
          - ROLE: !Ref AppServerIamRole

  AppServerAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true
    # CreationPolicy:
    #   AutoScalingCreationPolicy:
    #     MinSuccessfulInstancesPercent: 100
      # ResourceSignal:
      #   Count: 1
      #   Timeout: PT5M
    Properties:
      Cooldown: 60
      MaxSize: 1
      MinSize: 0
      DesiredCapacity: 0 #Make it zero as it will be taken away by blue green
      AutoScalingGroupName: !If
        - UseFriendlyNames
        - !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, default, ASG]]
        - !Ref 'AWS::NoValue'
      VPCZoneIdentifier:
        -
          Fn::ImportValue:
            !Sub "${NetworkStackName}-PublicSubnetId1"
        -
          Fn::ImportValue:
            !Sub "${NetworkStackName}-PublicSubnetId2"
      TargetGroupARNs: [!Ref AppServerTargetGroup]
      LaunchConfigurationName: !Ref AppServerLaunchConfig
      Tags:
        - 
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
          PropagateAtLaunch: True
        - 
          Key: Environment
          Value: !Ref EnvName
          PropagateAtLaunch: True
        - 
          Key: Organization
          Value: !Ref OrgName
          PropagateAtLaunch: True

  # Application Server ELB Target Group 
  AppServerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher: 
        HttpCode: 200,302
      Name: !Join [ '-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !Ref Name]]
      Port: !Ref InstancePort
      Protocol: HTTP
      VpcId:  
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VpcId"
      Tags:
        - 
          Key: Name
          Value: !Join [ '-', [!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !Ref Name]]

Outputs:

  AppServerEFSArn:
    Description: ARN of the AppServer EFS
    Value: !GetAtt AppServerFileSystem.Arn
