AWSTemplateFormatVersion: 2010-09-09
Description: AWS Backup for a list of ARNs

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Backup Configuration
        Parameters:
          - BackupARNList
    
    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      MultiAz:
        BackupARNList: List of ARNs to backup

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 8
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Staging
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  BackupARNList:
    Description: The list of ARN resources that need to be backed up
    Type: CommaDelimitedList

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  ProdBackupVault:
    Condition: IsProd
    Type: AWS::Backup::BackupVault
    DeletionPolicy: Retain #Prod vaults are retained
    Properties:
      BackupVaultName: !Join [ '-', [!Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]], vault]]
      BackupVaultTags:
        Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, vault]]
        Environment: !Ref EnvName
        Organization: !Ref OrgName

  NonProdBackupVault:
    Condition: IsNotProd #No retention for non-prod
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Join [ '-', [!Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]], vault]]
      BackupVaultTags:
        Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, vault]]
        Environment: !Ref EnvName
        Organization: !Ref OrgName

  ProdBackupPlan:
    Condition: IsProd
    DependsOn: ProdBackupVault
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, backup,plan]]
        BackupPlanRule:
          - RuleName: DailyBackup
            TargetBackupVault: !Ref ProdBackupVault
            ScheduleExpression: "cron(0 15 ? * * *)"
            StartWindowMinutes: 480
            CompletionWindowMinutes: 10080
            Lifecycle:
              DeleteAfterDays: 35
          - RuleName: WeeklyBackup
            TargetBackupVault: !Ref ProdBackupVault
            ScheduleExpression: "cron(0 15 ? * 7 *)"
            StartWindowMinutes: 480
            CompletionWindowMinutes: 10080
            Lifecycle:
              DeleteAfterDays: 90
          - RuleName: MonthlyBackup
            TargetBackupVault: !Ref ProdBackupVault
            ScheduleExpression: "cron(0 15 1 * ? *)"
            StartWindowMinutes: 480
            CompletionWindowMinutes: 10080
            Lifecycle:
              MoveToColdStorageAfterDays: 90
              DeleteAfterDays: 1825
      BackupPlanTags:
        Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, backup, plan]]
        Environment: !Ref EnvName
        Organization: !Ref OrgName

  NonProdBackupPlan:
    Condition: IsNotProd
    DependsOn: NonProdBackupVault
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, backup,plan]]
        BackupPlanRule: #only simple daily backup for non prod
          - RuleName: DailyBackup
            TargetBackupVault: !Ref NonProdBackupVault
            ScheduleExpression: "cron(0 9 ? * * *)" #Non prod usually only open during day time
            StartWindowMinutes: 480
            CompletionWindowMinutes: 10080
            Lifecycle:
              DeleteAfterDays: 35
      BackupPlanTags:
        Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, backup, plan]]
        Environment: !Ref EnvName
        Organization: !Ref OrgName
          
  BackupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - backup.amazonaws.com
          Action:
            - sts:AssumeRole
     ManagedPolicyArns:
       - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup 
       - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores

  BackupSelection:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !If [IsProd, !Ref ProdBackupPlan, !Ref NonProdBackupPlan]
      BackupSelection:
        SelectionName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, backup-selection]]
        IamRoleArn: !GetAtt BackupRole.Arn
        Resources: !Ref BackupARNList