AWSTemplateFormatVersion: 2010-09-09
Description: Backup plan with parameters

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Backup Configuration
        Parameters:
          - BackupARNList
          - BackupTime
          - ColdStorageTrigger
          - DailyExpiration
          - MonthlyExpiration
          - TagName
          - TagValue
          - WeeklyExpiration

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      BackupTime:
        default: UTC time of the backup
      BackupARNList:
        default: List of ARNs to backup
      ColdStorageTrigger:
        default: Number of days after which the backup goes to cold storage
      DailyExpiration:
        default: Number of days for daily backup expiration
      MonthlyExpiration:
        default: Number of days for monthly backup expiration
      WeeklyExpiration:
        default: Number of days for weekly backup expiration

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Staging
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
      - PreProd
  BackupARNList:
    Description: The list of ARN resources that need to be backed up
    Type: CommaDelimitedList
  BackupTime:
    Description: UTC time for the backup
    Type: Number
    Default: 15 #3PM UTC
    MinValue: 0
    MaxValue: 23
  ColdStorageTrigger:
    Description: Number of days after which the backup goes to cold storage
    Type: Number
    Default: 90 # 3 months
  DailyExpiration:
    Description: Number of days after which the daily backup expires
    Type: Number
    Default: 30 # 1 month
  MonthlyExpiration:
    Description: Number of days after which the monthly backup expires
    Type: Number
    Default: 1825 # 5 years
  TagName:
    Description: Name of the tag name to include
    Type: String
    Default: Name
  TagValue:
    Description: Name of the tag value to include
    Type: String
    Default: ''
  WeeklyExpiration:
    Description: Number of days after which the weekly backup expires
    Type: Number
    Default: 365 # 1 year

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  UseTagInclusion: !And [!Not [!Equals [!Ref TagName, ""]], !Not [!Equals [!Ref TagValue, ""]]]

Resources:

  ProdBackupVault:
    Condition: IsProd
    Type: AWS::Backup::BackupVault
    DeletionPolicy: Retain #Prod vaults are retained
    Properties:
      BackupVaultName: !Join [ '-', [!Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]], vault]]
      BackupVaultTags:
        Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, vault]]
        Environment: !Ref EnvName
        Organization: !Ref OrgName

  NonProdBackupVault:
    Condition: IsNotProd #No retention for non-prod
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Join [ '-', [!Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]], vault]]
      BackupVaultTags:
        Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, vault]]
        Environment: !Ref EnvName
        Organization: !Ref OrgName

  ProdBackupPlan:
    Condition: IsProd
    DependsOn: ProdBackupVault
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, backup,plan]]
        BackupPlanRule:
          - RuleName: DailyBackup
            TargetBackupVault: !Ref ProdBackupVault
            ScheduleExpression: !Join [' ', ['cron(0', !Ref BackupTime, '?', '*', '*', '*)']]
            StartWindowMinutes: 120
            CompletionWindowMinutes: 300
            Lifecycle:
              DeleteAfterDays: !Ref DailyExpiration
          - RuleName: WeeklyBackup
            TargetBackupVault: !Ref ProdBackupVault
            ScheduleExpression: !Join [' ', ['cron(0', !Ref BackupTime, '?', '*', 7, '*)']]
            StartWindowMinutes: 120
            CompletionWindowMinutes: 300
            Lifecycle:
              MoveToColdStorageAfterDays: !Ref ColdStorageTrigger
              DeleteAfterDays: !Ref WeeklyExpiration
          - RuleName: MonthlyBackup
            TargetBackupVault: !Ref ProdBackupVault
            ScheduleExpression: !Join [' ', ['cron(0', !Ref BackupTime, 1, '*', '?', '*)']]
            StartWindowMinutes: 120
            CompletionWindowMinutes: 300
            Lifecycle:
              MoveToColdStorageAfterDays: !Ref ColdStorageTrigger
              DeleteAfterDays: !Ref MonthlyExpiration
      BackupPlanTags:
        Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, backup, plan]]
        Environment: !Ref EnvName
        Organization: !Ref OrgName

  NonProdBackupPlan:
    Condition: IsNotProd
    DependsOn: NonProdBackupVault
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, backup,plan]]
        BackupPlanRule: #only simple daily backup for non prod
          - RuleName: DailyBackup
            TargetBackupVault: !Ref NonProdBackupVault
            ScheduleExpression: "cron(0 5 ? * * *)" #Non prod usually only open during day time
            StartWindowMinutes: 120
            CompletionWindowMinutes: 300
            Lifecycle:
              DeleteAfterDays: !Ref DailyExpiration
      BackupPlanTags:
        Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, backup, plan]]
        Environment: !Ref EnvName
        Organization: !Ref OrgName

  BackupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - backup.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
       - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup 
       - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores

  BackupSelection:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !If [IsProd, !Ref ProdBackupPlan, !Ref NonProdBackupPlan]
      BackupSelection:
        SelectionName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, backup-selection]]
        IamRoleArn: !GetAtt BackupRole.Arn
        Resources: !Ref BackupARNList
        ListOfTags: !If
          - UseTagInclusion
          - - ConditionType: STRINGEQUALS
              ConditionKey: !Ref TagName
              ConditionValue: !Ref TagValue
          - !Ref 'AWS::NoValue'