AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions all objects for blue green deployment

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName
      - Label:
          default: Deployment Configuration
        Parameters:
          - CreateDeployUser

    ParameterLabels:
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      CreateDeployUser:
        default: Create a deploy user ?

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 8
  CreateDeployUser:
    Description: Set to TRUE to create a new deploy user
    Type: String
    Default: FALSE
    AllowedValues:
      - FALSE
      - TRUE
  NetworkStackName:
    Description: The name of the cloudformation Network stack
    Type: String
    Default: iscale-dev-dev-uw2-network
  SNSStackName:
    Description: The name of the cloudformation SNS stack
    Type: String
    Default: iscale-dev-dev-uw2-sns

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  HasCreateDeployUser: !Equals [!Ref CreateDeployUser, TRUE]

Resources:
  
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties: 
      ApplicationName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, application]]
      ComputePlatform: Server

  NotifyReadyTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt  NotifyReadyFunction.Arn
  
  NotifyReadyFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AccessToDeploySetup
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codedeploy:GetDeployment
                Resource: !Join [":", ["arn:aws:codedeploy", !Ref 'AWS::Region', !Ref 'AWS::AccountId', "deploymentgroup:*"]]
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                Resource: '*'

  NotifyReadyFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Give the IP address of a ready EC2 instance in an AutoScaling group
      Handler: index.lambda_handler
      Role: !GetAtt  NotifyReadyFunctionRole.Arn
      Runtime: python3.6
      Timeout: 60
      Environment:
        Variables:
          ENV_NAME: !Ref EnvName
          REGION: !Ref AWS::Region
          SNS_TOPIC_ARN: 
            Fn::ImportValue:
              !Sub "${SNSStackName}-TopicArn"
      Code:
        ZipFile: |
          import boto3
          import logging
          import os
          import json

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
            # logger.info(event)
            # logger.info(context)
            
            eventSubject=event[0]['Sns']['Subject']
            eventSubject = eventSubject.split()
            
            deploymentId=eventSubject[3]
            instanceId=eventSubject[8]
            
            logger.info(deploymentId)
            logger.info(instanceId)
            
            codedeploy=boto3.client('codedeploy')
            deployment_details=codedeploy.get_deployment(deploymentId=deploymentId)
            application_name=deployment_details['deploymentInfo']['applicationName']

            region=os.environ['REGION']
            environment=os.environ['ENV_NAME']
            client=boto3.client('ec2',region_name=region)
            instance_details=client.describe_instances(InstanceIds=[instanceId])
            publicIp=instance_details['Reservations'][0]['Instances'][0]['PublicIpAddress']
            message='Deployment ID:' + deploymentId + '\nEC2 ready for '+ application_name + '(' + environment + '). \nInstance ' + instanceId + ' IP address:' +  publicIp
            
            sns = boto3.client('sns')
            logger.info(message)
            
            topic=os.environ['SNS_TOPIC_ARN']
            sns.publish(
              TopicArn=topic,    
              Message=message
            )

  NotifyReadyFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref NotifyReadyFunction
      Principal: sns.amazonaws.com   

  NotifyReadyTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref NotifyReadyTopic
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sns:Publish
            Resource: !Ref NotifyReadyTopic
            Principal:
              AWS: '*'
            Condition:
              ArnLike:
                AWS:SourceArn: !Sub 'arn:aws:*:*:${AWS::AccountId}:*'

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn
      TriggerConfigurations:
        - TriggerEvents:
            - DeploymentSuccess
            - DeploymentFailure
          TriggerName: DeploymentState
          TriggerTargetArn:
            Fn::ImportValue:
              !Sub "${SNSStackName}-TopicArn"
        - TriggerEvents:
            - InstanceReady
          TriggerName: InstanceReady
          TriggerTargetArn: !Ref  NotifyReadyTopic
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
      Ec2TagFilters: #Iannis - Need to make this an auto-scaling group
      - Key: Name
        Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
        Type: KEY_AND_VALUE

  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Join [".", [codedeploy, !Ref 'AWS::Region', amazonaws, com]]
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, code-deploy]]
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 3
          Status: Enabled
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, code-deploy]]
        - Key: Environment
          Value: !Ref EnvName

  DeploymentUserGroup:
    Type: AWS::IAM::Group
    Properties:
      Policies: 
        - PolicyName: S3DeployBucketWriteAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - s3:PutObject
                Resource: !Join ['',[!GetAtt DeploymentBucket.Arn, "/*"]]
        - PolicyName: DeploymentAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - codedeploy:CreateDeployment
                  - codedeploy:GetDeployment
                Resource: !Join [':', ['arn:aws:codedeploy', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'deploymentgroup', !Join ['/', [!Ref CodeDeployApplication, !Ref CodeDeployDeploymentGroup]]]]
              - Effect: Allow
                Action: 
                  - codedeploy:GetDeploymentConfig
                Resource: !Join [':', ['arn:aws:codedeploy', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'deploymentconfig', 'CodeDeployDefault.OneAtATime']]
              - Effect: Allow
                Action: 
                  - codedeploy:RegisterApplicationRevision
                  - codedeploy:GetApplicationRevision
                Resource: !Join [':', ['arn:aws:codedeploy', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'application', !Ref CodeDeployApplication]]
  
  DeploymentUser:
    Condition: HasCreateDeployUser
    Type: AWS::IAM::User
    Properties:
      UserName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, deploy-user]]
      Groups:
        - !Ref DeploymentUserGroup
  
  DeploymentUserAccessKey:
    Condition: HasCreateDeployUser
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref DeploymentUser

Outputs:

  DeploymentBucketArn:
    Description: The Arn of the Deployment Bucket
    Value: !GetAtt DeploymentBucket.Arn

  DeploymentBucketName:
    Description: The Name of the Deployment S3 Bucket
    Value: !Ref DeploymentBucket

  DeploymentUserAccessKey:
    Condition: HasCreateDeployUser
    Description: Access Key for the Deployment User
    Value: !Ref DeploymentUserAccessKey
  
  DeploymentUserSecretKey:
    Condition: HasCreateDeployUser
    Description: Secret Key for the Deployment User
    Value: !GetAtt DeploymentUserAccessKey.SecretAccessKey

  DeploymentUserGroup:
    Description: The Arn of the group allowed to perform deployement
    Value: !Ref DeploymentUserGroup

  CodeDeployApplicationName:
    Description: The name of the CodeDeploy application
    Value: !Ref CodeDeployApplication

  CodeDeployDeploymentGroupName:
    Description: The Arn of the deployment group for the stack
    Value: !Ref CodeDeployDeploymentGroup