AWSTemplateFormatVersion: 2010-09-09
Description: DNSSEC Settings. Must be run in us-east-1

Parameters:
  OrgName:
    Description: The name of the organization
    Type: String
    Default: iscale
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  ####
  # DNSSEC
  ###

  DNSSECKMSKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      Description: DNSSEC KMS Key
      Enabled: true
      KeySpec: ECC_NIST_P256
      KeyUsage: SIGN_VERIFY
      KeyPolicy:
        Version: 2012-10-17
        Id: DNSSEC
        Statement:
          - Sid: AllowKeyAdministration
            Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:TagResource'
              - 'kms:UntagResource'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
              - 'kms:Sign'
            Resource: '*'
          - Sid: Allow Route 53 DNSSEC Service
            Effect: Allow
            Principal:
              Service: dnssec-route53.amazonaws.com
            Action:
              - kms:DescribeKey
              - kms:GetPublicKey
              - kms:Sign
            Resource: '*'
          - Sid: Allow Route 53 DNSSEC to CreateGrant
            Effect: Allow
            Principal:
              Service: dnssec-route53.amazonaws.com
            Action:
              - kms:CreateGrant
            Resource: '*'
            Condition:
              Bool:
                kms:GrantIsForAWSResource: true

  KeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/DNSSEC
      TargetKeyId:
        !Ref DNSSECKMSKey

Outputs:

  DNSSECKey:
    Description: DNSSEC KMS Key
    Value: !Ref DNSSECKMSKey

  DNSSECKeyArn:
    Description: DNSSEC KMS Key ARN
    Value: !GetAtt [DNSSECKMSKey, Arn]