AWSTemplateFormatVersion: 2010-09-09
Description: EC2 Image Builder

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
          - ArmBased
      - Label:
          default: Sharing Configuration
        Parameters:
          - ShareImage
          - ShareAccountList
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      ArmBased:
        default: ARM Based Architecture
      ImageRecipeARN:
        default: Recipe ARN
      NetworkStackName:
        default: Network Stack Name
      ShareImage:
        default: set to true to share the image with other accounts
      ShareAccountList:
        default: Comma Delimited List of account Ids to share image to
      SNSStackName:
        default: SNS Topic Stack Name

Parameters:
  Name:
    Description: Unique name/identifier (e.g. amazon-linux).
    Type: String
    Default: image-builder
    AllowedPattern: "^[a-z0-9]+(-[a-z0-9]+)*$"
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ArmBased:
    Description: Is the image ARM based architecture?
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  ImageRecipeARN:
    Description: Image Recipe ARN
    Type: String
    MinLength: 1
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: iscale-dev-dev-uw2-network
    MinLength: 1
  ShareAccountList:
    Description: List of accounts to share this image with
    Type: CommaDelimitedList 
    Default: "178070162686" #178070162686: iscale-hosting
  ShareImage:
    Description: Set to true to enable image sharing. Default is private.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  SNSStackName:
    Description: the name of the SNS stack.
    Type: String
    Default: iscale-dev-dev-uw2-sns
    MinLength: 1

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml      
  IsShareImage: !Equals [!Ref ShareImage, true]
  IsArmBased: !Equals [!Ref ArmBased, true]

Resources:

  EC2ImageBuilderInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: EC2ReadTagPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeTags
                  - ec2:DescribeInstances
                  - cloudwatch:ListMetrics
                Resource: '*'
        - PolicyName: CloudWatchMetrics
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                Resource: '*'
        - PolicyName: AllowLogging
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
        - PolicyName: AllowEBSOperation
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:AttachVolume
                  - ec2:CreateTags
                  - ec2:CreateVolume
                  - ec2:DeleteVolume
                  - ec2:DescribeVolumes
                  - ec2:DetachVolume
                Resource: '*'
        - PolicyName: AllowNetworkInterfaceOperation
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:AttachNetworkInterface
                  - ec2:CreateNetworkInterface
                  - ec2:CreateTags
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeNetworkInterfaceAttribute
                  - ec2:DetachNetworkInterface
                Resource: '*'
  EC2ImageInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2ImageBuilderInstanceRole

  ImageInfrastructureConfig:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties: 
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
      InstanceProfileName: !Ref EC2ImageInstanceProfile
      InstanceTypes: !If
        - IsArmBased
        - - t4g.micro
          - t4g.small
          - t4g.medium
        - - t3.micro
          - t3.small
          - t3.medium        
      Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
      SecurityGroupIds: 
        - !Ref ImageSecurityGroup
      SnsTopicArn: 
        Fn::ImportValue:
          !Sub "${SNSStackName}-TopicArn"
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-PublicSubnetId1"
      TerminateInstanceOnFailure: true

  ImageSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VpcId"
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  ImageSecurityGroupAllowSSH:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId: !Ref ImageSecurityGroup
      IpProtocol: TCP
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0

  ImageDistributionConfiguration:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name: !Join ['-',[!Ref OrgName, !Ref Name]]
      Description: !Join [' ',['Distribution for', !Ref OrgName, !Ref Name]]
      Distributions:
        - Region: !Ref 'AWS::Region'
          AmiDistributionConfiguration:
            Name: !Join [' ', [!Ref OrgName, !Ref Name, base image, !Select [2, !Split ['/', !Ref ImageRecipeARN]], '{{ imagebuilder:buildDate }}']]
            Description: !Join [' ', [!Ref OrgName, !Ref Name, base image, !Select [2, !Split ['/', !Ref ImageRecipeARN]], '{{ imagebuilder:buildDate }}']]
            AmiTags:
              Name: !Join [' ', [!Ref OrgName, !Ref Name, base image, !Select [2, !Split ['/', !Ref ImageRecipeARN]], '{{ imagebuilder:buildDate }}']]
              Environment: !Ref EnvName
            LaunchPermissionConfiguration: !If
              - IsShareImage
              - UserIds: !Ref ShareAccountList
              - !Ref 'AWS::NoValue'
      Tags:
        Name: !Ref Name

  ImagePipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name: !Join [' ', [!Ref OrgName, !Ref Name]]
      Description: !Join [' ', [!Ref OrgName, !Ref Name, 'Pipeline']]
      ImageRecipeArn: !Ref ImageRecipeARN
      InfrastructureConfigurationArn: !Ref ImageInfrastructureConfig
      DistributionConfigurationArn: !Ref ImageDistributionConfiguration
      ImageTestsConfiguration:
        ImageTestsEnabled: true
        TimeoutMinutes: 60
      Status: ENABLED