AWSTemplateFormatVersion: 2010-09-09
Description: Elasticache Instance

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
          - ExportOutputs
          - UseFriendlyNames
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName
      - Label:
          default: Cache Configuration
        Parameters:
          - EngineName
          - EngineVersion
          - ValkeyEngineVersion
          - Port
          - NodeType
          - NumCacheClusters
          - AllowSecurityGroup
          - SnapshotRetentionLimit

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      EngineName:
        default: Cache engine name
      EngineVersion:
        default: Cache engine version (redis)
      ValkeyEngineVersion:
        default: Cache engine version (valkey)
      ExportOutputs:
        default: Export Stack Outputs
      Port:
        default: Port Number
      NetworkStackName:
        default: Network Stack Name
      NodeType:
        default: Cache Node Type
      NumCacheClusters:
        default: Number of cache Clusters
      SnapshotRetentionLimit:
        default: Number of daily backups to keep
      SNSStackName:
        default: SNS Topic Stack Name
      UseFriendlyNames:
        default: Use Friendly Resource Names

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
      - ProductionDR
      - StagingDR
      - DevelopmentDR
      - TestDR
  EngineName:
    Description: Cache engine name
    Type: String
    Default: redis
    AllowedValues:
      - redis
      - valkey
  EngineVersion:
    Description: Redis engine version (redis)
    Type: String
    Default: 5.0.6
    AllowedValues:
      - 5.0.6
      - 6.x
      - 6.0
      - 7.0
      - 7.1
  ValkeyEngineVersion:
    Description: Cache engine version (valkey)
    Type: String
    Default: 7.2
    AllowedValues:
      - 7.2
      - 8.0
      - 8.1
      - 8.2
      - 9.0
  EncryptInTransit:
    Description: Set to TRUE to encrypt in transit
    Type: String
    AllowedValues:
      - TRUE
      - FALSE
    Default: FALSE
  ExportOutputs:
    Description: Set to TRUE to export stack output
    Type: String
    AllowedValues:
      - TRUE
      - FALSE
    Default: FALSE
  NetworkStackName:
    Description: The name of the cloudformation Network stack
    Type: String
    Default: iscale-dev-dev-uw2-network
    MinLength: 1
  AllowSecurityGroup:
    Description: Security Group to be allowed to access the cache. Leave blank to allow from anywhere
    Type: String
    Default: ''
  NodeType:
    Description: The compute and memory capacity of the nodes in the node group (shard).
    Type: String
    Default: cache.t3.micro
  NumCacheClusters:
    Description: The number of clusters this replication group initially has.
    Type: Number
    Default: 1
  Port:
    Description: The port number on which the database accepts connections.
    Type: Number
    Default: 6379
    MinValue: 1
    MaxValue: 65535
  SnapshotRetentionLimit:
    Description: Number of daily snapshots to keep for backup
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 30
  SNSStackName:
    Description: The name of the cloudformation SNS stack
    Type: String
    Default: iscale-dev-dev-uw2-sns
    MinLength: 1
  UseFriendlyNames:
    Description: Set to TRUE to have nice formatted resource names
    Type: String
    AllowedValues:
      - TRUE
      - FALSE
    Default: TRUE

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  HasAllowSecurityGroup: !Not [!Condition HasNotAllowSecurityGroup]
  HasNotAllowSecurityGroup: !Equals [!Ref AllowSecurityGroup, '']
  HasExportOutputs: !Equals [!Ref ExportOutputs, TRUE]
  UseFriendlyNames: !Equals [!Ref UseFriendlyNames, TRUE]
  IsRedis: !Equals [!Ref EngineName, redis]
  IsValkey: !Equals [!Ref EngineName, valkey]
  UseRedisV5: !And [!Equals [!Ref EngineVersion, 5.0.6], !Condition IsRedis]
  UseRedisV6: !And [!Equals [!Ref EngineVersion, 6.0], !Condition IsRedis]
  UseRedisV7: !And [!Equals [!Ref EngineVersion, 7.0], !Condition IsRedis]
  UseRedisV71: !And [!Equals [!Ref EngineVersion, 7.1], !Condition IsRedis]
  UseValkeyV7: !And [!Equals [!Ref ValkeyEngineVersion, 7.2], !Condition IsValkey]
  UseValkeyV80: !And [!Equals [!Ref ValkeyEngineVersion, 8.0], !Condition IsValkey]
  UseValkeyV81: !And [!Equals [!Ref ValkeyEngineVersion, 8.1], !Condition IsValkey]
  UseValkeyV82: !And [!Equals [!Ref ValkeyEngineVersion, 8.2], !Condition IsValkey]
  UseValkeyV90: !And [!Equals [!Ref ValkeyEngineVersion, 9.0], !Condition IsValkey]

Resources:

  ElasticacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !If
        - UseFriendlyNames
        - !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, cache]]
        - !Ref 'AWS::NoValue'
      GroupDescription: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, cache]]
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VpcId"
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, cache]]

  CacheSecurityGroupIngressFromSecurityGroup:
    Condition: HasAllowSecurityGroup
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId: !GetAtt ElasticacheSecurityGroup.GroupId
      IpProtocol: TCP
      FromPort: !Ref Port
      ToPort: !Ref Port
      SourceSecurityGroupId: !Ref AllowSecurityGroup

  CacheSecurityGroupIngressFromAnywhere:
    Condition: HasNotAllowSecurityGroup
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId: !GetAtt ElasticacheSecurityGroup.GroupId
      IpProtocol: TCP
      FromPort: !Ref Port
      ToPort: !Ref Port
      CidrIp: 0.0.0.0/0

  Redis50CacheParameterGroup:
    Condition: UseRedisV5
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, cache]]
      CacheParameterGroupFamily: redis5.0
  
  Redis60CacheParameterGroup:
    Condition: UseRedisV6
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, v6, cache]]
      CacheParameterGroupFamily: redis6.x
  
  Redis70CacheParameterGroup:
    Condition: UseRedisV7
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, v7, cache]]
      CacheParameterGroupFamily: redis7

  Redis71CacheParameterGroup:
    Condition: UseRedisV71
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, v7, cache]]
      CacheParameterGroupFamily: redis7

  Valkey70CacheParameterGroup:
    Condition: UseValkeyV7
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, v7, cache-valkey]]
      CacheParameterGroupFamily: valkey7
  
  Valkey80CacheParameterGroup:
    Condition: UseValkeyV80
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, v8, cache-valkey]]
      CacheParameterGroupFamily: valkey8
  
  Valkey81CacheParameterGroup:
    Condition: UseValkeyV81
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, v8, cache-valkey]]
      CacheParameterGroupFamily: valkey8

  Valkey82CacheParameterGroup:
    Condition: UseValkeyV82
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, v8, cache-valkey]]
      CacheParameterGroupFamily: valkey8

  Valkey90CacheParameterGroup:
    Condition: UseValkeyV90
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, v9, cache-valkey]]
      CacheParameterGroupFamily: valkey9

  ElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, cache]]
      SubnetIds:
        - Fn::ImportValue:
            !Sub "${NetworkStackName}-InternalSubnetId1"
        - Fn::ImportValue:
            !Sub "${NetworkStackName}-InternalSubnetId2"  

  ElasticacheReplicationGroup:
    DeletionPolicy: Snapshot
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !If
        - UseFriendlyNames
        - !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, cache]]
        - !Ref 'AWS::NoValue'
      ReplicationGroupDescription: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, cache]]
      NumCacheClusters: !Ref NumCacheClusters
      AutomaticFailoverEnabled: false
      CacheNodeType: !Ref NodeType
      CacheParameterGroupName: !If
        - UseRedisV5
        - !Ref Redis50CacheParameterGroup
        - !If
          - UseRedisV6
          - !Ref Redis60CacheParameterGroup
          - !If
            - UseRedisV7
            - !Ref Redis70CacheParameterGroup
            - !If
              - UseRedisV71
              - !Ref Redis71CacheParameterGroup
              - !If
                - UseValkeyV7
                - !Ref Valkey70CacheParameterGroup
                - !If
                  - UseValkeyV80
                  - !Ref Valkey80CacheParameterGroup
                  - !If
                    - UseValkeyV81
                    - !Ref Valkey81CacheParameterGroup
                    - !If
                      - UseValkeyV82
                      - !Ref Valkey82CacheParameterGroup
                      - !If
                        - UseValkeyV90
                        - !Ref Valkey90CacheParameterGroup
                        - !Ref 'AWS::NoValue'
      Port: !Ref Port
      CacheSubnetGroupName: !Ref ElasticacheSubnetGroup
      SecurityGroupIds: [!GetAtt ElasticacheSecurityGroup.GroupId]
      SnapshotRetentionLimit: !Ref SnapshotRetentionLimit
      NotificationTopicArn:
        Fn::ImportValue:
          !Sub "${SNSStackName}-TopicArn"
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: !Ref EncryptInTransit
      Engine: !Ref EngineName
      EngineVersion: !If
        - IsRedis
        - !Ref EngineVersion
        - !Ref ValkeyEngineVersion
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, cache]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  ##
  # CloudWatch Alarms
  ##
  HighCPUAlarm:
    Condition: IsProd
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, cache, high, cpu]]
      MetricName: CPUUtilization
      Namespace: AWS/ElastiCache
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 60
      Statistic: Maximum
      Threshold: 80
      AlarmActions:
        - Fn::ImportValue:
            !Sub "${SNSStackName}-TopicArn"
      OKActions:
        - Fn::ImportValue:
            !Sub "${SNSStackName}-TopicArn"
      Dimensions:
        - Name: CacheClusterId
          Value: !Join ['-', [!Ref ElasticacheReplicationGroup, '001']]
        - Name: CacheNodeId
          Value: '0001'
      TreatMissingData: notBreaching

  LowMemoryAlarm:
    Condition: IsProd
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, cache, low, mem]]
      MetricName: DatabaseMemoryUsagePercentage
      Namespace: AWS/ElastiCache
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 60
      Statistic: Maximum
      Threshold: 80
      AlarmActions:
        - Fn::ImportValue:
            !Sub "${SNSStackName}-TopicArn"
      OKActions:
        - Fn::ImportValue:
            !Sub "${SNSStackName}-TopicArn"
      Dimensions:
        - Name: CacheClusterId
          Value: !Join ['-', [!Ref ElasticacheReplicationGroup, '001']]
        - Name: CacheNodeId
          Value: '0001'
      TreatMissingData: notBreaching

Outputs:
  
  CachePrimaryEndpoint:
    Description: The DNS address of the primary read-write cache node.
    Value: 
      Fn::GetAtt: [ ElasticacheReplicationGroup, PrimaryEndPoint.Address ]
  
  SecurityGroupId:
    Description: The security group id of the cache instance
    Value: !GetAtt ElasticacheSecurityGroup.GroupId

  ClusterPort:
    Description: The port number of the cache cluster
    Value: !Ref Port

  ElasticacheReplicationGroup:
    Description: Cache cluster
    Value: !Ref ElasticacheReplicationGroup
  
  HighCPUAlarm:
    Condition: IsProd
    Description: High CPU Alarm
    Value: !GetAtt HighCPUAlarm.Arn

  LowMemoryAlarm:
    Condition: IsProd
    Description: Low Memory Alarm
    Value: !GetAtt LowMemoryAlarm.Arn

  ExportCachePrimaryEndpoint:
    Condition: HasExportOutputs
    Description: The DNS address of the primary read-write cache node.
    Value:
      Fn::GetAtt: [ ElasticacheReplicationGroup, PrimaryEndPoint.Address ]
    Export:
      Name: !Sub '${AWS::StackName}-CachePrimaryEndpoint'

  ExportSecurityGroupId:
    Condition: HasExportOutputs
    Description: The security group id of the cache instance
    Value: !GetAtt ElasticacheSecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'

  ExportClusterPort:
    Condition: HasExportOutputs
    Description: The port number of the cache cluster
    Value: !Ref Port
    Export:
      Name: !Sub '${AWS::StackName}-ClusterPort'