AWSTemplateFormatVersion: 2010-09-09
Description: Receive Email System

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Cron Configuration
        Parameters:
          - ApiKeyName
          - ApiKeyValue
          - Description
          - Endpoint
          - Schedule
          

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      ApiKeyName:
        default: API Key name
      ApiKeyValue:
        default: API Key Value (Secret)
      Description:
        default: Description
      Endpoint:
        default: Destination Endpoint
      Schedule:
        default: Cron Schedule Expression

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 8
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Staging
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ApiKeyName:
    Description: The name of the API Key Name
    Type: String
    Default: app-id
  ApiKeyValue:
    Description: Secret value of the API Key name parameter
    Type: String
    NoEcho: true
  Description:
    Description: Description
    Type: String
    Default: Cron Job
  RuleSetName:
    Type: String
  ReceiptRuleName:
    Type: String
  ReceiptDomain:
    Type: String
  MyDeadLetterQueueName:
    Type: String
    Description: Standard Queue Name
  AttachmentBucket:
    Type: String
    Description: Destination bucket to upload email attachments
  Endpoint:
    Description: Destination endpoint (URL format)
    Type: String

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

# s3 
  EmailReceiveBucket:
    Type: AWS::S3::Bucket
    # This will become an issue if the stack is removed, then recreated. If retained, the bucket name will collide with the next instance of the stack
    # Recommend not specifying bucket name here for non-prod setups
    DeletionPolicy: Retain
    Condition: UseInternalS3
    Properties:
      BucketName:
        Fn::If:
          - IsProd
          - Fn::Join: 
            - '-'
            - - Ref: OrgName
              - Fn::FindInMap: 
                - EnvShort
                - Ref: EnvName
                - Name
              - Fn::FindInMap:
                - RegionShort
                - Ref: 'AWS::Region'
                - Name 
              - Ref: Name
          - Ref: 'AWS::NoValue' #let the system choose a bucket name
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 3
          Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: 
            Fn::Join: 
              - '-'
              - - Ref: OrgName
                - Fn::FindInMap: 
                  - EnvShort
                  - Ref: EnvName
                  - Name
                - Fn::FindInMap:
                  - RegionShort
                  - Ref: 'AWS::Region'
                  - Name
                - Ref: Name
        - Key: Environment
          Value: 
            Ref: EnvName
        - Key: Organization
          Value: 
            Ref: OrgName

# Lambda
  EmailReceiveLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: extract_attachment.handler
      Role: !GetAtt EmailReceiveLambdaExecutionRole.Arn
      Runtime: Node.js 14.x
      Timeout: 300
      Variables:
         S3_EMAIL: !Ref EmailReceiveBucket
         S3_UPLOAD: !Ref AttachmentBucket
         TOPIC_ARN: !GetAtt SNSEmailReceive.Arn
      Code:
        S3Bucket: CODE_LOCATION


  EmailReceiveLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: EmailReceiveLambdaFunctionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow 
                Action: 
                  - logs:CreateLogGroup
                Resource: arn:aws:logs:us-west-2:880804344419:*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt EmailReceiveLambda.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Ref EmailReceiveBucket
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Ref AttachmentBucket
              - Effect: Allow
                Action: 
                  - sns:Publish
                  - sns:Subscribe
                Resource:
                  - !GetAtt ApiDestination.Arn             
## ses
  ReceiptRuleSet:
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: !Ref RuleSetName
      Rule:
        Name: !Ref ReceiptRuleName
        Enabled: true
        ScanEnabled: true
        Recipients: !Ref ReceiptDomain
        Actions:
          - S3Action:
              BucketName: !Ref EmailReceiveBucket
              TopicArn: !GetAtt SNSEmailReceive.Arn
  
## sns 1 trigger lambda
  SNSEmailReceive:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], snstopic]]  
    
  SNSEmailReceiveTopicPolicy:
  Type: AWS::SNS::TopicPolicy
  Properties:
    PolicyDocument:
      Statement:
        - Sid: AllowServices
          Effect: Allow
          Principal:
            Service: ses.amazonaws.com
          Action: sns:Publish
          Resource: !GetAtt SNSEmailReceive.Arn

  EmailReceiveSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !GetAtt SNSEmailReceive.Arn
      Protocol: lambda
      Endpoint: !GetAtt EmailReceiveLambda.Arn
      RedrivePolicy: |
        {
          "deadLetterTargetArn": "arn:aws:sqs:us-east-2:123456789012:MyDeadLetterQueue"
        }

  MyDeadLetterQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Ref MyDeadLetterQueueName

# sns 2 after lambda
  SNSEmailProcess:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], snstopic]]  
    
  SNSEmailProcessTopicPolicy:
  Type: AWS::SNS::TopicPolicy
  Properties:
    PolicyDocument:
      Statement:
        - Sid: AllowServices
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sns:Publish
          Resource: !GetAtt SNSEmailProcess.Arn
          
  EmailProcessSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !GetAtt SNSEmailProcess.Arn
      Protocol: https
      Endpoint: !Ref Endpoint


# Cloudwatch
  MyDeadLetterQueue:
    Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: 1209600  # 14 days
        DelaySeconds: 60 #for alarms

  DLQthresholdAlarm:
    Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmDescription: "Alarm dlq messages when we have 1 or more messages in 1 minute"
        Namespace: AWS/SQS
        MetricName: NumberOfMessagesReceived
        Dimensions:
          - Name: "QueueName"
            Value:
              Fn::GetAtt:
                - "MyDeadLetterQueue"
                - "QueueName"
        Statistic: Minimum
        Period: 60  
        DatapointsToAlarm: 1
        EvaluationPeriods: 2
        Threshold: 1
        ComparisonOperator: "GreaterThanOrEqualToThreshold"
        AlarmActions: !Ref SNSDLQAlarm

# Sns for cloudwatch

  SNSDLQAlarm:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], snstopic]]  
    
  SNSDLQAlarmTopicPolicy:
  Type: AWS::SNS::TopicPolicy
  Properties:
    PolicyDocument:
      Statement:
        - Sid: AllowServices
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - SNS:Publish
          Resource: !GetAtt SNSDLQAlarm.Arn

  SNSDLQAlarmSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !GetAtt SNSEmailProcess.Arn
      Protocol: email
      Endpoint: my_email@example.com
