AWSTemplateFormatVersion: 2010-09-09
Description: Hosted Zone setup

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Domain Configuration
        Parameters:
          - DomainName
          - VPC
    
    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      DomainName:
        default: Domain Name
      VPC:
        default: VPC

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: iscale-software.com
  VPC:
    Description: VPC to use (for local domain names only)
    Type: String
    Default: ''

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  HasVPC: !Not [!Equals [!Ref VPC, '']]

Resources:

  HostedZone: 
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref DomainName]]
      Name: !Ref DomainName
      VPCs: !If
        - HasVPC
        - - VPCId: !Ref VPC
            VPCRegion: !Ref 'AWS::Region'
        - !Ref 'AWS::NoValue'
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], hostedzone]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

Outputs:

  HostedZoneId:
    Description: Hosted Zone ID for the domain
    Value: !Ref HostedZone
    Export:
      Name: !Sub "${AWS::StackName}-HostedZoneId"

  HostedZoneDomainName:
    Description: Domain Name for the hosted zone
    Value: !Ref DomainName
    Export:
      Name: !Sub "${AWS::StackName}-HostedZoneDomainName"