AWSTemplateFormatVersion: 2010-09-09
Description: Dummy stack to retrofit network (just import the VPC) and export key params to other stacks
Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Network Configuration
        Parameters:
          - VpcCidrBlock
          - VPC

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      VpcCidrBlock:
        default: VPC CIDR Block
      VPC:
        default: VPC
      

Parameters: 
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: "network"
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  CreatePrivate:
    Description: Set to true if creation of private subnet is enabled, this creates a Nat Gateway. Otherwise, disabled.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  DefaultVPCSecurityGroup:
    Description: Default VPC Security Group
    Type: AWS::EC2::SecurityGroup::Id
  PublicSubnetId1:
    Description: Public Subnet ID 1
    Type: AWS::EC2::Subnet::Id
  PublicSubnetId2:
    Description: Public Subnet ID 2
    Type: AWS::EC2::Subnet::Id
  PrivateSubnetId1:
    Description: Private Subnet ID 1
    Type: AWS::EC2::Subnet::Id
  PrivateSubnetId2:
    Description: Private Subnet ID 2
    Type: AWS::EC2::Subnet::Id
  VPC:
    Description: VPC
    Type: AWS::EC2::VPC::Id
  VpcCidrBlock:
    Description: The CIDR block for the VPC (e.g. 10.0.0.0/23)
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  IsCreatePrivate: !Equals [!Ref CreatePrivate, true]

##
# No resource creation for this stub - just a dummy, free resource
##
Resources:

  InternetGateway:
    Type: AWS::EC2::InternetGateway

##
# The output are just matching the interface but do not rely on real resources
##

Outputs:
  VpcId: 
    Description: The ID of the VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VpcId"

  VpcCidrBlock: 
    Description: The Cidr Block of the VPC
    Value: !Ref VpcCidrBlock
    Export:
      Name: !Sub "${AWS::StackName}-VpcCidrBlock"

  PublicSubnetId1: 
    Description: Public Subnet ID for AZ1
    Value: !Ref PublicSubnetId1
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnetId1"

  PublicSubnetId2:
    Description: Public Subnet ID for AZ2
    Value: !Ref PublicSubnetId2
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnetId2"

  PublicSubnetIds:
    Description: Public Subnet Ids
    Value: !Join [',', [!Ref PublicSubnetId1, !Ref PublicSubnetId2]]
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnetIds"

  PrivateSubnetId1:
    Condition: IsCreatePrivate
    Description: Private Subnet ID for AZ1
    Value: !Ref PrivateSubnetId1
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnetId1"

  PrivateSubnetId2:
    Condition: IsCreatePrivate
    Description: Private Subnet ID for AZ2
    Value: !Ref PrivateSubnetId2
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnetId2"

  PrivateSubnetIds:
    Condition: IsCreatePrivate
    Description: Private Subnet Ids
    Value: !Join [',', [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]]
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnetIds"

  InternalSubnetId1:
    Condition: IsCreatePrivate
    Description: Internal Subnet ID for AZ1
    Value: !Ref PrivateSubnetId1
    Export:
      Name: !Sub "${AWS::StackName}-InternalSubnetId1"

  InternalSubnetId2:
    Condition: IsCreatePrivate
    Description: Internal Subnet ID for AZ2
    Value: !Ref PrivateSubnetId2
    Export:
      Name: !Sub "${AWS::StackName}-InternalSubnetId2"

  InternalSubnetIds:
    Condition: IsCreatePrivate
    Description: Internal Subnet Ids
    Value: !Join [',', [!Ref PrivateSubnetId1, !Ref PrivateSubnetId2]]
    Export:
      Name: !Sub "${AWS::StackName}-InternalSubnetIds"

  DefaultSecurityGroupId:
    Description: The default VPC security group
    Value: !Ref DefaultVPCSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-DefaultSecurityGroupId"

  Region: 
    Description: The region that an Amazon VPC was created in
    Value: !Ref 'AWS::Region'
    Export:
      Name: !Sub "${AWS::StackName}-Region"