AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions an s3 bucket to be used for lambda package in a region

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Organization Configuration
        Parameters:
          - Name
          - OrgName

    ParameterLabels:
      Name:
        default: Name
      OrgName:
        default: Organization Name

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name)
    Type: String
    Default: lambda
  OrgName:
    Description: The name of the organization (e.g. iscale-dev)
    Type: String
    Default: iscale-dev

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Resources:

####
# S3 Section
####

  # S3 bucket for lambda packages
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join [ '-', [!Ref OrgName , !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Join [ '-', [!Ref OrgName , !Ref Name]]
        - Key: Organization
          Value: !Ref OrgName
