AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions an SNS Topic and sends notifications thru slack and email

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName
      - Label:
          default: Email Configuration
        Parameters:
          - Email
          - EnableEmailSubscription
      - Label:
          default: Slack Configuration
        Parameters:
          - EnableSlackSubscription
          - OpsidianEndpoint
          - SlackOrganization

    ParameterLabels:
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      Email:
        default: Recipient Email Address
      OpsidianEndpoint:
        default: Opsidian Endpoint
      EnableEmailSubscription:
        default: Enable Email Subscription
      EnableSlackSubscription:
        default: Enable Slack Subscription
      SlackOrganization:
        default: Slack Organization Name

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  Email:
    Description: The email address where to send the notifications.
    Type: String
    Default: ""
  OpsidianEndpoint:
    Description: The slack opsidian endpoint.
    Type: String
    Default: https://api.opsidian.ai/sns/5b69a30f0c16d0256b81a4371aca06b3
  EnableEmailSubscription:
    Description: Enables email subscription. Otherwise, disabled.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  EnableSlackSubscription:
    Description: Enables slack subscription. Otherwise, disabled.
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  SlackOrganization:
    Description: Specify the Slack organization name (e.g iscale-solutions)
    Type: String
    Default: iscale-solutions

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  IsEnableEmailSubscription: !Equals [ !Ref EnableEmailSubscription, true ]
  IsEnableSlackSubscription: !Equals [ !Ref EnableSlackSubscription, true ]

Resources:
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], snstopic]]
      TopicName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], snstopic]]

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsEnableEmailSubscription
    Properties:
      Endpoint: !Ref Email
      Protocol: email
      TopicArn: !Ref SnsTopic
  
  OpsidianAccountAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: 1
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: arn:aws:iam::326365640391:root
            Condition:
              StringEquals: 
                sts:ExternalId: !Ref SlackOrganization
      ManagedPolicyArns:
            - arn:aws:iam::aws:policy/ReadOnlyAccess

  SlackSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsEnableSlackSubscription
    Properties:
      Endpoint: !Ref OpsidianEndpoint
      Protocol: https
      TopicArn: !Ref SnsTopic

  EventTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Id: Default
        Statement:
          - 
            Sid: __Default__1
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 
              - SNS:Publish
            Resource: !Ref SnsTopic
          - 
            Sid: __Default__2
            Effect: Allow
            Principal:
              AWS: "*"
            Action: 
              - SNS:Publish
            Resource: !Ref SnsTopic
      Topics: [!Ref SnsTopic]

Outputs:
  TopicArn: 
    Description: Arn of the SNS Topic
    Value: !Ref SnsTopic
    Export:
      Name: !Sub "${AWS::StackName}-TopicArn"