AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for Proseso

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: proseso
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. iscale-solutions.us).
    Type: String
    Default: proseso-consulting.com

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref ClientDomainName]]
      Name: !Ref ClientDomainName
      HostedZoneTags:
        -
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], iscale-solutions]]
        -
          Key: Environment
          Value: !Ref EnvName
        -
          Key: Organization
          Value: !Ref OrgName

  GoogleMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Ref ClientDomainName
      Comment: Google MX Records
      ResourceRecords:
        - 1 ASPMX.L.GOOGLE.COM
        - 5 ALT1.ASPMX.L.GOOGLE.COM
        - 5 ALT2.ASPMX.L.GOOGLE.COM
        - 10 ALT3.ASPMX.L.GOOGLE.COM
        - 10 ALT4.ASPMX.L.GOOGLE.COM
        - 15 qbfeebh6hl7fubeiij3ugfy3m644mgc7fqaj56ifd3wb52vwfpbq.mx-verification.google.com
      TTL: 300
      Type: MX

  WildcardCertificateValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join [".", ["_e357ae2bd1dc580df4aacef02ce98e22", !Ref ClientDomainName]]
      Type: CNAME
      TTL: 300
      Comment: !Join ["", ["Validation for *.", !Ref ClientDomainName, "in us-west-2"]]
      ResourceRecords:
        - _a291719da1b0bbec7bc3d6d8d8d5b41f.bsgbmzkfwj.acm-validations.aws.

  WWWCertificateValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join [".", ["_1c085380ae1e8a4ccd39f35889b73574", "www", !Ref ClientDomainName]]
      Type: CNAME
      TTL: 300
      Comment: !Join ["", ["Validation for www.", !Ref ClientDomainName, "in us-east-1"]]
      ResourceRecords:
        - _a300d476f470d8dcf19d4196135dcea5.bsgbmzkfwj.acm-validations.aws.