AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for Proseso

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName
          - DomainName

    ParameterLabels:
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      DomainName:
        default: Domain Name

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: proseso
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The client's domain name (e.g. example.com).
    Type: String
    Default: proseso-consulting.com

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref DomainName]]
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], iscale-solutions]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  HostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref HostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

  HostedZoneDNSSEC:
    DependsOn: HostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref HostedZone

  DomainTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      ResourceRecords:
        - '"v=spf1 include:_spf.google.com include:amazonses.com ~all"'
        - '"google-site-verification=gEpCBP46_loEiEJ3QxcbZ7nGGF8sAJ75BR7sHuq2K8M"'
      TTL: 14400
      Type: TXT
      Comment: Domain TXT Record

  GoogleMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Ref DomainName
      Comment: Google MX Records
      ResourceRecords:
        - 1 ASPMX.L.GOOGLE.COM
        - 5 ALT1.ASPMX.L.GOOGLE.COM
        - 5 ALT2.ASPMX.L.GOOGLE.COM
        - 10 ALT3.ASPMX.L.GOOGLE.COM
        - 10 ALT4.ASPMX.L.GOOGLE.COM
      TTL: 14400
      Type: MX

  WildcardCertificateValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join [".", ["_e357ae2bd1dc580df4aacef02ce98e22", !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      Comment: !Join ["", ["Validation for *.", !Ref DomainName, " in us-west-2"]]
      ResourceRecords:
        - _a291719da1b0bbec7bc3d6d8d8d5b41f.bsgbmzkfwj.acm-validations.aws.

  WWWCertificateValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join [".", ["_1c085380ae1e8a4ccd39f35889b73574", "www", !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      Comment: !Join ["", ["Validation for www.", !Ref DomainName, " in us-east-1"]]
      ResourceRecords:
        - _a300d476f470d8dcf19d4196135dcea5.bsgbmzkfwj.acm-validations.aws.

  AmazonSESDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_amazonses, !Ref DomainName]]
      ResourceRecords: 
        - "\"3Mr138o4sEQWdF6KvX+YuVK+hLia47Zpy4bdD6Boy+Y=\""
      TTL: 14400
      Type: TXT
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], amazon-ses]]

  DKIMDnsRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[xgk437g65ejkvelfh2dg6ll2a7raw5tq._domainkey, !Ref DomainName]]
      ResourceRecords: 
        - xgk437g65ejkvelfh2dg6ll2a7raw5tq.dkim.amazonses.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], dkim1]]

  DKIMDnsRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[fqnnnokfltev5dghamu54cfnisdw53vm._domainkey, !Ref DomainName]]
      ResourceRecords: 
        - fqnnnokfltev5dghamu54cfnisdw53vm.dkim.amazonses.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], dkim2]]

  DKIMDnsRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[46jukmsxo353vy7oim4lryu3n7epaasn._domainkey, !Ref DomainName]]
      ResourceRecords: 
        - 46jukmsxo353vy7oim4lryu3n7epaasn.dkim.amazonses.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], dkim3]]

  EmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref DomainName
      DkimAttributes:
        SigningEnabled: true
      DkimSigningAttributes:
        NextSigningKeyLength: RSA_1024_BIT

  VolendraSESIdentityValidationRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[vh5mj6jit4kzs4aolwuw2b5t2aalwwxr, _domainkey, !Ref DomainName]]
      ResourceRecords: 
        - vh5mj6jit4kzs4aolwuw2b5t2aalwwxr.dkim.amazonses.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], volendra-ses-1]]

  VolendraSESIdentityValidationRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[fol3yehgcrb7xn4vwjmubuvrpplftllc, _domainkey, !Ref DomainName]]
      ResourceRecords: 
        - fol3yehgcrb7xn4vwjmubuvrpplftllc.dkim.amazonses.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], volendra-ses-2]]

  VolendraSESIdentityValidationRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[skwskl4voffzr6sdrz5k2hcpsytl4fvp, _domainkey, !Ref DomainName]]
      ResourceRecords: 
        - skwskl4voffzr6sdrz5k2hcpsytl4fvp.dkim.amazonses.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], volendra-ses-3]]

  WWWRedirectS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      MetricsConfigurations:
        - Id: EntireBucket
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Join ['.', [www, !Ref DomainName]]

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Join [' ', [ 'CloudFront Origin Access for', !Ref DomainName]]
 
  StaticWebsiteCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Join [' ', [ 'Redirect for', !Ref DomainName, 'to www.', !Ref DomainName]]
        Origins:
        - DomainName: proseso-consulting.com.s3-website-us-west-2.amazonaws.com
          Id: StaticWebsiteBucketOrigin
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: http2
        Aliases:
        - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: StaticWebsiteBucketOrigin
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: all
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 3600
          MaxTTL: 86400
        PriceClass: PriceClass_All
        ViewerCertificate: 
          SslSupportMethod: sni-only
          AcmCertificateArn: arn:aws:acm:us-east-1:178070162686:certificate/557ddd03-6c74-4f52-87a5-f8f2b1c23db4

  DomainNoWWWRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt [StaticWebsiteCloudFront, DomainName]
        HostedZoneId: Z2FDTNDATAQYW2 #hardcoded for all CloudFront (per AWS documentation)

  PortalPHRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[portalph, !Ref DomainName]]
      ResourceRecords: 
        - proseso-consulting.odoo.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], portalph]]

  PortalSGRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[portalsg, !Ref DomainName]]
      ResourceRecords: 
        - proseso-consulting.odoo.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], portalsg]]