AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for employ.global

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: dns
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: employ
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: employ.global

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone: 
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref DomainName]]
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], hostedzone]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  GoogleWorkspaceMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: Google Workspace MX Records
      Name: !Ref DomainName
      Type: MX
      TTL: 3600
      ResourceRecords:
        - 1 ASPMX.L.GOOGLE.COM
        - 5 ALT1.ASPMX.L.GOOGLE.COM.
        - 5 ALT2.ASPMX.L.GOOGLE.COM.
        - 10 ALT3.ASPMX.L.GOOGLE.COM.
        - 10 ALT4.ASPMX.L.GOOGLE.COM.
        - 15 hd2b72kjg6m3f6hqvkzyhmgl6bkq2wchjrvfwp3f6brbkp3fvbyq.mx-verification.google.com.

  # WildcardSSLValidationRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join ['.',[_a265eae198094a5c2481fdd70261fdfc, !Ref DomainName]]
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - _750fe3b49c5305d4d088a617f8d8a940.vtqfhvjlcp.acm-validations.aws.

  # SESDomainVerificationRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId : !Ref HostedZone
  #     Name: !Join ['.',[_amazonses, !Ref DomainName]]
  #     ResourceRecords: 
  #       - "\"YtbwlWfd19JPPorq1ZJon7ZqADbSEMVvAy8DSdRp+R8=\""
  #       - "\"se1+hTDiOg7VICRZ3cSp5a90VcvpiGynDaVORkxXqNI=\""
  #     TTL: 14400
  #     Type: TXT
  #     Comment: SES Domain Verification

  # SESDKIMSGRecord1:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join ['.',[ttfnygwwqkzma27dosmq4kzo2uke74vf._domainkey, !Ref DomainName]]
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - ttfnygwwqkzma27dosmq4kzo2uke74vf.dkim.amazonses.com

  # SESDKIMSGRecord2:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join ['.',[2aooyfadqemzpwrkeu2zyqsr76cka7x3._domainkey, !Ref DomainName]]
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - 2aooyfadqemzpwrkeu2zyqsr76cka7x3.dkim.amazonses.com

  # SESDKIMSGRecord3:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join ['.',[m3xjbzyu7gi2lhyadoytea3euxhqbkuw._domainkey, !Ref DomainName]]
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - m3xjbzyu7gi2lhyadoytea3euxhqbkuw.dkim.amazonses.com

  # SESDKIMORRecord1:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join ['.',[qjhzw3t6ejuhyq4bw4up2qysc7wi6j2v._domainkey, !Ref DomainName]]
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - qjhzw3t6ejuhyq4bw4up2qysc7wi6j2v.dkim.amazonses.com

  # SESDKIMORRecord2:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join ['.',[d6qe4pcdrgc52plft65khxqrluljnlpz._domainkey, !Ref DomainName]]
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - d6qe4pcdrgc52plft65khxqrluljnlpz.dkim.amazonses.com

  # SESDKIMORRecord3:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join ['.',[irvatckxot6slqbarkojo734tf7mbapr._domainkey, !Ref DomainName]]
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - irvatckxot6slqbarkojo734tf7mbapr.dkim.amazonses.com

  # SESMXRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Comment: SES Inbound MX Records
  #     Name: !Ref DomainName
  #     Type: MX
  #     TTL: 3600
  #     ResourceRecords:
  #       - 10 inbound-smtp.us-east-1.amazonaws.com