AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for Proseso

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName
          - DomainName

    ParameterLabels:
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      DomainName:
        default: Domain Name

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: knob
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The client's domain name (e.g. example.com).
    Type: String
    Default: knob.ph

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref DomainName]]
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], iscale-solutions]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  GoogleMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Ref DomainName
      Comment: Google MX Records
      ResourceRecords:
        - 1 SMTP.GOOGLE.COM
        - 15 7lvvqm7gsetfzmnctlhraobffgbinhg2twvuuk4ggq7cchgkubja.mx-verification.google.com.
      TTL: 86400
      Type: MX
  
  GmailDKIMRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[google._domainkey, !Ref DomainName]]
      ResourceRecords:
        - '"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCKKO2LOCqbQllTV5OFf+AwFBTFnQNrQOQ0bbnadqbY3N+rqV2ndffIDWMKYLVRVQo3kZInbFU6xzYwCfGs8VBVwUw5l2HpOmFg8NCK9EUBDFzwmiHHai6VMs85zjBDj+3mHTYzTDH06tXkZlNLOlUe+9TpjYbKdaK/Fen9AkRv+QIDAQAB"'
      TTL: 14400
      Type: TXT
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], gmail, dkim]]

  DMARCRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: DMARC record
      Name: !Join ['.', [_dmarc, !Ref DomainName]]
      Type: TXT
      TTL: 14400
      ResourceRecords:
        - !Join ['', ["\"v=DMARC1;fo=1;p=reject;rua=mailto:dmarc@", !Ref DomainName, "\""]]

  DomainSSLCertValidation:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_79ecfe5d2702fc1543dc8767ddf50a39, !Ref DomainName]]
      ResourceRecords:
        - _658dd64d127713acc6d3c6ce3c868193.qxcwttcyyb.acm-validations.aws.
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], odoo, ssl, validation]]

  WildcardSSLCertValidation:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_79ecfe5d2702fc1543dc8767ddf50a39, !Ref DomainName]]
      ResourceRecords:
        - _658dd64d127713acc6d3c6ce3c868193.qxcwttcyyb.acm-validations.aws.
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], odoo, ssl, validation]]