AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions an s3 bucket to be used as template url

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Organization Configuration
        Parameters:
          - Name
          - OrgName

    ParameterLabels:
      Name:
        default: Name
      OrgName:
        default: Organization Name

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name)
    Type: String
    Default: s3
  OrgName:
    Description: The name of the organization (e.g. iscale-dev)
    Type: String
    Default: volendra

Resources:

####
# S3 Section
####

  # S3 bucket for Volendra internal S3 bucket
  DataS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [!Ref OrgName, s3, data]]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Join [ '-', [!Ref OrgName , s3, data]]
        - Key: Organization
          Value: !Ref OrgName

  DataS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DataS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject*
              - s3:GetObject*
              - s3:DeleteObject
            Resource:
              - !GetAtt DataS3Bucket.Arn
              - !Join ['/',[!GetAtt DataS3Bucket.Arn, '*']]
            Principal:
              AWS:
                - !Ref 'AWS::AccountId'

  # S3 bucket for Volendra internal S3 bucket
  SharedS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [!Ref OrgName , s3, shared]]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Join [ '-', [!Ref OrgName , s3, shared]]
        - Key: Organization
          Value: !Ref OrgName

  SharedS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SharedS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: 
              - s3:PutObject*
              - s3:GetObject*
              - s3:DeleteObject
            Resource:
              - !GetAtt SharedS3Bucket.Arn
              - !Join ['/',[!GetAtt SharedS3Bucket.Arn,'*']]
            Principal:
              AWS:
                - !Ref 'AWS::AccountId'
                - 178070162686 #iscale-hosting is allowed to write in that bucket
                - 489336767866 #employ is allowed to write in that bucket
