AWSTemplateFormatVersion: 2010-09-09
Description: Zion ELB Deployment

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName
          - DeletionProtection
      - Label:
          default: Load Balancer Configuration
        Parameters:
          - ClientDomainName
          - LoadBalancerCertificateArn
          - LoadBalancerHostName

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      DeletionProtection:
        default: Protect core items against deletion
      LoadBalancerCertificateArn:
        default: Load Balancer SSL Certificate ARN
      LoadBalancerHostName:
        default: Load Balancer Host Name
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Topic Stack Name
      ClientDomainName:
        default: Domain Name

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name)
    Type: String
    MinLength: 3
    MaxLength: 12
    Default: zion
  OrgName:
    Description: The name of the organization
    Type: String
    Default: iscale
    AllowedPattern: '^[a-z]+(-[a-z]+)*$'
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-software.com)
    Type: String
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    Default: iscale-solutions.com
    MinLength: 1
  DeletionProtection:
    Description: Set to true to enable (valid only in Production mode)
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  LoadBalancerHostName:
    Description: (Optional) Custom Hostname for load balancer URL
    Type: String
    Default: ''
    MaxLength: 12
  LoadBalancerCertificateArn:
    Description: SSL Certificate for the ELB
    Type: String
    Default: arn:aws:acm:us-west-2:178070162686:certificate/f8e7a815-3e31-4644-baa5-19c87b7d74d1
  NetworkStackName:
    Description: The name of the network stack
    Type: String
    Default: iscale-hosting-prd-uw2-internal-network
    MinLength: 1
  SNSStackName:
    Description: The name of the SNS stack
    Type: String
    Default: iscale-hosting-prd-uw2-sns
    MinLength: 1

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

##
# Common Zion resources
##

  ELBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/loadbalancer.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        CertificateArn: !Ref LoadBalancerCertificateArn
        SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName
