AWSTemplateFormatVersion: 2010-09-09
Description: PCHC CICS2 ECR repository and env bucket

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName
      - Label:
          default: DocumentDB Configuration
        Parameters:
          - ClusterType
          - ShardCapacity
          - ShardCount
          - ShardInstanceCount

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 20
    Default: 'cics2-prereq'
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: pchc
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Staging
    AllowedValues:
      - Production #Prod
      - Staging #Pre-production
      - Development #Regular day to day commit / deplay
      - Test 
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: 'pchc-stg-uw2-cics2-network'
    MinLength: 1
  SNSStackName:
    Description: The name of the SNS stack.
    Type: String
    Default: 'pchc-test-uw2-sns'
    MinLength: 1
  ClusterType:
    Description: DocumentDB cluster type.
    Type: String
    Default: elastic
    AllowedValues:
      - instance
      - elastic
  ShardCapacity:
    Description: The number of vCPUs assigned to each elastic cluster shard. 
    Type: Number
    Default: 2
    AllowedValues: [2, 4, 8, 16, 32, 64]
  ShardCount:
    Description: The number of shards assigned to the elastic cluster.
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 32
    ConstraintDescription: Maximum is 32.
  ShardInstanceCount:
    Description: 'The number of replica instances applying to all shards in the cluster. A shardInstanceCount value of 1 means there is one writer instance, and any additional instances are replicas that can be used for reads and to improve availability.'
    Type: Number
    Default: 1

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

###
# ECR section
###

  ECR:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: false
      EncryptionConfiguration: 
        EncryptionType: AES256
      ImageScanningConfiguration: 
        ScanOnPush: true
      ImageTagMutability: MUTABLE # MUTABLE=overwritten, IMMUTABLE=not
      # LifecyclePolicy: 
      #   LifecyclePolicy
      RepositoryName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Select [0, !Split ["-", !Ref Name]], icltool-ecr]]
      # RepositoryPolicyText: Json
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Select [0, !Split ["-", !Ref Name]], icltool-ecr]]
  
  ECRPortal:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: false
      EncryptionConfiguration: 
        EncryptionType: AES256
      ImageScanningConfiguration: 
        ScanOnPush: true
      ImageTagMutability: MUTABLE # MUTABLE=overwritten, IMMUTABLE=not
      # LifecyclePolicy: 
      #   LifecyclePolicy
      RepositoryName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Select [0, !Split ["-", !Ref Name] ], portal-ecr]]
      # RepositoryPolicyText: Json
      Tags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Select [0, !Split ["-", !Ref Name] ], portal-ecr]]

###
# S3 section
###

  S3Bucket:
    Type: AWS::S3::Bucket
    # This will become an issue if the stack is removed, then recreated. If retained, the bucket name will collide with the next instance of the stack
    # Recommend not specifying bucket name here for non-prod setups
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, env-bucket]]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 3
          Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags: 
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, env-bucket]]
        - Key: Organization
          Value: !Ref OrgName
  
  IclS3Bucket:
    Type: AWS::S3::Bucket
    # This will become an issue if the stack is removed, then recreated. If retained, the bucket name will collide with the next instance of the stack
    # Recommend not specifying bucket name here for non-prod setups
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Select [0, !Split ["-", !Ref Name] ], icltool-bucket]]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 3
          Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags: 
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Select [0, !Split ["-", !Ref Name] ], icltool-bucket]]
        - Key: Organization
          Value: !Ref OrgName

###
# Document DB Section
###

  DocumentDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/docdb-database.yaml
      Parameters:
        Name: !Select [0, !Split ["-", !Ref Name] ] # cics2-prereq = [cics2, prereq]
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        ClusterType: !Ref ClusterType #instance | elastic
        BackupRetentionPeriod: !If [IsProd, 30, 7]
        ShardCapacity: !Ref ShardCapacity
        ShardCount: !Ref ShardCount
        ShardInstanceCount: !Ref ShardInstanceCount
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName

# allow jumpserver to docuDB

  AllowJumphostToDocumentDB:
    Condition: IsNotProd
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow connection from Jumphost to Document DB
      IpProtocol: TCP
      GroupId:
        Fn::GetAtt:
          - DocumentDBStack
          - Outputs.DocuDBElasticSecurityGroup
      FromPort: 27017
      ToPort: 27017
      SourceSecurityGroupId:
        Fn::ImportValue:
          !Sub '${NetworkStackName}-JumpHostSecurityGroupId'


########### Backup Section configure this, AWS Backup now supports DocumentDB

  BackupStack:
    Condition: IsProd
    DependsOn:
      - DocumentDBStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/backup.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        BackupARNList: !Join
          - ','
          - - Fn::GetAtt:
              - DocumentDBStack
              - Outputs.DBInstanceARN
        BackupTime: !If [IsProd, !Ref 'AWS::NoValue', 1] #Default backup time else 1AM UTC for dev
        DailyExpiration: 60 #60 days
        WeeklyExpiration: 180 #6 months but requirement is 4 weeks
        MonthlyExpiration: 3650 # 10 years

Outputs:
  EcrName:
    Description: DNS name of the Application Load Balancer
    Value: !Ref ECR
    Export:
      Name: !Sub ${AWS::StackName}-IclEcrName

  EcrArnName:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ECR.Arn
    Export:
      Name: !Sub ${AWS::StackName}-IclEcrArnName
  
  PortalEcrName:
    Description: DNS name of the Application Load Balancer
    Value: !Ref ECRPortal
    Export:
      Name: !Sub ${AWS::StackName}-PortalEcrName

  PortalEcrArnName:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ECRPortal.Arn
    Export:
      Name: !Sub ${AWS::StackName}-PortalEcrArnName

  S3Name:
    Description: Endpoint URL
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${AWS::StackName}-PortalS3Name
  
  IclS3Name:
    Description: Endpoint URL
    Value: !Ref IclS3Bucket
    Export:
      Name: !Sub ${AWS::StackName}-IclS3Name
  
  DocumentDBStackName:
    Description: DocumentDB stack name
    Value: !Ref DocumentDBStack
    Export:
      Name: !Sub ${AWS::StackName}-DocumentDBStackName
  
  DocuDBElasticSecurityGroup:
    Description: DocumentDB elastic security group
    Value: !GetAtt DocumentDBStack.Outputs.DocuDBElasticSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-DocuDBElasticSecurityGroup
  
  
