AWSTemplateFormatVersion: 2010-09-09
Description: Domain redirects to boholpadelclub.com. This MUST be run in us-east-1 for SSL

## boholpadel-prd-ue1-redirect

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      DomainName:
        default: Domain Name

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 10
    Default: redirects
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: boholpadel
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The domain name to be redirected to
    Type: String
    Default: boholpadelclub.com

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
      
Resources:

  ## bohol-padel-club.com ##
  BoholDashPadelDashClubDotComHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: bohol-padel-club.com

  # BoholDashPadelDashClubDotComSSLCert:
  #   Type: AWS::CertificateManager::Certificate
  #   Properties:
  #     DomainName: bohol-padel-club.com
  #     SubjectAlternativeNames:
  #       - www.bohol-padel-club.com
  #     ValidationMethod: DNS

  # BoholDashPadelDashClubDotComSSLValidationRecord1:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref BoholDashPadelDashClubDotComHostedZone
  #     Name: _f2e44ccb4b48539848045a6834a4154e.bohol-padel-club.com.
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - _34939d5b6ed2a0f2a52e8260cde2fddc.xlfgrmvvlj.acm-validations.aws.

  # BoholDashPadelDashClubDotComSSLValidationRecord2:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref BoholDashPadelDashClubDotComHostedZone
  #     Name: _f6b49407f082303916ecd8d06b172d17.www.bohol-padel-club.com.
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - _1c8ba5bb93f0355730994153b1c333c4.xlfgrmvvlj.acm-validations.aws.

  BoholDashPadelDashClubDotComHostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref BoholDashPadelDashClubDotComHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

  # BoholDashPadelDashClubDotComHostedZoneDNSSEC:
  #   DependsOn: BoholDashPadelDashClubDotComHostedZoneDNSSECSigningKey
  #   Type: AWS::Route53::DNSSEC
  #   Properties:
  #     HostedZoneId: !Ref BoholDashPadelDashClubDotComHostedZone

  # BoholDashPadelDashClubDotCom:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/domain-redirect-s3.yaml
  #     Parameters:
  #       Name: !Ref Name
  #       EnvName: !Ref EnvName
  #       OrgName: !Ref OrgName
  #       DomainSSLCert: !Ref BoholDashPadelDashClubDotComSSLCert
  #       SourceDomainName: bohol-padel-club.com
  #       RedirectDomainName: !Ref DomainName


  ## bohol-padel.com ##
  BoholDashPadelDotComHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: bohol-padel.com

  # BoholDashPadelDotComSSLCert:
  #   Type: AWS::CertificateManager::Certificate
  #   Properties:
  #     DomainName: bohol-padel.com
  #     SubjectAlternativeNames:
  #       - www.bohol-padel.com
  #     ValidationMethod: DNS

  # BoholDashPadelDotComSSLValidationRecord1:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref BoholDashPadelDotComHostedZone
  #     Name: _f4ad2517898f460286a92ee7a2497b93.bohol-padel.com.
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - _97fd897bf19208c90984f0ce8cc66731.xlfgrmvvlj.acm-validations.aws.

  # BoholDashPadelDotComSSLValidationRecord2:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref BoholDashPadelDotComHostedZone
  #     Name: _ee4125ddca95a73e83979ceffae41d7b.www.bohol-padel.com.
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - _ae95d05777e870d76edf013ba5f5e697.xlfgrmvvlj.acm-validations.aws.

  BoholDashPadelDotComHostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref BoholDashPadelDotComHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

  # BoholDashPadelDotComHostedZoneDNSSEC:
  #   DependsOn: BoholDashPadelDotComHostedZoneDNSSECSigningKey
  #   Type: AWS::Route53::DNSSEC
  #   Properties:
  #     HostedZoneId: !Ref BoholDashPadelDotComHostedZone

  # BoholDashPadelDotCom:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/domain-redirect-s3.yaml
  #     Parameters:
  #       Name: !Ref Name
  #       EnvName: !Ref EnvName
  #       OrgName: !Ref OrgName
  #       DomainSSLCert: !Ref BoholDashPadelDotComSSLCert
  #       SourceDomainName: bohol-padel.com
  #       RedirectDomainName: !Ref DomainName


  ## boholpadel.com ##
  BoholPadelDotComHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: boholpadel.com

  # BoholPadelDotComSSLCert:
  #   Type: AWS::CertificateManager::Certificate
  #   Properties:
  #     DomainName: boholpadel.com
  #     SubjectAlternativeNames:
  #       - www.boholpadel.com
  #     ValidationMethod: DNS

  # BoholPadelDotComSSLValidationRecord1:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref BoholPadelDotComHostedZone
  #     Name: _071f0b87b38c86849abfa592344645ba.boholpadel.com.
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - _ecbaeaa0cd262b3a35d03e0be8f56aac.xlfgrmvvlj.acm-validations.aws.

  # BoholPadelDotComSSLValidationRecord2:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref BoholPadelDotComHostedZone
  #     Name: _5cc78c955410ab3827a8aa6a7331c755.www.boholpadel.com.
  #     Type: CNAME
  #     TTL: 14400
  #     ResourceRecords:
  #       - _fdb0c1ceee4124d9c159edb154d8bf42.xlfgrmvvlj.acm-validations.aws.

  BoholPadelDotComHostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref BoholPadelDotComHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

  # BoholPadelDotComHostedZoneDNSSEC:
  #   DependsOn: BoholPadelDotComHostedZoneDNSSECSigningKey
  #   Type: AWS::Route53::DNSSEC
  #   Properties:
  #     HostedZoneId: !Ref BoholPadelDotComHostedZone

  # BoholPadelDotCom:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/domain-redirect-s3.yaml
  #     Parameters:
  #       Name: !Ref Name
  #       EnvName: !Ref EnvName
  #       OrgName: !Ref OrgName
  #       DomainSSLCert: !Ref BoholPadelDotComSSLCert
  #       SourceDomainName: boholpadel.com
  #       RedirectDomainName: !Ref DomainName

## bohol-padel-club.com.ph ##
  BoholDashPadelDashClubDotComDotPHHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: bohol-padel-club.com.ph

  BoholDashPadelDashClubDotComDotPHDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref BoholDashPadelDashClubDotComDotPHHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

## boholpadelclub.com.ph ##
  BoholPadelClubDotComDotPHHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: boholpadelclub.com.ph

  BoholPadelClubDotComDotPHDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref BoholPadelClubDotComDotPHHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

## bohol-padel.com.ph ##
  BoholDashPadelDotComDotPHHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: bohol-padel.com.ph

  BoholDashPadelDotComDotPHDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref BoholDashPadelDotComDotPHHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

## boholpadel.com.ph ##
  BoholPadelDotComDotPHHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: boholpadel.com.ph

  BoholPadelDotComDotPHDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref BoholPadelDotComDotPHHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

## bohol-padel-club.ph ##
  BoholDashPadelDashClubDotPHHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: bohol-padel-club.ph

  BoholDashPadelDashClubDotPHDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref BoholDashPadelDashClubDotPHHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

## boholpadelclub.ph ##
  BoholPadelClubDotPHHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: boholpadelclub.ph

  BoholPadelClubDotPHDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref BoholPadelClubDotPHHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

## bohol-padel.ph ##
  BoholDashPadelDotPHHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: bohol-padel.ph

  BoholDashPadelDotPHDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref BoholDashPadelDotPHHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

## boholpadel.ph ##
  BoholPadelDotPHHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: boholpadel.ph

  BoholPadelDotPHDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref BoholPadelDotPHHostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE
