AWSTemplateFormatVersion: 2010-09-09
Description: Externisy IAM users

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: externisy
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  OdooProdAccessGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ['-',[!Ref OrgName, odoo, prod, access]]
      Policies:
        - PolicyName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], odoo, prod, policy]]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: TerminateSSM
                Effect: Allow
                Action:
                  - ssm:ResumeSession
                  - ssm:TerminateSession
                Resource:
                  - arn:aws:ssm:*:*:session/${aws:username}-*
              - Sid: AllowSSMinEC2
                Effect: Allow
                Action:
                  - ssm:StartSession
                Resource: !Sub 'arn:aws:ec2:*:${AWS::AccountId}:instance/*'
                Condition:
                  StringLike:
                    ssm:resourceTag/Name: externisy-prd-ew3-odoo
              - Sid: AllowSSMSessionListing
                Effect: Allow
                Action:
                  - cloudwatch:DescribeAlarms
                  - ssm:DescribeSessions
                  - ssm:GetConnectionStatus
                  - ssm:DescribeInstanceProperties
                  - ssm:DescribeInstanceInformation
                  - ec2:DescribeInstances
                Resource: '*'

  OdooTestAccessGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ['-',[!Ref OrgName, odoo, test, access]]
      Policies:
        - PolicyName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], odoo, test, policy]]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: TerminateSSM
                Effect: Allow
                Action:
                  - ssm:ResumeSession
                  - ssm:TerminateSession
                Resource:
                  - arn:aws:ssm:*:*:session/${aws:username}-*
              - Sid: AllowSSMinEC2
                Effect: Allow
                Action:
                  - ssm:StartSession
                Resource: !Sub 'arn:aws:ec2:*:${AWS::AccountId}:instance/*'
                Condition:
                  StringLike:
                    ssm:resourceTag/Name: externisy-test-ew3-odoo
              - Sid: AllowSSMSessionListing
                Effect: Allow
                Action:
                  - cloudwatch:DescribeAlarms
                  - ssm:DescribeSessions
                  - ssm:GetConnectionStatus
                  - ssm:DescribeInstanceProperties
                  - ssm:DescribeInstanceInformation
                  - ec2:DescribeInstances
                Resource: '*'

  TPPScraperAccessGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ['-',[!Ref OrgName, tpp, scraper, access]]
      Policies:
        - PolicyName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], tpp, scraper]]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowOnOffServer
                Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:RebootInstances
                  - ec2:StartInstances
                  - ec2:StopInstances
                Resource: !Join [":", ["arn", "aws", "ec2", !Ref 'AWS::Region', !Ref 'AWS::AccountId', !Join ['/', ['instance', 'i-0024bc96914ed02fd']]]]
              - Sid: AllowResizeServer
                Effect: Allow
                Action:
                  - ec2:ModifyInstanceAttribute
                Resource: !Join [":", ["arn", "aws", "ec2", !Ref 'AWS::Region', !Ref 'AWS::AccountId', !Join ['/', ['instance', 'i-0024bc96914ed02fd']]]]
                Condition:
                  StringEquals:
                    ec2:Attribute: InstanceType

  AlexIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Alex123!! #will be reset right away
        PasswordResetRequired: true
      UserName: alex@iscale-solutions.com
      Groups:
        - Billing
        - ReadOnly
        - MFA
        - !Ref TPPScraperAccessGroup

  MandaIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Manda123! #will be reset right away
        PasswordResetRequired: true
      UserName: manda@iscale-solutions.com
      Groups:
        - Billing
        - ReadOnly
        - MFA
        - !Ref OdooProdAccessGroup
        - !Ref OdooTestAccessGroup
        - !Ref TPPScraperAccessGroup

  GithubUser:
    Type: AWS::IAM::User
    Properties:
      UserName: github_user
      Tags:
        - Key: Name
          Value: Github Access
        - Key: Email
          Value: github@externisy.fr

  GithubUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: GithubUser

# Outputs:

#   GithubUserAccessKeyId:
#     Description: Access Key Id for the Github user
#     Value: !Ref GithubUserAccessKey
  
#   GithubUserAccessKeySecret:
#     Description: Secret Key for the Github user
#     Value: !GetAtt [GithubUserAccessKey, SecretAccessKey]