AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for Externisy

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: externisy
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DomainName:
    Description: The client's domain name (e.g. iscale-solutions.us).
    Type: String
    Default: externisy.fr

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  IsIscaleHosting: !Equals [178070162686, !Ref 'AWS::AccountId']
  IsNotIscaleHosting: !Not [Condition: IsIscaleHosting]

Resources:

####
# Route53 Section
####

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref DomainName]]
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], iscale-solutions]]

  HostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref HostedZone
      KeyManagementServiceArn: !If
        - IsIscaleHosting
        - arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
        - arn:aws:kms:us-east-1:251337970614:key/d5f7cefc-d68d-4f82-8280-8b6b686387cf
      Name: key_signing_key
      Status: ACTIVE

  HostedZoneDNSSEC:
    DependsOn: HostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref HostedZone

  DomainTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      ResourceRecords:
        - '"v=spf1 include:_spf.google.com include:amazonses.com -all"'
        - '"google-site-verification=SyCBNt5jcla76ouNqCmCxDNlfu-MQ7zPwpqHnEcUV04"'
      TTL: 14400
      Type: TXT
      Comment: Domain TXT Record

  GoogleMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Ref DomainName
      Comment: Google MX Records
      ResourceRecords:
        - 1 ASPMX.L.GOOGLE.COM
        - 5 ALT1.ASPMX.L.GOOGLE.COM
        - 5 ALT2.ASPMX.L.GOOGLE.COM
        - 10 ALT3.ASPMX.L.GOOGLE.COM
        - 10 ALT4.ASPMX.L.GOOGLE.COM
      TTL: 14400
      Type: MX

  WildcardCertificateValidationRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join [".", ["_63185c6cf306c59fbe51cef8cc9d66b2", !Ref DomainName]]
      Type: CNAME
      TTL: 14400
      Comment: !Join ["", ["Validation for *.", !Ref DomainName, " in us-west-2"]]
      ResourceRecords:
        - _f15af7fd52c12817b3f10e5a5ebb452a.chvvfdvqrj.acm-validations.aws.

  AmazonSESDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_amazonses, !Ref DomainName]]
      ResourceRecords:
        - "\"ulLlUjWutgCH22B1EJ3LbtTUQ/kf61cCs8roBbW3TYc=\""
      TTL: 14400
      Type: TXT
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], amazon-ses]]

  GmailDKIMRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[google._domainkey, !Ref DomainName]]
      ResourceRecords: 
        - '"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCRwlal8tqehcrUGc49Vnfv6P3qZHb9bCYoOowHRdWXmbNYv3sx7RXrw7YQauG+VRrcYxqXaw7dweSIYXko5zssVndoO6h4QNVCzitoW1lvFl3b7Z8J65vjiTFqbJkTtURmTPXM+kC219hrrPSkbL7VfQ6+5DBOn2U4lIJpFpRHSwIDAQAB"'
      TTL: 14400
      Type: TXT
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], gmail, dkim]]

  DKIMDnsRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[keph7r2uokinlkgmgoxp4kwdb7gqjnft._domainkey, !Ref DomainName]]
      ResourceRecords: 
        - keph7r2uokinlkgmgoxp4kwdb7gqjnft.dkim.amazonses.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], dkim1]]

  DKIMDnsRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[ccfud7gtpk3zpgiazugegbvgubtsxmwh._domainkey, !Ref DomainName]]
      ResourceRecords: 
        - ccfud7gtpk3zpgiazugegbvgubtsxmwh.dkim.amazonses.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], dkim2]]

  DKIMDnsRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[bjueoaimmcjnc6dd5fkpio2ujplw7t2i._domainkey, !Ref DomainName]]
      ResourceRecords: 
        - bjueoaimmcjnc6dd5fkpio2ujplw7t2i.dkim.amazonses.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], dkim3]]

  DMARCRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: DMARC record
      Name: !Join ['.', [_dmarc, !Ref DomainName]]
      Type: TXT
      TTL: 14400
      ResourceRecords:
        - !Join ['', ["\"v=DMARC1;p=reject;pct=100;fo=1;rua=mailto:dmarc@", !Ref DomainName, "\""]]

  OdooCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[odoo, !Ref DomainName]]
      ResourceRecords: 
        - Hosti-Publi-JOP96QI64S4H-402462131.us-west-2.elb.amazonaws.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], widooit, odoo, ssl, validation]]

  WidooitOdooSSLCertValidation:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_55be172b290a662d0346d902a0110177.widooit-odoo, !Ref DomainName]]
      ResourceRecords: 
        - _e75e930e667bd83964701bfce2118b87.mwfgkbkczp.acm-validations.aws
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], odoo, cname]]

  OdooSSLCertValidation:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_9c73631bcd6bd04a2a3fd575c6325066.odoo, !Ref DomainName]]
      ResourceRecords: 
        - _94012ece33a3c47a43efb8ccd0365f5d.mwfgkbkczp.acm-validations.aws
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], odoo, ssl, validation]]

  WidooitOdooSSLCertValidation:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_55be172b290a662d0346d902a0110177.widooit-odoo, !Ref DomainName]]
      ResourceRecords: 
        - _e75e930e667bd83964701bfce2118b87.mwfgkbkczp.acm-validations.aws
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], widooit, odoo, ssl, validation]]

  EW3DKIMRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[chanchbnxeuolsyb3s56mfr2kuvy2fm2._domainkey, !Ref DomainName]]
      ResourceRecords: 
        - chanchbnxeuolsyb3s56mfr2kuvy2fm2.dkim.amazonses.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], dkim1]]

  EW3DKIMRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[a2vbafqvyu7iizwgh6ndsfsajvcnhtht._domainkey, !Ref DomainName]]
      ResourceRecords: 
        - a2vbafqvyu7iizwgh6ndsfsajvcnhtht.dkim.amazonses.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], dkim2]]

  EW3DKIMRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[jyz7jbhc42mak5yszmbd4c3iogqjfvfg._domainkey, !Ref DomainName]]
      ResourceRecords: 
        - jyz7jbhc42mak5yszmbd4c3iogqjfvfg.dkim.amazonses.com
      TTL: 14400
      Type: CNAME
      Comment: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], dkim3]]

    