AWSTemplateFormatVersion: 2010-09-09
Description: VPC Peering Setup for Monitoring
Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Network Configuration
        Parameters:
          - RequesterNetworkStackName
      - Label:
          default: CICS
        Parameters:
          - TargetNetworkStackNameCICS
      - Label:
          default: DSAPP
        Parameters:
          - TargetNetworkStackNameDSAPP
      - Label:
          default: PAYGATE
        Parameters:
          - TargetNetworkStackNamePAYGATE
      - Label:
          default: PDDTSEOD
        Parameters:
          - TargetNetworkStackNamePDDTSEOD

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName: 
        default: Environment Name
# requester - monitoring vpc
      RequesterNetworkStackName:
        default: Requester Network Stack Name
# target vpc 1 - cics
      TargetNetworkStackNameCICS:
        default: Target Network Stack Name
# target vpc 2 - dsapp
      TargetNetworkStackNameDSAPP:
        default: Target Network Stack Name
# target vpc 3 - paygate
      TargetNetworkStackNamePAYGATE:
        default: Target Network Stack Name
# target vpc 4 - pddtseod
      TargetNetworkStackNamePDDTSEOD:
        default: Target Network Stack Name

Parameters: 
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: network
    MinLength: 3
    MaxLength: 20
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 12
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
# Requester - Fortigate network
  RequesterNetworkStackName:
    Description: The name of the requester cloudformation Network stack
    Type: String
    Default: pchc-test-uw2-monitor-network
# target vpc 1 - cics
  TargetNetworkStackNameCICS:
    Description: The name of the target cloudformation Network stack
    Type: String
    Default: pchc-test-uw2-cics-network
# target vpc 2 - dsapp
  TargetNetworkStackNameDSAPP:
    Description: The name of the target cloudformation Network stack
    Type: String
    Default: pchc-test-uw2-dsapp-network
# target vpc 3 - paygate
  TargetNetworkStackNamePAYGATE:
    Description: The name of the target cloudformation Network stack
    Type: String
    Default: pchc-test-uw2-paygate-network
# target vpc 4 - pddtseod
  TargetNetworkStackNamePDDTSEOD:
    Description: The name of the target cloudformation Network stack
    Type: String
    Default: pchc-test-uw2-pddts-eod-network

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

###
# VPC Peering to Target VPC - CICS
###

  VPCPeeringToCICSNetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/vpc-peering.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName

        # Requester VPC Monitor
        RequesterVpcId: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-VpcId'
        RequesterCidr: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-VpcCidrBlock'
        RequesterPublicRouteTable: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-PublicRouteTable'


        # Target VPC CICS
        TargetVpcId: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNameCICS}-VpcId'
        TargetCidr: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNameCICS}-VpcCidrBlock'
        TargetPublicRouteTable: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNameCICS}-PublicRouteTable'
        TargetPrivateRouteTable1: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNameCICS}-PrivateRouteTable1'
        TargetPrivateRouteTable2: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNameCICS}-PrivateRouteTable2'
        TargetPrivateRouteTable3: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNameCICS}-PrivateRouteTable3'

###
# VPC Peering to Target VPC - DSAPP
###

  VPCPeeringToDSAPPNetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/vpc-peering.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName

        # Requester VPC Monitor
        RequesterVpcId: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-VpcId'
        RequesterCidr: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-VpcCidrBlock'
        RequesterPublicRouteTable: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-PublicRouteTable'


        # Target VPC CICS
        TargetVpcId: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNameDSAPP}-VpcId'
        TargetCidr: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNameDSAPP}-VpcCidrBlock'
        TargetPublicRouteTable: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNameDSAPP}-PublicRouteTable'
        TargetPrivateRouteTable1: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNameDSAPP}-PrivateRouteTable1'
        TargetPrivateRouteTable2: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNameDSAPP}-PrivateRouteTable2'
        # TargetPrivateRouteTable3: !ImportValue
        #   'Fn::Sub': '${TargetNetworkStackNameDSAPP}-PrivateRouteTable3'

###
# VPC Peering to Target VPC - paygate
###

  VPCPeeringToPAYGATENetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/vpc-peering.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName

        # Requester VPC Monitor
        RequesterVpcId: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-VpcId'
        RequesterCidr: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-VpcCidrBlock'
        RequesterPublicRouteTable: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-PublicRouteTable'


        # Target VPC CICS
        TargetVpcId: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNamePAYGATE}-VpcId'
        TargetCidr: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNamePAYGATE}-VpcCidrBlock'
        TargetPublicRouteTable: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNamePAYGATE}-PublicRouteTable'
        TargetPrivateRouteTable1: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNamePAYGATE}-PrivateRouteTable1'
        TargetPrivateRouteTable2: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNamePAYGATE}-PrivateRouteTable2'
        # TargetPrivateRouteTable3: !ImportValue
        #   'Fn::Sub': '${TargetNetworkStackNamePAYGATE}-PrivateRouteTable3'

###
# VPC Peering to Target VPC - PDDTSEOD
###

  VPCPeeringToPDDTSEODNetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/vpc-peering.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName

        # Requester VPC Monitor
        RequesterVpcId: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-VpcId'
        RequesterCidr: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-VpcCidrBlock'
        RequesterPublicRouteTable: !ImportValue
          'Fn::Sub': '${RequesterNetworkStackName}-PublicRouteTable'


        # Target VPC CICS
        TargetVpcId: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNamePDDTSEOD}-VpcId'
        TargetCidr: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNamePDDTSEOD}-VpcCidrBlock'
        TargetPublicRouteTable: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNamePDDTSEOD}-PublicRouteTable'
        TargetPrivateRouteTable1: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNamePDDTSEOD}-PrivateRouteTable1'
        TargetPrivateRouteTable2: !ImportValue
          'Fn::Sub': '${TargetNetworkStackNamePDDTSEOD}-PrivateRouteTable2'
        # TargetPrivateRouteTable3: !ImportValue
        #   'Fn::Sub': '${TargetNetworkStackNamePDDTSEOD}-PrivateRouteTable3'
