AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for HimexCorp.com

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: himex
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. iscale-solutions.us).
    Type: String
    Default: himexcorp.com

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref ClientDomainName]]
      Name: !Ref ClientDomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], iscale-solutions]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  DefaultDomainKeyTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[default._domainkey, !Ref ClientDomainName]]
      ResourceRecords: 
        - '"k=rsa; t=y; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCsWJmYswnHbgJttpBmqdxYnLiFGJpya/ZuMO841H0i56nX6wtvGnwnYtjMPWlt2xKfwfzEO9kVWKkFK1Ov6fYPIGvZ/rEEkxTCxZGKowb/PnjfnM7M8eEatZMsXaeosXoClxm/MIlpjpHrFu7JS5MuaW+yfceusccEVz1Mt5wkQwIDAQAB;"'
      TTL: 60
      Comment: !Join ['.', ['default._domainkey', !Ref ClientDomainName]]
      Type: TXT      

  DomainKeyTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_domainkey, !Ref ClientDomainName]]
      ResourceRecords: 
        - '"o=~"'
      TTL: 60
      Comment: !Join ['.', ['www', !Ref ClientDomainName]]
      Type: TXT      

  GoogleMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Ref ClientDomainName
      Comment: Google MX Records
      ResourceRecords:
        - 1 ASPMX.L.GOOGLE.COM
        - 5 ALT1.ASPMX.L.GOOGLE.COM
        - 5 ALT2.ASPMX.L.GOOGLE.COM
        - 10 ALT3.ASPMX.L.GOOGLE.COM
        - 10 ALT4.ASPMX.L.GOOGLE.COM
      TTL: 14400
      Type: MX

  GoogleTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref ClientDomainName
      ResourceRecords: 
        - '"google-site-verification=JEBZoeUnJShr_DDDgd1TBc7jR9LbniA60RhDfjM3i2A"'
        - '"=spf1 include:_spf.google.com ~all"'
      TTL: 14400
      Comment: !Join [' ', ['Google Gmail verification for', !Ref ClientDomainName]]
      Type: TXT      

  SSLValidationOregonCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['_7bd981e83ffb0ebe4b10f57a6cc5748c', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14400
      Comment: SSL Certificate Validation Record
      ResourceRecords:
        - _fc3c5129eebafaa77a385b1ce35a461d.wggjkglgrm.acm-validations.aws.

  SSLValidationVirginiaCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['_96669477dca6e69229023c9eaf8bf293.www', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14400
      Comment: SSL Certificate Validation Record
      ResourceRecords:
        - _228af60d3b9b7770012fe2c17a58975d.wggjkglgrm.acm-validations.aws.