AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for HimexCorp.com

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: himex
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. iscale-solutions.us).
    Type: String
    Default: himexcorp.com

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref ClientDomainName]]
      Name: !Ref ClientDomainName
      HostedZoneTags:
        -
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], iscale-solutions]]
        -
          Key: Environment
          Value: !Ref EnvName
        -
          Key: Organization
          Value: !Ref OrgName

  # GoogleMXRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId : !Ref HostedZone
  #     Name: !Ref ClientDomainName
  #     Comment: Google MX Records
  #     ResourceRecords:
  #       - 1 ASPMX.L.GOOGLE.COM
  #       - 5 ALT1.ASPMX.L.GOOGLE.COM
  #       - 5 ALT2.ASPMX.L.GOOGLE.COM
  #       - 10 ALT3.ASPMX.L.GOOGLE.COM
  #       - 10 ALT4.ASPMX.L.GOOGLE.COM
  #       - 15 qbfeebh6hl7fubeiij3ugfy3m644mgc7fqaj56ifd3wb52vwfpbq.mx-verification.google.com
  #     TTL: 60
  #     Type: MX

  # WildcardCertificateValidationRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join [".", ["_e357ae2bd1dc580df4aacef02ce98e22", !Ref ClientDomainName]]
  #     Type: CNAME
  #     TTL: 60
  #     Comment: !Join ["", ["Validation for *.", !Ref ClientDomainName, "in us-west-2"]]
  #     ResourceRecords:
  #       - _a291719da1b0bbec7bc3d6d8d8d5b41f.bsgbmzkfwj.acm-validations.aws.

  # WWWCertificateValidationRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: !Ref HostedZone
  #     Name: !Join [".", ["_1c085380ae1e8a4ccd39f35889b73574", "www", !Ref ClientDomainName]]
  #     Type: CNAME
  #     TTL: 60
  #     Comment: !Join ["", ["Validation for www.", !Ref ClientDomainName, "in us-east-1"]]
  #     ResourceRecords:
  #       - _a60d476f470d8dcf19d4196135dcea5.bsgbmzkfwj.acm-validations.aws.

  DefaultDomainKeyTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[default._domainkey, !Ref ClientDomainName]]
      ResourceRecords: 
        - '"k=rsa; t=y; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCsWJmYswnHbgJttpBmqdxYnLiFGJpya/ZuMO841H0i56nX6wtvGnwnYtjMPWlt2xKfwfzEO9kVWKkFK1Ov6fYPIGvZ/rEEkxTCxZGKowb/PnjfnM7M8eEatZMsXaeosXoClxm/MIlpjpHrFu7JS5MuaW+yfceusccEVz1Mt5wkQwIDAQAB;"'
      TTL: 60
      Comment: !Join ['.', ['default._domainkey', !Ref ClientDomainName]]
      Type: TXT      

  DomainKeyTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_domainkey, !Ref ClientDomainName]]
      ResourceRecords: 
        - '"o=~"'
      TTL: 60
      Comment: !Join ['.', ['www', !Ref ClientDomainName]]
      Type: TXT      

  GoogleTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref ClientDomainName
      ResourceRecords: 
        - '"google-site-verification=JEBZoeUnJShr_DDDgd1TBc7jR9LbniA60RhDfjM3i2A"'
      TTL: 60
      Comment: !Join ['.', ['www', !Ref ClientDomainName]]
      Type: TXT      

  MailARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['mail', !Ref ClientDomainName]]
      Type: A
      TTL: 60
      Comment: !Join ['.', ['mail', !Ref ClientDomainName]]
      ResourceRecords:
        - 203.175.174.4

  MXARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['mx', !Ref ClientDomainName]]
      Type: A
      TTL: 60
      Comment: !Join ['.', ['mx', !Ref ClientDomainName]]
      ResourceRecords:
        - 203.175.174.5

  HostSGMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Ref ClientDomainName
      Comment: Host MX Records
      ResourceRecords:
        - 0 mx.alpha.hostsg.com
      TTL: 60
      Type: MX

  IMAPCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['imap', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 60
      Comment: !Join ['.', ['imap', !Ref ClientDomainName]]
      ResourceRecords:
        - !Join ['.', ['mail', !Ref ClientDomainName]]

  MailARCARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['mailarc', !Ref ClientDomainName]]
      Type: A
      TTL: 60
      Comment: !Join ['.', ['mailarc', !Ref ClientDomainName]]
      ResourceRecords:
        - 203.175.174.30

  PopCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['pop', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 60
      Comment: !Join ['.', ['pop', !Ref ClientDomainName]]
      ResourceRecords:
        - !Join ['.', ['mail', !Ref ClientDomainName]]

  RelayCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['relay', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 60
      Comment: !Join ['.', ['relay', !Ref ClientDomainName]]
      ResourceRecords:
        - !Join ['.', ['mail', !Ref ClientDomainName]]

  RootARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref ClientDomainName
      Type: A
      TTL: 60
      Comment: !Ref ClientDomainName
      ResourceRecords:
        - 203.175.174.6

  SMTPCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['smtp', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 60
      Comment: !Join ['.', ['smtp', !Ref ClientDomainName]]
      ResourceRecords:
        - !Join ['.', ['mail', !Ref ClientDomainName]]

  WebmailCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['webmail', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 60
      Comment: !Join ['.', ['webmail', !Ref ClientDomainName]]
      ResourceRecords:
        - !Join ['.', ['mail', !Ref ClientDomainName]]

  WwwARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['www', !Ref ClientDomainName]]
      Type: A
      TTL: 60
      Comment: !Join ['.', ['www', !Ref ClientDomainName]]
      ResourceRecords:
        - 203.175.174.6