AWSTemplateFormatVersion: 2010-09-09
Description: DNS records for HimexCorp.com

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: himex
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. iscale-solutions.us).
    Type: String
    Default: himexcorp.com

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# Route53 Section
####

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [' ',[Hosted Zone for, !Ref ClientDomainName]]
      Name: !Ref ClientDomainName
      HostedZoneTags:
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], iscale-solutions]]
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName
  
  HostedZoneDNSSECSigningKey:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref HostedZone
      KeyManagementServiceArn: arn:aws:kms:us-east-1:178070162686:key/315d6bf8-09eb-4b0d-971c-5ef787b8d57b
      Name: key_signing_key
      Status: ACTIVE

  HostedZoneDNSSEC:
    DependsOn: HostedZoneDNSSECSigningKey
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref HostedZone

  DefaultDomainKeyTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[default._domainkey, !Ref ClientDomainName]]
      ResourceRecords: 
        - '"k=rsa; t=y; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCsWJmYswnHbgJttpBmqdxYnLiFGJpya/ZuMO841H0i56nX6wtvGnwnYtjMPWlt2xKfwfzEO9kVWKkFK1Ov6fYPIGvZ/rEEkxTCxZGKowb/PnjfnM7M8eEatZMsXaeosXoClxm/MIlpjpHrFu7JS5MuaW+yfceusccEVz1Mt5wkQwIDAQAB;"'
      TTL: 14400
      Comment: !Join ['.', ['default._domainkey', !Ref ClientDomainName]]
      Type: TXT

  DomainKeyTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[_domainkey, !Ref ClientDomainName]]
      ResourceRecords:
        - '"o=~"'
      TTL: 14400
      Comment: !Join ['.', ['www', !Ref ClientDomainName]]
      Type: TXT

  GmailDKIMRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.',[google._domainkey, !Ref ClientDomainName]]
      ResourceRecords: 
        - '"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCBuB6Jem2C9Q+DRB4DzKG0qVv6vMy2l2qC5P/EBUPvF5dXH5wUeDd5b0k2zg1lH7OuZ6mf2V6Ss3TsKyByN+oMeu1aNKnl0/FhOUdohIrkWrqkam+LhyZKc6dGAF2iGsJqHZ6eNGPyKet1PQLuOoEBkNP9OpKNQMJcQVAh9mCKBQIDAQAB"'
      TTL: 14400
      Comment: Gmail DKIM
      Type: TXT

  GoogleMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: !Ref ClientDomainName
      Comment: Google MX Records
      ResourceRecords:
        - 1 ASPMX.L.GOOGLE.COM
        - 5 ALT1.ASPMX.L.GOOGLE.COM
        - 5 ALT2.ASPMX.L.GOOGLE.COM
        - 10 ALT3.ASPMX.L.GOOGLE.COM
        - 10 ALT4.ASPMX.L.GOOGLE.COM
      TTL: 14400
      Type: MX

  GoogleTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref ClientDomainName
      ResourceRecords: 
        - '"google-site-verification=JEBZoeUnJShr_DDDgd1TBc7jR9LbniA60RhDfjM3i2A"'
        - '"v=spf1 include:_spf.google.com ~all"'
      TTL: 14400
      Comment: !Join [' ', ['Google Gmail verification for', !Ref ClientDomainName]]
      Type: TXT

  SSLValidationOregonCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['_7bd981e83ffb0ebe4b10f57a6cc5748c', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14400
      Comment: SSL Certificate Validation Record
      ResourceRecords:
        - _fc3c5129eebafaa77a385b1ce35a461d.wggjkglgrm.acm-validations.aws.

  SSLValidationVirginiaCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['_96669477dca6e69229023c9eaf8bf293.www', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14400
      Comment: SSL Certificate Validation Record
      ResourceRecords:
        - _228af60d3b9b7770012fe2c17a58975d.wggjkglgrm.acm-validations.aws.

  WWWCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['www', !Ref ClientDomainName]]
      Type: CNAME
      TTL: 14400
      Comment: WWW CNAME Record
      ResourceRecords:
        - !Ref ClientDomainName

  WWWNoRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref ClientDomainName
      Type: A
      TTL: 14400
      ResourceRecords:
        - 174.138.19.36

  APIRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['api', !Ref ClientDomainName]]
      Type: A
      TTL: 14400
      ResourceRecords:
        - 188.166.204.245

  IrisRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Join ['.', ['iris', !Ref ClientDomainName]]
      Type: A
      TTL: 14400
      ResourceRecords:
        - 188.166.204.245