AWSTemplateFormatVersion: 2010-09-09
Description: HIMEX Website

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - LoadBalancerStackName
          - SNSStackName
      - Label:
          default: Load Balancer Configuration
        Parameters:
          - ClientDomainName
      - Label:
          default: Static Hosting Configuration
        Parameters:
          - ClientStaticHostName
          - LambdaDefaultIndexARN
          - LambdaStaticSiteCachingARN
          - SSLCertificateArn

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      NetworkStackName:
        default: Network Stack Name
      LoadBalancerStackName:
        default: Load Balancer Stack Name
      SNSStackName:
        default: SNS Topic Stack Name
      LambdaDefaultIndexARN:
        default: Lambda Default Index ARN
      LambdaStaticSiteCachingARN:
        default: Lambda Static Site Caching ARN
      ClientStaticHostName:
        default: Client Static Name
      SSLCertificateArn:
        default: ELB SSL Certificate ARN

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: website
    MaxLength: 32
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: himex
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: iscale-hosting-prd-uw2-network
  LoadBalancerStackName:
    Description: The name of the load balancer stack.
    Type: String
    Default: HostingProductionELB
  SNSStackName:
    Description: the name of the SNS stack.
    Type: String
    Default: iscale-hosting-prd-uw2-sns
  ClientStaticHostName:
    Description: Static Host Name for the site (e.g. www)
    Type: String
    Default: www
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-solutions.com).
    Type: String
    Default: himexcorp.com
  CloudFrontCertificateArn:
    Description: CloudFront Certificate ARN (must be in us-east-1)
    Type: String
    Default: arn:aws:acm:us-east-1:178070162686:certificate/7ddddb94-e2fa-4980-938d-62f14166d142
  SSLCertificateArn:
    Description: ELB SSL Certificate ARN
    Type: String
    Default: arn:aws:acm:us-west-2:178070162686:certificate/2ac78469-d2a6-4c51-99f0-4edddc6801f9

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  StaticSiteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/static-s3-website.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        ClientDomainName: !Ref ClientDomainName
        ClientStaticHostName: !Ref ClientStaticHostName
        CloudFrontCertificateArn: !Ref CloudFrontCertificateArn
        SSLCertificateArn: !Ref SSLCertificateArn
        LoadBalancerStackName: !Ref LoadBalancerStackName
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName
        