AWSTemplateFormatVersion: 2010-09-09
Description: IAM Resources for iScale-odoo

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: iam
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-odoo
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

  DeveloperGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: OdooDevelopers
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/IAMUserChangePassword
        - arn:aws:iam::aws:policy/AmazonRoute53FullAccess
      Policies:
        - PolicyName: SSMAnywhere
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - ssm:StartSession
                Resource: '*'
  
  BertrandIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: bertrand123!
        PasswordResetRequired: true
      UserName: bertrand@iscale-solutions.com
      Groups:
        - !Ref DeveloperGroup

  DennisIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: dennis123!
        PasswordResetRequired: true
      UserName: dennis@iscale-solutions.com
      Groups:
        - !Ref DeveloperGroup

  MichaelIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: michael123!
        PasswordResetRequired: true
      UserName: michael@iscale-solutions.com
      Groups:
        - !Ref DeveloperGroup

  TinaIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: tina123!
        PasswordResetRequired: true
      UserName: tina@iscale-solutions.com
      Groups:
        - !Ref DeveloperGroup

  BitBucketIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: tina123!
        PasswordResetRequired: true
      UserName: bitbucket_user

  BitBucketAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref BitBucketIAMUser

  # OdooMaintenanceRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     Path: '/'
  #     ManagedPolicyArns: 
  #       - arn:aws:iam::aws:policy/ReadOnlyAccess
  #     RoleName: OdooMaintenanceRole
  #     AssumeRolePolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             AWS: arn:aws:iam::338284463834:user/dlagumbay
  #           Action:
  #             - sts:AssumeRole
  #           Condition:
  #             Bool:
  #               aws:MultiFactorAuthPresent: true
  #     Policies:
  #       - PolicyName: PipelineApproval
  #         PolicyDocument:
  #           Version: 2012-10-17
  #           Statement:
  #             - Effect: Allow
  #               Action: 
  #                 - codepipeline:PutApprovalResult
  #               Resource: 
  #                 - !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:*employ*/Approval/Approval'
  #             - Effect: Allow
  #               Action: 
  #                 - ssm:StartSession
  #               Resource: '*'
  #               Condition:
  #                 StringEquals:
  #                   ssm:resourceTag/Name: employ-prd-uw2-odoo

Outputs:
  
  BitBucketUserAccessKeyId:
    Description: Access Key Id for the bitbucket user
    Value: !Ref BitBucketAccessKey
  
  BitBucketUserAccessKeySecret:
    Description: Secret Key for the bitbucket user
    Value: !GetAtt [BitBucketAccessKey, SecretAccessKey]