AWSTemplateFormatVersion: 2010-09-09
Description: Role for RESPONSIBLE CYBER PTE. LTD. (RCPL)

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: rcpl-role
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: canon
    AllowedPattern: ^[a-z]+(-[a-z]+)*$
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production

Mappings:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# IAM Section
####

  RCPLAuditRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: 1
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: arn:aws:iam::579860521720:root
            Condition:
              StringEquals: 
                sts:ExternalId: ImmuneAwsScanner-dNH7pg55T2
      ManagedPolicyArns:
            - arn:aws:iam::aws:policy/SecurityAudit
      RoleName: RCPLAuditRole