AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions IAM resources

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName

    ParameterLabels:
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: canon
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# IAM
####

  CITechDeveloperGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: CITechDevelopers
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/IAMUserChangePassword
      Policies:
        - PolicyName: SSMAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: TerminateSSM
                Effect: Allow
                Action:
                  - ssm:ResumeSession
                  - ssm:TerminateSession
                Resource:
                  - arn:aws:ssm:*:*:session/${aws:username}-*
              - Sid: AllowSSMinEC2
                Effect: Allow
                Action:
                  - ssm:StartSession
                Resource: 
                  - 'arn:aws:ec2:*:*:instance/i-0b8907cf5fecac213'
                  - 'arn:aws:ec2:*:*:instance/i-02f950d6ca9552970'
                  - 'arn:aws:ec2:*:*:instance/i-0af5fe896478311a7'
                  - 'arn:aws:ec2:*:*:instance/i-0e74a628db0824f9b'
              - Sid: AccessPSSS3Bucket
                Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - arn:aws:s3:::canon-prd-ase1-pss
                  - arn:aws:s3:::canon-prd-ase1-pss/*

##
# Canon staff
##

  JMsCapulongIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: temp123!
        PasswordResetRequired: true
      UserName: JM_Capulong@canon.com.ph
      Groups:
        - Administrators
      Tags:
        - Key: Name
          Value: JM CAPULONG
        - Key: Email
          Value: JM_Capulong@canon.com.ph

  MichaelPalmianoIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: temp123!
        PasswordResetRequired: true
      UserName: Michael_Palmiano@canon.com.ph
      Groups:
        - Administrators
      Tags:
        - Key: Name
          Value: Michael PALMIANO
        - Key: Email
          Value: Michael_Palmiano@canon.com.ph

  RoySanLuisIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: temp123!
        PasswordResetRequired: true
      UserName: Roy_San_Luis@canon.com.ph
      Groups:
        - Administrators
      Tags:
        - Key: Name
          Value: Roy SAN LUIS
        - Key: Email
          Value: Roy_San_Luis@canon.com.ph

##
# CI Tech Staff
##

  BernardoIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: TempJg62gMk9123!
        PasswordResetRequired: true
      UserName: bernardo.edwardpet@mail.canon
      Groups:
        - !Ref CITechDeveloperGroup
      Tags:
        - Key: Name
          Value: Edward Peter BERNARDO
        - Key: Email
          Value: bernardo.edwardpet@mail.canon

  PauleneIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: TempJg629LjW123!
        PasswordResetRequired: true
      UserName: flores.paulenenicole@mail.canon
      Groups:
        - !Ref CITechDeveloperGroup
      Tags:
        - Key: Name
          Value: Paulene Nicole FLORES
        - Key: Email
          Value: flores.paulenenicole@mail.canon
