AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions IAM resources

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName

    ParameterLabels:
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: canon
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

####
# IAM
####

  CITechDeveloperGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: CITechDevelopers
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/IAMUserChangePassword
      Policies:
        - PolicyName: SSMAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: TerminateSSM
                Effect: Allow
                Action:
                  - ssm:ResumeSession
                  - ssm:TerminateSession
                Resource:
                  - arn:aws:ssm:*:*:session/${aws:username}-*
              - Sid: AllowSSMinEC2
                Effect: Allow
                Action:
                  - ssm:StartSession
                Resource: 
                  - 'arn:aws:ec2:*:*:instance/i-0b8907cf5fecac213'
                  - 'arn:aws:ec2:*:*:instance/i-02f950d6ca9552970'
                  - 'arn:aws:ec2:*:*:instance/i-0af5fe896478311a7'
                  - 'arn:aws:ec2:*:*:instance/i-0e74a628db0824f9b'
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:document/SSM-SessionManagerRunShell'
              - Sid: AccessPSSS3Bucket
                Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - arn:aws:s3:::canon-prd-ase1-pss
                  - arn:aws:s3:::canon-prd-ase1-pss/*

##
# Canon staff
##

  JMsCapulongIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: temp123!
        PasswordResetRequired: true
      UserName: JM_Capulong@canon.com.ph
      Groups:
        - Administrators
        - MFA
      Tags:
        - Key: Name
          Value: JM CAPULONG
        - Key: Email
          Value: JM_Capulong@canon.com.ph

  MichaelPalmianoIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: temp123!
        PasswordResetRequired: true
      UserName: Michael_Palmiano@canon.com.ph
      Groups:
        - Administrators
        - MFA
      Tags:
        - Key: Name
          Value: Michael PALMIANO
        - Key: Email
          Value: Michael_Palmiano@canon.com.ph

  RoySanLuisIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: temp123!
        PasswordResetRequired: true
      UserName: Roy_San_Luis@canon.com.ph
      Groups:
        - Administrators
        - MFA
      Tags:
        - Key: Name
          Value: Roy SAN LUIS
        - Key: Email
          Value: Roy_San_Luis@canon.com.ph

##
# CI Tech Staff
##

  EdwardBernardoIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: TempJg62gMk9123!
        PasswordResetRequired: true
      UserName:  edward_bernardo@canon.com.ph
      Groups:
        - !Ref CITechDeveloperGroup
      Tags:
        - Key: Name
          Value: Edward Peter BERNARDO
        - Key: Email
          Value: edward_bernardo@canon.com.ph

  LawrenceLomotanIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: TempJg62gMk9123!
        PasswordResetRequired: true
      UserName:  lawrence_lomotan@canon.com.ph
      Groups:
        - !Ref CITechDeveloperGroup
      Tags:
        - Key: Name
          Value: Lawrence Lomotan
        - Key: Email
          Value: lawrence_lomotan@canon.com.ph

  ElizzaRazalanIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: TempJg62gMk9123!
        PasswordResetRequired: true
      UserName: elizza_razalan@canon.com.ph
      Groups:
        - !Ref CITechDeveloperGroup
      Tags:
        - Key: Name
          Value: Elizza Razalan
        - Key: Email
          Value: elizza_razalan@canon.com.ph

  EdselSabulaoIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: TempJg62gMk9123!
        PasswordResetRequired: true
      UserName: Edsel_Sabulao@canon.com.ph
      Groups:
        - !Ref CITechDeveloperGroup
      Tags:
        - Key: Name
          Value: Edsel Sabulao
        - Key: Email
          Value: Edsel_Sabulao@canon.com.ph


##
# ThinkBit Staff
##

  ThinkBitIAMUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: TempJKWEsaYw38!
        PasswordResetRequired: true
      UserName: developer@thinkbitsolutions.com
      Groups:
        - !Ref ThinkBitGroup
        - MFA
      Tags:
        - Key: Name
          Value: Jerameel Cruz
        - Key: Email
          Value: developer@thinkbitsolutions.com

  ThinkBitGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], ThinkBit, group]]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCertificateManagerReadOnly
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEventBridgeReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSSecretsManagerClientReadOnlyAccess
      Policies:
        # - PolicyName: ThinkBitAccess
        #   PolicyDocument:
        #     Version: 2012-10-17
        #     Statement:
        #       - Sid: Beanstalk
        #         Effect: Allow
        #         Action:
        #           - elasticbeanstalk:*
        #         Resource:
        #           - !Sub 'arn:aws:elasticbeanstalk:${AWS::Region}:${AWS::AccountId}:environment/canonph.app/beta-canonph-app*'
        #       - Sid: CloudFormation
        #         Effect: Allow
        #         Action:
        #           - cloudformation:*
        #         Resource:
        #           - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/awseb-e-*'
        #       - Sid: RDS
        #         Effect: Allow
        #         Action:
        #           - rds:*
        #         Resource:
        #           - !Sub  'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db:beta-canonph-app'
        #       - Sid: SES
        #         Effect: Allow
        #         Action:
        #           - ses:*
        #         Resource: '*'
        #       - Sid: S3
        #         Effect: Allow
        #         Action:
        #           - s3:*
        #         Resource:
        #           - 'arn:aws:s3:::beta-canonph-app'
        #           - 'arn:aws:s3:::beta-canonph-app/*'
        #       - Sid: EC2
        #         Effect: Allow
        #         Action:
        #           - ec2:*
        #         Resource:
        #           - '*'
        #         Condition:
        #           StringEquals:
        #             ec2:resourceTag/Name:
        #               - beta-canonph-app
        #       - Sid: ALB
        #         Effect: Allow
        #         Action:
        #           - elasticloadbalancing:*
        #         Resource:
        #           - !Sub 'arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:loadbalancer/app/awseb-AWSEB-716ADBQZA616/*'
        #       - Sid: ASG
        #         Effect: Allow
        #         Action:
        #           - autoscaling:*
        #         Resource:
        #           - !Sub 'arn:aws:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:25f60029-13e2-46ee-be4e-9b7f5816ff45:autoScalingGroupName/awseb-e-*'
        - PolicyName: CanonDevAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: RDS
                Effect: Allow
                Action:
                  - rds:*
                Resource: '*'
                Condition:
                  StringEquals:
                    aws:ResourceTag/project:
                      - canon-dev
              - Sid: EC2
                Effect: Allow
                Action:
                  - ec2:*
                Resource: '*'
                Condition:
                  StringEquals:
                    aws:ResourceTag/project:
                      - canon-dev
        - PolicyName: SSM
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: RDS
                Effect: Allow
                Action:
                  - rds:*
                Resource: '*'
                Condition:
                  StringEquals:
                    aws:ResourceTag/project:
                      - canon-dev
              - Sid: RDSCreateDBSnapshot
                Effect: Allow
                Action:
                  - rds:CreateDBSnapshot
                Resource: !Sub 'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:*'
              - Sid: ElasticBeanstalk
                Effect: Allow
                Action:
                  - elasticbeanstalk:*
                Resource: '*'
                Condition:
                  StringEquals:
                    aws:ResourceTag/project:
                      - canon-dev
              - Sid: EC2
                Effect: Allow
                Action:
                  - ec2:*
                Resource: '*'
                Condition:
                  StringEquals:
                    aws:ResourceTag/project:
                      - canon-dev
              - Sid: CloudFormationIAM
                Effect: Allow
                Action:
                  - cloudformation:*
                Resource: '*'
                Condition:
                  StringEquals:
                    aws:ResourceTag/project:
                      - canon-dev
              - Sid: SSMReadOnly
                Effect: Allow
                Action:
                  - ssm:List*
                  - ssm:Describe*
                Resource:
                  - '*'
              - Sid: SSMModification
                Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:LabelParameterVersion
                  - ssm:DeleteParameter
                  - ssm:UnlabelParameterVersion
                  - ssm:GetParameterHistory
                  - ssm:GetParametersByPath
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:DeleteParameters
                Resource:
                  - !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/*'

###
# Terraform access
###

  TerraformGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], terraform, group]]
      Policies:
        - PolicyName: TerraformBetaAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: Access
                Effect: Allow
                Action:
                  - rds:*
                  - ec2:*
                  - iam:*
                  - vpc:*
                  - s3:*
                  - autoscaling:*
                  - cloudwatch:*
                  - elasticbeanstalk:*
                  - elasticloadbalancing:*
                Resource:
                  - '*'
              - Sid: AllowCloudformationOperationsOnElasticBeanstalkStacks
                Effect: Allow
                Action:
                  - cloudformation:*
                Resource:
                  - arn:aws:cloudformation:*:*:stack/awseb-*
                  - arn:aws:cloudformation:*:*:stack/eb-*

  TerraformUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], terraform, user]]
      Groups: 
        - !Ref TerraformGroup

  TerraformUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref TerraformUser  

# Outputs:

#   TerraformUserAccessKey:
#     Description: Access Key for the Terraform User
#     Value: !Ref TerraformUserAccessKey

#   TerraformUserSecretKey:
#     Description: Secret Key for the Terraform User
#     Value: !GetAtt TerraformUserAccessKey.SecretAccessKey