AWSTemplateFormatVersion: 2010-09-09
Description: 'TokiAsia - IAM.'

Resources:

####
# Groups
####

# Add iscale users to this group to access cloudwatch loogs

  DevTeam:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Iscale-DevTeam
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMUserChangePassword
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
      Policies:
        - PolicyName: cloudwatch-logs-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:DescribeLogGroups
                  - logs:ListTagsForResource
                  - cloudwatch:GetMetricData
                  - logs:DescribeLogStreams
                  - logs:GetLogEvents
                  - logs:FilterLogEvents
                Resource:
                  - '*'
