AWSTemplateFormatVersion: 2010-09-09
Description: Provision a Database Migration Service Task for MySQL

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Source Configuration
        Parameters:
          - SourceEndpoint
          - SourcePort
          - SourceSchemaName
          - SourceSecurityGroup
          - SourceCidrIp
          - SourceUser
          - SourceUserPassword
      - Label:
          default: Target Configuration
        Parameters:
          - TargetEndpoint
          - TargetPort
          - TargetSchemaName
          - TargetSecurityGroup
          - TargetUser
          - TargetUserPassword
      - Label:
          default: Other Settings
        Parameters:
          - MultiAZ
          - ReplicationInstanceClass
          - MigrationType
          - TableMappings
          - VPC
          - SubnetIds
      - Label:
          default: Cloudformation Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      MultiAZ:
        default: Multi AZ
      ReplicationInstanceClass:
        default: Replication Instance Class
      NetworkStackName:
        default: Network Stack
      SNSStackName:
        default: SNS Stack
      SubnetIds:
        default: Subnet IDs

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 30
    Default: pesonet20-dms
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: pchc
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Test
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  DMSReplicationSubnetGroup:
    Type: String
    Description: DMS Replication Subnet Group
    MinLength: 1
    Default: skip
  SubnetIds:
    Type: CommaDelimitedList
    Description: List of subnet IDs for DMS subnet group
    Default: ''
  MigrationType:
    Description: Type of migration to be performed
    Type: String
    Default: full-load
    AllowedValues:
      - full-load
      - full-load-and-cdc
  MultiAZ:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  ReplicationInstanceClass:
    Type: String
    Default: dms.t3.medium
    AllowedValues:
      - dms.t3.micro
      - dms.t3.small
      - dms.t3.medium
      - dms.t3.large
      - dms.c5.large
      - dms.c5.xlarge
      - dms.c5.2xlarge
      - dms.c5.4xlarge
  SourceEndpoint:
    Type: String
    Description: Source Database Endpoint
    MinLength: 1
    Default: <pesonet20.<rds_uid>.<region>.rds.amazonaws.com
  SourcePort:
    Type: Number
    Description: Source Database Port
    Default: 3306
  SourceSchemaName:
    Type: String
    Description: Source Database Schema Name
    MinLength: 1
    Default: pesonet20_schema_name
  SourceSecurityGroup:
    Type: String
    Description: Source Database Security Group (leave empty to use SourceCidrIp) #good for inter-account-region migration
    Default: ''
  SourceCidrIp:
    Type: String
    Description: Source Database Network CIDR (used if SourceSecurityGroup is not provided) #good for cross-account/cross-region migration
    Default: '10.0.0.0/16'
  SourceUser:
    Type: String
    Description: Source Database UserName
    MinLength: 1
    Default: database_user
  SourceUserPassword:
    Type: String
    Description: Source Database Password
    NoEcho: true
    MinLength: 1
  TableMappings:
    Type: String
    Description: Table Mappings # the table mappings in default is to copy all schema and table from source to target
    Default: "{ \"rules\": [ { \"rule-type\": \"selection\", \"rule-id\": \"1\", \"rule-name\": \"1\", \"object-locator\": { \"schema-name\": \"%\", \"table-name\": \"%\" }, \"rule-action\": \"include\" }] }"
  TargetEndpoint:
    Type: String
    Description: Target Database Endpoint
    MinLength: 1
    Default: <pesonet20.<rds_uid>.<region>.rds.amazonaws.com
  TargetPort:
    Type: Number
    Description: Source Database Port
    Default: 3306
  TargetSchemaName:
    Type: String
    Description: Target Database Schema Name
    Default: pesonet20_schema_name
    MinLength: 1
  TargetSecurityGroup:
    Type: String
    Description: Target Database Security Group
    MinLength: 1
    Default: 'sg-'
  TargetUser:
    Type: String
    Description: Target Database UserName
    MinLength: 1
    Default: database_user
  TargetUserPassword:
    Type: String
    Description: Target Database Password
    NoEcho: true
    MinLength: 1
  VPC:
    Description: VPC to use for shards
    Type: AWS::EC2::VPC::Id
    Default: 'vpc-'

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
  IsNotCidr: !Not [!Equals [!Ref SourceSecurityGroup, '']]
  IsCidr: !Equals [!Ref SourceSecurityGroup, '']

Resources:
  
  DMSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join [' ', ['DMS Replication (', !Join ['-', [!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name]]], ') Security Group']]
      VpcId: !Ref VPC

  SourceSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: IsNotCidr
    Properties: 
      Description: Allow connection from DMS
      IpProtocol: TCP
      GroupId: !Ref SourceSecurityGroup
      FromPort: !Ref SourcePort
      ToPort: !Ref SourcePort
      SourceSecurityGroupId: !Ref DMSSecurityGroup
  
  SourceCidrSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: IsCidr
    Properties: 
      Description: Allow connection from DMS
      IpProtocol: TCP
      GroupId: !Ref DMSSecurityGroup
      CidrIp: !Ref SourceCidrIp
      FromPort: !Ref SourcePort
      ToPort: !Ref SourcePort

  TargetSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow connection from DMS
      IpProtocol: TCP
      GroupId: !Ref TargetSecurityGroup
      FromPort: !Ref TargetPort
      ToPort: !Ref TargetPort
      SourceSecurityGroupId: !Ref DMSSecurityGroup

  DMSInstance: 
    Type: AWS::DMS::ReplicationInstance
    Properties: 
      AllowMajorVersionUpgrade: true
      EngineVersion: 3.5.4
      MultiAZ: !Ref MultiAZ
      PubliclyAccessible: false
      ReplicationInstanceClass: !Ref ReplicationInstanceClass
      ReplicationInstanceIdentifier: !Join ['-', [!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name], 'replication']]
      ReplicationSubnetGroupIdentifier: !Ref DMSSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DMSSecurityGroup
  
  DMSSubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    Properties:
      ReplicationSubnetGroupIdentifier: !Join ['-', [!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name], 'repsub-group']]
      ReplicationSubnetGroupDescription: Subnets for DMS instance
      SubnetIds: !Ref SubnetIds

  DMSSourceEndPoint: 
    Type: AWS::DMS::Endpoint
    Properties: 
      DatabaseName: !Ref SourceSchemaName
      EndpointIdentifier: !Join ['-', [!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name], 'source']]
      EndpointType: source
      EngineName: mysql
      Password: !Ref SourceUserPassword
      Port: !Ref SourcePort
      Username: !Ref SourceUser
      ServerName: !Ref SourceEndpoint

  DMSTargetEndPoint:
    Type: AWS::DMS::Endpoint
    Properties:
      DatabaseName: !Ref TargetSchemaName
      EndpointIdentifier: !Join ['-', [!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name], 'target']]
      EndpointType: target
      EngineName: mysql
      ExtraConnectionAttributes: "initstmt=SET FOREIGN_KEY_CHECKS=0"
      Password: !Ref TargetUserPassword
      Port: !Ref TargetPort
      Username: !Ref TargetUser
      ServerName: !Ref TargetEndpoint

  DMSReplicationTask:
    Type: AWS::DMS::ReplicationTask
    Properties: 
      MigrationType: !Ref MigrationType
      ReplicationInstanceArn: !Ref DMSInstance
      ReplicationTaskIdentifier: !Join ['-', [!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name], 'migration']]
      SourceEndpointArn: !Ref DMSSourceEndPoint
      TargetEndpointArn: !Ref DMSTargetEndPoint
      TableMappings: !Ref TableMappings
      

Outputs:
  
  DMSSecurityGroup:
    Description: DMS Security Group
    Value: !Ref DMSSecurityGroup