AWSTemplateFormatVersion: 2010-09-09
Description: >
  This cloudformation template provisions an SNS Topic for EC2 Image Builder notifications. 
  The SNS Topic will be used to trigger Lambda functions for Image Builder lifecycle events.

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - OrgName
          - EnvName

    ParameterLabels:
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name

Parameters:
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 11
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
      - ProductionDR
      - StagingDR
      - DevelopmentDR
      - TestDR

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Resources:

###
# SNS Topic for Image Builder notifications
###

  ImageBuilderSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join [' ',[!Ref OrgName, !Ref EnvName, !Ref 'AWS::Region', Image Builder SNS Topic]]
      KmsMasterKeyId: 'alias/aws/sns'
      TopicName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], image-buidler-sns-topic]]
  
Outputs:
  TopicArn: 
    Description: Arn of the SNS Topic
    Value: !Ref ImageBuilderSnsTopic
    Export:
      Name: !Sub "${AWS::StackName}-TopicArn"