AWSTemplateFormatVersion: 2010-09-09
Description: PMMS scheduler

Parameters:
  PmmsAD:
    Description: PMMS AD
    Type: String
    Default: 'i-0fdcfda2181ceb1ae'
    MinLength: 1
  PmmsDB:
    Description: PMMS DB
    Type: String
    Default: 'i-02c22b75006f87aff'
    MinLength: 1
  PmmsWEB:
    Description: PMMS DB
    Type: String
    Default: 'i-07520396c25f2f256'
    MinLength: 1
  StartScheduleExpression:
    Description: Schedule expression when to start the objects
    Type: String
    Default: cron(0 0 ? * MON-FRI *)
  StopScheduleExpression:
    Description: Schedule expression when to stop the objects
    Type: String
    Default: cron(0 10 ? * MON-FRI *)

Resources:

  SchedulerStack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
      Parameters:
        Name: pmms-ad
        StartScheduleExpression: !Ref StartScheduleExpression
        StopScheduleExpression: !Ref StopScheduleExpression
        UseFriendlyNames: FALSE
        EC2InstanceId: !Ref PmmsAD
  
  SchedulerStack2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
      Parameters:
        Name: pmms-db
        StartScheduleExpression: !Ref StartScheduleExpression
        StopScheduleExpression: !Ref StopScheduleExpression
        UseFriendlyNames: FALSE
        EC2InstanceId: !Ref PmmsDB
  
  SchedulerStack3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
      Parameters:
        Name: pmms-web
        StartScheduleExpression: !Ref StartScheduleExpression
        StopScheduleExpression: !Ref StopScheduleExpression
        UseFriendlyNames: FALSE
        EC2InstanceId: !Ref PmmsWEB
