AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions resources for iscale bastion

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: "Resource Configuration"
        Parameters:
          - Name
          - OrgName
          - EnvName
      -
        Label:
          default: "Stack Configuration"
        Parameters:
          - NetworkStackName
          - SNSStackName
      -
        Label:
          default: "EC2/Auto-Scaling Group Configuration"
        Parameters:
          - AssociatePublicIp
          - AssociateEIP
          - InstanceAMI
          - InstanceType
          - PolicyArns
          - EnableMonitoring
          - KeyName
          - TopicArn
          - EnableCPUCreditAlarm
          - ClientDomainName
      -
        Label:
          default: "Scheduler Configuration"
        Parameters:
          - StartScheduleExpression
          - StopScheduleExpression


    ParameterLabels:
      Name:
        default: "Resource Name"
      OrgName:
        default: "Organization Name"
      EnvName:
        default: "Environment Name"
      NetworkStackName:
        default: "Network Stack Name"
      SNSStackName:
        default: "SNS Topic Stack Name"
      AssociatePublicIp:
        default: "Associate Public IP"
      AssociateEIP:
        default: "Associate Elastic IP"
      InstanceAMI:
        default: "Instance AMI ID"
      InstanceType:
        default: "Instance Type"
      PolicyArns:
        default: "Policy ARNs"
      EnableMonitoring:
        default: "Enable Monitoring"
      KeyName:
        default: "Key Name"
      EnableCPUCreditAlarm:
        default: "Enable CPU Credit Alarm"
      ClientDomainName:
        default: "Domain Name"
      StartScheduleExpression:
        default: "Scheduled Expression (Start)"
      StopScheduleExpression:
        default: "Scheduled Expression (Stop)"

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: bastion
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-hosting
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: iscale-hosting-prd-uw2-internal-network
  SNSStackName:
    Description: the name of the SNS stack.
    Type: String
    Default: iscale-hosting-prd-uw2-sns
  AssociatePublicIp:
    Description: Set to true if associating public ip address to instance is enabled. Enable only if AssociateEIP is false. Otherwise, disabled.
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  AssociateEIP:
    Description: Set to true if associating elastic ip address to instance is enabled. Enable only if AssociatePublicIp is false. Otherwise, disabled.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  InstanceAMI:
    Description: AMI image used by the EC2 instance.
    Type: String
    Default: ami-0f7a70c59f1075728
  InstanceType:
    Description: The instnace type of the EC2 instance (e.g. t2.micro, t2.small, c4.large, etc).
    Type: String
    Default: t3.micro
  PolicyArns:
    Description: List of policy Arns associated to the EC2 instance.
    Type: String
    Default: "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  EnableMonitoring:
    Description: Set to true if monitoring is enabled for the EC2 instance. Otherwise, disabled.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  KeyName:
    Description: Name of the Key Pair to use.
    Type: String
    Default: ""
  EnableCPUCreditAlarm:
    Description: Set to true if CPU credit alarm is enabled (Applicable only for t* instance types. E.g. t2.small, t3.small). Otherwise, disabled.
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  StartScheduleExpression:
    Description: Schedule expression when to start the the ec2 instance.
    Type: String
    Default: cron(0 1 ? * MON-FRI *)
  StopScheduleExpression:
    Description: Schedule expression when to stop the the ec2 instance.
    Type: String
    Default: cron(0 9 ? * MON-FRI *)

Mappings: 
  EnvShort:
    Production:
      Name: prd
    Staging:
      Name: stg
    Development:
      Name: dev
    Test:
      Name: test
  RegionShort:
    us-east-2:
      Name: ue2
    us-east-1:
      Name: ue1
    us-west-1:
      Name: uw1
    us-west-2:
      Name: uw2
    ap-east-1:
      Name: ae1
    ap-south-1:
      Name: as1
    ap-northeast-1:
      Name: ane1
    ap-northeast-2:
      Name: ane2
    ap-northeast-3:
      Name: ane3
    ap-southeast-1:
      Name: ase1
    ap-southeast-2:
      Name: ase2
    ca-central-1:
      Name: cc1
    cn-north-1:
      Name: cn1
    cn-northwest-1:
      Name: cnw1
    eu-central-1:
      Name: ec1
    eu-west-1:
      Name: ew1
    eu-west-2:
      Name: ew2
    eu-west-3:
      Name: ew3
    eu-north-1:
      Name: en1
    me-south-1:
      Name: ms1
    sa-east-1:
      Name: se1
    us-gov-east-1:
      Name: uge1
    us-gov-west-1:
      Name: ugw1 

Conditions:

  IsEnableCPUCreditAlarm: !Equals [!Ref EnableCPUCreditAlarm, true]
  IsAssociatePublicIp: !Equals [!Ref AssociatePublicIp, true]
  IsAssociateEIP: !Equals [!Ref AssociateEIP, true]
  HasKeyName: !Not [!Equals [!Ref KeyName, ""]]

Resources:

####
# EC2 Section
####

  DefaultInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref InstanceAMI
      KeyName: !If [HasKeyName, !Ref KeyName, !Ref 'AWS::NoValue']
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref DefaultIamInstanceProfile
      Monitoring: !Ref EnableMonitoring
      NetworkInterfaces:
        - AssociatePublicIpAddress: !Ref AssociatePublicIp
          DeviceIndex: 0
          GroupSet: [!GetAtt DefaultSecurityGroup.GroupId]
          SubnetId: 
            Fn::ImportValue:
              !Sub "${NetworkStackName}-PublicSubnetId1"
      UserData:
        Fn::Base64: !Sub
          - |
            #cloud-config
            write_files:
              - path: /var/lib/cloud/instance/custom-data.sh
                permissions: 0700
                owner: root:root
                content: |
                  STACK_NAME=${AWS::StackName}
                  AWS_REGION=${AWS::Region}
                  ENVIRONMENT=${ENVIRONMENT}
                  CLIENT_NAME=${CLIENT_NAME}
                  APPLICATION_SITE=${APPLICATION_SITE}
                  INSTANCE_ROLE=${INSTANCE_ROLE}
          - ENVIRONMENT: !Ref EnvName
            CLIENT_NAME: !Ref Name
            APPLICATION_SITE: !Ref OrgName
            INSTANCE_ROLE: !Ref DefaultIamRole
      Tags:
        - 
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
        - 
          Key: Environment
          Value: !Ref EnvName
        - 
          Key: Organization
          Value: !Ref OrgName

  DefaultEIP:
    Type: AWS::EC2::EIP
    Condition: IsAssociateEIP
    Properties:
      InstanceId: !Ref DefaultInstance

####
# VPC Section
####

  DefaultSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
      GroupDescription: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
      VpcId: #vpc-0eeeb47ddc550dcb5
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VpcId"
      Tags:
        - 
          Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]

  # Access only from Office IP1 (Globe)
  DefaultSecurityGroupIngress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt DefaultSecurityGroup.GroupId
      IpProtocol: "tcp"
      FromPort: 22
      ToPort: 22
      CidrIp: "222.127.128.168/29"

  # Access only from Office IP2 (Eastern)
  DefaultSecurityGroupIngress2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt DefaultSecurityGroup.GroupId
      IpProtocol: "tcp"
      FromPort: 22
      ToPort: 22
      CidrIp: "116.50.239.72/29"
  
  DefaultSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !GetAtt DefaultSecurityGroup.GroupId
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      CidrIp: "0.0.0.0/0"

####
# IAM Section
####

  DefaultIamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
      Roles:
        - !Ref DefaultIamRole

  DefaultIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Sid: "1"
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "ec2.amazonaws.com"
      ManagedPolicyArns:
        - !Ref PolicyArns

####
# Cloudwatch Section
####

  CPUUtilizationCloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Join [ '-', [!Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]], cpu-utilization]]
      MetricName: CPUUtilization
      Namespace: "AWS/EC2"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      Statistic: Average
      Threshold: 80
      AlarmActions: 
        - Fn::ImportValue:
            !Sub "${SNSStackName}-TopicArn"
      OKActions: 
        - Fn::ImportValue:
            !Sub "${SNSStackName}-TopicArn"

  StatusChecksCloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Join [ '-', [!Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]], status-checks]]
      MetricName: StatusCheckFailed
      Namespace: "AWS/EC2"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      Statistic: Minimum
      Threshold: 1
      AlarmActions: 
        - Fn::ImportValue: 
            !Sub "${SNSStackName}-TopicArn"
      OKActions: 
        - Fn::ImportValue:
            !Sub "${SNSStackName}-TopicArn"

  CPUCreditBalanceCloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsEnableCPUCreditAlarm
    Properties:
      AlarmName: !Join [ '-', [!Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]], cpu-credit-balance]]
      MetricName: CPUCreditBalance
      Namespace: "AWS/EC2"
      ComparisonOperator: LessThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      Statistic: Minimum
      Threshold: 24
      AlarmActions: 
        - Fn::ImportValue: 
            !Sub "${SNSStackName}-TopicArn"
      OKActions: 
        - Fn::ImportValue: 
            !Sub "${SNSStackName}-TopicArn"


##################################################
#
# Scheduler Stack
#
##################################################

####
# IAM Section
####

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies:
        - 
          PolicyName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, lambda-execution-policy]]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - 
                Effect: Allow
                Action: 
                  - ec2:Start*
                  - ec2:Stop*
                  - ec2:DescribeInstances
                  - ec2:ReportInstanceStatus
                Resource: "*"
              - 
                Effect: Allow
                Action: 
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

####
# Cloudwatch Section
####

  StartLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref StartLambdaFunction]]

  StopLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref StopLambdaFunction]]

  StopEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Stops the instance at a specific time
      Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, stop]]
      ScheduleExpression: !Ref StopScheduleExpression
      State:  "ENABLED"
      Targets:
      - 
        Arn: !GetAtt StopLambdaFunction.Arn
        Id: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, stop]]

  PermissionForEventsToInvokeLambdaStop:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StopLambdaFunction
      Action:  "lambda:InvokeFunction"
      Principal:  "events.amazonaws.com"
      SourceArn: !GetAtt StopEventRule.Arn

  StartEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Starts the instance at a specific time
      Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, start]]
      ScheduleExpression: !Ref StartScheduleExpression
      State:  "DISABLED"
      Targets:
      - 
        Arn: !GetAtt StartLambdaFunction.Arn 
        Id: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, start]]

  PermissionForEventsToInvokeLambdaStart:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StartLambdaFunction
      Action:  "lambda:InvokeFunction"
      Principal:  "events.amazonaws.com"
      SourceArn: !GetAtt StartEventRule.Arn

  StartLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Lambda Function which starts the bastion instance"
      FunctionName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, start]]
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn 
      Runtime: python3.6
      Timeout: 900
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          INSTANCE_ID: !Ref DefaultInstance
      Code:
        ZipFile: |

          import boto3
          import logging
          import os

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
              
          def lambda_handler(event, context):
            region=os.environ['REGION']
            instanceId=os.environ['INSTANCE_ID']

            try:
              ec2 = boto3.client('ec2',region_name=region)

              logger.info('Stopping Instance: ' + str(instanceId))
              ec2.start_instances(InstanceIds=[instanceId],DryRun=False)

            except Exception:
              logger.exception('Error Encountered')

  StopLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Lambda Function which stops the bastion instance"
      FunctionName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, stop]]
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn 
      Runtime: python3.6
      Timeout: 900
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          INSTANCE_ID: !Ref DefaultInstance
      Code:
        ZipFile: |

          import boto3
          import logging
          import os

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
              
          def lambda_handler(event, context):
            region=os.environ['REGION']
            instanceId=os.environ['INSTANCE_ID']

            try:
              ec2 = boto3.client('ec2',region_name=region)
              
              logger.info('Stopping Instance: ' + str(instanceId))
              ec2.stop_instances(InstanceIds=[instanceId],DryRun=False)

            except Exception:
              logger.exception('Error Encountered')

Outputs:

  Name:
    Description: Unique name/identifier
    Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
    Export: 
      Name: !Sub ${AWS::StackName}-Name

  SecurityGroupId:
    Description: The security group id of the EC2 instance
    Value: !GetAtt DefaultSecurityGroup.GroupId
    Export: 
      Name: !Sub ${AWS::StackName}-SecurityGroupId

  InstanceRoleArn:
    Description: The instance role arn attached to the EC2 Instance
    Value: !GetAtt DefaultIamRole.Arn
    Export: 
      Name: !Sub ${AWS::StackName}-InstanceRoleArn