AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions a loadbalancer

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: "Resource Configuration"
        Parameters:
          - Name
          - OrgName
          - EnvName
      -
        Label:
          default: "Scheduler Configuration"
        Parameters:
          - StartScheduleExpression
          - StopScheduleExpression
          - TemplateUrl

    ParameterLabels:
      Name:
        default: "Resource Name"
      OrgName:
        default: "Organization Name"
      EnvName:
        default: "Environment Name"
      StartScheduleExpression:
        default: "Scheduled Expression (Start)"
      StopScheduleExpression:
        default: "Scheduled Expression (Stop)"
      TemplateUrl:
        default: "Template URL"

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    Default: payroll-loadbalancer-scheduler
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-hosting
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Production
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  StartScheduleExpression:
    Description: Schedule expression when to start the clouformation stack creation.
    Type: String
    Default: cron(0 0 ? * MON-FRI *)
  StopScheduleExpression:
    Description: Schedule expression when to stop the clouformation stack creation.
    Type: String
    Default: cron(0 13 ? * MON-FRI *)
  TemplateUrl:
    Description: The custom template url. This can be found on the s3 cloudformation custom folder.
    Type: String
    Default: https://iscale-hosting-uw2-cfn-templates.s3-us-west-2.amazonaws.com/loadbalancer.yaml

Mappings: 
  EnvShort:
    Production:
      Name: prd
    Staging:
      Name: stg
    Development:
      Name: dev
    Test:
      Name: test
  RegionShort:
    us-east-2:
      Name: ue2
    us-east-1:
      Name: ue1
    us-west-1:
      Name: uw1
    us-west-2:
      Name: uw2
    ap-east-1:
      Name: ae1
    ap-south-1:
      Name: as1
    ap-northeast-1:
      Name: ane1
    ap-northeast-2:
      Name: ane2
    ap-northeast-3:
      Name: ane3
    ap-southeast-1:
      Name: ase1
    ap-southeast-2:
      Name: ase2
    ca-central-1:
      Name: cc1
    cn-north-1:
      Name: cn1
    cn-northwest-1:
      Name: cnw1
    eu-central-1:
      Name: ec1
    eu-west-1:
      Name: ew1
    eu-west-2:
      Name: ew2
    eu-west-3:
      Name: ew3
    eu-north-1:
      Name: en1
    me-south-1:
      Name: ms1
    sa-east-1:
      Name: se1
    us-gov-east-1:
      Name: uge1
    us-gov-west-1:
      Name: ugw1 

Resources:

####
# IAM Section
####

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com" 
            Action: 
              - "sts:AssumeRole"
      Policies:
        - 
          PolicyName: "LambdaDefaultFunctionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - 
                Effect: Allow
                Action: "*"
                Resource: "*"
              - 
                Effect: "Allow"
                Action: 
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

####
# Lambda Section
####

  StartLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Payroll Prod - Start Load Balancer"
      FunctionName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, start]]
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn 
      Runtime: python3.9
      Timeout: 900
      Environment:
        Variables:
          TemplateUrl: !Ref TemplateUrl
          Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], payroll-loadbalancer]]
      Code:
        ZipFile: |

          import boto3
          import logging
          import os
          import cfnresponse

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          cfn = boto3.client('cloudformation')
              
          def lambda_handler(event, context):

            try:

              stackName=os.environ['Name']
              templateUrl=os.environ['TemplateUrl']

              cfn.create_stack(
                      StackName=stackName,
                      TemplateURL=templateUrl,
                      Capabilities=[
                          'CAPABILITY_IAM'
                        ]
                    )

            except Exception:
              logger.exception('Error Encountered')

  StopLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Payroll Prod - Stop Load Balancer"
      FunctionName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, stop]]
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn 
      Runtime: python3.9
      Timeout: 900
      Environment:
        Variables:
          TemplateUrl: !Ref TemplateUrl
          Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], payroll-loadbalancer]]
      Code:
        ZipFile: |

          import boto3
          import logging
          import os
          import cfnresponse

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          cfn = boto3.client('cloudformation')
              
          def lambda_handler(event, context):

            try:

              stackName=os.environ['Name']
              templateUrl=os.environ['TemplateUrl']

              cfn.delete_stack(
                    StackName=stackName
                  )

            except Exception:
              logger.exception('Error Encountered')

####
# Cloudwatch Section
####

  StartLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref StartLambdaFunction]]

  StopLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', ['/aws/lambda', !Ref StopLambdaFunction]]

  StopEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Stops the instance at a specific time
      Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, stop]]
      ScheduleExpression: !Ref StopScheduleExpression
      State:  "ENABLED"
      Targets:
      - 
        Arn: !GetAtt StopLambdaFunction.Arn
        Id: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, stop]]

  PermissionForEventsToInvokeLambdaStop:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StopLambdaFunction
      Action:  "lambda:InvokeFunction"
      Principal:  "events.amazonaws.com"
      SourceArn: !GetAtt StopEventRule.Arn

  StartEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Starts the instance at a specific time
      Name: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, start]]
      ScheduleExpression: !Ref StartScheduleExpression
      State:  "ENABLED"
      Targets:
      - 
        Arn: !GetAtt StartLambdaFunction.Arn 
        Id: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, start]]

  PermissionForEventsToInvokeLambdaStart:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StartLambdaFunction
      Action:  "lambda:InvokeFunction"
      Principal:  "events.amazonaws.com"
      SourceArn: !GetAtt StartEventRule.Arn


Outputs:

  Name:
    Description: Unique name/identifier
    Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name]]
    Export: 
      Name: !Sub ${AWS::StackName}-Name