AWSTemplateFormatVersion: 2010-09-09
Description: This  template provisions basic details for a customer AWS account

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: Resource Configuration
        Parameters:
          - OrgName
      - 
        Label:
          default: User Roles
        Parameters:
          - AdminUsers
          - CreateReadOnlyUsers
          - ReadOnlyUsers
    
    ParameterLabels:
      AdminUsers:
        default: Administrators
      OrgName:
        default: Organization Name
      ReadOnlyUsers:
        default: Read-Only Users

Parameters:
  
  AdminUsers:
    Description: List of account Administrators
    Type: CommaDelimitedList
    Default: "arn:aws:iam::383761724374:user/iannis@iscale-solutions.com"
  
  CreateReadOnlyUsers:
    Description: Set to true to specify read only users
    Default: false
    Type: String
    AllowedValues: [true, false]

  OrgName:
    Description: The name of the organization.
    Type: String
    Default: anchanto
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  
  ReadOnlyUsers:
    Description: List of Read-Only Users
    Type: CommaDelimitedList
    Default: ''

Conditions:
  ShouldCreateReadOnlyUsers: !Equals [true, !Ref CreateReadOnlyUsers]

Resources:

  # S3 bucket for DMS Asssessments
  AssessmentS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join [ '-', [!Ref OrgName , 'dms-assessments']]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags: 
        - Key: Name
          Value: !Join [ '-', [!Ref OrgName , 'dms-assessments']]
        - Key: Organization
          Value: !Ref OrgName

  CloudFormationImportAccessRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role designed for CloudFormation import and guarantee that no existing resources are modified
      RoleName: CloudFormationImportAccessRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  DMSAssessmentRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role designed for DMS to perform data assessment
      RoleName: DMSAssessmentRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: dms.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AssessmentBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: 
                  - !GetAtt AssessmentS3Bucket.Arn
                  - !Join ['/', [!GetAtt AssessmentS3Bucket.Arn, '*']]

  MasterAccountAccessRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Administrator access from trusted parties
      RoleName: MasterAccountAccessRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AdminUsers
            Action:
              - sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      Path: /

  ReadOnlyAccountAccessRole:
    Condition: ShouldCreateReadOnlyUsers
    Type: AWS::IAM::Role
    Properties:
      Description: Read only access from trusted parties
      RoleName: ReadOnlyAccountAccessRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref ReadOnlyUsers
            Action:
              - sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: false
      Path: /