AWSTemplateFormatVersion: 2010-09-09
Description: Privision Assets for Data team

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      - Label:
          default: Shards Configuration
        Parameters:
          - DBInstanceClass
          - DBSnapshotIdentifier
          - VPC
      - Label:
          default: Cloudformation Stack Configuration
        Parameters:
          - VPCDNSStackName
          - NetworkStackName
          - SNSStackName

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      DBInstanceClass:
        default: Instance Class
      NetworkStackName:
        default: Network Stack
      VPCDNSStackName:
        default: VPC DNS Stack
      SNSStackName:
        default: SNS Stack

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 8
    Default: datalake
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: anchanto
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Development
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  VPC:
    Description: VPC to use for shards
    Type: AWS::EC2::VPC::Id
    Default: vpc-00225838fec7973aa
  DBSnapshotIdentifier:
    Description: Name of the DB snapshot to use as source
    Type: String
    Default: arn:aws:rds:us-west-2:270124848746:snapshot:anchanto-data-stg-sgid-for-data-team-feb-03-2021
  NetworkStackName:
    Description: The name of the cloudformation Network stack
    Type: String
    Default: anchanto-dev-uw2-network
  SNSStackName:
    Description: The name of the cloudformation SNS stack
    Type: String
    Default: anchanto-stg-uw2-sns
  VPCDNSStackName:
    Description: VPC DNS Stack Name
    Type: String
    Default: anchanto-dev-vpc-dns

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml

Resources:

###
# Global DB Resources
###

  MySQL8ParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, data, params]]
      Family: mysql8.0
      Parameters:
        general_log: 0
        log_output: FILE
        long_query_time: 5
        slow_query_log: 1
        binlog_format: ROW
        binlog_checksum: NONE
        binlog_row_image: full
        innodb_autoinc_lock_mode: 2
      Tags:
        - Key: Name
          Value: MySQL 8 Parameter Group for data team

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Data Team - Server Security Group
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Data Team Server Security Group
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Data Team - DB Security Group
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol : TCP
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref ServerSecurityGroup
          Description: Connection from Data team server
      Tags:
        - Key: Name
          Value: Data Team DB Security Group
        - Key: Environment
          Value: !Ref EnvName
        - Key: Organization
          Value: !Ref OrgName
  
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
        DBSubnetGroupDescription: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, 'DB Subnet Group']]
        SubnetIds:
          - !ImportValue 
              'Fn::Sub': '${NetworkStackName}-InternalSubnetId1'
          - !ImportValue 
              'Fn::Sub': '${NetworkStackName}-InternalSubnetId2'
        Tags:
          - Key: Name
            Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, 'DB Subnet Group']]

  SGIDShard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/db-shard.yaml
      Parameters:
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        DBParameterGroupName: !Ref MySQL8ParameterGroup
        DBSnapshotIdentifier: !Ref DBSnapshotIdentifier
        DBSubnetGroup: !Ref DBSubnetGroup
        InstanceClass: db.r5.large
        SecurityGroup: !Ref DBSecurityGroup
        ShardName: sgid
        VPC: !Ref VPC
        VPCDNSStackName: !Ref VPCDNSStackName
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName

  RawS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, 'raw']]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags: 
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, 'raw']]
        - Key: Organization
          Value: !Ref OrgName

  ProcessedS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, 'processed']]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags: 
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, 'processed']]
        - Key: Organization
          Value: !Ref OrgName

  PublishedS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, 'published']]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags: 
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, 'published']]
        - Key: Organization
          Value: !Ref OrgName

  ScriptS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, 'script']]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags: 
        - Key: Name
          Value: !Join ['-',[!Ref OrgName, !FindInMap [EnvShort, !Ref EnvName, Name], !FindInMap [RegionShort, !Ref 'AWS::Region', Name], !Ref Name, 'script']]
        - Key: Organization
          Value: !Ref OrgName

  GlueIamRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Sid: 1
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: glue.amazonaws.com
      # ManagedPolicyArns:
      #   - arn:aws:iam::aws:policy/AdministratorAccess
      Path: /
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - s3:Get*
                  - s3:List*
                Resource: 
                  - !GetAtt [RawS3Bucket, Arn]
                  - !Join ['/', [!GetAtt [RawS3Bucket, Arn], '*']]
              - Effect: Allow
                Action: 
                  - s3:Get*
                  - s3:List*
                  - s3:Put*
                  - s3:Delete
                Resource: 
                  - !GetAtt [ProcessedS3Bucket, Arn]
                  - !Join ['/', [!GetAtt [ProcessedS3Bucket, Arn], '*']]
                  - !GetAtt [PublishedS3Bucket, Arn]
                  - !Join ['/', [!GetAtt [PublishedS3Bucket, Arn], '*']]
                  - !GetAtt [ScriptS3Bucket, Arn]
                  - !Join ['/', [!GetAtt [ScriptS3Bucket, Arn], '*']]

  # RDSGlueConnection:
  #   Type: AWS::Glue::Connection
  #   Properties: 
  #     CatalogId: !Ref AWS::AccountId
  #     ConnectionInput: 
  #       ConnectionProperties: Json 
  #       ConnectionType: String
  #       Description: String
  #       MatchCriteria: 
  #         - String
  #       Name: String
  #       PhysicalConnectionRequirements: 
  #         PhysicalConnectionRequirements
