CREATE USER 'ssread'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*8B68C3E1E38510BDA37D8358D09E1610630204A6' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT USAGE ON *.* TO `ssread`@`%`;
GRANT SELECT ON *.* TO `ssread`@`%`;

CREATE USER 'selluseller_web'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*EFC6ECF8474444FBE778AB539E9F6A2C4EECD6B2' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY DEFAULT PASSWORD REUSE INTERVAL DEFAULT PASSWORD REQUIRE CURRENT DEFAULT;
GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO `selluseller_web`@`%`;
GRANT SHOW_ROUTINE ON *.* TO `selluseller_web`@`%`;
