AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template provisions resources for BowtieDuck

Metadata:
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      -
        Label:
          default: Resource Configuration
        Parameters:
          - Name
          - OrgName
          - EnvName
      -
        Label:
          default: Stack Configuration
        Parameters:
          - NetworkStackName
          - SNSStackName
          - LoadBalancerStackName
      -
        Label:
          default: Instance Configuration
        Parameters:
          - InstanceKeyName
          - InstanceAMI
      -
        Label:
          default: Load Balancer Configuration
        Parameters:
          - ClientDomainName
          - LoadBalancerPriority
          - LoadBalancerPriority2
      -
        Label:
          default: Scheduler Configuration
        Parameters:
          - StartScheduleExpression
          - StopScheduleExpression

    ParameterLabels:
      Name:
        default: Resource Name
      OrgName:
        default: Organization Name
      EnvName:
        default: Environment Name
      InstanceKeyName:
        default: Instance Key Name
      InstanceAMI:
        default: Instance AMI
      LoadBalancerPriority:
        default: Load Balancer Rule 1 Priority
      LoadBalancerPriority2:
        default: Load Balancer Rule 2 Priority
      LoadBalancerStackName:
        default: Load Balancer Stack Name
      NetworkStackName:
        default: Network Stack Name
      SNSStackName:
        default: SNS Topic Stack Name
      ClientDomainName:
        default: Domain Name
      StartScheduleExpression:
        default: Start Schedule CRON Expression
      StopScheduleExpression:
        default: Stop Schedule CRON Expression

Parameters:
  Name:
    Description: Unique name/identifier (Can be client name or resource name).
    Type: String
    MinLength: 3
    MaxLength: 9
  OrgName:
    Description: The name of the organization.
    Type: String
    Default: iscale-dev
    AllowedPattern: "^[a-z]+(-[a-z]+)*$"
    ConstraintDescription: Organization must only contain lowercase letters, numbers and hyphen.
    MaxLength: 10
  EnvName:
    Description: The name of the environment
    Type: String
    Default: Staging
    AllowedValues:
      - Production
      - Staging
      - Development
      - Test
  ClientDomainName:
    Description: The client's domain name (e.g. example.com, iscale-software.com).
    Type: String
    Default: iscale-software.com
    AllowedPattern: ^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,7}$
    MinLength: 1
  InstanceAMI:
    Description: Instance AMI ID
    Type: AWS::EC2::Image::Id
    Default: ami-0f6cc9840182cbde0 #Bowtie Duck image
  InstanceKeyName:
    Description: Instance Key Name
    Type: String
    Default: ''
  LoadBalancerPriority:
    Description: The priority for ELB Listener (first rule).
    Type: Number
    Default: 300
    MinValue: 1
    MaxValue: 50000
  LoadBalancerPriority2:
    Description: The priority for ELB Listener (second rule).
    Type: Number
    Default: 301
    MinValue: 1
    MaxValue: 50000
  LoadBalancerStackName:
    Description: THe name of the load balancer stack.
    Type: String
    Default: iscale-dev-stg-uw2-alb
    MinLength: 1
  NetworkStackName:
    Description: The name of the network stack.
    Type: String
    Default: iscale-dev-dev-uw2-network
    MinLength: 1
  SNSStackName:
    Description: the name of the SNS stack.
    Type: String
    Default: iscale-dev-dev-uw2-sns
    MinLength: 1
  StartScheduleExpression:
    Description: Schedule expression when to start the objects
    Type: String
    Default: cron(0 0 ? * MON-FRI *)
  StopScheduleExpression:
    Description: Schedule expression when to stop the objects
    Type: String
    Default: cron(0 10 ? * MON-FRI *)

Mappings: 
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/mappings.yaml

Conditions:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://iscale-dev-cloudformation/include/conditions.yaml
      
Resources:

  DBStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/database.yaml
      Parameters: 
        Name: !Ref Name
        DatabaseName: !Join ['',[!Ref Name, !FindInMap [EnvShort, !Ref EnvName, Name]]]
        EnableCPUCreditAlarm: true
        EnableEnhancedMonitoring: true
        EnvName: !Ref EnvName
        Engine: aurora-postgresql
        EngineVersion: 11.8 #12.2
        Family: aurora-postgresql11
        InstanceType: db.t3.medium
        MasterUser: root
        Port: 5432
        NetworkStackName: !Ref NetworkStackName
        OrgName: !Ref OrgName
        SNSStackName: !Ref SNSStackName
        StorageEncrypted: true

  DeployStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/deployment.yaml
      Parameters: 
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        NetworkStackName: !Ref NetworkStackName
        SNSStackName: !Ref SNSStackName
  
  AppServerStack: 
    DependsOn: 
      - DBStack
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/appserver-basic.yaml
      Parameters: 
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        LoadBalancerPriority: !Ref LoadBalancerPriority
        DatabaseEndpoint: 
          Fn::GetAtt:
            - DBStack
            - Outputs.ClusterEndpointAddress
        DatabasePort: 
          Fn::GetAtt:
            - DBStack
            - Outputs.ClusterPort
        DatabaseSecurityGroupId:
          Fn::GetAtt:
            - DBStack
            - Outputs.SecurityGroupId
        InstanceAMI: !Ref InstanceAMI
        InstanceKeyName: !Ref InstanceKeyName
        InstanceOS: Ubuntu
        LoadBalancerStackName: !Ref LoadBalancerStackName
        SNSStackName: !Ref SNSStackName
        NetworkStackName: !Ref NetworkStackName
        ClientDomainName: !Ref ClientDomainName

  BackupStack:
    DependsOn: 
      - DBStack
      - AppServerStack
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/backup.yaml
      Parameters: 
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        BackupARNList: 
          Fn::GetAtt:
            - DBStack
            - Outputs.DBClusterARN

  SchedulerStack: 
    DependsOn: 
      - DBStack
      - AppServerStack
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://iscale-dev-cloudformation.s3-us-west-2.amazonaws.com/common/scheduler.yaml
      Parameters: 
        Name: !Ref Name
        EnvName: !Ref EnvName
        OrgName: !Ref OrgName
        StartScheduleExpression: !Ref StartScheduleExpression
        StopScheduleExpression: !Ref StopScheduleExpression
        UseFriendlyNames: TRUE
        DatabaseClusterArn:
          Fn::GetAtt:
            - DBStack
            - Outputs.DBClusterARN
        CodeDeployApplicationName:
          Fn::GetAtt:
            - DeployStack
            - Outputs.CodeDeployApplicationName
        CodeDeployDeploymentGroupName:
          Fn::GetAtt:
            - DeployStack
            - Outputs.CodeDeployDeploymentGroupName


  #####
  # In addition, create a special bowtieduck.staging.iscale-software.com record
  #####

  BTDStagingELBDNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Condition: IsStaging
    Properties:
      HostedZoneName:
        Fn::Join:
          - ''
          - - Ref: ClientDomainName
            - '.'
      RecordSets:
        - Name:
            Fn::Join:
              - '.'
              - - bowtieduck
                - Fn::FindInMap:
                  - EnvLowerCase
                  - Ref: EnvName
                  - Name
                - Ref: ClientDomainName
          Type: A
          AliasTarget:
            HostedZoneId:
              Fn::ImportValue:
                Fn::Sub: "${LoadBalancerStackName}-CanonicalHostedZoneID"
            DNSName:
              Fn::ImportValue:
                Fn::Sub: "${LoadBalancerStackName}-DNSName"

  BTDStagingSSLListenerRule:
    Condition: IsStaging
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      Actions:
        - Type: forward
          TargetGroupArn: 
            Fn::GetAtt:
              - AppServerStack
              - Outputs.AppServerTargetGroup
      Conditions: 
        - Field: host-header
          Values:
            - Fn::Join:
              - '.'
              - - bowtieduck 
                - Fn::FindInMap:
                  - EnvLowerCase
                  - Ref: EnvName
                  - Name
                - Ref: ClientDomainName
      ListenerArn:
        Fn::ImportValue:
          Fn::Sub: "${LoadBalancerStackName}-ApplicationListenerArn"
      Priority:
        Ref: LoadBalancerPriority2
        
Outputs:
  DeploymentUserGroup:
    Description: Add the BitBucket user into this group
    Value: 
      Fn::GetAtt:
        - DeployStack
        - Outputs.DeploymentUserGroup
